### ISSUE TITLE
Recursive Lambda Expression

### ISSUE THREAD

**Issue by Mandated** [dotnet/docs#10464] opened 2019-02-14 04:35 UTC
Unfortunately this link seems to be broken.  
https://blogs.msdn.microsoft.com/madst/2007/05/11/recursive-lambda-expressions/

It's the last link under See Also

Are those anything important?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567260f8-0f94-b48c-8344-0d9780ab4448
* Version Independent ID: 1bebe367-5b93-0b83-72f5-bdf31d65ef5d
* Content: [Lambda expressions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions#expression-lambdas)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/lambda-expressions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment] 2019-02-25 22:24
I'm just going to remove that link unless I hear from @MadsTorgersen that his blog will not be deleted.

**Comment by pkulikov** [comment] 2019-03-14 17:08
@mairaw I'm working now on the referenced article about lambda expressions in scope of #11253.
I guess, the link can be removed? Or still on hold?

**Comment by mairaw** [comment] 2019-03-14 22:15
I'm going to close this one as a duplicate of #9807. That's where I'm tracking all these broken blog posts links as the migration is happening. I still don't know whether Mads blog will be ported or not.

**Closed by mairaw** 2019-03-14 22:15 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, broken-link
