### ISSUE TITLE
Index from end of collection

### ISSUE THREAD

**Issue by PeterKnaggs** [dotnet/docs#13641] opened 2019-07-30 16:26 UTC
Why now allow a negative index to reference from the end of the collection as per other langauges.

var last = list[-1];    // list[list.Count - 1]
var range = list[1 .. -1];

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcdddc9e-3060-4a72-95fa-93f8a4b6b741
* Version Independent ID: a70329e0-1d30-2e54-e8b8-22f9733bd09f
* Content: [Ranges - C# 8.0 language proposals](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges#feedback)
* Content Source: [proposals/csharp-8.0/ranges.md](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-8.0/ranges.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment] 2019-07-30 22:48
Hi! Thank you for opening this issue. The documentation does accurately reflect the language design choice.

I am going to close this.  However, if you want to continue to advocate for a different design, consider commenting on the referenced design notes, or other issues on ranges in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.

Duplicate of #11324

**Comment by Thraka** [comment] 2019-07-30 22:49
Duplicate of #11324

**Closed by Thraka** 2019-07-30 22:49 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, duplicate, product-feedback
