### ISSUE TITLE
Language reference for `init` seems to be missing example for `required`

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#37979] opened 2023-11-08 17:43 UTC
### Type of issue

Missing information

### Description

Page says:

> An init accessor doesn't force callers to set the property. Instead, it allows an object initializer to set the initial value while prohibiting later modification. You can add the required modifier to force callers to set a property. The following example shows the same behavior:

but the example following that text doesn't use `required` - instead it shows something about nullability (and there is no discussion of nullability elsewhere in that page).

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/init.md

### Document Version Independent Id

fc780319-a7fd-d9d1-1877-638ac05eb5f4

### Article author

BillWagner

**Comment by BillWagner** [comment] 2023-11-09 14:23
Hi @IanKemp 

You're right. This is a duplicate of #37625

I've planned on fixing it next month.

**Closed by BillWagner** 2023-11-09 14:23 UTC
Labels: :watch: Not Triaged, Pri3, dotnet-csharp/prod, csharp-language-reference/tech
