### ISSUE TITLE
Add topic on SDK style project

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#4168] opened 2018-01-22 06:21 UTC
# Add topic on SDK style project

I was writing about SDK style projects and wanted an authoritative link in our docs but didn't find one. We should add some docs on this topic if we don't have any.

It would also be good to talk about the degree to which the .NET Core SDK supports existing project files (not SDK style).

**Comment by cartermp** [comment] 2018-01-22 14:37
It appears that whatever we're doing in the docs is being picked up by google differently:

![image](https://user-images.githubusercontent.com/6309070/35225979-b21ba29a-ff3e-11e7-9387-c78476155654.png)

Takes you here: https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

"Additions to the csproj format for .NET Core"

**Comment by cartermp** [comment] 2018-01-22 14:38
I imagine this page has a high bounce rate.

**Comment by mairaw** [comment] 2018-01-22 19:30
I think this is a dupe of #2642, no? Our intention there is to create a project file reference for .net core projects.
Yes, that page you linked to @cartermp has a very low csat. I'll change the title metadata of it for now since it's wrong.

**Comment by mairaw** [comment] 2018-01-29 18:44
Ping @cartermp @richlander - can I close this as a dupe of #2642 or do you think it's a different issue?

**Comment by richlander** [comment] 2018-01-29 22:28
Yes, you can close this one as a dupe. The other topic seems to have more folks focussed on it.

I agree that we need to document this project type on its own w/o any migration nature to it. If we do add migration, I'd focus more on regular csproj to SDK style rather than p.j to this.

**Comment by mairaw** [comment] 2018-01-29 22:35
Yes. The new topic would be standalone, with no migration focus.

**Comment by mairaw** [comment] 2018-01-29 22:35
Duplicate of #2642

**Closed by mairaw** 2018-01-29 22:35 UTC
Labels: waiting-on-feedback

**Comment by gewarren** [comment] 2020-04-25 00:32
New topic is at https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview.
