### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by briangithex** [dotnet/docs#11796] opened 2019-04-11 19:24 UTC
https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/asynchronous-programming.md links to:
https://blogs.msdn.microsoft.com/adonet/2012/04/20/using-sqldatareaders-new-async-methods-in-net-4-5/ and to 
https://blogs.msdn.microsoft.com/adonet/2012/07/15/using-sqldatareaders-new-async-methods-in-net-4-5-part-2-examples/ .

However, the blog at https://blogs.msdn.microsoft.com/adonet/ has been disabled.

**Comment by mairaw** [comment] 2019-04-11 23:01
Thanks @briangithex. I'm going to resolve this as a duplicate of #9807, where we're tracking the work for fixing these links after the migration/exclusion of some blogs.

**Closed by mairaw** 2019-04-11 23:01 UTC
Labels: :watch: Not Triaged
