### ISSUE TITLE
Missing T <member> records

### ISSUE THREAD

**Issue by gggustafson** [dotnet/docs#41597] opened 2024-06-29 18:20 UTC
### Type of issue

Other (describe below)

### Description

There is a problem with the generation of XML.

If a module begins
<pre>
using System;
using System.IO;

namespace Utilities
    {

    public class TextFileIO
        {
</pre>
no XML <member> record with an ID character 'T' will be generated, even if the &lt;member&gt; record has no children. 

To get a 'T' record, &lt;summary&gt;..&lt;/summary&gt; must precede the declaration. An then, the generated XML is 
<pre>
        &lt;member name=&quot;T:Utilities.TextFileIO&quot;&gt;
            &lt;summary&gt;
            
            &lt;/summary&gt;
        &lt;/member&gt;
</pre>
Many classes have no XML comments. So if they are required, that requirement should be stated in documentation.

Also, documentation uses the phrase &quot;ID string&quot;. IMHO that should read &quot;ID character&quot;.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/xmldoc/index.md

### Document Version Independent Id

707b352c-ea51-494c-d4f1-33e140ab9d17

### Article author

@BillWagner

### Metadata

* ID: 5b320175-c9fe-d92e-748a-8cd511e7c12d 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by gggustafson** [comment] 2024-06-30 15:52
I should add that namespace records, e.g.,
<pre>
    &lt;member name="N:Utilities"&gt;
</pre>
suffer from the same problem as the basic issue.

**Comment by BillWagner** [comment] 2024-07-01 14:54
Hi @gggustafson 

Can you attach a full sample? I can't reproduce the issue you report here.

**Comment by gggustafson** [comment] 2024-07-01 16:08
This is the source:
<pre>
using System.Runtime.InteropServices;
using System.Text;

namespace Utilities
    {

    // ********************************************* class ShortenPath

    public class ShortenPath
        {

        [ DllImport ( &quot;shlwapi.dll&quot;,
                      CharSet = CharSet.Auto ) ]
        static extern bool PathCompactPathEx (
                               [ Out ] StringBuilder  pszOut,
                                       string         szPath,
                                       int            cchMax,
                                       int            dwFlags );

        // ********************************************** shorten_path

        /// &lt;summary&gt;
        /// Given path_to_shorten and a desired_length, shortens the 
        /// path by replacing path components with elipses (...).
        /// &lt;/summary&gt;
        /// &lt;param name=&quot;path_to_shorten&quot;&gt;
        /// The path that is to be shortened.
        /// &lt;/param&gt;
        /// &lt;param name=&quot;desired_length&quot;&gt;
        /// The maximum number of characters to be contained in the 
        /// new string, including the terminating null character. For 
        /// example, if desired_length = 8, the resulting string can 
        /// contain a maximum of 7 characters plus the terminating 
        /// null character. 
        /// &lt;/param&gt;
        /// &lt;remarks&gt;
        /// The '/' separator will be used instead of &quot; if the 
        /// original string used it. If desired_length points to a 
        /// file name that is too long, instead of a path, the file 
        /// name will be truncated to desired_length characters, 
        /// including the ellipsis and the terminating NULL character. 
        /// For example, if the input file name is &quot;My Filename&quot; and 
        /// desired_length is 10, shorten_path will return &quot;My Fil...&quot;.
        /// &lt;/remarks&gt;
        /// &lt;returns&gt;
        /// If truncation is successful, the shortened path; otherwise
        /// the empty string.
        /// &lt;/returns&gt;
        public static string shorten_path ( string path_to_shorten,
                                            int    desired_length )
            {
            StringBuilder  sb = new StringBuilder (
                                        desired_length + 1 );

            if ( !PathCompactPathEx ( sb,
                                      path_to_shorten,
                                      desired_length,
                                      0 ) )
                {
                sb.Length = 0;
                }

            return ( sb.ToString ( ) );
            }

        } // class ShortenPath

    } // namespace Utilities
</pre>
This is the generated XML (with other methods in the namespace removed):
<pre>
&lt;?xml version=&quot;1.0&quot;?&gt;
&lt;doc&gt;
    &lt;assembly&gt;
        &lt;name&gt;Utilities&lt;/name&gt;
    &lt;/assembly&gt;
    &lt;members&gt;
        &lt;member name=&quot;M:Utilities.ShortenPath.shorten_path(System.String,System.Int32)&quot;&gt;
            &lt;summary&gt;
            Given path_to_shorten and a desired_length, shortens the 
            path by replacing path components with elipses (...).
            &lt;/summary&gt;
            &lt;param name=&quot;path_to_shorten&quot;&gt;
            The path that is to be shortened.
            &lt;/param&gt;
            &lt;param name=&quot;desired_length&quot;&gt;
            The maximum number of characters to be contained in the 
            new string, including the terminating null character. For 
            example, if desired_length = 8, the resulting string can 
            contain a maximum of 7 characters plus the terminating 
            null character. 
            &lt;/param&gt;
            &lt;remarks&gt;
            The '/' separator will be used instead of &quot; if the 
            original string used it. If desired_length points to a 
            file name that is too long, instead of a path, the file 
            name will be truncated to desired_length characters, 
            including the ellipsis and the terminating NULL character. 
            For example, if the input file name is &quot;My Filename&quot; and 
            desired_length is 10, shorten_path will return &quot;My Fil...&quot;.
            &lt;/remarks&gt;
            &lt;returns&gt;
            If truncation is successful, the shortened path; otherwise
            the empty string.
            &lt;/returns&gt;
        &lt;/member&gt;
    &lt;/members&gt;
&lt;/doc&gt;
</pre>
What is missing are entries for the namespace and the class:
<pre>
        &lt;member name=&quot;N:Utilities&quot;&gt;
        &lt;member name=&quot;T:Utilities.ShortenPath&quot;&gt;
</pre>
I should also point out that the ID character ("ID string") "T" is ambiguous. IMO the record should have a type attribute that distinguished between "class, interface, struct, enum, or delegate".  So for the class record, above, the addition would read:
<pre>
        &lt;member name=&quot;T:Utilities.ShortenPath&quot; type=&quot;class&quot;&gt;
</pre>
Hope that helps.

**Comment by BillWagner** [comment] 2024-07-02 15:27
adding @CyrusNajmabadi 

I believe this is the correct behavior. Also, I don't think the documentation needs to change. Why should nodes be added when they aren't created in the source?

**Comment by CyrusNajmabadi** [comment] 2024-07-02 16:18
@BillWagner This is the behavior we've had for 25 years.  If you don't put doc comments on the item, you don't get anything in the doc file.  It's a simple 1:1 relation.  Thanks.

**Comment by BillWagner** [comment] 2024-07-02 17:02
I'll close this. I don't see a docs issue here either.

**Closed by BillWagner** 2024-07-02 17:02 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/svc, lang-reference/subsvc

**Comment by gggustafson** [comment] 2024-07-03 18:13
My apologies for my delay in responding. I was taken aback by your statement.

Bugs exist in two varieties: those that are caused by the implementers of a requirement; those that are caused by a failure in the requirements themselves The former are programmer errors. The latter are architectural errors. Both may exist for a long time before discovery - even 25 years.

The failure to produce T and N records means that I am not able to use the compiler generated XML document as input to my HTML producing program. There does not appear to be anyway to get the compiler-known namespace. I have a version of the program that compiles the source code and extracts the needed data. But the only way that I can get the namespace is through the .CSPROJ file's RootNamespace. (The only way that I can get the Assembly is through the .CSPROJ file's AssemblyName.)

IMHO, the failure to supply T and N records (and some type of record for the assembly name) in the compiler-generated XML is a requirements failure. It seems that MS's intent was to encourage programmers to document their code. Yet MS is not providing the necessary data to fulfill that intent.

Note the web page for DataTable:

**DataTable Class**
<pre>
    Reference
</pre>
**Definition**
<pre>
    Namespace:  System.Data 
    Assembly:  System.Data.Common.dll
    Source:  DataTable.cs
</pre>
This and countless other web pages begin the same way. Using my own compiler, I can obtain:

**BoyerMoore Class**
**Definition**
<pre>
    Namespace: Utilities
</pre>
Must I use my own compiler and access the CSPROJ file for other data, or can I depend of MS. Today, I must and I cannot!

**Comment by CyrusNajmabadi** [comment] 2024-07-03 18:38
> The failure to produce T and N records means that I am not able to use the compiler generated XML document as input to my HTML producing program.

You are able to do this.  You just have no docs for those items.  Since there were no docs in the source file, there are no docs emitted into the doc file.

If you want to know about what types there are that don't have docs, we have many apis available that can help you with that.

> IMHO, the failure to supply T and N records (and some type of record for the assembly name) in the compiler-generated XML is a requirements failure. 

Only to you.  But you don't define our requirements.  THe ecosystem does.  And in 25 years, the millions of users who have used this system and the docs haven't needed this.  As such, it seems like the requirements have been fine and correct for both us and the ecosystem all this time.

I would recommend you see what other options are available to you.  As stated, we have many apis for thsi purpose.  So reusing docs for this purpose is something we would consider a *misuse* of that particular api. 

> Yet MS is not providing the necessary data to fulfill that intent.

We are.  Just not in the way you would prefer.  But it is not our intent or goal to provide *all* the data that *every* user needs in *every* api we provide.  We have numerous APIs, suited for many different purposes, that our users can use in concert to get the final outcome they need.  This is how things have worked since we've been making apis (and def for the lifetime of .net) and it has been more than sufficient for the rest of the ecosystem and community.  So we're unlikely to change that here.

Thanks! :)

**Comment by CyrusNajmabadi** [comment] 2024-07-03 18:39
> Must I use my own compiler and access the CSPROJ file for other data, or can I depend of MS. 

You can use our APIs.  We have many you can use here.  Reflection.  Roslyn.  Etc.
