### ISSUE TITLE
Example regarding "multiple $ characters in an interpolated raw string literal" is not correct

### ISSUE THREAD

**Issue by ppaschedag** [dotnet/docs#29127] opened 2022-04-20 14:51 UTC
The output of the following example does not match the "pointMessage" interpolated string. I think in this case the pointMessage should be changed to:

` var pointMessage = $$"""The point {{{X}}, {{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";`

Original example:
```
int X = 2;
int Y = 3;

var pointMessage = $$"""The point {{{X}}}, {{{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";

Console.WriteLine(pointMessage);
// output:  The point {2, 3} is 3.605551275463989 from the origin.
```

Note: the output for this example is: The point {2}, {3} is 3.605551275463989 from the origin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-04-20 14:56
Thanks @ppaschedag 

This is a duplicate of #29121 

I've opened #29126 to address it.

Closing as a duplicate.

**Closed by BillWagner** 2022-04-20 14:56 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-language-reference/tech
