### ISSUE TITLE
Menu wrapping too much

### ISSUE THREAD

**Issue by johnsimons** [dotnet/docs#1484] opened 2017-02-01 01:36 UTC
![image](https://cloud.githubusercontent.com/assets/122651/22491910/7acf818c-e872-11e6-91ef-cc16162d6787.png)

I tried it in IE and Chrome

**Comment by mairaw** [comment] 2017-02-01 01:43
Thank you @johnsimons! We're aware of this issue and working to fix this. I'm going to close this one as a duplicate of #1283.

**Closed by mairaw** 2017-02-01 01:43 UTC
