### ISSUE TITLE
Controlling the Prediction Score Range

### ISSUE THREAD

**Issue by dorofino** [dotnet/docs#12242] opened 2019-05-07 20:47 UTC
Hi everyone,
I have a question in regards to the Prediction Score.

I was wondering if there is any way I set up a range for the score between 0 to 1
For example:
0.5 &gt; positive
0.5 = neutral
0.5 &lt; negative

I'm currently using Cognitive Service Text Analytics API, and as you probably know their score between 0-1 Link

&gt; The sentiment analyzer classifies text as predominantly positive or negative, assigning a score in the range of 0 to 1. Values close to 0.5 are neutral or indeterminate. A score of 0.5 indicates neutrality. When a string cannot be analyzed for sentiment or has no sentiment, the score is always 0.5 exactly. For example, if you pass in a Spanish string with an English language code, the score is 0.5.

Let me know if you know an easy way to implement this method.

Thanks
Diego

[AB#1572600](https://dev.azure.com/mseng/677da0fb-b067-4f77-b89b-f32c12bb8617/_workitems/edit/1572600)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Tutorial: Analyze website comments - binary classification - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment] 2019-05-08 14:53
Closing because it's a duplicate of #12235

**Comment by luisquintanilla** [comment] 2019-05-08 14:57
Reopening because this question is more related to this article than *What is ML.NET and How Does It Work?*

**Comment by luisquintanilla** [comment] 2019-07-31 18:26
Hi @dorofino 

Thank you for your question. Since this is more of a product question, can you please raise an issue for it in the [ML.NET Repo](https://github.com/dotnet/machinelearning) instead.

**Closed by luisquintanilla** 2019-07-31 18:26 UTC
Labels: :books: Area - ML.NET Guide, Source - Docs.ms, product-question, triaged
