### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#8924] opened 2018-11-07 19:22 UTC
Nested Control Structures link not found https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/programming-guide/language-features/control-flow/nested-control-structures

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4099464-c3a0-f9f0-ac92-04f15512e8ea
* Version Independent ID: 0fd42897-47a8-cb07-e8b1-458131eaf78d
* Content: [With...End With Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference//statements/with-end-with-statement)
* Content Source: [docs/visual-basic/language-reference/statements/with-end-with-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/with-end-with-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by pkulikov** [comment] 2018-11-07 19:53
@maryob77062 does it work if you select the link from the following page:
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/with-end-with-statement

**Comment by pkulikov** [comment] 2018-11-07 19:54
Note, the link to the page in the original message contains double backslash (before "statements"):
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference//statements/with-end-with-statement

**Comment by maryob77062** [comment] 2018-11-08 16:30
yes

**Comment by pkulikov** [comment] 2018-11-08 16:41
@maryob77062 do you remember how you arrived at the page with double `//`?

**Comment by maryob77062** [comment] 2018-11-09 07:15
Sorry, no

**Comment by mairaw** [comment] 2018-11-19 22:14
I'll try to check if there's any place in our repo that has double //. Otherwise, I'll have to close this.

**Comment by mairaw** [comment] 2019-01-14 22:34
This is caused by the same issue as #9753. Google has the wrong URL indexed. I'll close this one as duplicate.

**Closed by mairaw** 2019-01-14 22:34 UTC
Labels: :books: Area - Visual Basic Guide, :mag: Under Investigation, :watch: Not Triaged, Source - Docs.ms
