### ISSUE TITLE
Inconsistent .NET Core 3.1 dependencies

### ISSUE THREAD

**Issue by weezlemsneezle** [dotnet/docs#19608] opened 2020-07-21 09:09 UTC
The "Dependencies" Section for .NET Core 3.1 does not match with the linked .NET Core 3.1 Supported OS Versions document.

The other document lists Windows 7 SP1 and Windows 10 1607, this page does not list Windows 7 and it lists Windows 10 1609 (is this the same as 1607?)

Which of these tables is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by weezlemsneezle** [comment] 2020-07-21 09:17
I just saw that I can view all issues for this page. I guess this issue is a duplicate of #19384 but there is still the discrepancy between this document and the linked document. This issue can be closed if everything can be tracked in #19384

**Comment by adegeo** [comment] 2020-07-21 16:33
Thanks, yeah looks like duplicate 😄 But thank you for filing an issue and interacting with the docs!

**Comment by adegeo** [comment] 2020-07-21 16:33
Duplicate of #19384

**Closed by adegeo** 2020-07-21 16:33 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged
