### ISSUE TITLE
.NET 4.8.1 is missing

### ISSUE THREAD

**Issue by dotMorten** [dotnet/docs#30905] opened 2022-08-29 17:15 UTC
4.8.1 version is missing from this table: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#minimum-version
See  https://devblogs.microsoft.com/dotnet/announcing-dotnet-framework-481/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#minimum-version)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2022-08-29 17:18
This will be addressed by #30619. Closing as a duplicate of #30553.

**Closed by gewarren** 2022-08-29 17:18 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-framework/prod, dotnet-appcompat/tech
