### ISSUE TITLE
EnforceCodeStyleInBuild has no effect in our netcoreapp3.1 projects

### ISSUE THREAD

**Issue by MattLavalleeMA** [dotnet/docs#23565] opened 2021-03-31 06:26 UTC
We recently enabled the "Enable CodeStyle on build" and are not seeing the expected behavior:  For us, the analyzers only run in our netcoreapp3.1 projects when code is edited (triggering IntelliSense) and **do not** (ever) run during build.  Build output (seems to) only show the results of Microsoft.CodeQuality.Analyzers, but none of the other ~20.

Judging by the documentation, this is expected to work for netcoreapp3.1 projects, so is there another setting beyond EnforceCodeStyleInBuild that needs to be applied?

Note that this also seems to be affecting the traditional convention for Tasks, as TODO or HACK comments no longer appear in build results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8906b2c-b984-0427-d064-829e7ea2fc55
* Version Independent ID: 128f9903-971d-6a66-a2cb-9b12acbc55e7
* Content: [Code analysis in .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview)
* Content Source: [docs/fundamentals/code-analysis/overview.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment] 2021-03-31 07:13
@MattLavalleeMA What version of the SDK are you using? Can you run `dotnet --info` at the directory of your project and paste the output here? Can you also write `#error version` at the top of any code file and paste the error message you get when you build?

**Comment by MattLavalleeMA** [comment] 2021-04-02 10:02
dotnet info:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Build output:
```
error CS8304: Compiler version: '3.9.0-6.21160.10 (59eedc33)'. Language version: 8.0.
```

**Comment by Youssef1313** [comment] 2021-04-02 10:18
@MattLavalleeMA I can't reproduce the issue you're facing:

---

*Project.csproj*:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>
```

---

*Program.cs*:

```csharp
class T {}
```

---

*.editorconfig*:

```ini
[*.cs]

# IDE0040: Add accessibility modifiers
dotnet_diagnostic.IDE0040.severity = error
```

---

Build output from command line:

```
error IDE0040: Accessibility modifiers required
```

- Have you configured the IDE rules that you want to enforce from an editorconfig or a globalconfig?
- Have you added the section header in editorconfig (e.g: `[*.cs]`) before the lines where you set the severity?

It would be helpful if you can attach a sample project demonstrating the issue.

**Comment by MattLavalleeMA** [comment] 2021-04-02 10:21
We have no editorconfig in this particularly project... Do we have to manually assign every severity to see them on build?

**Comment by MattLavalleeMA** [comment] 2021-04-02 10:27
Here is a very simple repro:
ClassLibrary1.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
      <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
</Project>
```
Class1.cs:
```
namespace ClassLibrary1
{
    /// <summary>
    /// The class1.
    /// </summary>
    public class Class1
    {
        public string _unused;

    }
}
```

With the Class1.cs file open, I have 1 warning:
> Severity	Code	Description	Project	File	Line	Suppression State
> Warning	S1104	Make this field 'private' and encapsulate it in a 'public' property.	ClassLibrary1	Class1.cs	10	Active

If I close the file, then close the solution, then reopen the solution and rebuild all, I have no warnings either in the Error List or in Build Output.

**Comment by Youssef1313** [comment] 2021-04-02 10:35
@MattLavalleeMA IDE Style rules (by default) have severity of suggestion, so they don't appear in command line builds, and even in IDE, they will show as suggestions, not as warnings/errors. So you need to manually configure the rules you're interested in to be warnings, or you can enable all style rules at once with `dotnet_analyzer_diagnostic.category-Style.severity = warning`, then exclude any rules you don't want with `dotnet_diagnostic.IDExxxx.severity = silent`.

See [Enable on build](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#enable-on-build) for more information.

---

For your example, it's not about a built-in code style analyzer. S1104 comes from a third-party analyzer, so it has nothing to do with `EnforceCodeStyleInBuild`.

**Comment by MattLavalleeMA** [comment] 2021-04-02 10:46
Okay, I disabled SonarLint (the third-party analyzer) and tried this again.

Here's the updated class file:
```
using System;

namespace ClassLibrary1
{
    public class Class1
    {
        // TODO: fix this
        public string _unused;

        public string UnusedMethod()
        {
            // HACK: temporary return
            return string.Empty;
        }
    }
}
```

With IntelliSense (the file open & active), I receive these:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	ClassDocumentationHeader	The class must have a documentation header.	ClassLibrary1	Class1.cs	5	Active
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MethodDocumentationHeader	The method must have a documentation header.	ClassLibrary1	Class1.cs	10	Active
Severity	Code	Description	Project	File	Line	Suppression State
Message	CA1822	Member 'UnusedMethod' does not access instance data and can be marked as static	ClassLibrary1 Class1.cs	10	Active
```
... and my Build Output shows nothing.

The UI also shows IDE0005 "Using directive is unnecessary" on line 1, but there is no informational in the Error List unless I manually set the dotnet_diagnostic.IDE0005.severity = suggestion in editorconfig.

These are both changed behaviors from 16.8.5.

**Comment by Youssef1313** [comment] 2021-04-02 10:56
Regarding `CA1822`, its severity is not a warning, so for it to show in command line builds you need to set its severity via editorconfig (this will work regardless EnforceCodeStyleInBuild).

Regarding IDE0005, I believe it always had been a hidden ("silent") diagnostic, which doesn't show in error list.
If you changed it to suggestion, it will show in error list, but not in command line builds.
For it to show in command line builds, you need either warning or error.

---

> Also note that neither HACK nor TODO are showing up in the Error list as warnings, which they previously did, and now only appear in the Task List.

I'm not aware of any IDExxxx or CAxxxx rule that warns against `HACK`s or `TODO`s, this is probably a third-party analyzer?

**Comment by MattLavalleeMA** [comment] 2021-04-02 11:11
> Regarding `CA1822`, its severity is not a warning, so for it to show in command line builds you need to set its severity via editorconfig (this will work regardless EnforceCodeStyleInBuild).
 
If I reinstall Microsoft.CodeAnalysis.FxCopAnalyzers, CA1822 and CA1051 appear right away as warnings and as part of build logs.

On the others, it looks like we did/do have StyleCop.Analyzers with preferences, so we can ignore those for the sake of this discussion.

However, at the very least, there is a distinct behavior change (and apparently some classification nuances) between the old analyzers and new.

**Comment by Youssef1313** [comment] 2021-04-02 11:29
@MattLavalleeMA You're correct that CA1822 used to be a warning. This behavior was changed in https://github.com/dotnet/roslyn-analyzers/pull/3190.

**Comment by MattLavalleeMA** [comment] 2021-04-02 12:23
> @MattLavalleeMA You're correct that CA1822 used to be a warning. This behavior was changed in [dotnet/roslyn-analyzers#3190](https://github.com/dotnet/roslyn-analyzers/pull/3190).

Okay, and it looks like CA1051 has also been disabled by default now.  Is there some obvious way that we can export the old rules/classifications and compare or (better still) apply them?

**Comment by Youssef1313** [comment] 2021-04-02 12:30
> > @MattLavalleeMA You're correct that CA1822 used to be a warning. This behavior was changed in [dotnet/roslyn-analyzers#3190](https://github.com/dotnet/roslyn-analyzers/pull/3190).
> 
> Okay, and it looks like CA1051 has also been disabled by default now. Is there some obvious way that we can export the old rules/classifications and compare or (better still) apply them?

You can enable **all** rules using `<AnalysisMode>AllEnabledByDefault</AnalysisMode>` in your csproj. It's certainly too aggressive than what FxCopAnalyzers had, but from here you can disable rules that you don't want.

**Comment by MattLavalleeMA** [comment] 2021-04-02 12:34
Ultimately, we also got on a tangent about the particulars of these warnings, but we still have a discrepancy in our real project between the number of warnings appearing in the Error List (only **after** opening individual code files) and that only 2 out of 146 appear in the Build Output.  For example, I have a CS0108 that appears when I open that file, but does not appear in Build.

**Comment by Youssef1313** [comment] 2021-04-02 12:39
Building from command-line should show all warnings. (If it doesn't, try `dotnet build --no-incremental`). However, from IDE, there are some that don't appear in live analysis.

**Comment by MattLavalleeMA** [comment] 2021-04-02 12:48
> You can enable **all** rules using `<AnalysisMode>AllEnabledByDefault</AnalysisMode>` in your csproj. It's certainly too aggressive than what FxCopAnalyzers had, but from here you can disable rules that you don't want.

Aha -- now we are getting much closer to the deprecated analyzers.

So here's the outstanding behavior issue -- previously, Informationals would still _generate_ on build, even though they did not appear in the Build Output, but now they _only_ appear when browsing each individual file.

**Comment by Youssef1313** [comment] 2021-04-02 12:53
@MattLavalleeMA This *could* be related to the following option from **Tools** > **Options** > **Editor** > **C#** > **Advanced**:

![image](https://user-images.githubusercontent.com/31348972/113417119-0e22ce80-93c3-11eb-8876-837f01aad777.png)

**Comment by mavasani** [comment] 2021-04-02 12:56
> So here's the outstanding behavior issue -- previously, Informationals would still generate on build, even though they did not appear in the Build Output, but now they only appear when browsing each individual file.

that is an intentional design change in the compiler. Anything you want on the command line output needs to be at least a warning level. Informational or suggestion diagnostics are more suitable for IDE experience. Note that you don’t need to open each file in IDE to get all informational diagnostics. You can execute “Analyze -> Run Code Analysis” on a project or solution node in Solution explorer to force compute these across a project or solution.

**Comment by MattLavalleeMA** [comment] 2021-04-02 13:39
> @MattLavalleeMA This _could_ be related to the following option from **Tools** > **Options** > **Editor** > **C#** > **Advanced**:

Bingo.  It's not "on build", but I'd rather have the Analysis be "always on" than "sometimes on".

> that is an intentional design change in the compiler. Anything you want on the command line output needs to be at least a warning level. Informational or suggestion diagnostics are more suitable for IDE experience. Note that you don’t need to open each file in IDE to get all informational diagnostics. You can execute “Analyze -> Run Code Analysis” on a project or solution node in Solution explorer to force compute these across a project or solution.

Okay, just for argument's sake, to replicate the old behavior, is there a way to Run Code Analysis automatically on build?

**Comment by BradKnowles** [comment] 2021-08-23 16:30
I can replicate this issue using @Youssef1313's example.

Add a `global.json` to your directory.
```json
{
  "sdk": {
    "version": "3.1.101",
    "rollForward": "latestFeature"
  }
}
```
Output from `dotnet --info` (after adding `global.json`)
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.411
 Commit:    d100cdf718

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.411\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.524 [C:\Program Files\dotnet\sdk]
  2.1.816 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.117 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
\#error version output
```
Program.cs(1,8): error CS8304: Compiler version: '3.7.0-6.20570.4 (dc3f4eef)'. Language version: 8.0.
```

**Comment by gewarren** [comment] 2022-01-22 04:40
I'm going to close this issue now as it seems to be resolved.

**Closed by gewarren** 2022-01-22 04:40 UTC
Labels: product-question, Pri1, dotnet-fundamentals/prod
