### ISSUE TITLE
.NET Framework on Docker Guide

### ISSUE THREAD

**Issue by FimePradeep** [dotnet/docs#12364] opened 2019-05-15 04:04 UTC
.NET Framework on Docker Guide - Navigating same page. no details about docker .net framework run and install guide. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c04fb826-aa70-5a14-2a13-4eed6cbb304f
* Version Independent ID: 2835b981-f482-8fa2-df47-469291d93a5a
* Content: [.NET Framework documentation](https://docs.microsoft.com/en-gb/dotnet/framework/#feedback)
* Content Source: [docs/framework/index.md](https://github.com/dotnet/docs/blob/master/docs/framework/index.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment] 2019-05-15 04:27
That has been fixed by #12298 and goes live, most probably, within next 12 hours.

**Comment by Thraka** [comment] 2019-05-17 00:46
Duplicate of #12298

**Closed by Thraka** 2019-05-17 00:46 UTC
Labels: :books: Area - .NET Framework Guide, :watch: Not Triaged, Source - Docs.ms

**Comment by Thraka** [comment] 2019-05-17 00:47
Duplicate of #12286
