### ISSUE TITLE
Set of WarningLevel values is incomplete

### ISSUE THREAD

**Issue by tmeschter** [dotnet/docs#28806] opened 2022-03-25 21:11 UTC
The set of WarningLevel values is incomplete, and the description for 5 is also incomplete. We want something like:

- 5: Includes warnings from C# 9.0 and built-in .NET 5.0 analyzers.
- 6: Includes warnings from C# 10.0 and built-in .NET 6.0 analyzers.
- 9999: Includes all warnings.

These are all values the .NET 6.0 SDK itself sets in Microsoft.NET.Sdk.Analyzers.targets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26ef35c2-6df4-26f8-32b2-9b50eb76c037
* Version Independent ID: e57ac82b-307e-163b-8172-52644b3a6baa
* Content: [C# Compiler Options - errors and warnings](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings)
* Content Source: [docs/csharp/language-reference/compiler-options/errors-warnings.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/errors-warnings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by cremor** [comment] 2022-03-28 06:26
Duplicate of #27927?

**Closed** 2022-05-11 22:38 UTC
Labels: doc-bug, Pri2, dotnet-csharp/prod, csharp-language-reference/tech
