### ISSUE TITLE
String interpolation not supported on ILogger methods? (Error list messages)

### ISSUE THREAD

**Issue by MikeMcWilliams** [dotnet/docs#30444] opened 2022-08-01 21:36 UTC
Getting what I call a false positive message.
```

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Message	CA2254	The logging message template should not vary between calls to 'LoggerExtensions.LogInformation(ILogger, string?, params object?[])'
```	

The following should be perfectly fine, but VS2022, complains about string interpollation
`
 _logger.LogInformation($"{nameof(Person)} [{nameof(Person.Id)}:{person.Id}] updated with {nameof(Person.MigrationStatusId)} of {Person.MigrationComplete}");`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5662dc7-dcf6-47d5-9340-55b22ebfeca8
* Version Independent ID: 0df9ae80-f763-ba60-a876-a98e86d64887
* Content: [CA2254: Template should be a static expression - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2254.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2254.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment] 2022-08-02 20:29
This is not a false positive, it is accurate. The logging APIs have analyzers in place to help guide their intended behaviors. String interpolation within the log APIs technically does work, sure, but it's less than ideal, and you should be using log message templates instead.

Nick Chapsas has video on this topic here: https://www.youtube.com/watch?v=bnVfrd3lRv8
And our docs call attention to it here: https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#log-message-template-formatting-examples

I'm going to close this issue, but if you have more questions, please let us know.

**Closed by IEvangelist** 2022-08-02 20:29 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-fundamentals/prod

**Comment by MikeMcWilliams** [comment] 2022-08-02 22:19
@IEvangelist Thank you so much!  Love Nick Chapsas.
For now I suppressed the messages, but I will look into the message templates.  imo, if logger accepts a string then string interpolation should be supported.  Thank you for your quick reply sir.

**Comment by gavinBurtonStoreFeeder** [comment] 2022-11-15 11:40
> This is not a false positive, it is accurate. The logging APIs have analyzers in place to help guide their intended behaviors. String interpolation within the log APIs technically does work, sure, but it's less than ideal, and you should be using log message templates instead.
> 
> Nick Chapsas has video on this topic here: https://www.youtube.com/watch?v=bnVfrd3lRv8 And our docs call attention to it here: https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#log-message-template-formatting-examples
> 
> I'm going to close this issue, but if you have more questions, please let us know.

I watched the video.  Are you sure you linked the right one?

It talks about the cost of calling LogDebug when debug level logging is disabled. It talks about how, when you use a template with interpolation, you are boxing a type, and suggests you should bypass the API call to LogDebug entirely using an if statement. 

This is where he shows a benchmark;

https://youtu.be/bnVfrd3lRv8?t=486

He even shows that using a template with parameters is slower - implying that we should do the opposite of CA2254

As it stands, it seems that CA2254 is bad advice - which we should ignore.
