### ISSUE TITLE
Documentation for installation of .NET 7 for Ubuntu  

### ISSUE THREAD

**Issue by tarifrr** [dotnet/docs#32695] opened 2022-11-22 15:22 UTC
When will the document be updated to include documentation for installation of .NET 7 for Ubuntu ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **.net**
* Technology: **dotnet-installation**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-11-28 21:35
Duplicate of #32541

**Closed by adegeo** 2022-11-28 21:35 UTC
Labels: duplicate, Pri1, .net/prod, dotnet-installation/tech
