### ISSUE TITLE
Why accessing custom attribute from within the class where it is applied?

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/docs#11949] opened 2019-04-19 20:26 UTC
Please elaborate on the use case when you create a custom attribute, apply it to a class, and then from within that class want to read the very same custom attribute. Wouldn't it be easier just define the attributes properties as constant private fields in the class?  Why Would you create an attribute for something like this?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a62174c-7cdd-54b7-6740-49caf6d5b043
* Version Independent ID: be1f8622-f6ea-5da9-d038-a4459b94c671
* Content: [Retrieving Information Stored in Attributes](https://docs.microsoft.com/en-us/dotnet/standard/attributes/retrieving-information-stored-in-attributes)
* Content Source: [docs/standard/attributes/retrieving-information-stored-in-attributes.md](https://github.com/dotnet/docs/blob/master/docs/standard/attributes/retrieving-information-stored-in-attributes.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment] 2019-04-23 15:17
Hello!

That would not be the normal use-case of an attribute. The attribute is extra metadata describing what it's attached to. 

I'm going to close this issue. I think the answer to your other question #11952 will help.

**Closed by Thraka** 2019-04-23 15:17 UTC
Labels: :books: Area - .NET Guide, :watch: Not Triaged, Source - Docs.ms

**Comment by Thraka** [comment] 2019-04-23 15:19
Duplicate of #11952

**Comment by EricHerlitz** [comment] 2019-12-09 16:08
It is certainly not the normal use-case of an attribute to be used within its own. 
The normal usecase: Attributes are used to extend methods, properties and class instances with metadata to be read when it is constructed. I.e. the [Obsolete] annotation gives feedback to the developer that this method/property/class is soon to become obsolete, but there is really no need for the information within the class itself.
