### ISSUE TITLE
Please add complete example for callback

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9928] opened 2019-01-10 13:38 UTC
@miya898 commented on [Thu Jan 10 2019](https://github.com/dotnet/docs.zh-cn/issues/319)

On https://docs.microsoft.com/zh-cn/dotnet/standard/native-interop, can you also add the C/C++ code part in above examples for readers to better understand callback methods?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bfe2d36f-8718-cf05-adf9-55725c959388
* Version Independent ID: df8f9d5d-816a-d285-b4d7-b3ba74aafd9a
* Content: [本机互操作性](https://docs.microsoft.com/zh-cn/dotnet/standard/native-interop)
* Content Source: [docs/standard/native-interop.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/native-interop.md)
* Product: **dotnet**
* GitHub Login: @blackdwarf
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment] 2019-01-10 13:39
Hi team, 
I'm moving this here since the suggestion is about the code
best regards

**Comment by rpetrusha** [comment] 2019-03-18 22:00
The external routines are all in system libraries. Closing as By Design.

**Closed by rpetrusha** 2019-03-18 22:00 UTC
Labels: :books: Area - .NET Guide, Source - Docs.ms, by-design
