### ISSUE TITLE
multi class classification? 

### ISSUE THREAD

**Issue by bs6523** [dotnet/docs#5984] opened 2018-06-16 16:41 UTC
which method can i use to make multi-class classification? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment] 2018-06-16 17:02
@bs6523 the [get started example](https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows) uses [StochasticDualCoordinateAscentClassifier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.stochasticdualcoordinateascentclassifier?view=ml-dotnet) 

Other multiclass classification trainers in ML.NET are
- [LogisticRegressionClassifier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.logisticregressionclassifier?view=ml-dotnet)
- [NaiveBayesClassifier](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.trainers.naivebayesclassifier?view=ml-dotnet)

The topic that describes ML.NET trainers is under construction; see PR #5698

**Comment by bs6523** [comment] 2018-06-16 21:38
Do you have any tutorials for this?

**Comment by pkulikov** [comment] 2018-06-16 21:50
> Do you have any tutorials for this?

To my knowledge, there is only the [one linked earlier](https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows).

**Comment by bs6523** [comment] 2018-06-17 16:13
that one is not working in my case, I want to classify sentiment as Neutral, Positive and negative, do you have any idea about this?

**Comment by pkulikov** [comment] 2018-06-17 16:19
What makes you think that that is not working in your case?

**Comment by bs6523** [comment] 2018-06-17 16:44
the training file in the tutorial is numbers, but in my case, it will be text with values 
example 
"Hi how are you" 0
"I am sad" 1
"I am good " 2

0 - neutral
1 - negative 
2 - positive

**Comment by pkulikov** [comment] 2018-06-17 17:15
The [training file](https://github.com/dotnet/machinelearning/blob/master/test/data/wikipedia-detox-250-line-data.tsv) in the tutorial has the same structure as in your example, except the two columns are swapped (value - text). 

Or we look at different files?

**Comment by bs6523** [comment] 2018-06-17 17:28
[Data](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data)
Yes, the data set you provided from the tutorial that used Binary classifier, it's working for me, 
but i am trying with StochasticDualCoordinateAscentClassifier with https://www.microsoft.com/net/learn/apps/machine-learning-and-ai/ml-dotnet/get-started/windows
tutorial,

**Comment by pkulikov** [comment] 2018-06-17 17:50
What happens if you try to use the [sentiment analysis](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis) tutorial with `StochasticDualCoordinateAscentClassifier`?

**Comment by bs6523** [comment] 2018-06-17 22:33
its giving error, because the formats are different, the tutorial is for FastTreeBinaryClassifier,

**Comment by pkulikov** [comment] 2018-06-18 05:54
@bs6523 oh! that's becoming interesting.

Try this one in the `Train` method:
```csharp
pipeline.Add(new Dictionarizer("Label"));
pipeline.Add(new TextFeaturizer("Features", "SentimentText"));
pipeline.Add(new StochasticDualCoordinateAscentClassifier());
pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });
```

And also update the `SentimentPrediction` class to use `float` type for the field:
```csharp
public class SentimentPrediction
{
    [ColumnName("PredictedLabel")]
    public float Sentiment;
}
```

Of course, you should update the `Evaluate` method as well:
```csharp
var testData = new TextLoader(_testDataPath).CreateFrom<SentimentData>();
var evaluator = new ClassificationEvaluator();
ClassificationMetrics metrics = evaluator.Evaluate(model, testData);
```

That would break the code that displays metrics, because `ClassificationMetrics` has other properties. Check [its API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.models.classificationmetrics?view=ml-dotnet) to decide what metrics you would like to see.

I hope that helps.

**Comment by bs6523** [comment] 2018-06-18 16:40
`using System;
using Microsoft.ML.Models;
using Microsoft.ML.Runtime;
using Microsoft.ML.Runtime.Api;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using System.Collections.Generic;
using System.Linq;
using Microsoft.ML;

namespace FMSforTelicom.Models
{
    public class SentimentData
    {
        [Column(ordinal: "0")]
        public string SentimentText;
        [Column(ordinal: "1", name: "Label")]
        public float Sentiment;
    }

    public class SentimentPrediction
    {
        [ColumnName("PredictedLabel")]
        public float Sentiment;
    }

    public static class Globals
    {
        public static PredictionModel<SentimentData, SentimentPrediction> model_Sentiment;
    }

    class SentimentAnalysis
    {
        const string _dataPathNeutral = @"..\Sentiment_Training_Data\sentiment labelled sentences\Training_NeuNonneu.txt";
        const string _dataPathPosNeg = @"..\Sentiment_Training_Data\sentiment labelled sentences\Training_PosNeg.txt";
        const string _testDataPathPosNeg = @"..\Sentiment_Training_Data\sentiment labelled sentences\Evaluate_PosNeg.txt";
        const string _testDataPathNeuNonneu = @"..\Sentiment_Training_Data\sentiment labelled sentences\Evaluate_NeuNonneu.txt";


        static void Main(string[] args)
        {
            SentimentAnalysis.Training();
            String Sentiment = SentimentAnalysis.Predict("how are you doing, i am not good today");
            Console.Read();
        }


        public static void Training()
        {

            var pipeline = new LearningPipeline();
            pipeline.Add(new TextLoader<SentimentData>(_dataPathNeutral, useHeader: false, separator: "tab"));
            pipeline.Add(new Dictionarizer("Label"));
            pipeline.Add(new TextFeaturizer("Features", "SentimentText"));
            pipeline.Add(new StochasticDualCoordinateAscentClassifier());
            pipeline.Add(new PredictedLabelColumnOriginalValueConverter() { PredictedLabelColumn = "PredictedLabel" });


            //  var testData = new TextLoader(_testDataPath).CreateFrom<SentimentData>();
            //  var evaluator = new ClassificationEvaluator();
            //  ClassificationMetrics metrics = evaluator.Evaluate(model, testData);


           Globals.model_Sentiment = pipeline.Train<SentimentData, SentimentPrediction>();

            //training end
        }


        public static String Predict(String text)
        {
            String _Sentiment = "Null";
            String _SentimentText = text;

            IEnumerable<SentimentData> sentiments = new[]{
            new SentimentData{
              SentimentText = _SentimentText,
              Sentiment = 0
              },
            };

            IEnumerable<SentimentPrediction> predictions = Globals.model_Sentiment.Predict(sentiments);
 
            Console.WriteLine();
            Console.WriteLine("Sentiment Predictions");
            Console.WriteLine("---------------------");

            Console.WriteLine("Text: " + predictions.ToList()[0].Sentiment);

            return _Sentiment;
        }
    }
}`


this is my code, I am getting this error 

> System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
InvalidOperationException: Source column 'Label' is required but not found

**Comment by Dirkster99** [comment] 2018-06-18 16:43
I saw this and got this MultiClass language classification to work (I also had an Exception on my first trial - these exception are realy not helpful unless you know what it means :-) ...

https://github.com/Dirkster99/ML/tree/master/source/MultibleClasses

**Comment by pkulikov** [comment] 2018-06-18 16:53
@bs6523 do you use the latest version of the library: 0.2?

**Comment by Dirkster99** [comment] 2018-06-18 17:01
yes

**Comment by bs6523** [comment] 2018-06-18 19:43
pipeline.Add(new TextLoader<SentimentData>(_dataPathNeutral, useHeader: false, separator: "tab"));
any replacement for this line after updating to .ML 0.2.0? (not working ufter updating)

**Comment by Dirkster99** [comment] 2018-06-18 19:54
Yes there is a syntax change between 0.1 and 0.2, consider something like this:
`new TextLoader(dataPath).CreateFrom<Digit>(separator: ',', allowQuotedStrings:false)`

from here:
https://github.com/Dirkster99/ML/blob/bbda50bee5b8f0d086fce50d7b28f61a00a21c17/source/IrisDataset/Models/PredictDigits/PredictDigit.cs

Your solution is probably something like this (useHeader: false is default):
`new TextLoader(_dataPathNeutral).CreateFrom<Digit>(separator: '\t')`

**Comment by JRAlexander** [comment] 2018-06-18 19:54
Try new pipeline.Add(new TextLoader(_dataPathNeutral).CreateFrom<SentimentData>(useHeader:false, separator:','));

**Comment by bs6523** [comment] 2018-06-18 20:58
@pkulikov  the code is working after updating to 0.2.0
@Dirkster99  @JRAlexander  thanks for the code, its working fine, 

anyone know how is "StochasticDualCoordinateAscentClassifier()" working? is there any explanation for that? i cant understand how its working in background

**Comment by pkulikov** [comment] 2018-06-18 23:23
@bs6523 

> anyone know how is "StochasticDualCoordinateAscentClassifier()" working? is there any explanation for that? I cant understand how it's working in the background.
Is it a neural net model or some other model?

Current docs don't explain learners in detail. The mentioned learner might be [that one](http://www.vlfeat.org/api/svm-sdca.html). In any case, if you ask this question in the [ML.NET repo](https://github.com/dotnet/machinelearning/issues) itself, the probability to get an answer is higher.

**Comment by bs6523** [comment] 2018-06-21 23:40
@pkulikov 
do you know how to get this values? 
    
     Accuracy: 
     Auc:
     F1Score: 
     Negative Precision: 
     Positive Precision: 
     Negative Recal: 
     Positive Recall

usign var evaluator = new ClassificationEvaluator();?

I used **BinaryClassificationEvaluator** and got these scores but for **ClassificationEvaluator** it's not working,

**Comment by pkulikov** [comment] 2018-06-22 05:58
@bs6523 muliclass classification has other set of evaluation metrics. Check the [properties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.models.classificationmetrics?view=ml-dotnet) of the **ClassificationMetrics** class. For example, you can get [confusion matrix](https://en.wikipedia.org/wiki/Confusion_matrix) by [ClassificationMetrics.ConfusionMatrix](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.models.classificationmetrics.confusionmatrix?view=ml-dotnet#Microsoft_ML_Models_ClassificationMetrics_ConfusionMatrix) property.

**Comment by JRAlexander** [comment] 2018-07-09 23:07
Closing this as it appears resolved.

**Closed by JRAlexander** 2018-07-09 23:07 UTC
Labels: Source - Docs.ms
