### ISSUE TITLE
This page needs to be updated for latest VS 2019 - only core apps offer "Publish to folder"

### ISSUE THREAD

**Issue by paszesoft** [dotnet/docs#24455] opened 2021-05-30 14:13 UTC
The page [Tutorial: Publish a .NET console application using Visual Studio for Mac](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio-mac)  
[Enter feedback here] is based on [Tutorial: Create a .NET console application using Visual Studio for Mac](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac) 
Both pages currently talk about non-Core apps. The current VS 2019 requires the app to be .Net Core to offer the "Publish to Folder" menu item. For non-Core apps the button is not present.

Suggestion - the whole tutorial series for macOs may need to be updated to use the .Net Core Console App, rather than the classic .Net Console App. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f63ffef8-9e15-1382-1c14-0888b7fe7414
* Version Independent ID: a4ec3817-940b-16c2-b1e9-68412301ef94
* Content: [Publish a .NET console application using Visual Studio for Mac - .NET](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio-mac)
* Content Source: [docs/core/tutorials/publishing-with-visual-studio-mac.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/publishing-with-visual-studio-mac.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by tdykstra** [comment] 2021-06-03 19:54
The "create" tutorial has you create a .NET 5.0 project. [.NET 5.0 is the same implementation of .NET as .NET Core](https://docs.microsoft.com/en-us/dotnet/standard/glossary#net-5-and-later-versions). Is your VS 2019 version 8.8 or later?

**Comment by paszesoft** [comment] 2021-06-03 20:08
Latest stable, yes

**Comment by tdykstra** [comment] 2021-06-03 20:12
Then if you created a .NET 5 console app, you did create a .NET Core console app, it just doesn't have "Core" in the name starting with version 5.

**Comment by paszesoft** [comment] 2021-06-03 21:04
that may be so, yet the debug behaviour for the 2 apps differ.

The explicit CORE app debugs fine, while the other shows some bugs - in the
debugger :) like conditional breakpoint not being hit when it should on:
String.IsNullOrEmty(name) where name was assigned "", would not break...

**Comment by tdykstra** [comment] 2021-06-03 21:11
That would be an issue with Visual Studio for Mac -- see the top of the [Create tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/with-visual-studio-mac) for ways to report issues to the VS Mac development team.

**Comment by tdykstra** [comment] 2021-07-08 17:09
Closing, as it appears the issue is with VS for Mac rather than the documentation.

**Closed by tdykstra** 2021-07-08 17:09 UTC
Labels: Pri2, dotnet-fundamentals/prod
