### ISSUE TITLE
Mixed language article in VB guide

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#13619] opened 2019-07-29 08:13 UTC
The article exists in Visual Basic Guide, However, it as some code written in C#
It's also NOT the same code snippet written in both languages, but a class is written in C#, and it's used in visual basic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79aab2e-8c3d-2878-14ff-064e098db357
* Version Independent ID: 0b7fbd1d-eb37-c6f8-25cc-100a63e7623b
* Content: [Ref Return Values (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/procedures/ref-return-values)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/ref-return-values.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/language-features/procedures/ref-return-values.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Thraka** [comment] 2019-07-29 14:53
YIKES! Thank you for spotting this and reporting it!

**Comment by Thraka** [comment] 2019-07-29 14:54
@rpetrusha @KathleenDollard The article was ported but not scrubbed well. Lots of links to CS code and even mentions C# quite a bit.

**Comment by pkulikov** [comment] 2019-07-29 15:59
Isn't it by design? The second paragraph of the article starts with:
>Visual Basic does not allow you to author methods with reference return values, but it does allow you to consume reference return values. 

So, I would expect some C# code that defines a method with a ref return and Visual Basic code that calls that method. The current article seems to do that.

**Comment by rpetrusha** [comment] 2019-07-29 18:05
Thanks for raising the issue, @Youssef1313. Yes, it's by design, as @pkulikov points out. Reference return values can't be defined in Visual Basic; they can only be consumed. So the examples use C# code to define a reference return value, and the Visual Basic code consumes it.

I'll close this issue as by design. If you think that that the reason for the presence of C# examples and the for the discussion of C# needs to be made clearer, @Youssef1313, feel free to submit a PR.

**Closed** 2019-07-29 18:05 UTC
Labels: :books: Area - Visual Basic Guide, Source - Docs.ms, by-design
