### ISSUE TITLE
this does not work

### ISSUE THREAD

**Issue by darkoverlordofdata** [dotnet/docs#18220] opened 2020-05-02 05:18 UTC
The following packages have unmet dependencies:
 dotnet-sdk-3.1 : Depends: dotnet-runtime-3.1 (&gt;= 3.1.3) but it is not going to be installed
                  Depends: aspnetcore-runtime-3.1 (&gt;= 3.1.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Biep** [comment] 2020-05-02 15:00
I have a comparable issue.
De volgende pakketten hebben niet-voldane vereisten:
 dotnet-sdk-3.1 : Vereisten: dotnet-runtime-3.1 (>= 3.1.3) maar het zal niet geïnstalleerd worden
                  Vereisten: aspnetcore-runtime-3.1 (>= 3.1.3) maar het zal niet geïnstalleerd worden
E: Kan problemen niet verhelpen, u houdt defecte pakketten vast.

**Comment by Dutchglory** [comment] 2020-05-03 13:03
The following packages have unmet requirements:
  dotnet-runtime-deps-3.1: Requirements: libicu but it is not installable or
                                       libicu63 but it is not installable or
                                       libicu60 but it is not installable or
                                       libicu57 but it is not installable or
                                       libicu55 but it is not installable or
                                       libicu52 but it is not installable
E: Can't fix problems, you are holding defective packages.

**Comment by Biep** [comment] 2020-05-03 13:05
The following solves it:
wget http://mirrors.edge.kernel.org/ubuntu/pool/main/i/icu/libicu63_63.2-2_amd64.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt update

**Comment by darkoverlordofdata** [comment] 2020-05-03 17:09
Close, but that also get's an error:
sudo dpkg -i packages-microsoft-prod.deb
dpkg: error: cannot access archive 'packages-microsoft-prod.deb': No such file or directory
darko@barsoomian:~$ 

So I tried it this way and it works now:
sudo dpkg -i ./libicu63_63.2-2_amd64.deb

**Comment by Thraka** [comment] 2020-05-04 17:34
@rbhanda @leecow can you help?

**Comment by leecow** [comment] 2020-05-04 23:20
What version of Ubuntu are you trying to install to? If it's 20.04, those packages (and install instructions) will be available 5/12.

**Comment by Rick-Anderson** [comment] 2020-05-05 22:03
Dup of #17638 and Dup of #18255

**Comment by Thraka** [comment] 2020-05-06 17:06
Closing with the assumption the customer is trying to install on 20.04

**Comment by Thraka** [comment] 2020-05-06 17:07
Duplicate of #17638

**Closed by Thraka** 2020-05-06 17:07 UTC
Labels: :books: Area - .NET Core Guide, product-feedback
