### ISSUE TITLE
Stop!  And bring back the documentation on MSDN!

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/docs#13527] opened 2019-07-23 21:02 UTC
Please stop messing up the documentation!!!

Bring back everything as it was on MSDN and keep it there until you get this new system working, because as it is now, it is not working!!!

Just look at this page (just an example, there are thousand others with the same quality)
https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_read_usn_journal

And then compare it to the old page on MSDN:
https://msdn.microsoft.com/en-us/ie/aa364563(v=vs.100)

**Comment by drewbatgit** [comment] 2019-07-23 22:19
Thanks for your feedback. I apologize for the negative experience you are having with the documentation. Unfortunately we are unable to revert back to MSDN, so the only solution is to fix issues as they are reported. This particular issue is related to a technical issue our new system is having with IOCTLs. This is a known issue that is being tracked in a bug by our engineering team. I will follow up with team and revisit the priority of this issue and try to get it fixed ASAP. Please let us know if you find issues in other page types. Thank you for your help in improving the docs and helping the issues introduced by our migration to a new content publishing system.

**Comment by Bartolomeus-649** [comment] 2019-07-25 12:45
The documentation on msdn had evolved over decades!
So what's the logic behind deleting stuff from MSDN and making it unsearchable before you have migrated it?
And this new system is a complete mess, no logic to it whatsoever, impossible to navigate in a productive way, don't integrate with Visual Studio, broken links all over the place, links to pages that when you navigate to them you are told they are "old" and not maintained" and then you are told to go to the "new documentation" which brings you to the root page of the documentation site.
who ever thought this was a great idea?

And on top of this, thousands upon thousands of links to articles, KB-articles, blog posts, MSDN-Journal articles and more, are now broken not only on microsoft pages, but also on pages all over the Internet.
Samples referred to in SDKs and other places are gone, there's no end to the mess you have created!
Decades of knowledge and information just gone!

**Comment by mairaw** [comment] 2019-09-11 18:57
Given that going back to MSDN is not an option, I'm closing this issue.

@drewbatgit feel free to update this thread when the issue is addressed on that Windows content.

For content that doesn't have the feedback button, the best option is to use the site feedback link at the bottom: https://aka.ms/sitefeedback

**Closed by mairaw** 2019-09-11 18:57 UTC
Labels: external, waiting-on-feedback
