### ISSUE TITLE
Suggestion for improvement: add notion of "multiple executors" - only in context of "multiple executors" async programming makes sense

### ISSUE THREAD

**Issue by DmitrySemikin** [dotnet/docs#32643] opened 2022-11-17 12:31 UTC
Hello. 

The article is good, but in my opinion it lacks one fundamental point, and without this point async programming (and correspondingly async-await) dooes not make much sense.

In my opinion async programming only makes sense, when there are multiple "executors" present, i.e. multiple "objects", which can execute tasks, of which our program consists. If there is only one "executor" (i.e. the program runs on one PC, which has only one processor - and we do not consider logical threads and scheduling for simplicity), then it does not make sense to try to parallel the work. We can schedule tasks to be executed in parallel, but they will anyway be executed sequentially.

it all looks different, when we for example have two or more processors. Then we can start multiple tasks simultaneously and have our job done faster this way. In the metaphor used in the article it would be similar to the situation, when there are multiple cooks, so one cook can make a toast and another can make a tea. The third one cannot put butter on the toast until it is toasted though...

Another possibility is, that we send our job to some external executor. E.g. we send some request to the external server and wait for the response. It fits very well to the metaphor of the article. Indeed, when we put a bread into toaster and turn it on we like sending the request to the toaster to prepare our toast. The response with the toast takes a while and the cook is not busy at this time (job is outsourced to the external executor - toaster). Thus it makes sense to start doing some other task.

I really believe, that introducing this notion of executors into the article would make much more sense out of the async programming. Besides it would provide ground for discussion of more complicated concepts. E.g., that if we have multiple executors, then someone need to orchestrate them, - consider the metaphor with multiple cooks... and by the way, it is possible, that one cook starts cooking the dish, but another one finishes it...

I hope, those thoughts may help improve your content.

Best Regards,
Dmitrii.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17d27a0d-c072-8c9f-7e31-3de60bee9ae8
* Version Independent ID: e0c09794-e712-19ff-cb9f-12648d60d4f6
* Content: [Asynchronous programming in C#](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/?source=docs)
* Content Source: [docs/csharp/programming-guide/concepts/async/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/concepts/async/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-11-17 16:25
Hi @DmitrySemikin 

This is a common misconception. In fact, asynchronous programming is useful even with only one CPU or core. It's important to make the distinction between *asynchronous* programming and *multi-threaded programming*. 

Consider a program that consumes a network endpoint, using REST over HTTP for example. Once the program makes the request, the CPU could do other work while awaiting the network response. Asynchronous requests make that possible.

I'll close this as by design.

**Closed by BillWagner** 2022-11-17 16:25 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-async/tech
