### ISSUE TITLE
Text and example mismatch

### ISSUE THREAD

**Issue by stevebroshar** [dotnet/docs#19014] opened 2020-06-19 10:10 UTC
Text says "Do not use implicit typing to determine the type of the loop variable in foreach loops."
But example uses implicit: foreach (var ch in laugh)

My guess is that the text is wrong. At least I always use implicit for foreach.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-06-19 13:48
duplicate of #18900

**Closed by BillWagner** 2020-06-19 13:48 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged

**Comment by stevebroshar** [comment] 2020-06-19 15:07
Well, mine is a little different. I think the recommendation (text) should change; not the example.
