### ISSUE TITLE
Business logic inside queries 

### ISSUE THREAD

**Issue by gmatv** [dotnet/docs#6749] opened 2018-07-31 06:45 UTC
One question bothers me when I see such code inside queries 

    SUM(oi.units*oi.unitprice) as total

Isn't it a part of business logic and we have duplication here? Yes, in this case it looks simple but imagine if it will invovle, for example, discount system.

To compare, the same in domain model: [Order.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.Domain/AggregatesModel/OrderAggregate/Order.cs)

        public decimal GetTotal()
        {
            return _orderItems.Sum(o => o.GetUnits() * o.GetUnitPrice());
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24f63ac2-6309-006c-0c94-1dd65194ca06
* Version Independent ID: c235e2be-f005-f889-51df-33e1b1cf0b7e
* Content: [Implementing reads/queries in a CQRS microservice](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads)
* Content Source: [docs/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment] 2018-10-09 12:30
Hi @gmatv,

That wouldn't qualify as "business logic", it's just a simple math.

However, I do agree simple math can be not so simple, when you have to consider issues such as different tax rates per item.

A complex discount system would qualify as business logic

But then again, if that were the case, you would have to handle the complex calculation inside the Order and have it persisted, so you could use it in the query.

In this particular case we can't use GetTotal() in the query, because we are using CQRS and the query part is handled by Dapper, as plain SQL queries to the base tables and the order total is not persisted.

So, as usual, it depends on the context. 

If you had to handle complex calculations AND were using CQRS with Dapper, you would have to calculate internally and persist the value. 

If you where Using EF you could just call Order.GetTotal() although that could impose a heavy load on the system, or perhaps not, if you are handling a small number of orders anyway.

IMHO, in the context of this application, as a learning resource for microservices architecture, it's ok just the way it is. 

I would even add that just because of the fact it raises this kind of dicusions.

Hope this helps.

**Comment by mairaw** [comment] 2019-07-30 23:20
should we close this as by design @mvelosop?

**Comment by mvelosop** [comment] 2019-08-07 17:56
Hi @mairaw, yes it's ok to just close it, so doing it now!

**Closed by mvelosop** 2019-08-07 17:56 UTC
Labels: :book: guide - .NET Microservices, :books: Area - .NET Guide, :card_file_box: Technology - .NET Architecture, Source - Docs.ms
