### ISSUE TITLE
how to recover from that issue

### ISSUE THREAD

**Issue by PRITIPATEL02** [dotnet/docs#35580] opened 2023-05-31 22:24 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 396c23ca-a799-032b-527b-d9362e44b514
* Version Independent ID: 884704df-8e4c-2dde-8c2d-96287f8d673d
* Content: [Compiler Error CS0229](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0229?f1url=%3FappId%3Droslyn%26k%3Dk(CS0229))
* Content Source: [docs/csharp/language-reference/compiler-messages/cs0229.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-messages/cs0229.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**
<img width="960" alt="sheets" src="https://github.com/dotnet/docs/assets/133033747/f3a150ca-885d-4c40-bb9d-9dff89feb107">

**Comment by BillWagner** [comment] 2023-06-01 13:49
Hi @PRITIPATEL02 

I can't tell the answer from the screenshot you added here. 

In general, this error is because a name could resolve to multiple objects. You have to specify which of the types are in use.

In COM interop, it can also be caused by importing multiple versions of the same interface. 

I'd check both of those, and if neither help resolve the issue, you should post a follow up on our [Q & A](https://learn.microsoft.com/answers/tags/321/office-development) section. That area is better for specific support questions.

I'll close this as a support request.

**Closed by BillWagner** 2023-06-01 13:49 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-diagnostics/tech
