### ISSUE TITLE
Please update dox for .Net Core 3

### ISSUE THREAD

**Issue by djaus2** [dotnet/docs#15981] opened 2019-11-26 04:30 UTC
[Enter feedback here]
Please update dox for .Net Core 3   and Visual Studio 16.3 (or later)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50511188-600e-18f6-6d92-c93b135d3db6
* Version Independent ID: 559262e6-f27b-e581-255f-0967b006a922
* Content: [Deploy .NET Core apps with Visual Studio - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?toc=%2Fvisualstudio%2Fdeployment%2Ftoc.json&bc=%2Fvisualstudio%2Fdeployment%2F_breadcrumb%2Ftoc.json&tabs=vs156)
* Content Source: [docs/core/deploying/deploy-with-vs.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/deploy-with-vs.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment] 2019-11-27 20:45
@djaus2 Thank you for opening this issue. We have another issue tracking this work, which we want to get to next month. I'm going to close this one as duplicate. This whole "deploying" area will be looked at as a whole. Thanks again.

**Comment by Thraka** [comment] 2019-11-27 20:45
Duplicate of #15081

**Closed** 2019-11-27 20:45 UTC
Labels: :books: Area - .NET Core Guide, duplicate
