### ISSUE TITLE
Documentation for CA1848 and CA1727 doesn't exist.

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [dotnet/docs#27144] opened 2021-11-18 04:16 UTC
**Help us make content visible**

In Visual Studio, clicking the warning `CS1848: For improved performance, use the LoggerMessage delegates instead of calling 'LoggerExtensions.LogInformation(ILogger, string, params object[])'` takes me to https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1848 , and clicking the warning `CA1727: Use PascalCase for named placeholders in the logging message template` takes me to https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1727

These pages don't exist.

**Describe the new article**

**Comment by Youssef1313** [comment] 2021-11-18 15:07
cc @maryamariyan

**Comment by gewarren** [comment] 2021-11-22 20:00
This page indicates that these are known gaps in the documention: https://github.com/dotnet/roslyn-analyzers/blob/9cd12bf61357662069562f350e1bf09a87a0940e/src/NetAnalyzers/RulesMissingDocumentation.md.

**Comment by Bosch-Eli-Black** [comment] 2021-11-23 06:29
Thanks, @gewarren 🙂

With VS2022 just released, I think a lot of people are going to start seeing these warnings 🙂

**Comment by gewarren** [comment] 2021-11-23 23:45
Closing this as a dupe of #23900.

**Closed by gewarren** 2021-11-23 23:45 UTC
Labels: :watch: Not Triaged, Pri3
