### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by cevergara-apex** [dotnet/docs#40294] opened 2024-04-02 17:38 UTC
### Type of issue

Missing information

### Description

[Enter feedback here]
This article is about 

- AsEnumerable
- AsQueryable
- Cast
- OfType
- ToArray
- ToDictionary
- ToList
- ToLookup

however non of the examples uses none of that!

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/linq/standard-query-operators/converting-data-types

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/linq/standard-query-operators/converting-data-types.md

### Document Version Independent Id

130b1e00-89df-3980-5731-1c8c11db2418

### Article author

@BillWagner

### Metadata

* ID: 547067ff-1368-4551-a2ed-8d7ea1b98781 
* Service: **dotnet-csharp**
* Sub-service: **csharp-linq**

**Comment by BillWagner** [comment] 2024-04-03 13:49
Hi @cevergara-apex 

I'm going to close this without action. It's true that this page doesn't have an example of each of these uses. That's by design. These other methods would be similar to using `Cast` as a method (none have a query expression syntax). You can find examples by clicking on any of the methods listed.

It's important to keep these docs on the concepts of LINQ, rather than a reference of every API available in the `System.Linq` namespace. That's what the API reference is for.

**Closed by BillWagner** 2024-04-03 13:49 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/svc, csharp-linq/subsvc
