### ISSUE TITLE
Broken formatting on Object.GetHashCode Method page

### ISSUE THREAD

**Issue by ChrisMaddock** [dotnet/docs#3678] opened 2017-11-14 14:46 UTC
There's various bits of broken formatting in the 'Notes to Inheritors' section of this page. 

https://docs.microsoft.com/en-gb/dotnet/api/system.object.gethashcode?view=netframework-4.7.1#Notes_to_Inheritors

- Backticks not being recognised
- Bulletted list being collapsed into inline text
- Broken keyword links (`[System.Object.Equals](xref:System.Object.Equals*)`)

Apologies - I'd send a PR myself, but I'm not familiar with the formatting required.

**Comment by svick** [comment] 2017-11-14 15:17
I think this is the same issue as https://github.com/dotnet/docs/issues/3652.

**Comment by ChrisMaddock** [comment] 2017-11-14 15:41
Thanks. I wondered if it might be part of a larger migration issue.

**Comment by mairaw** [comment] 2017-11-20 21:31
Thanks @ChrisMaddock. Yes, this is a larger migration issue. I'll close this one since we already have one covering this issue. We'll need a global fix for this and I believe our engineering team is already working on that.

Duplicate of #3652.

**Comment by mairaw** [comment] 2017-11-20 21:32
Duplicate of #3652.

**Closed by mairaw** 2017-11-20 21:32 UTC
