### ISSUE TITLE
Microsoft WCF Web Service Reference Provider Tool

### ISSUE THREAD

**Issue by lhuang** [dotnet/docs#5741] opened 2018-06-01 14:16 UTC
not on the list of services in vs 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e89651a-5ad9-c3f9-146f-8d87b87d9e11
* Version Independent ID: 85c0e55f-abc0-3b2d-409a-06042b1f3ebb
* Content: [Microsoft WCF Web Service Reference Provider Tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide)
* Content Source: [docs/core/additional-tools/wcf-web-service-reference-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/wcf-web-service-reference-guide.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **johalex**

**Comment by JRAlexander** [comment] 2018-06-01 17:12
@mlacouture, can you answer this?

**Comment by mlacouture** [comment] 2018-06-01 17:47
@lhuang, can you provide more details about what you are trying to do? what version of Visual Studio are you using? this connected service tool is available in VS 2017 v15.5 and later.  What project type are you working on? this is only available on .NET Core/Standard and ASP.NET Core projects.

**Comment by mlacouture** [comment] 2018-06-04 18:22
BTW: for technical questions about the tool please open issues at https://github.com/dotnet/wcf/issues/new as explained in the Feedback section of the doc. thanks,

**Comment by mairaw** [comment] 2018-07-09 20:10
@lhuang since we didn't have any answers back from you, I'm closing this issue. If you still have questions, please file an issue at https://github.com/dotnet/wcf/issues/new.

**Closed** 2018-07-09 20:10 UTC
Labels: Source - Docs.ms, needs-more-info, product-question

**Comment by dlussier** [comment] 2018-11-19 10:35
Using version 15.8.9 of Visual Studio Community 2017. Microsoft WCF Web Service Reference Provider Tool doesn't show up in my search results in the Extensions and Updates dialogue (likely what lhuang was initially reporting). To reproduce:
- Tools>Extensions and Updates
- Select Online from left menu
- Enter Microsoft WCF Web Service Reference Provider Tool into search box
This returns 5+ pages of results, likely due to "Microsoft" in the search criteria. Also the desired extension doesn't appear in the first page of results.
- Enter WCF Web Service Reference Provider Tool 
This returns 5+ pages of results as well, and the desired extension doesn't appear in the first page of results.

**Comment by mlacouture** [comment] 2018-12-05 20:19
@dlussier, this tool is part of Visual Studio and shows up for .NET Core projects only as explained in the [docs](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/wcf-web-service-reference-guide).
