### ISSUE TITLE
Show which package a class/method is part of

### ISSUE THREAD

**Issue by stevedesmond-ca** [dotnet/docs#25670] opened 2021-08-17 18:11 UTC
**Issue description**

It would be great if the .NET docs could show which package a class or method is part of (in addition to the namespace and assembly).

I wanted to add a JSON configuration file to a class. I eventually found that `IConfigurationRoot` was part of `Microsoft.Extensions.Configuration.Abstractions`, so I added that to my project.

I then needed to pass in a concrete configuration, which I knew to do via `new ConfigurationBuilder().Build()`, but that couldn't be found until I added the `Microsoft.Extensions.Configuration` package (as the `.Abstractions` obviously didn't have any concrete versions)

Then when I tried to add the `.AddJsonFile()` extension method, that couldn't be found either, since it's in the `Microsoft.Extensions.Configuration.Json` package.

All of these are in the same namespace, but spread across 3 different packages. It would be great if the .NET docs could show which package a class/method is part of (in addition to the namespace/assembly).

Alternatively, if there is always a 1:1 relationship between package and assembly, maybe that could be made clearer in the docs? Label as "Assembly/Package:"?

Note that this could also be a design issue with the `Microsoft.Extensions.Configuration` packages themselves, that could be combined into less fine-grained ones.

**Target framework**

- [x] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

Using .NET 5 for this app, but it applies across the board.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.411 [/usr/share/dotnet/sdk]
  5.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
</details>

**Comment by BillWagner** [comment] 2021-08-19 13:36
adding @gewarren @mimisasouvanh 

I think there's an internal work item tracking this request. Is that accurate?

**Comment by mimisasouvanh** [comment] 2021-08-19 21:51
We do. Here is an [internal item](https://ceapex.visualstudio.com/Engineering/_workitems/edit/433262/). This is also similar to https://github.com/MicrosoftDocs/feedback/issues/72

**Comment by gewarren** [comment] 2021-08-20 23:12
Closing as a duplicate of https://github.com/MicrosoftDocs/feedback/issues/3433.

**Closed by gewarren** 2021-08-20 23:12 UTC
Labels: :watch: Not Triaged, Pri3
