### ISSUE TITLE
Links to MSDN are broken.

### ISSUE THREAD

**Issue by voroninp** [dotnet/docs#17705] opened 2020-04-04 20:33 UTC
Cannot navigate to F# API reference.

For example: [Seq.reduce](https://msdn.microsoft.com/library/a2ad4f64-ac69-47d2-92f0-7173d9dfeae9)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67fae525-473a-3072-b024-6d91d0e033b9
* Version Independent ID: 6e162795-52bd-f9df-4105-6919c1c72c88
* Content: [Sequences - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/sequences#sorting-comparing-and-grouping)
* Content Source: [docs/fsharp/language-reference/sequences.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/sequences.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment] 2020-04-07 19:20
Thanks for letting us know. This is a duplicate of #17557.

**Closed by gewarren** 2020-04-07 19:20 UTC
Labels: :books: Area - F# Guide, :watch: Not Triaged
