### ISSUE TITLE
Why is it not allowed that a documentation text ends with an exclamation point

### ISSUE THREAD

**Issue by MarkusMeyer13** [dotnet/docs#22584] opened 2021-01-31 11:27 UTC
SA1629 requires that text ends with a period:

"A section of the Xml header documentation for a C# element does not end with a period (also known as a full stop)."

Why is not allowed to use an exclamation point?

**Valid:**
```
    /// <remarks>  
    /// Lorem Ipsum.
    /// </remarks>
```

```
    /// <remarks>  
    /// Lorem Ipsum!.
    /// </remarks>
```

**Invalid:**
```
    /// <remarks>  
    /// Lorem Ipsum!
    /// </remarks>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 306c4f25-192e-0980-c663-d829f38ef7c4
* Version Independent ID: 8918a37b-cbfa-33f1-21e2-6bf5ea3ccb54
* Content: [XML documentation comments - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/)
* Content Source: [docs/csharp/programming-guide/xmldoc/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-01-31 16:53
It's a third-party analyzer package, so it's unrelated to this repository. See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2724

**Comment by BillWagner** [comment] 2021-02-01 14:50
ping @sharwell 

Should this move to the DotNetAnalyzers repo?

**Comment by sharwell** [comment] 2021-02-01 15:03
Duplicate of DotNetAnalyzers/StyleCopAnalyzers#2724

**Closed by sharwell** 2021-02-01 15:03 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged, Pri1, csharp-fundamentals/tech, dotnet-csharp/prod
