### ISSUE TITLE
IsNullOrWhiteSpace with capital S not a "s".

### ISSUE THREAD

**Issue by viveleltsi** [dotnet/docs#9732] opened 2018-12-24 08:25 UTC
Hello
I think there's a mistake on the RegexUtilities class.
"
if (string.IsNullOrWhitespace(email))
            return false;
"
string.IsNullOrWhitespace(email) should be string.IsNullOrWhiteSpace(email) with a capital "S" at space not a "s").

I hope my comment will help.

Best regards

Dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to: Verify that Strings Are in Valid Email Format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2019-01-14 23:13
Thanks for your comment, @viveleltsi. In the C# code, the method call appears as is `string.IsNullOrWhiteSpace(email)`. Whether the type name is capitalized (`String`) or not (`string`) is a matter of coding style, since the C# `string` keyword is an alias for the .NET `String` class. Either form compiles successfully.
I'll close this issue as By Design.

**Comment by viveleltsi** [comment] 2019-01-15 05:51
I was talking to the name of the method not the string class. IsNullOrWhitespace do not work.

**Comment by StephaneMartignier** [comment] 2019-01-15 08:17
I agree with viveleltsi, the example is not working because there is a typo in the method name 'string.IsNullOrWhiteSpace(email)'. It's writtent 'IsNullOrWhitespace', missing the capital 'S' to 'space'.

He is not talking about the class name string.

**Comment by mairaw** [comment] 2019-01-15 18:37
Thank you for clarifying the issue. Reopening this.

**Closed** 2019-01-15 21:36 UTC
Labels: :books: Area - .NET Guide, :file_folder: Repo - samples, P1, Source - Docs.ms, doc-bug
