### ISSUE TITLE
how to get settings in console app 

### ISSUE THREAD

**Issue by figuerres** [dotnet/docs#26779] opened 2021-11-02 20:42 UTC
this works:

` static void Main(string[] args) { 
            IConfiguration Config = new ConfigurationBuilder().AddJsonFile("appSettings.json").Build();
            Settings options = new();
            Config.GetSection(nameof(Settings)).Bind(options);`

no host builder, no async no await no task......   
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b458a209-339d-e896-4e85-6d1c6a7aa1f9
* Version Independent ID: 0d5de37c-8f89-b6a5-3132-2c5214196bfd
* Content: [Configuration in .NET](https://docs.microsoft.com/en-us/dotnet/core/extensions/configuration)
* Content Source: [docs/core/extensions/configuration.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/configuration.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment] 2021-11-03 12:51
Closing this as it's a duplicate of #26769

**Closed by IEvangelist** 2021-11-03 12:51 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-fundamentals/prod
