### ISSUE TITLE
Bad command line practices

### ISSUE THREAD

**Issue by carlosporter** [dotnet/docs#16261] opened 2019-12-14 22:27 UTC
**Before you open an issue**

If the issue is:

- A simple typo or similar correction, you can submit a PR. See [the contributor guide](https://docs.microsoft.com/contribute/#quick-edits-to-existing-documents) for instructions.
- A general support question, consider asking on a support forum site.
- A site design concern, create an issue at [MicrosoftDocs/feedback](https://github.com/MicrosoftDocs/feedback/issues/new/choose).
- A problem completing a tutorial, compare your code with the completed sample.
- A duplicate of an open or closed issue, leave a comment on that issue.

**Issue description**

&lt;include description here&gt;

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by carlosporter** [comment] 2019-12-14 22:35
The commands used on this document are too redundant about the use of "apt-get update", you need to run the command only  once after installing the package packages-microsoft-prod.deb which adds the Microsoft repository.

It's not necessary to run "apt-get update" before every single "apt-get install" command

You can take this:
```
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-3.1
```

And just replease it with this:
```
sudo apt-get update
sudo apt-get install apt-transport-https dotnet-sdk-3.1 -y
```

**Comment by mairaw** [comment] 2019-12-16 03:56
Duplicate of #16262

**Closed by mairaw** 2019-12-16 03:56 UTC
Labels: :watch: Not Triaged
