### ISSUE TITLE
Make side bar collapsible

### ISSUE THREAD

**Issue by jgscherber** [dotnet/docs#6951] opened 2018-08-10 19:48 UTC
It would make the site easier to use if the side bar on the left was collapsible. When using the site is resized to only take up half the screen, like done by Windows when dragged to the edge of the screen, the side bar takes up over a quarter of the web page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a1a95c-8781-373d-679e-42785069b4af
* Version Independent ID: d4174861-aefd-2d26-81d2-fbf0de60f9d6
* Content: [Monitor Class (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.monitor?view=netframework-4.7.1#feedback)
* Content Source: [xml/System.Threading/Monitor.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/Monitor.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment] 2018-08-10 22:25
Thank you for your feedback @jgscherber. I'll be closing this one as a duplicate of https://github.com/MicrosoftDocs/feedback/issues/167.  You should follow progress there.

**Closed by mairaw** 2018-08-10 22:25 UTC
Labels: Source - Docs.ms, docs-experience, external
