### ISSUE TITLE
Document nint and nuint

### ISSUE THREAD

**Issue by canton7** [dotnet/docs#23269] opened 2021-03-10 08:59 UTC
I'm struggling to find any documentation on `nint` and `nuint`, introduced in C# 9, other than a brief mention on [What's new in C# 9.0](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#performance-and-interop) and the [proposal](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/native-integers).

Searching for `nint`, brings up the docs for the [Xamarin.iOS System.nint](https://docs.microsoft.com/en-us/dotnet/api/system.nint?view=xamarin-ios-sdk-12) struct, which is something completely different. Right now it's hard for someone to find out what an `nint` is, without being mislead

In addition to the page associated with this issue, I might have expected to see them on:

- [Built-in types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types)
- The [C# language spec](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#integral-types)
- Some other page which tells me that e.g. `nint.MaxValue` exists

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a22464d-b60c-36c0-e4e8-b209a33b0219
* Version Independent ID: cb500323-82a3-09ea-0468-dd16c9e13675
* Content: [Integral numeric types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#feedback)
* Content Source: [docs/csharp/language-reference/builtin-types/integral-numeric-types.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/integral-numeric-types.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-03-10 09:25
Related to https://github.com/dotnet/docs/issues/20582

**Comment by canton7** [comment] 2021-03-10 09:26
My bad, I missed that. Happy to close as a dup.

**Comment by BillWagner** [comment] 2021-03-10 16:00
Thanks @canton7 

This is on the list, and we should get to it shortly. In the meantime, we do publish the [feature spec}(https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/native-integers). I hope that answers your questions in the interim.

Closing as a duplicate of #20582

**Closed by BillWagner** 2021-03-10 16:00 UTC
Labels: :watch: Not Triaged, Pri1, csharp-language-reference/tech, dotnet-csharp/prod
