### ISSUE TITLE
Needed to modify Dockerfile

### ISSUE THREAD

**Issue by candlinpatrick** [dotnet/docs#38809] opened 2023-12-16 15:35 UTC
### Type of issue

Typo

### Description

[Enter feedback here]
I needed to modify the `Dockerfile` to the below
```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# # Copy everything
COPY . ./
# # Restore as distinct layers
RUN dotnet restore Dotnet.Docker.csproj
# # Build and publish a release
RUN dotnet publish -c Release -o out Dotnet.Docker.csproj

# # Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "DotNet.Docker.dll"]
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/docker/build-container?tabs=windows&pivots=dotnet-8-0

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/docker/build-container.md

### Document Version Independent Id

58d57b81-4ca6-6536-8788-f212402b41a7

### Article author

@IEvangelist

### Metadata

* ID: 4c7470d2-9a57-7654-e13a-4f912898f7aa 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-docker**

**Comment by IEvangelist** [comment] 2023-12-18 14:32
I just tested the article this AM and didn't experience an issue with the _Dockerfile_ as currently documented. If you're in the _App_ directory and follow along it should work without your suggested changes. I'm going to leave this as is and close this PR, as I'm not able to reproduce any errors. But I thank you for submitting this, and I'm happy to discuss it further if you believe I'm missing something.

**Closed by IEvangelist** 2023-12-18 14:32 UTC
Labels: docs-experience, Pri1, dotnet-fundamentals/prod, dotnet-docker/tech, okr-experience, :world_map: reQUEST

**Comment by candlinpatrick** [comment] 2023-12-18 14:45
Thanks @IEvangelist!
