### ISSUE TITLE
Wrong example code

### ISSUE THREAD

**Issue by brigo91** [dotnet/docs#39002] opened 2024-01-08 19:12 UTC
### Type of issue

Other (describe below)

### Description

Don't try to install the .NET 8.0 in the example.
Use the latest version instead.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu-2204.md

### Document Version Independent Id

909b29bd-2729-3b59-beb5-20a7281344d0

### Article author

@adegeo

### Metadata

* ID: 5ac16736-f225-12d0-2de2-efded54a505a 
* Product: **dotnet-fundamentals**
* Technology: **dotnet-install**

**Comment by adegeo** [comment] 2024-02-06 19:12
I'll be handling this in a different issue. Thank you for reporting!

**Comment by adegeo** [comment] 2024-02-06 19:12
Duplicate of #39263

**Closed by adegeo** 2024-02-06 19:12 UTC
Labels: doc-enhancement, Pri1, dotnet-fundamentals/svc, install/subsvc, dotnet-fundamentals/prod, dotnet-install/tech

**Comment by adegeo** [comment] 2024-02-06 19:29
test

**Comment by adegeo** [comment] 2024-02-06 19:31
Testing theory...
