### ISSUE TITLE
apt-get update

### ISSUE THREAD

**Issue by icelava** [dotnet/docs#21214] opened 2020-10-26 07:06 UTC
Why is _sudo apt-get update_ executed again after installing apt-transport-https?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET Core on Ubuntu - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-ubuntu.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2020-10-26 16:51
I don't remember, but I think it has something to do with the update being able to process more/different items after the transport package is added, something that hooks it together so that the step after works correctly. This was asked before but I can't find the issue.

Ahhhh Found it: https://github.com/dotnet/docs/issues/16262

**Comment by adegeo** [comment] 2020-10-26 16:51
Duplicate of #16262

**Closed by adegeo** 2020-10-26 16:51 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged
