### ISSUE TITLE
Unclear what is the earliest .Net/C# version for the described feature

### ISSUE THREAD

**Issue by virtuosummer4** [dotnet/docs#12151] opened 2019-05-02 11:26 UTC
I have been having trouble with other pages in the past as well: previously I remember seeing a note on the earliest C# version that supports the described feature in the documentation, but I cannot do that any more and every time I want to check if something works for the version I am dealing with, I have to spend 10-20 minutes searching online and in version notes to discover whether I should expect the feature to work or not.

Could you please include a note in the documentation of each feature on the earliest C#/.Net version that supports it?, or at least have some collapsible hint about it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d6e6220-cbdf-c81c-1f3f-eceaac577b3d
* Version Independent ID: d7516eb5-db45-8651-70a3-21115a4ba432
* Content: [nameof  - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/nameof#feedback)
* Content Source: [docs/csharp/language-reference/keywords/nameof.md](https://github.com/dotnet/docs/blob/staging/docs/csharp/language-reference/keywords/nameof.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-05-13 21:30
I'm going to close this as a duplicate of #6531 

The fix proposed there will address this as well.

**Closed by BillWagner** 2019-05-13 21:30 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, duplicate
