### ISSUE TITLE
KB2533623 (a .NET Core 3.1/.NET 5 necessary dependency) download links are broken

### ISSUE THREAD

**Issue by bairog** [dotnet/docs#21706] opened 2020-11-24 05:43 UTC
**KB2533623 (a .NET Core 3.1/.NET 5 necessary dependency) download links are broken**
On [.NET Core 3.1/.NET 5 dependency page](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50#dependencies) there is a link to [KB2533623](https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot). 
All links (for example for [Windows 7 x86](http://www.microsoft.com/download/details.aspx?familyid=c79c41b0-fbfb-4d61-b5d8-cadbe184b9fc) and for [Windows 7 x64](http://www.microsoft.com/download/details.aspx?familyid=146ed6f7-b605-4270-8ec4-b9f0f284bb9e)) are broken:
![image](https://user-images.githubusercontent.com/44995181/100053058-4ec87500-2e30-11eb-897c-620bb240c668.png)
Microsoft Update Catalog also contains only [Windows Vista variant](https://www.catalog.update.microsoft.com/Search.aspx?q=KB2533623).
Google found me a [topic on reddit ](https://www.reddit.com/r/windows/comments/ik7sp7/does_anybody_have_the_kb2533623_update_for/) where users have similar problems - the solution was to use [Web Archive link](https://web.archive.org/web/20200225191104/https://www.microsoft.com/en-us/download/details.aspx?id=26767).
Than is not normal way I think - correct all links ASAP please.
Thank you in advance.

**Target framework**

- [x ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

**Comment by adegeo** [comment] 2020-11-24 22:18
Duplicate of #20459

**Closed by adegeo** 2020-11-24 22:18 UTC
Labels: :watch: Not Triaged, Pri3
