### ISSUE TITLE
Not supported on .net core platform

### ISSUE THREAD

**Issue by svver** [dotnet/docs#5676] opened 2018-05-30 11:42 UTC
Though the method is available in .net core 2.x projects the System.PlatformNotSupportedException is thrown when you try to use it. I think that this info should be in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a8ddcfc-735a-b44c-ad27-7b84f2e21e76
* Version Independent ID: 56f5b699-5568-9d50-e720-b02d8015e007
* Content: [Assembly.ReflectionOnlyLoadFrom(String) Method (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.reflectiononlyloadfrom?view=netcore-2.0#feedback)
* Content Source: [xml/System.Reflection/Assembly.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/Assembly.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-05-31 18:49
Thanks @svver for the feedback. We could probably link to the chart types articles under https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/dd489233(v%3dvs.110) for more info for each chart type.

**Comment by mairaw** [comment] 2018-05-31 19:26
Thanks @svver for your feedback (and apologies for the wrong comment before). 

Yes, we have an issue created where we'd like to add this info to our API docs: #2934. The information would be based on the following page: https://github.com/dotnet/corefx/wiki/ApiCompat

However, I'm not seeing this particular API on that list. @pjanotti can you help?

**Comment by JRAlexander** [comment] 2018-07-23 20:35
Closing as duplicate of #2934. If this is not the case, then please reopen. Thanks!

**Comment by JRAlexander** [comment] 2018-07-23 20:39
@DnlHarvey and @jeffschwMSFT

**Closed by JRAlexander** 2018-07-23 20:39 UTC
Labels: :file_folder: Repo - dotnet-api-docs, Area - API Reference, Source - Docs.ms
