### ISSUE TITLE
dotnet core packages are missing from packages.microsoft.com

### ISSUE THREAD

**Issue by crisismaple** [dotnet/docs#24716] opened 2021-06-17 06:05 UTC
https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb shows 404 and all apt install command are failed due to packages not found in prod pool

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by Youssef1313** [comment] 2021-06-17 14:21
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by adegeo** [comment] 2021-06-17 15:44
I believe the main discussion is at dotnet/sdk#18304 hopefully it gets working 100% soon!

**Comment by adegeo** [comment] 2021-06-17 15:44
duplicate of #24711

**Comment by adegeo** [comment] 2021-06-17 15:44
duplicate of #24711

**Closed by adegeo** 2021-06-17 15:44 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
