### ISSUE TITLE
Parameterless constructors and field initializers – 0-bit pattern does not apply to `Nullable<T>` variables

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/docs#27178] opened 2021-11-19 14:18 UTC
> As the preceding example shows, the default value expression ignores a parameterless constructor and produces the default value of a structure type, which is the value produced by setting all value-type fields to their default values (the 0-bit pattern) and all reference-type fields to null.

This is slightly incomplete. See for instance [Default values of C# types (C# reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/default-values)

> An instance for which the HasValue property is false and the Value property is undefined. That default value is also known as the null value of a nullable value type.

Or quote from [Arrays (C# Programming Guide)|Array overview|Default value behaviour](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/#default-value-behaviour)

> * For value types, the array elements are initialized with the default value, the 0-bit pattern; the elements will have the value 0.
> * All the reference types (including the non-nullable), have the values null.
> * For nullable value types, HasValue is set to false and the elements would be set to null.

---

Thus reference to Default values of C# types (C# reference) could be more appropriate. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9220116-e950-04cf-b6d5-70d15a084a22
* Version Independent ID: 0960802e-80c3-cb56-cb8b-ab1f1b20fb4e
* Content: [Structure types - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#parameterless-constructors-and-field-initializers)
* Content Source: [docs/csharp/language-reference/builtin-types/struct.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/struct.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-11-19 14:49
This is actually correct: The [C# standard](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/structs#default-values) declares that all struct types are initialized to the 0 bit pattern. Therefore, a `Nullable<T>` does get initialized to the 0 bit pattern. The `Value` property is *undefined*, because any library implementation's behavior is not defined when `HasValue` is false. Namely, it can return 0, throw any exception, or implement some other behavior.

I'll close this as by design.

**Closed by BillWagner** 2021-11-19 14:49 UTC
Labels: :watch: Not Triaged, dotnet-csharp/prod, csharp-language-reference/tech

**Comment by Uzivatel919** [comment] 2021-11-19 16:21
Yes, you’re absolutely right. I verified it and _nullable value type_ is initialized the same as other _value types_. Both `default` and `new` end up using [_initobj_](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.initobj?view=net-6.0).

Specification is slightly misleading regard default value of _Nullable value type_ since denotes specific occasion while in fact there is not initialization behavioral change.

From [Default constructors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/types#default-constructors)
> For a nullable_type the default value is an instance for which the HasValue property is false and the Value property is undefined. The default value is also known as the null value of the nullable type.
