### ISSUE TITLE
Replace broken links in Exceptions section

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#5367] opened 2018-05-14 18:58 UTC
# Replace broken links in Exceptions section

In numerous cases, .NET for Windows Store apps and Portable Class Libraries throw a different exception than apps and libraries that target the .NET Framework.  In most of those cases, the exception information appears in Markdown format. However, since the \<exception> section is included in IntelliSense, it must be in XML format and should be enclosed in a `<see href=...>` element.

Typically, the offending text appears as follows: 

>  In the \[.NET for Windows Store apps](http://go.microsoft.com/fwlink/?LinkID=247912) or the \[Portable Class Library](~/docs/standard/cross-platform/cross-platform-development-with-the-portable-class-library.md), catch...

It should instead appear as:

> In \<see href="https://msdn.microsoft.com/library/windows/apps/br230232(v=vs.110).aspx">.NET for Windows Store apps\</see> or the \<see href="~/docs/standard/cross-platform/cross-platform-development-with-the-portable-class-library.md">Portable Class Library\</see>, catch...

**Comment by ChrisMaddock** [comment] 2018-05-15 19:07
@rpetrusha - out of interest, is this the same issue in the namespace summary's - like seen on pages like this one?

https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7.2

I'd assumed it was just a bug on docs.microsoft.com - didn't realise they needed to be that way for Intellisense. 🙂

**Comment by mairaw** [comment] 2018-05-15 19:13
Yes @ChrisMaddock. But I'll close this as a dupe of #1931. I'm not sure if the href works with the .md links though. I usually transform them into absolute paths. I'll need to test this.

**Comment by mairaw** [comment] 2018-05-15 19:13
Duplicate of #1931

**Closed by mairaw** 2018-05-15 19:13 UTC
Labels: :file_folder: Repo - dotnet-api-docs, Area - API Reference, migration-fixes

**Comment by mairaw** [comment] 2018-05-15 19:31
You can see an example of where I did this fix here for one summary: https://github.com/dotnet/dotnet-api-docs/pull/14/files
