### ISSUE TITLE
Missing compiler option: -features 

### ISSUE THREAD

**Issue by prjm** [dotnet/docs#8704] opened 2018-10-28 14:38 UTC
See also: https://stackoverflow.com/questions/37299549/how-to-specify-the-equivalent-of-featuresstrict-of-csc-exe-to-msbuild-exe-or

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b29fc27-0985-b3ea-e1d4-338c1dc126ed
* Version Independent ID: cc362e14-4bcb-0b38-36ce-9b8502e5e4e2
* Content: [C# Compiler Options Listed Alphabetically](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/listed-alphabetically)
* Content Source: [docs/csharp/language-reference/compiler-options/listed-alphabetically.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/listed-alphabetically.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment] 2018-10-28 19:39
I believe the `-features` switch is generally used for experimental features, so it's probably intentional that it's not documented.

**Comment by prjm** [comment] 2018-10-29 17:49
I did not know that this switch is only for experimental features. Still, I'd propose to include this switch in documentation: not its possible values but only the fact that this switch is only used for experimental features. So that uninformed people which stumble over it on StackOverflow can understand the purpose of the switch.

**Comment by BillWagner** [comment] 2018-11-29 02:15
ping @jcouv  for comments. I'm inclined to agree with @svick but I'd like confirmation.

**Comment by jcouv** [comment] 2018-11-29 03:53
Yes, `-features` is mostly used for experimental features. 
My initial inclination was that we should document the option minimally (just to acknowledge its existence). But then I noticed we don't even list it in `csc.exe -help`. That indicates it was intentionally left undocumented.
So I recognize the issue @prjm points out (potential confusion), but I think we still shouldn't document it.
 
Some background:
We're making decreasing use of this option. It was used for prototype features, but nowadays we tend to use branched code base instead.
It seems we currently support two features, but I wouldn't want to document either: 
- `strict` (which is a non-experimental feature, but will likely be superseded by warning waves)
- `peverify-compat` (which we'll probably remove some day). 
Last year we also had `IOperation` for a few months. We removed it once the feature shipped.

**Comment by BillWagner** [comment] 2018-11-29 14:54
Thanks for the additional notes @jcouv 

I'm closing this as by-design

**Closed by BillWagner** 2018-11-29 14:54 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged, Source - Docs.ms

**Comment by prjm** [comment] 2018-12-01 18:57
Thank you for the information - while I understand the reasoning not to document experimental flags, I think the switch name `feature` is misleading in this case - it suggests that there are optional (and stable) features which can be enabled.

**Comment by BillWagner** [comment] 2023-01-24 14:35
Hi @cremor 

Yes, those options exist. They are intended for internal use. They are for testing potential new features, or testing specific compiler code paths. 

In general, none of the options under `feature` flags are supported. They aren't documented by design.
