### ISSUE TITLE
Title 'Train model with real-time data' is misleading

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet/docs#11888] opened 2019-04-17 19:35 UTC
'real-time data' is usually related to events coming from devices or live info directly coming from user apps.
As soon as you have a database in between, that is usually not considered "real-time data".

Therefore, I think this page's title should be renamed to something like:
"Train model from other datasources such as databases" or simply "Train model from other datasources"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d52d4fbe-df9c-f410-85b4-786b139e94d3
* Version Independent ID: ce6265fd-1d0b-4d58-c60d-178d512486b4
* Content: [Train a machine learning model with data that's not in a text file - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/load-non-file-training-data-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/load-non-file-training-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/load-non-file-training-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by luisquintanilla** [comment] 2019-05-03 15:52
Duplicate of #11887

**Closed** 2019-05-03 15:53 UTC
Labels: :books: Area - ML.NET Guide, :watch: Not Triaged, Source - Docs.ms
