### ISSUE TITLE
Whole section set as hyperlink

### ISSUE THREAD

**Issue by mysteryx93** [dotnet/docs#18776] opened 2020-06-03 16:55 UTC
The section "Pattern matching with the switch statement" has a whole paragraph set with a hyperlink by mistake.

Also the entire section "The case statement and the when clause"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d9cc47-5caf-184a-0ad6-cb968850be7a
* Version Independent ID: f058bf17-04e9-9e23-05c7-66c1864445ad
* Content: [C# switch statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch)
* Content Source: [docs/csharp/language-reference/keywords/switch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/switch.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-06-04 14:10
Duplicate of #18784

**Closed by BillWagner** 2020-06-04 14:10 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged
