### ISSUE TITLE
C# version configuration intro implies it is discouraged and should be avoided

### ISSUE THREAD

**Issue by ite-klass** [dotnet/docs#14893] opened 2019-10-02 13:12 UTC
> If you must specify your C# version explicitly, you can do so in several ways:

The wording here with *must* implies that it should be avoided if possible.

I am currently looking at the using declarations introduced in C# 8.0 in .NET framework projects. We have been using `latest` in the past, and it automatically worked even for projects targeting .NET Framework 4.0. This tells me no additional requirements are necessary to use this even when the default for .NET Framework is 7.3 (in VS 2019).

Reading this article talking about defaults and [Relationships between language features and library types](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/relationships-between-language-and-library) talking about using newer versions for newer features and installing nuget packages where necessary tells me this is a valid use case.

The wording with *must* implies differently though.

Which one is it? I suspect the “if you must” should be weakened and elaborated to something like the following?

> If you decide to use a newer C# version for newer features and to manage where they are not immediately usable (see [Managing your dependencies](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/relationships-between-language-and-library#managing-your-dependencies)) you can do so in several ways:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-10-02 16:24
@ite-klass 

The language is correct here. Updating the language version for a different framework has many implications. Therefore, it's not officially supported. For example:

. The libraries for framework have not been annotated with nullable reference types. That means the nullable warnings are much less useful when targeting that framework.
. Some packages for necessary types are provided by 3rd parties. While we welcome that effort, we haven't validated those packages.
. New CLR support is required for default interface members.

What you've described above is an advanced scenario. I'm closing this as by design.

**Closed by BillWagner** 2019-10-02 16:24 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, by-design
