### ISSUE TITLE
Stream.Read reads all it can

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42836] opened 2024-10-04 14:13 UTC
### Type of issue

Typo

### Type of issue

Other (describe below)

### Description

From https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-7#net-libraries

> [Stream.Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read) may return less data than what's available in **the stream**.

In fact, `Read` can return less bytes than buffer size is. Meaning all stream bytes are read as long as buffer is capacitated for it.

See https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-8.0#system-io-stream-read(system-span((system-byte))).

> The total number of bytes read into the buffer. This can be less than the size of the buffer **if that many bytes are not currently available**, or zero (0) if the buffer's length is zero or the end of the stream has been reached.

### Research

I made some research and found no explenation under which condtion `Stream` would return less bytes than buffer capacity while having them. How it would be even possible to read it if it randomly returned not-all bytes?

FMPOV, description at https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-8.0#system-io-stream-read(system-span((system-byte))) is correct.

Is possible to return less data than buffer is sized because data are not available in _stream_. While data are available, they are returned, AFAIK.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-7

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-7.md

### Document Version Independent Id

0d5a2ef0-b8a5-181f-db39-5a0ad4c182ff

### Article author

@gewarren

### Metadata

* ID: 766e4a37-f4f9-be4e-f390-e03f5cbe62b4 
* Service: **dotnet-fundamentals**

---
This is recreation of https://github.com/dotnet/docs/issues/42496 which was closed by bot w/o option to reopen in error.

**Comment by adegeo** [comment] 2024-10-04 22:21
Duplicate of #42496

**Closed by adegeo** 2024-10-04 22:21 UTC
Labels: Pri2, dotnet-fundamentals/svc
