### ISSUE TITLE
API reference for many types is broken

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1910] opened 2017-04-14 15:40 UTC
When I go the API reference page for [`System.Windows.Controls.CheckBox`](https://docs.microsoft.com/en-us/dotnet/api/System.Windows.Controls.CheckBox?view=netframework-4.7) and click on the link to the `ToggleButton` type in the inheritance chain, lots of weird things happen:

* The URL and the linked page are actually about `ToggleButton.ToString`.
* The TOC seems to indicate this page is for `ToggleButton` itself and all if its members.
* Breadcrumbs say this page is about the `ToggleButton` constructor.
* The link to the `ToggleButton` type in breadcrumbs links back to `ToggleButton.ToString`.

This seems to affect many other types, including `CheckBox` (with different member for different types).

Changing the URL manually to https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.togglebutton?view=netframework-4.7 leads to the right page, even though it's not recognized by the TOC or breadcrumbs. (Though links from this page are still broken.)

**Comment by svick** [comment] 2017-04-14 15:52
Turns out this affects even types that worked fine few hours ago, like [`Regex`](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.system-runtime-serialization-iserializable-getobjectdata?view=netframework-4.7).

**Comment by svick** [comment] 2017-04-14 15:53
And I was too slow, this is a duplicate of https://github.com/dotnet/docs/issues/1909.

**Comment by rpetrusha** [comment] 2017-04-14 16:32
Thanks, @svick. I'm going to reopen this issue, since it illustrates that the problem is not confined to Regex. Also, thank you so very much for all the hard work you've put in to combing through docs.microsoft.com and identifying issues and bugs. I can't even begin to tell you how much we appreciate your effort.

**Comment by svick** [comment] 2017-04-14 16:46
@rpetrusha You're welcome 🙂 .

**Comment by rpetrusha** [comment] 2017-04-14 17:21
This issue also affects TimeZoneInfo; see #1911. It almost certainly affects numerous other types as well.
/cc @mduberstein

**Comment by rpetrusha** [comment] 2017-04-17 16:58
All of the types for which this behavior is reported now appear to work as expected; I can no longer reproduce this behavior anywhere in our doc set. I'm closing this issue.

**Closed by rpetrusha** 2017-04-17 16:58 UTC
Labels: Area - API Reference, bug, P0
