### ISSUE TITLE
Windows 7 support status unclear

### ISSUE THREAD

**Issue by weltkante** [dotnet/docs#20613] opened 2020-09-12 15:08 UTC
[This page](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#dependencies) says minimum client version for .NET Core 3 is Windows 8.1, yet the [page](https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1-supported-os.md) linked a few lines below says Windows 7 SP 1 is still supported.

This contradicts each other, please check and update the support status of Windows 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eeab451-820f-de42-983e-4d0d5764f6ab
* Version Independent ID: d11d0d14-8a03-50e4-5c00-9a4417ad4d0a
* Content: [Install .NET Core on Windows](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=netcore31#dependencies)
* Content Source: [docs/core/install/windows.md](https://github.com/dotnet/docs/blob/master/docs/core/install/windows.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2020-09-14 03:34
fyi @leecow 

Hi @weltkante I do have another issue opened to fix these discrepancies. Sorry for the confusion.

**Comment by adegeo** [comment] 2020-09-14 03:35
Duplicate of #19384

**Closed** 2020-09-14 03:42 UTC
Labels: :books: Area - .NET Core Guide, duplicate
