### ISSUE TITLE
Add remark to call GetType before calling GetClass

### ISSUE THREAD

**Issue by gewarren** [dotnet/docs#6013] opened 2018-06-18 20:52 UTC
This topic doesn't mention that you should call ICorDebugType::GetType before calling ICorDebugType::GetClass. Please update document to mention this.

This topic has the necessary information: https://technet.microsoft.com/nl-nl/library/ms230268(v=vs.100).aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74aa0f5a-088e-8a38-b052-d35b442b5088
* Version Independent ID: b23f3282-8517-b84d-3fe6-bbf38a8c0b16
* Content: [ICorDebugObjectValue::GetClass Method](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugobjectvalue-getclass-method)
* Content Source: [docs/framework/unmanaged-api/debugging/icordebugobjectvalue-getclass-method.md](https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/icordebugobjectvalue-getclass-method.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2018-06-18 21:56
@gewarren, given that ICorDebugType::GetType and ICorDebugType::GetClass are deprecated, the guidance to call ICorDebugType::GetType before calling ICorDebugType::GetClass was deliberately removed; the guidance is to call ICorDebugValue2::GetExactType instead. Since this was by design, I'm going to close this issue.  If you disagree, please feel free to respond.

**Closed by rpetrusha** 2018-06-18 21:56 UTC
Labels: :file_folder: Repo - docs, Area - .NET Framework Guide, triaged
