### ISSUE TITLE
Files are missing from server

### ISSUE THREAD

**Issue by DavidKurokawa** [dotnet/docs#24713] opened 2021-06-17 02:18 UTC
The packages-microsoft-prod.deb files are missing (at least right now). For example this leads to a 404:
https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by crisismaple** [comment] 2021-06-17 05:55
Same with 20.04

**Comment by Youssef1313** [comment] 2021-06-17 07:09
Also reported in https://github.com/dotnet/docs/issues/24711

**Comment by Youssef1313** [comment] 2021-06-17 14:21
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by adegeo** [comment] 2021-06-17 15:44
I believe the main discussion is at dotnet/sdk#18304 hopefully it gets working 100% soon!

**Comment by adegeo** [comment] 2021-06-17 15:44
Duplicate of #24711

**Closed by adegeo** 2021-06-17 15:44 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
