### ISSUE TITLE
Need more about usage of documentation of runtimeconfig.json

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/docs#4684] opened 2018-03-16 04:22 UTC
@vulcanlee commented on [Fri Dec 22 2017](https://github.com/dotnet/core/issues/1180)

Where can I find the detail usage and configuration content of runtimeconfig.json?

What about more detail of runtimeOptions, configProperties, applyPatches?

**Comment by mairaw** [comment] 2018-03-16 06:29
Duplicate of #2645

**Closed by mairaw** 2018-03-16 06:29 UTC
