### ISSUE TITLE
I couldn't understand the Indices example

### ISSUE THREAD

**Issue by taxpayer** [dotnet/docs#11641] opened 2019-04-03 10:34 UTC
&lt;code&gt;
Index i1 = 3;  // number 3 from beginning
Index i2 = ^4; // number 4 from end
int[] a = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
Console.WriteLine($"{a[i1]}, {a[i2]}"); // "3, 6"
&lt;/code&gt;

Why a[i1] shows "3" and a[i2] shows "6"? If I understood correctly, a[i1] should show the 3rd indexed item from the array, ie., "2". a[i2] should be the 4th indexed item from the end, ie., "6" (correctly shown). It wasn't clear if Index uses, as usual, a 0-based index. If so, a[i1] is showing correctly, but why a[i2] is showing "6" instead of "5"? From the end shouldn't it be 0-based indexed also?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [What's new in .NET Core 3.0](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#c-8)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs/blob/master/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by BillWagner** [comment] 2019-04-03 13:23
Thanks for taking the time to join the discussion @taxpayer 

The choice between inclusive and exclusive ranges was a difficult one to make. There are good arguments for either choice. In the end, the C# Language Design team decided to use exclusive ranges.  

We are going to thoroughly explain this decision between now and when .NET Core 3.0 ships (See #3966, which should be addressed this month.)

https://github.com/dotnet/docs/issues/3966#issuecomment-475614440 is a quick summary of the justification for exclusive ranges.

Closing as a duplicate.

/cc @Thraka

**Closed by BillWagner** 2019-04-03 13:23 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged, Source - Docs.ms

**Comment by taxpayer** [comment] 2019-04-03 13:46
@BillWagner I read your explanation but for me it's still confusing because it looks like it was chosen one logic for the beginning and another for the end (the ^x Indice) when it says in the example:

```
Index i1 = 3; // number 3 from beginning
Index i2 = ^4; // number 4 from end
```
"number 3 from beginning" sounds like "get the 3rd number from the beginning" as "number 4 from end" sounds like "take the fourth number counting from end".

I couldn't understand not because of the choice between inclusive and exclusive ranges, but why was it chosen to get the n-th element from begin using a 0-based index in an array (the usual) and not use the same logic the get the n-th element from the end.

**Comment by Thraka** [comment] 2019-04-03 23:33
Duplicate of #3966

**Comment by prashantalhat** [comment] 2019-06-18 03:06
I was going to write exactly same comment. Should be same logic for beginning and end index.
