### ISSUE TITLE
words[^1] is very ugly

### ISSUE THREAD

**Issue by newpost** [dotnet/docs#12696] opened 2019-06-06 04:17 UTC
words[^1] is very ugly.why not use words[-1]!!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [What's New in C# 8.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#readonly-members)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by svick** [comment] 2019-06-06 08:45
The reason is that `words[-1]` already means something: it throws `IndexOutOfRangeException`. It's very likely that there are programs out there that rely on that, which means changing the meaning of `words[-1]` would be a breaking change and C# is generally unwilling to have those.

**Comment by newpost** [comment] 2019-06-06 09:25
Is it meant to be compatible with previous versions?

**Comment by svick** [comment] 2019-06-06 09:29
It is meant to be backwards compatible: code you write in C# 7.x should work the same if you compile it as C# 8.0.

**Comment by Thraka** [comment] 2019-06-06 16:45
_copied from Bill's response in another issue_

The documentation does accurately reflect the language design choices.  

I am going to close this.  However, if you want to continue to advocate for a different design, consider commenting on the referenced design notes, or other issues on ranges in the [dotnet/csharplang](https://github.com/dotnet/csharplang) repository.

Duplicate of #11324

**Comment by Thraka** [comment] 2019-06-06 16:45
Duplicate of #11324

**Closed by Thraka** 2019-06-06 16:45 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged, Source - Docs.ms
