### ISSUE TITLE
Mutable readonly fields

### ISSUE THREAD

**Issue by berkarslan-cs** [dotnet/docs#9325] opened 2018-11-30 11:31 UTC
I see very useful cases of using mutable readonly types and I don't see why I shouldn't use it. For example, I wouldn't want my "private readonly List&lt;string&gt;" field to be assigned a new value by mistake. What's wrong with that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34bf1136-6fbf-dd12-71ec-bd4e7a75013a
* Version Independent ID: f184192b-0070-4e7b-09f5-bbf454f05c88
* Content: [Field Design](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/field)
* Content Source: [docs/standard/design-guidelines/field.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/field.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2019-01-14 23:38
Thanks for your feedback, @berkarslan-cs. As the documentation indicates, the problem with making a mutable type read-only is that, although the List\<string> in your example can't be assigned a different List<String> instance, an individual element in the collection can be modified. So in this case, `readonly` makes the developer's design intent clear, it doesn't fully enforce the rule that the members of the collection can be modified only in the instance constructor.
I hope that that helps to answer your question. I'll close this issue as By Design.

**Closed by rpetrusha** 2019-01-14 23:38 UTC
Labels: :books: Area - .NET Guide, Source - Docs.ms, by-design
