### ISSUE TITLE
What to use for ftp?

### ISSUE THREAD

**Issue by henrikmbach** [dotnet/docs#27081] opened 2021-11-15 11:22 UTC
HttpClient is no good for ftp, so what to use then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cef6c88-811c-4651-4e8f-87365a799dda
* Version Independent ID: 3d53a1d2-c6bf-7698-02ed-759679547f2b
* Content: [Breaking change: WebRequest, WebClient, and ServicePoint are obsolete - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated)
* Content Source: [docs/core/compatibility/networking/6.0/webrequest-deprecated.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/networking/6.0/webrequest-deprecated.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by vip-ehowlett** [comment] 2021-11-15 16:20
Had this same issue, https://github.com/dotnet/docs/issues/27028. It appears that it's no longer going to be supported and we have to use 3rd party libraries.

**Comment by gewarren** [comment] 2021-11-15 16:48
Closing this as a duplicate of #27028.

**Closed by gewarren** 2021-11-15 16:48 UTC
Labels: :watch: Not Triaged, dotnet-fundamentals/prod
