### ISSUE TITLE
Missing .editorconfig Setting

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/docs#23096] opened 2021-03-03 12:21 UTC
The following .editorconfig Settings is missing from this list:

```
dotnet_style_operator_placement_when_wrapping = end_of_line
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f19aa22-56d1-ff22-a410-e5e0b6a80e6d
* Version Independent ID: 012968d3-07d2-5c37-fa3d-e3561eff8681
* Content: [Code style language rules - .NET](https://docs.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/language-rules?view=vs-2019#parameter-preferences)
* Content Source: [docs/fundamentals/code-analysis/style-rules/language-rules.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/style-rules/language-rules.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment] 2021-03-03 13:05
@mavasani I don't see this is tied to any analyzer, but only used for code generation.

The list in this article is for options used by analyzers. Not sure where should this be documented and what other options might be missing.

**Comment by gewarren** [comment] 2021-03-04 17:44
It might belong somewhere in this area of the docs: https://docs.microsoft.com/en-us/visualstudio/ide/code-generation-in-visual-studio?view=vs-2019. @mikadumont, what do you think?

**Comment by Youssef1313** [comment] 2021-03-04 18:00
@gewarren Searched through VS Docs repo and found an issue there (https://github.com/MicrosoftDocs/visualstudio-docs/issues/3641), but it was actually moved here (https://github.com/dotnet/docs/issues/20884).

**Comment by gewarren** [comment] 2021-03-04 18:58
I guess I moved it because the article it was logged against in VS got "moved" to dotnet/docs. I might just reopen the original VS issue and log this as a duplicate of it. I'd like to hear what @mikadumont has to say though. This is a bit of a grey area.

**Comment by gewarren** [comment] 2022-06-30 21:13
I'm going to close this in favor of https://github.com/MicrosoftDocs/visualstudio-docs/issues/3641. This should be documented in the VS docs because there's no .NET analyzer.

**Closed by gewarren** 2022-06-30 21:13 UTC
Labels: doc-enhancement, Pri2, dotnet-fundamentals/prod
