### ISSUE TITLE
Replacement for makecert.exe

### ISSUE THREAD

**Issue by ThangHuuVu** [dotnet/docs#6391] opened 2018-07-10 10:28 UTC
makecert.exe is now deprecated. Please take a look at all the pages where it is mentioned and remove it. I suggest you can use New-SelfSignedCertificateEx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1e7ee35-26bf-fcd4-712e-06b27f3c154c
* Version Independent ID: f3d043e8-8dbc-edf1-ea49-177098ff4ad6
* Content: [Message Security Certificate](https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/message-security-certificate)
* Content Source: [docs/framework/wcf/samples/message-security-certificate.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/samples/message-security-certificate.md)
* Product: **dotnet-framework**
* GitHub Login: @BrucePerlerMS
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-07-10 18:35
Thanks @ThangHuuVu for your feedback. We already have a backlog item tracking this work. So I'll be closing this as a duplicate.

**Comment by mairaw** [comment] 2018-07-10 18:35
Duplicate of #5619

**Closed by mairaw** 2018-07-10 18:35 UTC
Labels: :card_file_box: Technology - WCF, Source - Docs.ms, duplicate, triaged
