### ISSUE TITLE
If inhreit from EmployeeListNotFoundException, do I need overwrite the three init method?

### ISSUE THREAD

**Issue by naughtyGitCat** [dotnet/docs#17279] opened 2020-03-02 13:29 UTC
for example :

just do this:

class EmployeeListNotFoundDueToNetWorkException : EmployeeListNotFoundException{}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041f6b4c-2b7e-5332-f24e-12af7a5b07aa
* Version Independent ID: e9c2287f-1c4e-ee07-a1ff-77a3f07ce1a4
* Content: [How to: Create User-Defined Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions)
* Content Source: [docs/standard/exceptions/how-to-create-user-defined-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/how-to-create-user-defined-exceptions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by BillWagner** [comment] 2020-03-10 16:58
@naughtyGitCat Yes, you should create those three constructors.

If you don't the developers that want to use the new exception type you've created are going to be frustrated because that can't set the message, or set an inner exception to set the root cause.

I'll close this as an answered question.

**Closed by BillWagner** 2020-03-10 16:58 UTC
Labels: :books: Area - .NET Guide, :watch: Not Triaged
