### ISSUE TITLE
Indirect usage of BinaryFormatter via WinForms ImageList causes compiler warnings

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/docs#40044] opened 2024-03-17 18:18 UTC
### Type of issue

Missing information

### Description

After updating my WinForms application to .NET 8, I'm now getting MSB3825 compiler warnings saying that `BinaryFormatter` is deprecated and will be removed in a future version.

This article recommends that I *"migrate away from BinaryFormatter due to its security and reliability flaws."*

But this isn't helpful. I never opted into using `BinaryFormatter`. I added other WinForm components, and apparently *they* are using this type. In my case, it appears that an `ImageList` control is using it.

So does this mean I need to stop using `ImageList`? How can I migrate away from something that is being used behind the scenes by WinForms? None of this information helps me to resolve the issue.

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/binaryformatter-disabled

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/compatibility/serialization/8.0/binaryformatter-disabled.md

### Document Version Independent Id

5048d220-6e5c-3130-b1db-ead1efbf7c36

### Article author

@gewarren

### Metadata

* ID: 0eba416b-f96c-6684-b54e-1c765f0c6efe 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment] 2024-03-18 14:43
@merriemcgaw Could you advise on this issue?

**Comment by merriemcgaw** [comment] 2024-03-18 16:55
@JeremyKuhne @lonitra I'll let you two advise. @gewarren - I think we'll want some official guidance in the docs specific to WinForms.

**Comment by jeffhandley** [comment] 2024-04-02 19:09
@JeremyKuhne -- I've renamed this issue to describe the issue better. I'm tempted to transfer this issue over to [dotnet/winforms](https://github.com/dotnet/winforms) so we can track it against the 9.0.0 milestone there. What do you think?

**Comment by Tanya-Solyanik** [comment] 2024-12-19 00:25
@jeffhandley  - how that BinaryFormatter is not used to deserialize resources at the runtime, we don't need this warning, who do we work with on it?

**Comment by Tanya-Solyanik** [comment] 2024-12-20 21:21
Duplicate of - https://github.com/dotnet/msbuild/issues/11185

**Closed by Tanya-Solyanik** 2024-12-20 21:21 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-fundamentals/svc

**Comment by SoftCircuits** [comment] 2024-12-20 22:38
I was able to find an error in my markup.

It was the following block. Note the two double quotes at the end of the `form-check form-switch` `<div>`.

```
<div class="d-flex justify-content-between" title="Automatically refresh this page every 5 minutes">
    <div>
        <h4>@ViewData["Title"] (@truckCount)</h4>
    </div>
    <div>
        <div class="form-check form-switch"">
            <input class="form-check-input" type="checkbox" id="auto-refresh">
            <label class="form-check-label" for="auto-refresh">Auto Refresh</label>
        </div>
    </div>
</div>
```

Okay, would be nice if the editor could flag this somehow, but it's due to my error. Apologies, and thanks for looking.
