### ISSUE TITLE
Document ServerGarbageCollection for enabling Server GC

### ISSUE THREAD

**Issue by mjrousos** [dotnet/docs#4245] opened 2018-01-29 21:41 UTC
Current documentation does not cover how to enable server GC in .NET Core apps. 

It would be useful to explain the ServerGarbageCollection project file property, as well as comparing it to the app.config gcServer property since some developers may not realize that different properties are used for projects targeting net46x/net47 compared to netcoreapp.

**Comment by mairaw** [comment] 2018-01-29 21:48
@mjrousos we do cover that property but in the mapping topic: https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#runtimeoptions 

We also have a proposed topic in issue #2642 which would cover all the SDK properties in .NET Core project. Would that cover what you're asking?

**Comment by mjrousos** [comment] 2018-01-29 21:52
I think the mapping doc isn't sufficient since someone writing a new ASP.NET Core app (for example) might not look at migration docs.

I think #2642 may cover it as long as we're sure to include ServerGarbageCollection among the MSBuild properties documented.

**Comment by mairaw** [comment] 2018-01-29 23:14
Yes, I know the mapping isn't sufficient @mjrousos but that's the only place where we explain that right now. There are a lot of requests coming for that topic so I'll try to make sure I review all issues that I'm closing as dupe when I'm working on that topic.

@ghogen who owns MSBuild docs now? I'm wondering if a lot of these requests we're getting is because the MSBuild reference doesn't cover the new .NET Core SDK properties as well.

**Comment by mairaw** [comment] 2018-01-29 23:15
Duplicate of #2642

**Closed by mairaw** 2018-01-29 23:15 UTC

**Comment by dotnetchris** [comment] 2019-08-05 15:06
Most reasonable documentation i've found available presently: https://dotnet.github.io/orleans/Documentation/clusters_and_clients/configuration_guide/configuring_.NET_garbage_collection.html

**Comment by gewarren** [comment] 2020-01-16 01:26
For anyone finding this issue, the GC options have been documented here: https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector
