### ISSUE TITLE
Document NUnit in .NET Core Guide > Unit Testing

### ISSUE THREAD

**Issue by guardrex** [dotnet/docs#1785] opened 2017-03-22 22:00 UTC
#@VitalyLitvinuk asks on [Unit testing with MSTest and .NET Core](https://docs.microsoft.com/en-us/dotnet/articles/core/testing/unit-testing-with-mstest) ...

>What about NUnit? Is there any guide how to create/setup project to use this framework? Have any plans about NUnit test project creation via "dotnet new nunit"?

A doc covering NUnit might be temporarily blocked by https://github.com/nunit/nunit3-vs-adapter/issues/297, and commentary in https://github.com/nunit/nunit3-vs-adapter/issues/308 indicates on-going work.

cc/ @rprouse

[EDIT] Note to self: Add to `dotnet test` topic.

**Comment by rprouse** [comment] 2017-03-24 12:44
I am working on support in the NUnit adapter, although we don't have an issue yet to track adding templates. At the moment, the only way to run NUnit .NET Core tests that have been converted to CSPROJ is to convert them to NUnitLite self-executing tests, but that shouldn't be documented.

**Comment by GuardRex** [comment] 2017-03-24 16:32
@rprouse Thanks. I'll keep an eye on progress. If this doc is approved later by management, someone will get right on it when you're ready and they pull the trigger.

**Comment by GuardRex** [comment] 2017-06-27 03:46
Hello @rprouse ... can I ping you for a sec for an update on where things stand? It looks like according to https://github.com/nunit/nunit3-vs-adapter/issues/297 that things aren't quite ready yet.

**Comment by rprouse** [comment] 2017-06-27 12:34
@GuardRex there have been a few issues reported with the alpha release of the adapter, but nothing serious or consistently reproducible. We actually haven't released a second alpha yet because we haven't found anything serious enough to fix. I have a couple of smaller issues on my plate, so there will likely be an update soon.

If the docs are updated, they should probably use a `*` for the version, but other than that, everything is pretty much good to go. See http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/

**Comment by GuardRex** [comment] 2017-06-27 13:04
Thanks @rprouse for the update.

@mairaw Do u want this after the current/upcoming workload assignments ("upcoming" == that you said you would be making soon), or do u want this one worked now?

**Comment by GuardRex** [comment] 2017-06-27 21:06
@rprouse We're going to hold for just a sec while you get past alpha. I'll keep an :eye: out. I'm tracking on issue https://github.com/nunit/nunit3-vs-adapter/issues/297. If there's a better spot to monitor for beta landing, let me know, and I'll watch it.

**Comment by rprouse** [comment] 2017-06-29 00:59
@GuardRex I guess I'd better get off my butt and release a beta then. The other place to track will be the https://github.com/nunit/nunit3-vs-adapter/releases, although you don't get notifications for those.

To be honest, except for the version, the documentation won't change. The code is very stable and I won't be changing much.

**Comment by GuardRex** [comment] 2017-06-29 01:13
@rprouse Thanks for the link. I'll keep an eye on both.

> I'd better get off my butt and release a beta then ... except for the version, the documentation won't change.

:grinning: It's more of a fear of changes :ghost: than anything else. I think we just want to make sure we dedicate the time and don't get much churn between beta and release when that comes later. Alpha-TO-beta-TO-release ... that whole chain of possible changes is the scary part.

I can get to the outline and get that setup soon-ish. This week isn't looking good tho ... early next week perhaps ... but soon.

**Comment by GuardRex** [comment] 2017-07-21 00:35
@mairaw Working this is going to post-date my tenure on the team, so I'm un-assigning it. Do u want to re-assign?

**Comment by rprouse** [comment] 2017-07-24 22:25
@GuardRex we have released the 3.8 version of the NUnit adapter. It is no longer pre-release.

**Comment by GuardRex** [comment] 2017-07-24 22:32
@rprouse :tada: 🎈 :beers: Excellent news! This work will post-date my tenure with the docs team, hence my un-assignment. The least I can do tho is get it off of "blocked" status. This is a priority issue, so they'll get someone on it asap. Thanks for letting us know! ... and congrats on the latest release! The community speaks *very highly* of NUnit.

**Comment by BillWagner** [comment] 2017-09-05 16:56
@KathleenDollard Where in the backlog for the CLI is support for `dotnet new NUnit`?  We'll move this issue to the milestone that matches that addition.

**Comment by rprouse** [comment] 2017-09-14 16:06
@KathleenDollard or @BillWagner is there an issue tracking `dotnet new nunit`? Can we help out?

**Comment by mairaw** [comment] 2017-09-15 01:29
Tagging some other folks to see if we have an issue tracking `dotnet new nunit`

/cc @livarcocc @mlorbetske @sayedihashimi

**Comment by sayedihashimi** [comment] 2017-09-15 18:09
dotnet new has support for installing templates from NuGet. In this case I would think that the NUnit team should author and own their own template.

**Comment by rprouse** [comment] 2017-12-01 19:31
I am working on these docs. I will submit separate PRs for each language.

**Comment by rprouse** [comment] 2017-12-05 19:52
@BillWagner you should be able to close this issue once my three PRs are merged.

**Comment by BillWagner** [comment] 2017-12-05 22:06
Closed in a combination of #3856 #3858 and #3859

**Closed by BillWagner** 2017-12-05 22:06 UTC
Labels: Area - Conceptual Docs, new-content, P1
