### ISSUE TITLE
Error in declaring code array

### ISSUE THREAD

**Issue by xiaofa-fenye** [dotnet/docs#38436] opened 2023-11-27 02:33 UTC
### Type of issue

Code doesn't work

### Description

In the Code about "int[] xs = [4, 7, 9];" and "int[] ys = [-9, 0, 67, 100];" we should replace '[]' with '{}'.

### Page URL

https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/value-tuples#use-cases-of-tuples

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/builtin-types/value-tuples.md

### Document Version Independent Id

1778e921-76f6-32d5-4509-7bd944a01e0d

### Article author

BillWagner

### Metadata

* ID: 0e533179-50e7-813d-be49-e1248134dd10 
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**

**Comment by patr543a** [comment] 2023-11-27 10:14
This is a new .NET 8 feature and is correct, no change should be made then.

**Comment by BillWagner** [comment] 2023-11-27 14:51
Hi @xiaofa-fenye 

As @patr543a pointed out, this is a new C# 12 feature. 

I'll close this as by design.

**Closed by BillWagner** 2023-11-27 14:51 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-language-reference/tech
