### ISSUE TITLE
Please add information about precedence of pattern matching operators

### ISSUE THREAD

**Issue by Hermholtz** [dotnet/docs#33397] opened 2023-01-10 09:17 UTC
Hi,

I'm missing the information about how pattern matching operators precedence fits in this table, for example:
- what's the priority of `or` and `and`, is it lower or higher than `is`, how about relation to `&&`?

I find myself writing code like the below more and more often, and I need to be sure how it supposed to work, not only by experimentation, but by being able to reach out to definite source of information. Specification linked on the bottom of the page is also... less than ideal with this respect.

```csharp
var monthBeginsOnWeekend = (DateTime date) =>
	date.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday
	&& date.Day == 1;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeac581-6235-2192-d909-e7fe3d21197f
* Version Independent ID: 9d8e2a57-1c18-8cba-9bd4-eef546fe2dcb
* Content: [C# operators and expressions - List all C# operators and expression](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/)
* Content Source: [docs/csharp/language-reference/operators/index.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/index.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2023-01-10 13:43
Adding @333fred and @jcouv 

I looked at the [speclet](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-9.0/patterns3.md) for the pattern combinators, and I don't see the precedence clearly stated.

That said, I think the `and`, `or`, and `not` combinators are a lower precedence than `is` or `&&`. I think these might be a new category that applies only to combining patterns, and is the lowest precedence. 

Once clear on the precedence, we'll make the change.

**Comment by jcouv** [comment] 2023-01-19 20:04
I couldn't find this in speclets or LDM notes either. Looking at the code, I don't think there is a simple/general answer. It depends on the context where the pattern exists.

In the code, we treat the patterns inside an `is` with the same precedence as `is`, namely `Precedence.Relational` (the precedence of `SyntaxKind.IsPatternExpression`).
`Precedence.Relational` is **higher** than the precedence for logical binary operators (`LogicalOr`, `LogicalXor`, `LogicalAnd`).

But inside a switch statement, in sub-pattern, and in list-pattern, we use `Precedence.Conditional`.
Inside a switch expression, we use `Precedence.Coalescing`.

`Precedence.Conditional` and `Precedence.Coalescing` are **lower** than the precedence for logical binary operators.

Tagging @CyrusNajmabadi in case anything to add.

```
        private CSharpSyntaxNode ParseTypeOrPatternForIsOperator()
        {
            var pattern = ParsePattern(GetPrecedence(SyntaxKind.IsPatternExpression), afterIs: true);
            ...
        }

        private CSharpSyntaxNode ParseExpressionOrPatternForSwitchStatement()
        {
            var pattern = ParsePattern(Precedence.Conditional, whenIsKeyword: true);
            ...
        }
        
        private SeparatedSyntaxList<SwitchExpressionArmSyntax> ParseSwitchExpressionArms()
        {
            ...
            while (this.CurrentToken.Kind != SyntaxKind.CloseBraceToken)
            {
                // We use a precedence that excludes lambdas, assignments, and a conditional which could have a
                // lambda on the right, because we need the parser to leave the EqualsGreaterThanToken
                // to be consumed by the switch arm. The strange side-effect of that is that the conditional
                // expression is not permitted as a constant expression here; it would have to be parenthesized.
                var switchExpressionCase = _syntaxFactory.SwitchExpressionArm(
                    ParsePattern(Precedence.Coalescing, whenIsKeyword: true),
                    ParseWhenClause(Precedence.Coalescing),
                    this.EatToken(SyntaxKind.EqualsGreaterThanToken),
                    ParseExpressionCore());
                ....
        }
```

```
        private static Precedence GetPrecedence(SyntaxKind op)
        {
            switch (op)
            {
                case SyntaxKind.QueryExpression:
                    return Precedence.Expression;
                case SyntaxKind.ParenthesizedLambdaExpression:
                case SyntaxKind.SimpleLambdaExpression:
                case SyntaxKind.AnonymousMethodExpression:
                    return Precedence.Lambda;
                case SyntaxKind.SimpleAssignmentExpression:
                ...
                    return Precedence.Assignment;
                case SyntaxKind.CoalesceExpression:
                case SyntaxKind.ThrowExpression:
                    return Precedence.Coalescing;
                case SyntaxKind.LogicalOrExpression:
                    return Precedence.ConditionalOr;
                case SyntaxKind.LogicalAndExpression:
                    return Precedence.ConditionalAnd;
                case SyntaxKind.BitwiseOrExpression:
                    return Precedence.LogicalOr;
                case SyntaxKind.ExclusiveOrExpression:
                    return Precedence.LogicalXor;
                case SyntaxKind.BitwiseAndExpression:
                    return Precedence.LogicalAnd;
                case SyntaxKind.EqualsExpression:
                case SyntaxKind.NotEqualsExpression:
                    return Precedence.Equality;
                case SyntaxKind.LessThanExpression:
                case SyntaxKind.LessThanOrEqualExpression:
                case SyntaxKind.GreaterThanExpression:
                case SyntaxKind.GreaterThanOrEqualExpression:
                case SyntaxKind.IsExpression:
                case SyntaxKind.AsExpression:
                case SyntaxKind.IsPatternExpression:
                    return Precedence.Relational;
                case SyntaxKind.SwitchExpression:
                case SyntaxKind.WithExpression:
                    return Precedence.Switch;
                case SyntaxKind.LeftShiftExpression:
                case SyntaxKind.RightShiftExpression:
                case SyntaxKind.UnsignedRightShiftExpression:
                    return Precedence.Shift;
                case SyntaxKind.AddExpression:
                case SyntaxKind.SubtractExpression:
                    return Precedence.Additive;
                case SyntaxKind.MultiplyExpression:
                case SyntaxKind.DivideExpression:
                case SyntaxKind.ModuloExpression:
                    return Precedence.Multiplicative;
                case SyntaxKind.UnaryPlusExpression:
                ...
                    return Precedence.Unary;
                case SyntaxKind.CastExpression:
                    return Precedence.Cast;
                case SyntaxKind.PointerIndirectionExpression:
                    return Precedence.PointerIndirection;
                case SyntaxKind.AddressOfExpression:
                    return Precedence.AddressOf;
                case SyntaxKind.RangeExpression:
                    return Precedence.Range;
                case SyntaxKind.ConditionalExpression:
                    return Precedence.Expression;
                ...
                case SyntaxKind.DefaultExpression:
                ...
                case SyntaxKind.FalseLiteralExpression:
                case SyntaxKind.GenericName:
                case SyntaxKind.IdentifierName:
                ...
                    return Precedence.Primary;
                default:
                    throw ExceptionUtilities.UnexpectedValue(op);
            }
        }
```
```

        private enum Precedence : uint
        {
            Expression = 0, // Loosest possible precedence, used to accept all expressions
            Assignment = Expression,
            Lambda = Assignment, // "The => operator has the same precedence as assignment (=) and is right-associative."
            Conditional,
            Coalescing,
            ConditionalOr,
            ConditionalAnd,
            LogicalOr,
            LogicalXor,
            LogicalAnd,
            Equality,
            Relational,
            Shift,
            Additive,
            Multiplicative,
            Switch,
            Range,
            Unary,
            Cast,
            PointerIndirection,
            AddressOf,
            Primary,
        }
```

**Comment by BillWagner** [comment] 2023-04-26 21:30
Defering this for the moment.

I want to discuss with the ECMA committee as we're adding the initial Patterns text in the standard. Moving to the June iteration.

**Comment by pkulikov** [comment] 2023-07-02 08:26
@Hermholtz what confuses you? What experiments did you make to clarify your confusion? I see both `and` and `or` as **not** operators but combinators of patterns which are not related to operators like `is` or `&&`, so I cannot grasp your confusion. The code example in the issue is clear and I don't see how it may confuse.

**Comment by Hermholtz** [comment] 2023-07-06 10:23
Every decent programming language has a clear specification and written documentation of all its features. If it's not documented, but requires "intuition" or experimentation then how am I supposed to know if it works correctly? How am I supposed to know whether the observed behavior is by design or buggy?

**Closed** 2023-07-07 15:09 UTC
Labels: doc-bug, Pri1, dotnet-csharp/prod, csharp-language-reference/tech, in-pr, okr-health
