### ISSUE TITLE
Unable to install on Ubuntu20.04

### ISSUE THREAD

**Issue by v-radelg** [dotnet/docs#18255] opened 2020-05-04 21:25 UTC
@F-Unction commented 2 days ago — with docs.microsoft.com

dotnet-sdk-3.1-&gt; dotnet-runtime-3.1-&gt; dotnet-runtime-deps-3.1-&gt; libicu63
But only libicu66 in the system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by iBolski** [comment] 2020-05-04 21:35
Your best bet is to manually install the SDK. YOu can either download the tarball yourself and extract it to a folder in your home directory and update your $PATH variable to point to that folder, or you can use the automated install shell script to specify which version you want and where to install it.

dotnet-install.sh --channel 3.1 --install-dir ~/dotnet3.1

Will download, untar and install the 3.1 Core SDK into a folder called "dotnet3.1" in your home folder. Then you can modify your .bashrc script at the bottom like this:

export DOTNET_HOME=/home/{your user id}/dotnet3.1
export PATH=$PATH:$DOTNET_HOME

If you did this in a terminal session, close it out and launch terminal again and then do this at the bash command prompt:

dotnet --version

You should see the version you installed. For me it was 3.1.201.

I skipped the package manager because it will remove the previous version. So if you want multiple versions of the SDK installed, the best way is to manually download the specific versions you want from the web page and install them manualy, or use the "dotnet-install.sh" script. You can get the script at:

https://dotnet.microsoft.com/download/dotnet-core/scripts

**Comment by byroniac** [comment] 2020-05-05 08:56
The way I'm currently doing it on 20.04 is that I installed the snap "sudo snap install dotnet-sdk". Then I would ordinarily do a "sudo snap alias dotnet-sdk.dotnet dotnet" to create a "dotnet" alias for the operating system. However, in my case I am using the snap versions of Visual Studio Code and Insiders, and they do not see dotnet available for some reason. So I did a "sudo ln -sv /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet" to make the command available system-wide (however you must manually remove from /usr/local/bin when no longer needed). Finally, I created a ~/.bash_aliases file and with my aliases I put this at the bottom:

if [ -d /snap/dotnet-sdk/current ]; then
    export DOTNET_ROOT=/snap/dotnet-sdk/current
    export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
	export PATH=$PATH:/snap/dotnet-sdk/current
fi

That DOTNET_SYSTEM_GLOBALIZATION_INVARIANT is critical due to the different version of libicu on 20.04, I think.

**Comment by svick** [comment] 2020-05-05 10:02
See https://github.com/dotnet/core/issues/4360. The official packages for Ubuntu 20.04 should be released on 12 May. In the meantime, you can try the workarounds mentioned in that issue, if you want.

**Comment by Rick-Anderson** [comment] 2020-05-05 21:59
Dup of #18220
Recommend closing both. Perhaps updating doc with this information.
cc @Thraka

**Comment by Rick-Anderson** [comment] 2020-05-05 22:44
@v-radelg  please review open and closed issues before opening a new issue.

**Comment by Thraka** [comment] 2020-05-06 17:06
Duplicate of #17638

**Closed by Thraka** 2020-05-06 17:06 UTC
Labels: :books: Area - .NET Core Guide, product-feedback
