### ISSUE TITLE
WCF package references not added with version 1.0.0

### ISSUE THREAD

**Issue by ralphhendriks** [dotnet/docs#6929] opened 2018-08-10 07:30 UTC
I followed the instructions exactly, and I didn't see the following behavior (as mentioned under step 5):

> The dotnet_svcutil tool also adds to the project the appropriate WCF packages required by the proxy code as package references.

I figured out that this only happens using the 1.0.0 version of the tool. The latest version available (1.0.2) indeed adds the WCS package references.

Under step 3, I think it is better to include a wildcard specifier for the patch level in the CLI tool reference:

```xml
<ItemGroup>
  <DotNetCliToolReference Include="dotnet-svcutil" Version="1.0.*" />
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d0bd854-fec8-fc4a-760a-42dc22e07f99
* Version Independent ID: f04e9f8b-24d2-79fb-7521-6222c434e80f
* Content: [Microsoft WCF dotnet-svcutil tool](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-svcutil-guide)
* Content Source: [docs/core/additional-tools/dotnet-svcutil-guide.md](https://github.com/dotnet/docs/blob/master/docs/core/additional-tools/dotnet-svcutil-guide.md)
* Product: **dotnet-core**
* GitHub Login: @mlacouture
* Microsoft Alias: **jralexander**

**Comment by JRAlexander** [comment] 2018-08-13 17:03
@ralphhendriks, thanks for the feedback! @mlacouture, any thoughts?

**Comment by mlacouture** [comment] 2018-08-13 17:06
@ralphhendriks, thank you for your feedback, I think you are right!  @JRAlexander, can we do that? thanks

**Comment by Kexerval** [comment] 2018-10-25 23:48
Asking to close issue as the issue is now resolved in current MS documentation. @mlacouture

**Comment by regal60740** [comment] 2018-11-01 16:42
When I tried to run "dotnet svcutil http://contoso.com/SayHello.svc" from step 5 above, I got this error: Microsoft (R) WCF Service Model Proxy Generation Tool for .Net Core platform
[dotnet-svcutil, Version 1.0.4]
Copyright (c) Microsoft Corporation.  All rights reserved.

This tool collects information about how it is used in order to improve the tool. This functionality can be disabled by setting the environment variable "DOTNET_SVCUTIL_TELEMETRY_OPTOUT" to 1.

Attempting to download metadata from 'http://contoso.com/SayHello.svc' using WS-Metadata Exchange and HttpGet.
Error: Cannot obtain Metadata from http://contoso.com/SayHello.svc

If this is a Windows (R) Communication Foundation service to which you have access, please check that you have enabled metadata publishing at the specified address.  For help enabling metadata publishing, please refer to the MSDN documentation at http://go.microsoft.com/fwlink/?LinkId=65455.
WS-Metadata Exchange Error
    URI: http://contoso.com/SayHello.svc

The remote server returned an error: (404) Not Found.
If you would like more help, type "dotnet svcutil -h"

**Comment by mlacouture** [comment] 2018-11-01 18:15
Hi @regal60740!

Thank you for trying the tool.  You need to use a real URI because the one in the documentation is 'assumed' to exist.

**Comment by mlacouture** [comment] 2018-11-01 18:15
@JRAlexander, I don't seem to be able to close this issue, do you mind closing it? thanks,

**Comment by JRAlexander** [comment] 2018-11-01 19:20
Done!

**Closed by JRAlexander** 2018-11-01 19:20 UTC
Labels: :card_file_box: Technology - WCF, Source - Docs.ms, external, product-feedback, resolved

**Comment by atifalibhatti** [comment] 2019-02-19 01:36
I am getting following error when I try to execute dotnet svcutil --help/url/wsdl file or anyting.

Unable to generate deps.json, it may have been already generated.  You can specify the "-d" option before the tool name for diagnostic output (for example, "dotnet -d <toolname>": C:\Program Files\dotnet\sdk\2.2.104\Sdks\Microsoft.NET.Sdk\targets\GenerateDeps\GenerateDeps.proj
