### ISSUE TITLE
.NET 7 Ubuntu installation instructions

### ISSUE THREAD

**Issue by aradalvand** [dotnet/docs#32684] opened 2022-11-20 22:29 UTC
Please provide package installation instructions for .NET 7, I've been waiting for this, still nothign :(
https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

**Comment by adegeo** [comment] 2022-11-28 21:34
Duplicate of #32541

**Closed by adegeo** 2022-11-28 21:34 UTC
Labels: :watch: Not Triaged, Pri3
