### ISSUE TITLE
This does not reflect current state of the Wix which is v5

### ISSUE THREAD

**Issue by hebrayah** [dotnet/docs#42118] opened 2024-08-12 22:35 UTC
### Type of issue

Code doesn't work

### Description

Provided code does not work with Wix v5 which is newest.

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/extensions/windows-service-with-installer?tabs=wix

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/extensions/windows-service-with-installer.md

### Document Version Independent Id

83c4d805-1394-90b7-6def-cf809c33ae22

### Article author

@IEvangelist

### Metadata

* ID: e044209a-0802-07c0-7518-208967a3ef02 
* Service: **dotnet-fundamentals**

**Comment by IEvangelist** [comment] 2024-08-13 14:32
Hi @hebrayah - thank you so much for posting this issue. Is this something you'd be interested in helping fix? When I originally wrote the article, I wrote it targeting v4 and everything worked perfectly there. If v5 introduced breaking changes, it would take me a bit to figure out what changed and how to adjust the article, but I'd be happy to review a PR that fixes it - again, if you're interested. Thank you, regardless.

**Comment by IEvangelist** [comment] 2024-08-13 16:48
This looks like a duplicate of #41989. Closing this issue in favor of the other, but the offer still stands @hebrayah - just let me know.

**Closed by IEvangelist** 2024-08-13 16:48 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-fundamentals/svc

**Comment by hebrayah** [comment] 2024-08-13 20:23
Hello,

Problem is that I am a java guy - so I am kind of learning dotnet - this is
why I cannot do it all by myself.
Also due to coming from the opensource world i am maybe spoiled with
extensive documentation of the opensource libraries - while this wix is
terrible.
Probably you have to pay to get something more informational.

It is not that bad - when I did a few steps back with my program it finally
compiled, however thanks for initiative of writing such documents, I
thought that this was created by Microsoft employees.

I would love to help when I learn a little more :)

Best regards

Marcin


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Nie
zawiera wirusów.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

wt., 13 sie 2024 o 16:33 David Pine ***@***.***> napisał(a):
