### ISSUE TITLE
Potentially improve note about unauthorized access during file enumeration

### ISSUE THREAD

**Issue by atifaziz** [dotnet/docs#16553] opened 2020-01-06 14:44 UTC
Instead of the currently noted strategy for handling unauthorized access during lazy enumeration of file system entries:

> **Note**
>
> Although you can immediately enumerate all the files in the subdirectories of a parent directory by using the [`AllDirectories`](https://docs.microsoft.com/en-us/dotnet/api/system.io.searchoption#System_IO_SearchOption_AllDirectories) option of the optional [`SearchOption`](https://docs.microsoft.com/en-us/dotnet/api/system.io.searchoption) enumeration, [`UnauthorizedAccessException`](https://docs.microsoft.com/en-us/dotnet/api/system.unauthorizedaccessexception) errors may make the enumeration incomplete. You can catch these exceptions by first enumerating directories and then enumerating files.  

How about something like the following that simply catches `UnauthorizedAccessException` errors and resumes with the next?

```c#
var slash = Path.DirectorySeparatorChar.ToString();
var dir = new DirectoryInfo(Environment.GetFolderPath(System.Environment.SpecialFolder.Windows));
using var e = dir.EnumerateFileSystemInfos("*", SearchOption.AllDirectories)
                 .GetEnumerator();
while (true)
{
    try
    {
        if (!e.MoveNext())
            break;
    }
    catch (UnauthorizedAccessException ex)
    {
        Console.Error.WriteLine(ex.GetBaseException().Message);
        continue;
    }
    var fsi = e.Current;
    Console.WriteLine(fsi.FullName + (fsi is DirectoryInfo ? slash : string.Empty));
}
```

This is better, but more importantly, it would also document if the above is _supported behaviour_. In other words, if the iteration fails part way, can we assume that the enumerator's internal state is still intact and therefore it is safe to continue iterating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19880b28-5edd-695d-726e-4f627d00b843
* Version Independent ID: ebafb0b4-da0a-36ca-2246-df3e9d0a863e
* Content: [How to: Enumerate directories and files](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-enumerate-directories-and-files)
* Content Source: [docs/standard/io/how-to-enumerate-directories-and-files.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-enumerate-directories-and-files.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment] 2020-01-08 16:58
This is a good suggestion. However, I think this should be a whole new section + example in this article.

**Comment by atifaziz** [comment] 2020-01-08 17:09
Before adding the section + example, it would be good to know if the behaviour is by-design (and therefore will continue to be supported in the future) or just a by-product of the _current_ implementation.

**Comment by Thraka** [comment] 2020-01-09 18:41
@JeremyKuhne @carlossanlop can you comment on this suggestion?

**Comment by JeremyKuhne** [comment] 2020-01-09 19:32
It isn't explicitly by-design. This particular scenario is explicitly handled by [EnumerationOptions.IgnoreInaccessible](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.ignoreinaccessible?view=netcore-3.1#System_IO_EnumerationOptions_IgnoreInaccessible), which is what we should be calling out here.

In fact, we do have to do some work around throwing exceptions during enumeration. We currently leave the directory handle open, which is a problem if the enumerator doesn't get disposed. We need to do some work here to avoid locking directories.

**Comment by atifaziz** [comment] 2020-01-10 13:04
> It isn't explicitly by-design. This particular scenario is explicitly handled by [EnumerationOptions.IgnoreInaccessible](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.ignoreinaccessible?view=netcore-3.1#System_IO_EnumerationOptions_IgnoreInaccessible), which is what we should be calling out here.

Thanks @JeremyKuhne but didn't you just contradict yourself by saying it isn't explicit by-design yet it is? That's how I read it, but re-reading, did you perhaps mean to say is it by-design by virtue of relying on [`EnumerationOptions.IgnoreInaccessible`](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumerationoptions.ignoreinaccessible?view=netcore-3.1#System_IO_EnumerationOptions_IgnoreInaccessible) internally? If so, I think that's interesting to call out as an implementation detail, but in the end and for sake of simplicity, the reader should just to be told if the simpler enumeration methods support exception-safe iteration. That is, it is safe and supported to continue to use the iterator if one call to its `MoveNext()` fails (especially with respect to permissions).

**Comment by atifaziz** [comment] 2020-01-10 13:07
> In fact, we do have to do some work around throwing exceptions during enumeration. We currently leave the directory handle open, which is a problem if the enumerator doesn't get disposed. We need to do some work here to avoid locking directories.

So do you mean that it isn't explicitly by-design because there is this work pending?

> We currently leave the directory handle open, which is a problem if the enumerator doesn't get disposed.

Isn't that a problem with not disposing anything that holds on to an unmanaged resource? Won't the handle eventually get closed during finalization?

**Comment by Thraka** [comment] 2020-01-10 23:17
@atifaziz I think what he's saying is that by using `EnumerationOptions.IgnoreInaccessible` you enable the ability to avoid the exception. Your suggestion does work, but it's not the intended behavior. Using `foreach` automatically disposes the object, so if you use `GetEnumerator`, you'll have to do that yourself.

I think what we should do is add a new section covering this scenario and detail using `EnumerationOptions.IgnoreInaccessible`

**Comment by atifaziz** [comment] 2020-01-13 08:54
@Thraka Thanks for clearing that up. I was hoping that the simpler APIs support the behaviour (directly or indirectly) so that .NET Standard libraries can rely on it. `EnumerationOptions.IgnoreInaccessible` requires using the new API that besides missing documentation right now (except for an [archived blog entry](https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/custom-directory-enumeration-in-net-core-2-1)), requires the high bar of targeting .NET Standard 2.1.

**Comment by Thraka** [comment] 2020-01-21 17:14
@atifaziz Looking at this a bit more, I think it really is covered by the ending example of the article. It's just not super pretty as it handles the directories apart from the files, but it does work and allows the enumeration to continue, keeping the foreach loop intact so that the enumerator is properly disposed.

I'm going to close this suggestion. Thanks though!

**Closed** 2020-01-21 17:15 UTC
Labels: :books: Area - .NET Guide, P2, doc-enhancement, up-for-grabs
