### ISSUE TITLE
out-of-order named arguments are invalid if they're followed by positional arguments - add 1

### ISSUE THREAD

**Issue by SharunasBielskis** [dotnet/docs#14602] opened 2019-09-23 14:23 UTC
I analyzed the example of code which explains this feature and found that my additional code line - PrintOrderDetails("Gift Shop", productName: "Red Mug", orderNum: 31); - added into this example works correctly and didn't throw an error.

That means that if all parameters after the out-of-order parameter are named, an error will not be thrown.  Maybe the meaning of the sentence  - out-of-order named arguments are invalid if they're followed by positional arguments - is the same as - out-of-order named arguments are invalid if after them are positional arguments. My native language isn't English and sentence part - they're followed by positional arguments - I understood as after positional argument is out-of-order named argument. According to comments in The StackOverflow page - https://stackoverflow.com/questions/58005404/named-parameters-from-c-sharp-7-2/58061274#58061274 I see that this misinterpretation is not mine alone. 

Is it possible the sentence in the documentation "out-of-order named arguments are invalid if they're followed by positional arguments" to change into unambiguous variation?
          

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e335f6e5-7d90-bfab-f95d-ab8ef3ba41fc
* Version Independent ID: 6be20f15-e5eb-0778-5fbe-38326d8e8f00
* Content: [Named and Optional Arguments - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#feedback)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-09-25 13:30
Thanks for adding these details @SharunasBielskis 

I'm going to close this as a duplicate of #14598 (I'll make one PR to address both concerns).

**Closed by BillWagner** 2019-09-25 13:30 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, duplicate
