### ISSUE TITLE
Dotnet-SDK support for Centos Stream 8, 9 ?

### ISSUE THREAD

**Issue by Mizux** [dotnet/docs#28438] opened 2022-03-01 16:48 UTC
I would be happy if you provide information about dotnet-sdk support for distro `Centos Stream 8` and `Centos Stream 9` which is the new red hat distro model (note: rolling release).

annoucement: https://www.redhat.com/en/topics/linux/what-is-centos-stream
and docker images provided: https://quay.io/repository/centos/centos?tab=tags

Quick test as of March 1st 2022
```sh
# docker run --rm -it quay.io/centos/centos:stream8
...
[root@43e8da7f83a7 /]# dnf search dotnet-sdk
Last metadata expiration check: 0:02:29 ago on Tue Mar  1 16:44:19 2022.
========================================================================================================== Name Matched: dotnet-sdk ===========================================================================================================
dotnet-sdk-2.1.x86_64 : .NET Core 2.1 Software Development Kit
dotnet-sdk-2.1.5xx.x86_64 : .NET Core 2.1.5xx Software Development Kit
dotnet-sdk-3.0.x86_64 : .NET Core 3.0 Software Development Kit
dotnet-sdk-3.1.x86_64 : .NET Core 3.1 Software Development Kit
dotnet-sdk-5.0.x86_64 : .NET 5.0 Software Development Kit
dotnet-sdk-6.0.x86_64 : .NET 6.0 Software Development Kit
```

and
```sh
# docker run --rm -it quay.io/centos/centos:stream9
...
[root@43e8da7f83a7 /]# dnf search dotnet-sdk
Last metadata expiration check: 0:00:07 ago on Tue Mar  1 16:47:37 2022.
========================================================================================================== Name Matched: dotnet-sdk ===========================================================================================================
dotnet-sdk-3.1.x86_64 : .NET Core 3.1 Software Development Kit
dotnet-sdk-6.0.x86_64 : .NET 6.0 Software Development Kit
```

note: we need it to support google/or-tools C++/.Net wrapper package on these distros... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 577ce9b2-5b48-4ed2-c309-a78880015dd2
* Version Independent ID: 26300783-8df5-56a1-4ab6-4b8511e37f51
* Content: [Install .NET on CentOS - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-centos)
* Content Source: [docs/core/install/linux-centos.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-centos.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-03-01 21:44
@omajid Can you comment? Should we create CentOS Stream install pages?

**Comment by omajid** [comment] 2022-03-01 22:26
My understanding of CentOS Stream is that it's literally a (rebuild of) the in-development versions of RHEL. CentOS Stream 9 is tracking changes going into the release of RHEL 9. CentOS Stream 8 is tracking changes that are going into the next minor version of RHEL 8, which is 8.6.

The .NET packages my team releases for RHEL 9 will be automatically built and included into CentOS Stream 9, as soon as they are built for RHEL 9. The same thing is true for RHEL 8, though CentOS Stream 8 picks up changes from RHEL 8 at a slightly slower pace.

I can definitely seem value in documenting this so anyone using CentOS Stream has direct documentation they can refer to. But I expect it to be pretty much a 100% duplicate of what's currently documented in RHEL docs. Any difference between RHEL and CentOS Stream would be either bugs or point-in-time issues that should disappear in days/weeks. Perhaps we can just extend/rename the RHEL docs to cover this? Would you like me to work on a PR for that?

**Comment by omajid** [comment] 2022-03-01 22:51
As a side-note RHEL 9 and CentOS Stream 9 will only include .NET 6 on release. The 3.1 packages are about to be removed for a few reasons, including issues building/running against OpenSSL 3.0. See https://github.com/dotnet/corefx/pull/43078 for that.

**Comment by adegeo** [comment] 2022-03-04 18:49
Thanks for the info @omajid I can update the articles, adding info about CentOS Stream to the RHEL article. I'll put a CentOS Stream specific entry in the TOC though, but it will still link to the RHEL+CentOS Stream article.

**Closed** 2022-03-22 20:25 UTC
Labels: doc-enhancement, Pri1, dotnet/prod, dotnet-install/tech
