### ISSUE TITLE
Project Model Reference Tasks

### ISSUE THREAD

**Issue by cartermp** [dotnet/docs#325] opened 2016-03-15 23:30 UTC
Get story straight on and write about:
- [ ]  commands
- [x]  preserveCompilationContext
- [x]  languageId
- [ ]  frameworkAssemblies NuGet vs GAC story
- [ ]  wrappedProject
- [ ]  imports
- [x]  What the default languageVersion is in the compilation options

**Comment by dls314** [comment] 2016-06-30 13:00
Really interested in the frameworkAssemblies NuGet vs GAC story at the moment. Any intermediate references about what the straight story is there?

**Comment by cartermp** [comment] 2016-06-30 14:54
You can take a look t at #448 for our changes.

> Any intermediate references about what the straight story is there?

NuGet is the preferred mechanism by which you get your dependencies.  If you're building something for `netstandard1.x` or `netcoreapp1.0`, then all of your dependencies should be in the form of NuGet packages.

I don't think I could articulate the significance of frameworkAssemblies vs using the GAC.  However, this becomes a concern only when multitargeting to generate platform-specific assemblies.  @davidfowl would know more here.

**Comment by BillWagner** [comment] 2017-07-17 18:21
@cartermp Can this be closed at this time?  If not, can you make a new issue for which tasks remain on this work in the `csproj` based tools, and then close this one?

**Comment by mairaw** [comment] 2017-10-09 20:48
I think this can be closed as dupe of #2642 where we wanna create a CSPROJ reference topic.

**Closed by mairaw** 2017-10-09 20:48 UTC
Labels: enhancement
