### ISSUE TITLE
Does dotnet restore not support authenticated (private) feeds at all

### ISSUE THREAD

**Issue by kexxxfeng** [dotnet/docs#5699] opened 2018-05-31 06:06 UTC
For more detail: https://inedo.com/support/questions/7319

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b256dc4-c4ad-c115-f4e2-40310bc3505a
* Version Independent ID: 0b993779-65a2-6092-4047-2fc2ec16170b
* Content: [dotnet restore command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-restore.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-restore.md)
* Service: **unspecified**
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment] 2018-05-31 18:20
@dsplaisted @KathleenDollard @livarcocc I believe you can specify private feeds via source no? But how does it work with authenticated private feeds?

**Comment by livarcocc** [comment] 2018-05-31 18:22
@rohit21agrawal @rrelyea

**Comment by nkolev92** [comment] 2018-05-31 21:35
@kexxxfeng 
This is something we're actively working on. 
Please follow https://github.com/NuGet/Home/issues/6486 for updates.

**Comment by BillWagner** [comment] 2018-06-20 17:46
Closing as duplicate of https://github.com/NuGet/Home/issues/6486

**Closed by BillWagner** 2018-06-20 17:46 UTC
Labels: Area - .NET Core Guide, Source - Docs.ms, product-question
