### ISSUE TITLE
Just now i added some keys to   registry settings

### ISSUE THREAD

**Issue by RAJU2529** [dotnet/docs#8873] opened 2018-11-05 19:07 UTC
just i added new valuses to 

[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics]
"MaxMultisampleType"=dword:00000004
"UseReferenceRasterizer"=dword:00000001
"DisableHWAcceleration"=dword:00000000

Below keys are already  added  by default after installed intel hd graphicds 620 driver and i modified setrting intel graphics control panel .
Display1 is belongs to intel HD graphics 620
[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY1]
"PixelStructure"=dword:00000001
"GammaLevel"=dword:00000898
"ClearTypeLevel"=dword:00000064
"EnhancedContrastLevel"=dword:00000190
"GrayscaleEnhancedContrastLevel"=dword:00000190
"TextContrastLevel"=dword:00000002

My asus laptop have  two  GPUs  .
1. intel hd graphics 620  ( default )
2.nvidia geforce 940mx   (  rendering gpu )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89a3478-1985-d631-b57e-2d2f540b9734
* Version Independent ID: 912bbf84-a3b4-ff78-4464-6851417c0ac2
* Content: [Graphics Rendering Registry Settings](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings)
* Content Source: [docs/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by tdykstra** [comment] 2019-12-05 20:09
@RAJU2529 Thanks for contacting us. But from the description I can't tell what the question is -- please clarify what the issue is about.

**Comment by RAJU2529** [comment] 2019-12-06 06:22
@tdykstra .   I have added for the optimizing the graphics device and it's driver. More registry keys are modified by me by taking various documents and  research

**Comment by tdykstra** [comment] 2019-12-06 15:53
Sorry, it's still not clear to me what is the issue or question related to this article.

**Comment by RAJU2529** [comment] 2019-12-07 04:42
@tdykstra.. I added registry keys .but I have doubts, those registry keys will give device problems?

**Comment by tdykstra** [comment] 2019-12-10 16:42
The answer to that seems to be covered by the response to https://github.com/dotnet/docs/issues/8874 -- closing this one as a duplicate.

**Closed by tdykstra** 2019-12-10 16:42 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WPF
