### ISSUE TITLE
How to include the referenced dlls ?

### ISSUE THREAD

**Issue by kishorpise** [dotnet/docs#11255] opened 2019-03-11 16:12 UTC
.net core project name C depends on B which again depends on A. if nuget package is to formed with C, how to include B and A inside without creating another nuget packages ?

**Comment by mairaw** [comment] 2019-03-11 21:17
Hi @kishorpise, thank you for the question. I think this question is better suited for a community like StackOverflow. I'm going to close this because the issue is not related to our documentation. But please let us know if I misunderstood you.

**Closed by mairaw** 2019-03-11 21:17 UTC
Labels: :books: Area - .NET Core Guide, forum, product-question
