### ISSUE TITLE
Minor grammar issue with Compiler Error CS0225 message

### ISSUE THREAD

**Issue by equin0x80** [dotnet/docs#26272] opened 2021-09-26 20:30 UTC
The current text reads:
"The params parameter must be a single dimensional array"
That means it must be a "dimensional array", and only one of them (a single one).
It should be hyphenated: "a single-dimensional array", i.e. one that has only a single dimension.
I see that the phrase is correctly hyphenated in the explanatory body text, but not in the error message itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b73a4632-67ad-01fd-7ec3-269018571a4f
* Version Independent ID: 439c2200-39d0-d5b7-84fc-a7699b450c29
* Content: [Compiler Error CS0225](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0225)
* Content Source: [docs/csharp/misc/cs0225.md](https://github.com/dotnet/docs/blob/main/docs/csharp/misc/cs0225.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-09-27 13:57
Thanks @equin0x80 

You are correct on the grammar. However, I'm going to close this without action. That text exactly matches the error message generated by [the compiler](https://github.com/dotnet/roslyn/blob/main/src/Compilers/CSharp/Portable/CSharpResources.resx#L1042). That's by design to improve search results when developers search for a compiler warning or error message.

**Closed by BillWagner** 2021-09-27 13:57 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-csharp/prod, csharp-diagnostics/tech
