### ISSUE TITLE
Visual Studio option for public signing

### ISSUE THREAD

**Issue by MichaelKetting** [dotnet/docs#7471] opened 2018-09-04 06:16 UTC
I believe the documentation in regards to setting this option via Visual Studio to be incorrect. Doing the follwoing in VS 15.8.1 only triggers the "/delaysign+" compiler option:
1. Open the Properties page for the project.
2. Modify the Delay sign only property.

In order to trigger the "/publicsign+" compiler option, the project file must be edited and the "&lt;publicsign&gt;true&lt;/publicsign&gt;" property must be set. There appears to be no way to configure this behavior from within the Visual Studio UI itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7871f3-e680-0424-01fe-9fd91b154275
* Version Independent ID: b2f4b5bd-d13b-36b2-a064-9b4d519c4348
* Content: [-publicsign (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/publicsign-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/publicsign-compiler-option.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/compiler-options/publicsign-compiler-option.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by sharpe5** [comment] 2018-09-17 10:34
I can confirm this issue. There is no option in the Visual Studio GUI to select public signing. Am running 
latest as of today (15.8.4).

**Comment by chucker** [comment] 2019-05-02 21:39
Of note, plans to (possibly) add a UI for this switch appear to be tracked in https://github.com/dotnet/project-system/issues/126.

Until then, the entire "To set this compiler option in the Visual Studio development environment" section should be removed, as there is clearly no UI for `/publicsign` at this point; you have to edit the file by hand (which as of VS 2019 can be done by double-clicking the project).

**Comment by a-ctor** [comment] 2020-09-14 07:50
I think this issue can be closed because the duplicate #18772 was fixed with PR #20047.

**Closed** 2021-01-19 22:46 UTC
Labels: :books: Area - C# Guide, P1, Pri2, doc-bug, dotnet-csharp/prod
