### ISSUE TITLE
Confusing statement

### ISSUE THREAD

**Issue by deivid321** [dotnet/docs#7588] opened 2018-09-08 19:47 UTC
X DO NOT define mutable value types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9a59d65-a915-4a7f-47d8-f212dd30d952
* Version Independent ID: be012363-e0c4-abec-df76-19c29c33bb1a
* Content: [Struct Design](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/struct)
* Content Source: [docs/standard/design-guidelines/struct.md](https://github.com/dotnet/docs/blob/master/docs/standard/design-guidelines/struct.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2018-09-10 18:34
Thanks for the comment, @deivid321. Unfortunately, the Design Guidelines section is reprinted with permission of Pearson Education, so it cannot be modified. I'm also unsure what the confusing statement is; the text that immediately follows "DO NOT define mutable value types" provides an explanation.  For more information, see [Mutable value types: the good, the bad and the ugly](https://blogs.msdn.microsoft.com/pfxteam/2009/05/06/mutable-value-types-the-good-the-bad-and-the-ugly/). If the issue is that a mutable value type is not defined, it's a C# struct or a Visual Basic structure with members whose values can be modified after they are created. I hope that this helps to clear up any confusion.
Since we can't modify the text, I'll close this issue.

**Closed by rpetrusha** 2018-09-10 18:34 UTC
Labels: :books: Area - .NET Guide, :file_folder: Repo - docs, Source - Docs.ms, question
