### ISSUE TITLE
string.Create is missing

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/docs#22898] opened 2021-02-18 09:33 UTC
[string.Create](https://docs.microsoft.com/en-us/dotnet/api/system.string.create) is a performant way of creating strings and should be on this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c76a8206-037e-7563-d856-cf13fdb81d6d
* Version Independent ID: ba06f202-b642-4ec0-0755-9777b80fda64
* Content: [Creating New Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/creating-new)
* Content Source: [docs/standard/base-types/creating-new.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/creating-new.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by HugoDurana** [comment] 2021-02-18 09:44
+1

**Comment by adegeo** [comment] 2021-02-18 17:03
@paulomorgado @HugoDurana This seems like an advanced scenario/usage though, not a fundamental.

**Comment by paulomorgado** [comment] 2021-02-18 17:52
You have a point there, @adegeo.

But it's even more advanced if it's not discoverable.

And it's a disservice to users if basic concepts do not have links to advanced concepts. How would they progress?

**Comment by adegeo** [comment] 2022-12-08 02:43
Duplicate of #20420

**Closed by adegeo** 2022-12-08 02:43 UTC
Labels: doc-enhancement, Pri2, dotnet-fundamentals/prod
