### ISSUE TITLE
The nuance of working with the var keyword.

### ISSUE THREAD

**Issue by lutk** [dotnet/docs#21594] opened 2020-11-16 20:11 UTC
Why is there no mention of the nuance of working with the var keyword in any document on this topic?

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/var
"When var is used with nullable reference types enabled, it always implies a nullable reference type even if the expression type isn't nullable."

In my opinion, this outweighs absolutely all the advantages of using nullable reference types and makes reading and refactoring a real hell.
Madness..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* Technology: **csharp-null-safety**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-11-18 14:40
Thanks for writing this @lutk 

I've added this to our backlog to address when we next update this topic.

**Comment by tdykstra** [comment] 2021-08-09 18:36
Closing as duplicate of #21716

**Closed by tdykstra** 2021-08-09 18:36 UTC
Labels: doc-enhancement, Pri2, dotnet-csharp/prod, csharp-null-safety/tech
