### ISSUE TITLE
DataKind Enum is not well documented

### ISSUE THREAD

**Issue by niteshkumarshaw** [dotnet/docs#9278] opened 2018-11-28 03:31 UTC
DataKind Enum is not well documented, this is an very important think to be documented with a priority bases. Earlier i use python for ML part now i wish to use this library further but i can't find any documentation on so many parts this is one of them and a very impotent one. please give some documentation so that anyone can understand situation/purpose to use these enum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbe7af6f-d0db-6da8-5e2c-301750a3695d
* Version Independent ID: b67dfcf5-5d21-d81f-37d1-76d8d7111111
* Content: [DataKind Enum (Microsoft.ML.Runtime.Data)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.runtime.data.datakind?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.ML.Runtime.Data.DataKind);k(DevLang-csharp)%26rd%3Dtrue&view=ml-dotnet)
* Content Source: [dotnet/xml/Microsoft.ML.Runtime.Data/DataKind.xml](https://github.com/dotnet/ml-api-docs/blob/live/dotnet/xml/Microsoft.ML.Runtime.Data/DataKind.xml)
* Product: **dotnet-ml-api**
* GitHub Login: @sfilipi
* Microsoft Alias: **johalex**

**Comment by koav** [comment] 2018-12-10 13:16
Hello, maybe this will be useful for you. Inside the library I found the following type match:

            I1= sbyte
            U1= byte
            I2= short
            U2= ushort
            I4= int
            U4= uint
            I8= long
            U8= ulong
            R4= Single
            R8= Double
            TX= ReadOnlyMemory<char>
            BL= bool
            TS= TimeSpan
            DT= DateTime
            DZ= DateTimeOffset
            UG= UInt128

**Comment by mairaw** [comment] 2018-12-17 22:10
Duplicate of #9184

**Closed by mairaw** 2018-12-17 22:10 UTC
Labels: :file_folder: Repo - ml-api-docs, :watch: Not Triaged, Source - Docs.ms

**Comment by Faizansoft** [comment] 2018-12-18 14:50
With regards to:
 TS= TimeSpan
        DT= DateTime
        DZ= DateTimeOffset
Could anyone give some examples of data that would work with these types? I had some issue using them, when i tried ML.net with my own data.
