### ISSUE TITLE
Broken "LocBaml" link

### ISSUE THREAD

**Issue by tomahawk1277** [dotnet/docs#7868] opened 2018-09-24 18:18 UTC
The introduction paragraph has a broken link to "LocBaml Tool Sample" that is trying to go to https://archive.msdn.microsoft.com/Project/Download/FileDownload.aspx?ProjectName=wpfsamples&DownloadId=9333 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4baeeb7d-bba4-c8c5-6f54-97dc68a59aef
* Version Independent ID: d248598d-5657-1a8c-3f91-b37384243eff
* Content: [WPF Globalization and Localization Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-globalization-and-localization-overview)
* Content Source: [docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-09-24 20:08
Thank you for your feedback @tomahawk1277. This is a duplicate of #3623. We're still trying to figure out where that link should go.

**Closed by mairaw** 2018-09-24 20:08 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WPF, :watch: Not Triaged, Source - Docs.ms
