### ISSUE TITLE
Duplication of Linux distro dependencies

### ISSUE THREAD

**Issue by mthalman** [dotnet/docs#18978] opened 2020-06-16 21:02 UTC
**Issue description**

There is a lot of duplicate content between https://github.com/dotnet/docs/blob/master/docs/core/install/dependencies.md and each of the individual distro pages (e.g. https://github.com/dotnet/docs/blob/master/docs/core/install/linux-alpine.md).  Specifically, I'm referring to the list of dependencies that .NET has for a given distro.  For Alpine Linux, you can see the list [here](https://github.com/dotnet/docs/blob/master/docs/core/install/dependencies.md#alpine) and a duplicate [here](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-alpine.md#dependencies).  Duplicate content like this is problematic because it just adds one more spot that needs to get updated when a change occurs.  This can easily lead to content getting out of sync (related: https://github.com/dotnet/runtime/issues/13291).

To me, it seems like the entire Linux section of https://github.com/dotnet/docs/blob/master/docs/core/install/dependencies.md#linux-distribution-dependencies should be removed in favor of https://github.com/dotnet/docs/blob/master/docs/core/install/linux.md.  The only stuff left would be Windows-specific.

The main point is that this needs to get cleaned up.

cc @thraka

**Comment by Thraka** [comment] 2020-06-17 17:21
@mthalman Yes, as part of the process of cleaning this up, I had this issue filed: #18870 I didn't explicitly call out the dependencies article in it, but it would have migrated as part of that change. I just updated the issue to cover it.

I'm going to close this in favor of that one.

**Comment by Thraka** [comment] 2020-06-17 17:21
Duplicate of #18870

**Closed by Thraka** 2020-06-17 17:21 UTC
Labels: :watch: Not Triaged
