### ISSUE TITLE
Explain how to use System.Text.Json with VB

### ISSUE THREAD

**Issue by paul1956** [dotnet/docs#22096] opened 2020-12-20 07:48 UTC
Most article have VB and C# dropdown, this one is missing that and could use it. If this is open source and someone can explain how to do the dropdown I would be willing to convert the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by Youssef1313** [comment] 2020-12-20 14:34
The markdown file for this is <https://github.com/dotnet/docs/blob/master/docs/standard/serialization/system-text-json-how-to.md>, you can submit a PR against it.

In this markdown file, you'll find lines starting with `:::code language="csharp"`, you'll need to add parallel lines under them for vb.

Then you'll need to add a dev_langs metadata.

Adding @tdykstra to confirm whether he wants to add parallel VB code for this article.

**Comment by paul1956** [comment] 2020-12-20 22:35
@Youssef1313 thanks, I will wait to hear if @tdykstra wants VB samples. I assume if not there is no point in doing a PR. If yes I don't know how to add dev_langs metadata is there a sample?

**Comment by tdykstra** [comment] 2020-12-21 18:42
Yes, we'd be happy to incorporate VB for the System.Text.Json articles. See this example for dev_langs in the metadata block at the top of the article:  https://raw.githubusercontent.com/dotnet/docs/master/docs/core/tutorials/with-visual-studio.md

**Comment by paul1956** [comment] 2020-12-22 03:29
@tdykstra Some of the features/examples are not compatible with VB but the most useful ones coming from Newtonsoft work correctly in VB, How do you want me to handle that? BTW without this article I would have thought the whole library was broken for VB, it is excellent.

**Comment by tdykstra** [comment] 2020-12-23 19:02
For now, just don't make a VB version for a snippet if it doesn't work in VB, and I'll look into how we want to display that (perhaps a standardized VB code block that just says the feature is not available).

FYI You'll find two approaches to presenting code in the docs -- there's a project for the original doc created for 3.1 and there's a project for the 5.0 additions.  The older project uses snippet tags (XML tags in code comments that define which part of a file to display in the doc) to minimize the amount of code shown in the doc, while the latter does not use snippet tags and instead goes  the route of displaying entire code files so the person who reads the code in the doc isn't missing any context and can try it out by just copying and pasting the whole code block into a project.

**Comment by paul1956** [comment] 2020-12-25 04:29
@tyclintw I ported both and if I suppress the Obsolete error, (almost) all the code from both paths run in VB without error, the few that don't are bugs in my port that I need to resolve. Without that suppression very few run at all and would require significate rewriting and probably a different article just focused on how to use the library with VB and many of the performance comments would not apply.  @CyrusNajmabadi wants to remove the suppression to prevent VB from using most of this libraries like this one. if the is the case you should probably close this issue and open one to document the library just for VB.

**Comment by CyrusNajmabadi** [comment] 2020-12-25 05:26
We absolutely should not doc this for vb using suppression of the obsolete attribute. That is definitely not at all what we would want people to do. Please do not publish docs that do that under any circumstances.

**Comment by paul1956** [comment] 2020-12-25 06:28
@tdykstra @CyrusNajmabadi that is why I copied you and based on that I don't think documenting this article for VB is correct either.

**Comment by tdykstra** [comment] 2020-12-26 21:27
@paul1956 Do you have the converted VB code in a repository where I can take a look and see what is showing up as obsolete?

**Comment by paul1956** [comment] 2020-12-26 21:41
I have it on my local machine. I can push in about an hour. I will not do a PR. So it will be on https://github.com/paul1956/docs. There are now VisualBasic directories for both snippets with project files.

**Comment by paul1956** [comment] 2020-12-26 22:58
@tdykstra I posted it, let me know if you have any questions, just search for
```
<Obsolete("Ignore", False)>
```
to see all the places I needed to use the workaround. Most of the examples run a few don't because port is not complete, they pointed too issues with converter that I am fixing and I am not working on this for now because of the Obsolete issue.

**Comment by tdykstra** [comment] 2020-12-27 02:03
@layomia what guidance should we give regarding System.Text.Json use in Visual Basic? Trying to convert existing C# projects to VB results in many BC40000 obsolete warnings (which indicate user-defined types are obsolete, not STJ APIs), some of which seem to result from root cause errors like this one:

> BC30668	'Utf8JsonReader' is obsolete: 'Types with embedded references are not supported in this version of your compiler.'.

Most of the translated code runs successfully when the BC40000 errors are ignored.

**Comment by paul1956** [comment] 2020-12-27 03:29
@layomia I would say all will work correctly what doesn't currently work is due to translation errors caused by automatic translation. They would need to be manually fixed before I would do a PR (which as of now I am not doing). This was only posted in this state so @tdykstra could review. There are also all kind of formatting issues.

**Comment by CyrusNajmabadi** [comment] 2020-12-27 05:43
Please see: https://github.com/dotnet/docs/issues/22096#issuecomment-751174985

These types are marked as Obsolete precisely so they are not used from languages that we haven't added explicit ref-struct support for.  That includes VB.  

> Trying to convert existing C# projects to VB results in many BC40000 obsolete warnings

Yes.  This is the expected behavior.  These APis are *not* supported from languages that do not have ref-struct support.  We should not doc otherwise as that could be very confusing for users in terms of making it seem like they are supported in some fashion.  Tagging @KathleenDollard

**Comment by tdykstra** [comment] 2020-12-28 01:16
@CyrusNajmabadi Thanks for the explanation. It sounds like we should simply advise against using System.Text.Json with VB. For VB users it would be helpful if we could give a better error message than BC40000 obsolete.

**Comment by CyrusNajmabadi** [comment] 2020-12-28 01:54
> For VB users it would be helpful if we could give a better error message than BC40000 obsolete.

Agreed. However, this was done to prevent older compilers (including c#) from using these. The only way to get an older compiler to reject it is to use something they recognize is not allowed. In the car 'Obsolete'

**Comment by tdykstra** [comment] 2021-01-04 22:31
@paul1956 I'm sorry about the time you spent converting the snippets to VB - I didn't know about the ref struct issue when I said go ahead.  I've created a PR to add a note that explains the BC40000 errors and advises against using System.Text.Json with VB.

**Comment by paul1956** [comment] 2021-01-04 23:08
There may be some functions in the library usable by VB but the article would need a rewrite because they are not the high performance ones.

**Comment by tdykstra** [comment] 2021-01-13 17:52
Reopening the issue to be about publishing an article explaining how to use System.Text.Json with VB, rather than a note warning not to use it. See revised note in the C# article - #22323.

**Comment by tdykstra** [comment] 2021-01-15 02:07
@paul1956 We've had some discussions offline and here's the revised plan:

* Make the VB note we just added into an H2 section that we can link to.
* Expand the note to explain that this means you can’t write custom converters (since you can’t override the Read method, because it takes a Utf8JsonReader)
* At the top of several docs, link to the VB note:
  * How to write custom converters
  * How to migrate from Newtonsoft docs
  * How to use JsonDocument, Utf8JsonReader, and Utf8JsonWriter
* Make VB versions of Utf8JsonReader and custom converter snippets that contain only a link to the VB note. When the reader selects VB, the link to that note is all they'll see for tasks that can't be done safely in VB.
* Make VB version of the first snippet under [Deserialize from UTF-8](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-5-0#deserialize-from-utf-8), by changing
  ```
  var readOnlySpan = new ReadOnlySpan<byte>(jsonUtf8Bytes);
  weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(readOnlySpan);
  ```
  to the VB equivalent of:
  ```
  var jsonString = Encoding.UTF8.GetString(jsonUtf8Bytes);
  weatherForecast = JsonSerializer.Deserialize<WeatherForecast>(jsonString);
  ```
* All other snippets can just convert from C# to VB, as there are no other uses of reader or span.

So we can use your VB code, it just needs:
* Remove all of the obsolete-ignore attributes.
* Replace the snippet noted above that uses Span with the String alternative.
* Replace all of the other snippets that use Utf8JsonReader with 
  ```
  https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-how-to#visual-basic-support
  ```
* Remove all of the code that is used to support Utf8JsonReader-related snippets but isn't displayed in a doc as a snippet.

I'll take care of the doc changes listed above.  Do you want to make the changes to your existing VB code and make a PR for that? We will need the [5.0 snippets](https://github.com/dotnet/docs/tree/master/docs/standard/serialization/snippets/system-text-json-how-to-5-0/csharp) as well as the [original collection written for 3.1](https://github.com/dotnet/docs/tree/master/docs/standard/serialization/snippets/system-text-json-how-to/csharp) and [the configure options project](https://github.com/dotnet/docs/tree/master/docs/standard/serialization/snippets/system-text-json-configure-options/csharp). If you'd prefer, I can take the code you have and make the required changes and a PR for that.

**Comment by paul1956** [comment] 2021-01-15 02:19
@tdykstra you can make the changes, let me know if there is any thing you need from me. Thank you and everyone else that contributed to coming to this fantastic resolution. If it OK I will like this discussion to the GitHub discussion, it is much better then I had hoped for.

**Comment by tdykstra** [comment] 2021-01-19 21:44
>let me know if there is any thing you need from me.

If you could review the PR https://github.com/dotnet/docs/pull/22414 it would be much appreciated. You can make fixes and suggestions in the browser, or via a PR to my fork/branch before the PR is merged, or via a PR to master after the PR is merged.

>If it OK I will like this discussion to the GitHub discussion

OK with me

**Comment by paul1956** [comment] 2021-01-20 01:13
@tdykstra would love to review, I forked you repo which Branch should I review? FYI I have never reviewed a PR in Visual Studio.

**Comment by tdykstra** [comment] 2021-01-20 01:38
Branch is vbnotes. I haven't done a GitHub review in VS either, I usually use the browser.  You can make changes to the code in VS and make them into a pull request if you prefer.

**Comment by paul1956** [comment] 2021-01-20 02:22
Figured it out, cleaned up code, by opening project file in VS and running "code cleanup". Also dot rid of 2 our of 3 IDE issues. The last is an assignment that is never used but that makes sense since user code after the assignment is intentionally missing.

**Comment by layomia** [comment] 2021-01-21 17:10
> - Expand the note to explain that this means you can’t write custom converters (since you can’t override the Read method, because it takes a Utf8JsonReader)

@tdykstra - just want to note that a workaround for this is to implement custom converters in a C# library assembly, and reference that assembly from your VB project. This assumes that all that is being done is registering the converters into the serializer, and not calling the `Read` methods of the converters from VB code. We could mention this in the planned docs, and maybe show an example.

**Closed** 2021-02-16 18:56 UTC
Labels: Pri1, doc-idea, dotnet-core/prod, dotnet-fundamentals/prod
