### ISSUE TITLE
Nothing provides krb5-libs (openSUSE 15.1)

### ISSUE THREAD

**Issue by rooper149** [dotnet/docs#16330] opened 2019-12-19 04:49 UTC
It seems "dotnet-runtime-deps-3.1-3.1.0-1.x86_64" depends on "krb5-libs" which is not provided by either the Leap repositories or the .net Core repositories. I imagine that the krb5 or krb5-client packages provide the same functionality on SUSE as krb5-libs does on Red Hat. The dependencies probably need to be updated for openSUSE 15.1.

edit by @mairaw: add topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6baea63-f650-e232-854b-c1722ed72543
* Version Independent ID: 56c0bff6-2630-06f8-9c86-e81ca292fd2f
* Content: [Install .NET Core on openSUSE 15 - package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-opensuse15)
* Content Source: [docs/core/install/linux-package-manager-opensuse15.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-opensuse15.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by mairaw** [comment] 2019-12-19 22:45
Thanks for your feedback @rooper149. Is this about the following page:
https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux?

**Comment by rooper149** [comment] 2019-12-19 22:53
@mairaw That page and: 
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-opensuse15

You show support for openSUSE, but there are breaking package dependencies in the install. openSUSE does not provide the package "krb5-libs", it is provided under the name "krb5" instead. This causes the installation to break on openSUSE.

**Comment by mairaw** [comment] 2019-12-19 22:56
Ok, thanks for the additional information.

**Comment by dagood** [comment] 2019-12-23 20:51
This is a release issue (probably related to the other 3.1.0 problems) where the RPM for some distro where it's called `krb5-libs` is showing up when trying to install for this one. This is a problem for 15.0 as well, not just 15.1. See https://github.com/dotnet/runtime/issues/929#issuecomment-566211014 for more info.

> As a workaround, run this command before the normal .NET Core install command to grab the correct version of this package:
> 
> ```
> sudo zypper install https://packages.microsoft.com/opensuse/15/prod/dotnet-runtime-deps-3.1.0-opensuse.42-x64.rpm
> ```

(Even though this doc comment is a duplicate of https://github.com/dotnet/runtime/issues/929, it would make sense to me to leave it open so others hitting it can see it easily on the docs page until we get it resolved. Thanks for filing.)

**Comment by Thraka** [comment] 2019-12-26 22:51
@dagood with how easy it is to update the docs, we should put a note in the instructions that call this out. When it's fixed, we can remove it from the docs.

**Closed** 2020-01-07 19:19 UTC
Labels: :books: Area - .NET Core Guide, doc-bug
