### ISSUE TITLE
Update for .NET Core 3.0

### ISSUE THREAD

**Issue by jawn** [dotnet/docs#14891] opened 2019-10-02 09:50 UTC
This and other pages in the dotnet core site should be updated to indicate .NET Core 3.0 support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6c9b5-64cb-1dc6-21d0-ad8f0a1185fe
* Version Independent ID: 0f6c658c-b477-2d2c-2a9a-d74f6ae38d3f
* Content: [dotnet command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21)
* Content Source: [docs/core/tools/dotnet.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment] 2019-10-02 16:56
Hello. Thank you for letting us know, we already have an issue tracking this work. Sorry for the delay.

Duplicate of #9893

**Comment by mairaw** [comment] 2019-10-02 16:57
Thanks for your feedback @jawn. We're tracking that work with issue #9893. About ref of the reference was updated already. Half still needs to be done.

**Comment by Thraka** [comment] 2019-10-02 16:57
Duplicate of #9893

**Closed by Thraka** 2019-10-02 16:56 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, Source - Docs.ms
