### ISSUE TITLE
VB.NET code missing

### ISSUE THREAD

**Issue by AntonioCaroppos** [dotnet/docs#5636] opened 2018-05-27 22:08 UTC
As title says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b0b11b-f27e-a4df-8804-e443ba1b91d7
* Version Independent ID: fdccc459-a827-154d-7a9b-4ad295e07ab2
* Content: [How to: Use a Color Matrix to Transform a Single Color](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-use-a-color-matrix-to-transform-a-single-color)
* Content Source: [docs/framework/winforms/advanced/how-to-use-a-color-matrix-to-transform-a-single-color.md](https://github.com/dotnet/docs/blob/master/docs/framework/winforms/advanced/how-to-use-a-color-matrix-to-transform-a-single-color.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by AntonioCaroppos** [comment] 2018-05-27 22:09
Found it on the right side of the screen, not in the usual spot.

**Comment by rpetrusha** [comment] 2018-05-29 17:00
@AntonioCaroppos, do you mean that you found the version selector on the right side of the screen, and that when you changed it to VB, the VB code was present? If so, that's by design.
I'm going to close this issue, since that's my interpretation of what you mean, and the VB code is present. If I'm mistaken, feel free to respond.

**Closed by rpetrusha** 2018-05-29 17:00 UTC
Labels: Source - Docs.ms
