### ISSUE TITLE
Introduce Prev and Next buttons for easy navigation

### ISSUE THREAD

**Issue by reyou** [dotnet/docs#817] opened 2016-07-18 19:54 UTC
Please include Prev and Next buttons at the beginning and end of the content. There are 2 reasons it will be helpful:

1- For mobile devices, mostly left navigation bar is collapsed and it makes it very hard to jump on next article.
2- For long articles we need to always scroll top to find our last point and click the next topic link.
For Example: https://docs.microsoft.com/en-us/dotnet/articles/standard/index

Good Example: https://developer.xamarin.com/guides/cross-platform/getting_started/
Good Example 2: https://docs.unity3d.com/Manual/index.html

**Comment by mairaw** [comment] 2016-07-18 20:42
Thanks @reyou. As I said on the article, we'll be definitely adding the prev and next buttons to the step-by-step tutorials.

The ASP.NET docs also currently has this: https://docs.asp.net/en/latest/getting-started.html

Thoughts?

/cc @BillWagner @Rick-Anderson @richlander @danroth27

**Comment by reyou** [comment] 2016-07-19 12:54
Thanks @mairaw. Yes, that implementation looks great. I was thinking entire Microsoft developer documentation will be under one umbrella like docs.microsoft.com/{technology}, but looks like fragmentation already started with asp.net core. Anyway this is another discussion point :) I am looking forward to have updated documentation as well (asp.net core with MsBuild support). Thanks!

**Comment by mairaw** [comment] 2016-08-03 17:38
We're trying to fix the fragmentation. Eventually all docs will be at docs.microsoft.com.

**Comment by BillWagner** [comment] 2016-12-07 18:26
@EisenbergEffect I think this request would might be addressed by some of the different ideas you have in the design backlog.  Would you like to comment?

**Comment by EisenbergEffect** [comment] 2016-12-07 21:34
Two points related to this:

* We currently have a feature to improve the ToC so that it remains always in view and automatically scrolls the current article into view. So, no more need to scroll to top. The feature is implemented but still needs final review. I'm hopeful that it will go out soon.
* For next and back buttons specifically, we have some other features that we're working on related step-by-step experiences. I'm not sure if it make sense to put these on every article though. If it's mostly an issue of being able to navigate through a lot of content in a single sitting, then perhaps the ToC improvement above will address that?

**Comment by reyou** [comment] 2016-12-07 22:05
@EisenbergEffect 
I would recommend navigation buttons for docs. 
Unfortunately, automatic scrolling will not fix issue for users who are on their phones.  Since navigation bar will be hidden from small screens, navigating to next section creates a little hassle. And, for fresh-new developers, who will start reading docs, after 5 chapters, they would want to bookmark page and continue reading from their phone.

Honestly, I do this very easily while I am reading xamarin, unity3d and even amazon lumberyard documentations. Since these documentations are structured as book-like contents, I can read them like a book by skipping next article easily.

**Comment by EisenbergEffect** [comment] 2016-12-07 23:52
If the problem is primarily related to navigation between docs on a mobile device, we are planning to completely re-design the mobile UX. We were actually just discussing that yesterday :)

**Comment by mairaw** [comment] 2018-09-17 20:47
We do have Prev and Next buttons to selected areas like the e-books and the mobile experience has been improving over time. But we won't be adding Prev and Next buttons to every docs page here.

**Closed by mairaw** 2018-09-17 20:47 UTC
Labels: P2, doc-enhancement, external
