### ISSUE TITLE
Can't get dotnet-runtime-3.1 installed on Debian Buster / RPi ZeroW

### ISSUE THREAD

**Issue by HansR00** [dotnet/docs#19923] opened 2020-08-09 07:30 UTC
Tried install  dotnet-runtime-3.1 on Debian Buster with every possibility offered on the main page and on the APT-troubleshoot page. Unfortunately it keeps coming with the message:

E: Kan pakket dotnet-runtime-3.1 niet vinden
E: Kon geen enkel pakket vinden via expansie (glob) 'dotnet-runtime-3.1'
E: Kon geen enkel pakket vinden via regex 'dotnet-runtime-3.1'

Translation: Can't find package (neither through expansion nor through regex)

Hardware: Pi ZeroW (with Raspberry Pi OS (32-bit) with desktop)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET Core on Debian - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-debian.md)
* Product: **dotnet-core**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by dagood** [comment] 2020-08-12 06:25
RPi devices are ARM, not x64, so you need to follow these instructions at the top of the doc:

> _Package manager installs are only supported on the **x64** architecture_. Other architectures, such as **ARM**, must manually install the .NET Core SDK or .NET Core Runtime. For more information, see the manually install section below.

Getting this documented better on the page (it's easy to miss!) is tracked by https://github.com/dotnet/docs/issues/19564.
Supporting arm/arm64 on our Linux package repos is tracked by https://github.com/dotnet/runtime/issues/3263.

**Comment by adegeo** [comment] 2020-09-11 23:52
Duplicate of #19564

**Closed by adegeo** 2020-09-11 23:52 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged
