### ISSUE TITLE
Group clause section of this page

### ISSUE THREAD

**Issue by PostalMike** [dotnet/docs#23883] opened 2021-04-22 17:44 UTC
[Enter feedback here]
Use the group clause to produce a sequence of groups organized by a key that you specify. The key can be any data type. For example, the following query creates a sequence of groups that contains one or more Country objects and whose key is a char value.

C#

Copy
var queryCountryGroups =
    from country in countries
    group country by country.Name[0];
For more information about grouping, see group clause.

This section could be clarified.  The key really is a *string* and not a *char* value, yes? A char is a single character and a string consists of 2 or more char values.  So this confused me.  My definition of string may not be programmatically correct but yes a string is 2 or more char values.

The [0] indexer is confusing, I would think country.Name would be the grouping qualifier but I'm thinking SQL here too.  This would group any with Suriname, for instance, together.  Any from Germany together and so on.  So what does the [0] indexer do?

This said I do get from the context what a group clause does here.  This could be a code snippet and the context not seen here might have an array where the names are all at [0] index but by itself the indexer introduces confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888d4d4e-48ca-db9d-e36d-006f4aeeb83b
* Version Independent ID: ac336cb4-251f-51d1-c35e-cc3693677f41
* Content: [Query expression basics (LINQ in C#)](https://docs.microsoft.com/en-us/dotnet/csharp/linq/query-expression-basics)
* Content Source: [docs/csharp/linq/query-expression-basics.md](https://github.com/dotnet/docs/blob/main/docs/csharp/linq/query-expression-basics.md)
* Product: **dotnet-csharp**
* Technology: **csharp-linq**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-04-23 15:10
Thanks for reaching out @PostalMike 

I'll close this as a duplicate of #23885 which has similar information, but more details.

**Closed by BillWagner** 2021-04-23 15:10 UTC
Labels: :watch: Not Triaged, Pri1, csharp-linq/tech, dotnet-csharp/prod
