### ISSUE TITLE
The example give syntax error when using in Word 2016

### ISSUE THREAD

**Issue by cscuser3** [dotnet/docs#7971] opened 2018-10-01 18:31 UTC
I am working with Microsoft word 2016. Error 5991 is not being captured with On Error. So, I tried your example.
World complains err.clear() is not valid. But it accepts err.clear. When I run your example it does not capture divide by -0-.
The if statement isn't executed because the error number is 11 not 6. Other than that the code worked. 
Thanks.
Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6084eed-4de2-830f-c53e-a8546d5ef97a
* Version Independent ID: a50deb55-d5a9-db11-0eeb-e03402dd356d
* Content: [On Error Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement#feedback)
* Content Source: [docs/visual-basic/language-reference/statements/on-error-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/on-error-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment] 2018-10-01 22:17
Thanks for your feedback, @cscuser3. Word 2016 supports Visual Basic for Applications. The articles in docs.microsoft.com/dotnet/visual-basic document Visual Basic .NET, which is a different programming language that supports .NET Framework. Although they are similar, there are numerous differences, some of which you've reported here.

Since this is Visual Basic .NET documentation, I'll close this issue as by design.

**Closed by rpetrusha** 2018-10-01 22:17 UTC
Labels: :books: Area - Visual Basic Guide, :file_folder: Repo - docs, Source - Docs.ms, by-design, triaged
