### ISSUE TITLE
Auto formatting issue in VB

### ISSUE THREAD

**Issue by jamieyello** [dotnet/docs#9845] opened 2019-01-05 04:55 UTC
When using the example code in a place where File is already being used for its static methods, VS doesn't differentiate the object 'file' and the class 'File' and throws an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a619af2e-3561-968c-f48c-c16812f90787
* Version Independent ID: e3bc516e-bfc9-7903-0897-cf911c97c1ee
* Content: [How to: Write Text to Files with a StreamWriter in Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/developing-apps/programming/drives-directories-files/how-to-write-text-to-files-with-a-streamwriter)
* Content Source: [docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-write-text-to-files-with-a-streamwriter.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/developing-apps/programming/drives-directories-files/how-to-write-text-to-files-with-a-streamwriter.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by KathleenDollard** [comment] 2019-01-08 19:54
@jamieyello Are you just pointing out that "file" may not be a good variable name here?

**Comment by jamieyello** [comment] 2019-01-11 07:14
Basically. It throws an error when used alongside a static File.Method().

**Comment by KathleenDollard** [comment] 2019-01-11 20:52
Are you surprised by the behavior? 

I am not sure what I'm overlooking here, but this feels like basic VB behavior and I'm not sure what we should change in this article. 

Sorry if I am being dense here.

**Comment by mairaw** [comment] 2019-01-14 22:08
Should we then just change the variable name @KathleenDollard as you suggested earlier?

**Comment by KathleenDollard** [comment] 2019-01-17 22:41
Yes. That should be the action item here I believe.

**Comment by KathleenDollard** [comment] 2019-01-17 22:42
I'm unclear that we would even need to do that. It is an imperfect variable name, but it looks like normal VB behavior.

**Comment by mairaw** [comment] 2019-03-04 22:41
So I'll close this as by design.

**Closed by mairaw** 2019-03-04 22:41 UTC
Labels: :books: Area - Visual Basic Guide, P2, Source - Docs.ms, waiting-on-feedback
