### ISSUE TITLE
Implicit or Explicit in the foreach example?

### ISSUE THREAD

**Issue by fosstin** [dotnet/docs#18958] opened 2020-06-15 15:36 UTC
It seems there may be a typo in the code example below following the line, "The following example uses explicit typing in a foreach statement."

The bullet above the example reads, "Do not use implicit typing to determine the type of the loop variable in foreach loops."  However, the code example contains: **foreach** (**var** ch **in** laugh) in the foreach statement.  Should this be **string** ch instead of **var** ch?

Thanks,
Austin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-06-15 15:44
Duplicate of #18940

**Closed by BillWagner** 2020-06-15 15:44 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged
