### ISSUE TITLE
Rule feedback

### ISSUE THREAD

**Issue by dionito** [dotnet/docs#23748] opened 2021-04-10 17:18 UTC
[Enter feedback here]
When setting the rule 
csharp_style_var_when_type_is_apparent = true

it considers apparent something like:
var x = Foo-bar().ToList();

In my opinion this is not apparent at all since it can be a List of anything.

However, it does not consider apparent something like:
Document doc = CreateDocument<Document>(foo-bar);

where the return type and the generic are the same. IMO this is way more apparent that the ToList() case.

Cheers,
Dioni

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9e99e36-a3b1-ac38-c66d-905d9be1fa01
* Version Independent ID: d035351b-536b-6f80-69ac-4d12527284c3
* Content: [IDE0007 and IDE0008: 'var' preferences - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0007-ide0008.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment] 2021-04-10 18:35
Duplicate of https://github.com/dotnet/roslyn/issues/29657.

**Comment by gewarren** [comment] 2021-04-12 15:41
Closing this as a duplicate.

**Closed by gewarren** 2021-04-12 15:41 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-fundamentals/prod
