### ISSUE TITLE
.NET 8 - CA1863 analyzer rule's web page returns 404 Not Found

### ISSUE THREAD

**Issue by felpel** [dotnet/docs#38319] opened 2023-11-18 22:09 UTC
### Type of issue

Missing information

### Description

I'm currently fiddling with .NET 8 and stumbled on this warning in my project:

![image](https://github.com/dotnet/docs/assets/5000004/4b11771e-67da-4f7a-928b-34bfa479a215)

Given I'm not familiar with this, I wanted to have a look at the help article and see whether it is worth applying to my project or not, but the [configured hyperlink](https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/quality-rules/ca1863) leads nowhere.

![image](https://github.com/dotnet/docs/assets/5000004/61cd627d-e48a-4d08-b865-34cec743a8c7)

### Page URL

https://learn.microsoft.com/en-ca/dotnet/fundamentals/code-analysis/overview?tabs=net-8

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/overview.md

### Document Version Independent Id

128f9903-971d-6a66-a2cb-9b12acbc55e7

### Article author

gewarren

### Metadata

* ID: f8906b2c-b984-0427-d064-829e7ea2fc55 
* Product: **dotnet-fundamentals**

**Comment by Rageking8** [comment] 2023-11-19 15:33
Duplicate of #38266

**Comment by felpel** [comment] 2023-11-19 17:51
@Rageking8 I've closed this one in favor of the one you've linked, thank you 🙏

**Closed** 2023-11-19 17:51 UTC
Labels: resolved-by-customer, Pri1, dotnet-fundamentals/prod
