### ISSUE TITLE
Use kbd tag when possible and general markdown improvements

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/docs#14987] opened 2019-10-06 16:54 UTC
The usage of they `<kbd>` tag would be better than bold or just normal text. Currently, `<kbd>` is used in a really few articles. Example where it's used is [Tutorial: Create a .NET Core solution in macOS using Visual Studio Code](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos).

-----

**General markdown improvements:**

Make sure that the following points from the current style guide are followed:

1. This point caused an issue before with some regex being rendered incorrectly. There could be many occurrences where it causes a problem.

> Markdown uses special characters such as *, `, and # for formatting. If you wish to include one of these characters in your content, you must do one of two things:
> - Put a backslash before the special character to "escape" it (for example, \* for a *)
> - Use the HTML entity code for the character (for example, &#42; for a *).

2. This is less priority but may be taken into consideration at some point of time.

> File names use the following rules:
> - Use action verbs that are specific, such as develop, buy, build, troubleshoot. No -ing words.
> - No small words - don't include a, and, the, in, or, etc.

3. This was changed in the guide soon, it **was** to **capitalize** the word following a colon, so there are a lot of articles that doesn't follow this **current** guide.

> Use sentence-style capitalization. Always capitalize the first word of a heading, but don't capitalize the word following a colon in a title or heading (for example, "How to: sort an array").

4. 

> *Italics* Use for files, folders, paths (for long items, split onto their own line), new terms.
> **Bold** Use for UI elements.
> `Code` Use for inline code, language keywords, NuGet package names, command-line commands, database table and column names, and URLs that you don't want to be clickable.

/cc @mairaw, @rpetrusha, @BillWagner, @Thraka, Thoughts ?

**Comment by Thraka** [comment] 2019-10-07 21:16
I like it, I always have. `KBD` is in the whitelist on the contributors guide. So we just need an agreement on using it.

**Comment by mairaw** [comment] 2019-10-07 21:32
Thanks @Youssef1313 for opening this issue. We really appreciate your passion and contributions so far to the .NET documentation. I discussed this issue with my team. 
 
Given the amount of legacy content we have, we could spend considerable amount of time trying to make all of our content follow the style guide rules, which takes time away for our team to work on new and updated content without much added value. But we do try to follow the guidance when creating or significantly updating an article.
 
I think that fixing inaccuracies caused by #1 would be a priority for us but I wouldn't use the HTML code for that. I'd suggest that if you find broken content because of the use of special characters, to file an issue or PR for that specific page. The other improvements are OK if they are done on a case by case scenario but not in bulk. That way, we can easily review and merge the PR.

For this reason, I'm closing the issue.

**Closed by mairaw** 2019-10-07 21:32 UTC
Labels: backlog, doc-enhancement, up-for-grabs

**Comment by tdykstra** [comment] 2019-10-07 22:51
Follow-up on the `<kbd>` tag

> Currently, `<kbd>` is used in a really few articles.

This is because guidance in our internal Contributor Guide for docs.ms.com currently advises against using any style at all. For example:  Ctrl+Shift+Enter. Unless we change that guidance, it would be better not to add `<kbd>` to articles as they will be out of sync with the rest of the docs across the docs.ms.com site.
