### ISSUE TITLE
EmbeddedResource logical name is not set properly for .NET Core desktop applications

### ISSUE THREAD

**Issue by tarekgh** [dotnet/docs#10031] opened 2019-01-17 19:56 UTC
@diverdan92 commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190)

When porting existing WPF or WinForms applications to target .NET Core that contain EmbeddedResources, the logical name is not fully defined and results in missing resources. 

@ericstj @dsplaisted fyi from our debugging session last week. 

---

@danmosemsft commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449136579)

In what cases -- do you have a repro case? There is a bit convoluted mechanism for picking these names.

This is all done in the build though -- any reason I shouldn't move this to MSBuild?

---

@nguerrera commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449159316)

RootNamespace is defaulted to project name in sdk. If you had an empty one or a different one before the port, then you need to keep it in your csproj.

---

@nguerrera commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449159658)

Please supply a repro showing expected and actual behavior. If it's the root namespace default as I suspect, I don't think we can do anything about it. 

---

@ericstj commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449171593)

I think this bug belongs in the SDK or MSBuild repo, it's all about the build tooling for this stuff.  I think the gist here is the globbing and how that interacts with folks when they are porting their stuff.  If they manually organized a project into folders without using those folders to represent a namespace then the generated .resources will have the wrong name.

---

@nguerrera commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449181313)

If that's what the issue is, then I think this should go to docs, not sdk or msbuild. 

We can't say that it "is not set properly", or that it is "not fully defined". I will grant that it is certainly a pain point in migration.

The algorithm for picking the names is the same as always. If you are using default RootNamespace + default globs, then you get the corresponding names from those defaults. If you go from File -> New classic project, add a folder, add a resource to it,  then do the same for an sdk project, you will get the same names in both projects: (RootNamespace=ProjectNameByDefault).(FolderName).(Filename).resources.

If you were not using the folder names in your resource names before, then you had one of LogicalName, Link, or MainfestResourceName metadata (possibly others) to override that behavior. In the new world, you can still do that with item updates or by disabling globs and copying over your old explicit includes wholesale. We cannot guess these overrides, you have to carry them over.

---

@danmosemsft commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449219500)

Are there any exception messages commonly seen in working through these difficulties, that we can improve? That at least is within BCL control. Eg., "did not find stream named X, only streams named Y and Z" might be pretty helpful?

---

@nguerrera commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449220537)

Yes, we don't have the Y and Z part, but it would be helpful. A link to a document describing how names are assigned and how to control them would be a nice touch as well.

---

@nguerrera commented on [Thu Dec 20 2018](https://github.com/dotnet/corefx/issues/34190#issuecomment-449228714)

I _think_ this is the common failure case: https://github.com/dotnet/coreclr/blob/791332b101524034ca9a69ab7669d5a87713447b/src/System.Private.CoreLib/src/System/Resources/ManifestBasedResourceGroveler.cs#L512

---

@tarekgh commented on [Thu Jan 17 2019](https://github.com/dotnet/corefx/issues/34190#issuecomment-455310378)

Will move this to the doc repo.

**Comment by BillWagner** [comment] 2020-03-31 16:51
assigning to @Thraka

**Comment by Thraka** [comment] 2020-04-14 17:18
@tarekgh I just really noticed this one. Can someone give a real example? I'm really unsure how to document this.. ?

**Comment by tarekgh** [comment] 2020-04-14 20:01
@nguerrera may advise more according to his comment https://github.com/dotnet/corefx/issues/34190#issuecomment-449181313. I believe the RootNamespace is not part of the core resources but it is something used in ASP.NET, WinForm, and WPF.

We have fixed the original issue in the code when having missing resources by listing the main folders of resources in the exception message.

**Comment by nguerrera** [comment] 2020-04-14 20:28
I believe this can now be closed as a duplicate of https://github.com/dotnet/docs/issues/16964, fixed by https://github.com/dotnet/docs/pull/17044

cc @gewarren, @BenVillalobos

**Comment by gewarren** [comment] 2020-04-15 00:11
I've been digging into this a bit more and it seems to me that we need to add this as a breaking change from .NET Framework to .NET Core, not just for .NET Core 2.2 -> 3.0/3.1.

Also, since the linked breaking change (https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#resource-manifest-file-names) is categorized as MSBuild, I'm not sure that WinForms developers would necessarily find it. Should we also add it under WinForms breaking changes?

Lastly, it seems that one way to resolve the build error is by explicitly adding the embedded resources to the project file and then disabling implicit embedded resource globs by setting `EnableDefaultEmbeddedResourceItems` to false. Is that reasonable guidance to provide?

**Comment by Thraka** [comment] 2020-04-28 16:25
@tarekgh @nguerrera Greetings! Can you comment on the thoughts by @gewarren ?

**Comment by nguerrera** [comment] 2020-04-28 16:48
Deferring to @BenVillalobos to take point here. I've moved to a different team. 

(But Ben, if you need to discuss anything with me, feel free to grab some time on Teams.)

**Comment by BenVillalobos** [comment] 2020-05-06 00:38
Thanks @nguerrera (and this is late but welcome back!).

@gewarren this is definitely a breaking change for anyone migrating from .NET Framework to .NET Core 3.0+. See https://github.com/dotnet/sdk/pull/3533/files#diff-a623537ebee239407a19ac49d9cdc9a3R100, we default to using dependentupon convention only in .NET Core 3.0+. So anyone expecting a 1:1 transition (at least in terms of resources) will need to be aware of this. I would personally suggest putting it anywhere that it's relevant.

Per https://github.com/dotnet/templates/commit/77f3917e36f8e258407f93275c712da54e614169 it looks like `EnableDefaultEmbeddedResourceItems` enables automatically picking up all .resx files as `EmbeddedResource` items, though I don't have full context on what's happening behind the scenes. @tmeschter , could you point me in the right direction?

**Comment by tmeschter** [comment] 2020-05-06 16:44
@BenVillalobos I'm not sure I can be much help here. The change I made in dotnet/templates was in response to `EnableDefaultEmbeddedResourceItems` being _disabled_. I don't really know how `EnableDefaultEmbeddedResourceItems` is implemented.

**Comment by BenVillalobos** [comment] 2020-05-06 21:13
@gewarren I found [where `EnableDefaultEmbeddedResourceItems` is implemented](https://github.com/dotnet/sdk/search?q=enabledefaultembeddedresourceitems&unscoped_q=enabledefaultembeddedresourceitems) (thanks @tmeschter), and I believe as long as someone follows the guidelines listed [in the docs](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.0#resource-manifest-file-names) or in my [original issue](https://github.com/dotnet/docs/issues/16964) that should resolve their issue.

**Comment by gewarren** [comment] 2020-05-07 20:19
Closing as duplicate of #16964.

**Closed by gewarren** 2020-05-07 20:19 UTC
Labels: :card_file_box: Technology - .NET Standard, :card_file_box: Technology - WPF, :checkered_flag: Release: .NET Core 3.0, P1, duplicate
