### ISSUE TITLE
Missing C# 10 Info

### ISSUE THREAD

**Issue by mattferderer** [dotnet/docs#25602] opened 2021-08-11 21:34 UTC
It looks like multiple C# 10 features are missing here, such as the following based off (https://github.com/dotnet/csharplang/blob/main/Language-Version-History.md):

* Record structs
* Global using directives
* Improved definite assignment
* Extended property patterns
* Incremental source generators
* #line span directive
* Lambda improvements
* Interpolated string handlers
* File-scoped namespaces
* Parameterless struct constructors
* CallerArgumentExpression

Are these things in progress or do you need help with them or am I just mistaken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's new in C# 10.0 - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10)
* Content Source: [docs/csharp/whats-new/csharp-10.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-10.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-08-13 13:52
Thanks for noting this @mattferderer 

I'm going to close this as a duplicate of #24078 

I've only finished a few of the new features so far. As I add each of the ones you've listed, I'll make an update to this article to point to the more complete additions.

You can track all the work in [this project](https://github.com/dotnet/docs/projects/133).

**Closed by BillWagner** 2021-08-13 13:52 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-whats-new/tech
