### ISSUE TITLE
why  nvidia   garphics  control panel  modified settings not in registry 

### ISSUE THREAD

**Issue by RAJU2529** [dotnet/docs#8874] opened 2018-11-05 19:10 UTC
actually it should be under  this key na
[HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY2]
Why   the keys  are not created  in registry ? but key is  not there  on my  windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89a3478-1985-d631-b57e-2d2f540b9734
* Version Independent ID: 912bbf84-a3b4-ff78-4464-6851417c0ac2
* Content: [Graphics Rendering Registry Settings](https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings)
* Content Source: [docs/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/graphics-multimedia/graphics-rendering-registry-settings.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by TherealGenius** [comment] 2019-04-25 05:08
which is your manufacturer of laptop/desktop computer?
and model number

**Comment by RAJU2529** [comment] 2019-04-25 05:26
Asus vivobook 15 R542UQ-DM153 with bios X542UQ.305 Laptop .

Gpu is Nvidia GeForce  940MX GDDR5  2GB VRAM 

On 24-4-2019, I installed nvidia GeForce DCH based driver 430.39

**Comment by TherealGenius** [comment] 2019-04-25 05:56
@RAJU2529 
Have you seen this problem only with this driver or with several others?

**Comment by RAJU2529** [comment] 2019-04-25 06:10
yes sir I checked all drivers.  problems persists.  This is laptop.

If you have  laptop, please Check the corresponding registry key, that I have mentioned previously.

Thanks sir for reply

**Comment by tdykstra** [comment] 2019-12-05 20:18
@RAJU2529 Apologies for the late response.  Did you find an answer somewhere else or are you still looking for an answer?

**Comment by RAJU2529** [comment] 2019-12-06 06:27
@tdykstra. No sir I never got answer

**Comment by tdykstra** [comment] 2019-12-06 17:01
@grubioe @SamBent Can you help with this question?

**Comment by SamBent** [comment] 2019-12-06 18:04
The keys are not in the registry, by design.  They are used to troubleshoot and work around problems related to WPF's interaction with your video driver;  if you need them, you're expected to create the keys yourself either directly (regedit) or with a tool.  

Nvidia's control panel is probably not setting WPF-specific diagnostic registry keys.  You'd have to ask Nvidia about the expected effects of their settings.

WPF does not recognize [HKEY_CURRENT_USER\Software\Microsoft\Avalon.Graphics\DISPLAY2].  The doc page lists the four keys that WPF recognizes;  any others come from somewhere else (not WPF or .NET).

**Comment by mairaw** [comment] 2019-12-06 18:33
Thanks @SamBent for your help. Closing the issue then.

**Closed by mairaw** 2019-12-06 18:33 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WPF, waiting-on-feedback
