### ISSUE TITLE
Formatting/indentation of multiline arguments

### ISSUE THREAD

**Issue by toburger** [dotnet/docs#7227] opened 2018-08-23 07:03 UTC
Sometimes the argument list can become quite wide (especially with type annotations in place) and I start to split each argument into a separate line. I couldn't find a good advice of how to indent the arguments though so I wonder whats the official guideline for this scenario?

I normally indent the arguments by two tabs (technically 8 spaces) to have a visual distinction between arguments and function body (one tab):
```fsharp
let transformSomething
        (f: Something -> From -> 'a -> 'b)
        (s: Something)
        (from: From)
        (a: 'a): 'b =
	// do something
	// meaningful
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 425ec13f-3caf-c592-f3b5-31ad432ccd86
* Version Independent ID: a1689564-647f-f466-466a-be66b0d08e91
* Content: [Code Formatting Guidelines (F#)](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/code-formatting-guidelines)
* Content Source: [docs/fsharp/language-reference/code-formatting-guidelines.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/code-formatting-guidelines.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment] 2018-08-24 05:37
There isn't an official guideline for this scenario, but I do like indenting one scope further than the body of the function. Would you feel comfortable submitting a PR that explains this and provides an example? I'd definitely take it.

**Comment by cartermp** [comment] 2020-08-16 02:52
Will close as a duplicate of https://github.com/dotnet/docs/issues/18806 given the discussion that has gone on there

**Closed by cartermp** 2020-08-16 02:52 UTC
Labels: :books: Area - F# Guide, doc-enhancement, duplicate, up-for-grabs
