### ISSUE TITLE
Installing `dotnet-sdk-6.0` only installs runtime

### ISSUE THREAD

**Issue by ichibanbrew** [dotnet/docs#30678] opened 2022-08-14 14:26 UTC
In the section on `Install the SDK` the following command does not actually install the SDK. It only installs the runtime.
    
    sudo apt-get update && \
      sudo apt-get install -y dotnet-sdk-6.0

After installing dotnet using the above command on Kubuntu 22.04 I run `dotnet --info` and get the following output.

    global.json file:
      Not found
    
    Host:
      Version:      6.0.8
      Architecture: x64
      Commit:       55fb7ef977
    
    .NET SDKs installed:
      No SDKs were found.
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]
    
    Download .NET:
      https://aka.ms/dotnet-download
    
    Learn about .NET Runtimes and SDKs:
      https://aka.ms/dotnet/runtimes-sdk-info

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2022-08-15 18:47
Duplicate of #30686

**Closed by adegeo** 2022-08-15 18:47 UTC
Labels: :watch: Not Triaged, Pri1, dotnet/prod, dotnet-install/tech
