### ISSUE TITLE
A Result error of HighWaterGateOpen 

### ISSUE THREAD

**Issue by wangw-git** [dotnet/docs#28457] opened 2022-03-02 14:09 UTC
[Enter feedback here]

In "What is new in C# -> Tutorials -> explore pattern in objects -> Implement the commands with patterns",
according to the table(row 4)
New setting = Closed
Gate state = Open
Water Level = High
Result = Open

well, Result should be Closed.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afb14275-1810-ff4d-783f-733e8ea3d858
* Version Independent ID: 071e85e4-6fc9-8aff-bbf5-778d5e499f88
* Content: [Use patterns in objects - C# tutorial](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/patterns-objects#prerequisites)
* Content Source: [docs/csharp/whats-new/tutorials/patterns-objects.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/tutorials/patterns-objects.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-03-02 15:48
closing as a duplicate of #28455

**Closed by BillWagner** 2022-03-02 15:48 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-csharp/prod, csharp-whats-new/tech
