### ISSUE TITLE
Examples are all the same and not updated to the text

### ISSUE THREAD

**Issue by Cyrille-Precetti** [dotnet/docs#24472] opened 2021-06-01 14:22 UTC
The code examples are all the same and not updated to illustrate the modifications suggested in the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 176f6e77-fdd7-5f97-feb3-5376c85baa5a
* Version Independent ID: fc865789-6896-4cf5-7cdf-2080047563e4
* Content: [Organizing types in namespaces](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/types/namespaces)
* Content Source: [docs/csharp/fundamentals/types/namespaces.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/types/namespaces.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-06-01 15:27
Duplicate of https://github.com/dotnet/docs/issues/24456.

**Comment by BillWagner** [comment] 2021-06-02 13:48
closing as duplicate of #24456

**Closed by BillWagner** 2021-06-02 13:48 UTC
Labels: Pri1, csharp-fundamentals/tech, doc-bug, dotnet-csharp/prod
