### ISSUE TITLE
Any chance to include .NET Core in this subject ?

### ISSUE THREAD

**Issue by MarcioAB** [dotnet/docs#15136] opened 2019-10-12 13:41 UTC
I understand this is for .NET Framework only, but, is it possible to (somehow) address this subject ( Load Assemblies into the Reflection-Only Context ) for .NET Core ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5801d799-a851-bfee-e3ab-2ea0dd1524de
* Version Independent ID: c47b567c-5b31-fb04-29c0-c1cddd956bef
* Content: [How to: Load Assemblies into the Reflection-Only Context](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context)
* Content Source: [docs/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context.md](https://github.com/dotnet/docs/blob/master/docs/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Thraka** [comment] 2019-10-14 21:50
We haven't written a tutorial on it yet, but .NET Core can use the NuGet package [System.Reflection.MetadataLoadContext](https://www.nuget.org/packages/System.Reflection.MetadataLoadContext/) for this kind of work.

**Comment by Thraka** [comment] 2019-10-14 21:52
I'm going to closet his as a duplicate. I'm adding information about how MetadataLoadContext needs to be covered for the reflection-only type of loading in .NET Core. Thanks!

**Comment by Thraka** [comment] 2019-10-14 21:52
Duplicate of #2729

**Closed by Thraka** 2019-10-14 21:52 UTC
Labels: :books: Area - .NET Framework Guide, Source - Docs.ms
