### ISSUE TITLE
C# tutorials - hello world

### ISSUE THREAD

**Issue by stevehoag** [dotnet/docs#53] opened 2015-10-12 20:04 UTC
Create a basic Hello World tutorial for developers new to C#.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by matthewreily** [comment] 2015-12-01 19:47
If this is still needed please assign to me and I will work on it. cc @BethMassi

**Comment by cartermp** [comment] 2015-12-01 20:15
Done!

**Comment by matthewreily** [comment] 2015-12-01 20:34
Thanks!

**Comment by radu-matei** [comment] 2016-06-21 12:23
Hi, everyone!

I would like to start contribuiting on the .NET Core documentation and I was wondering (not sure if this is the right issue for it, but anyway) wether we might use some code and documentation I have already developed for [introducing C# to newer audiences - It is a separate repository with various examples and documentation.](https://github.com/microsoft-dx/csharp-fundamentals/tree/master/CSharpFundamentals).

Let me know wether we can use this in any way (I'm surely open to modifications of any kind) or wether I can start creating some new materials.

Thanks!

**Comment by tsolarin** [comment] 2016-07-14 16:21
@BillWagner PR open

**Comment by BillWagner** [comment] 2016-07-14 16:38
@tsolarin I see that. I will review it later today.

**Comment by mairaw** [comment] 2017-03-08 18:27
Duplicate of #942

**Closed by mairaw** 2017-03-08 18:27 UTC
Labels: Area - C# tutorials, P1
