### ISSUE TITLE
按照教程里的步骤不能执行

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#18671] opened 2020-05-27 20:42 UTC
@cnazev commented on [Wed May 27 2020](https://github.com/dotnet/docs.zh-cn/issues/606)

按照教程步骤走下来
在调试部分跟教程里的截图不一致
有一个提示 Open a file which can be debugged or run.
下方的Run and Debug按钮不可用。

另外这篇教程题目是‘使用 Visual Studio Code 在 macOS 中创建 .NET Core 解决方案’
但文章基本跟cli下开发一样，只是在Visual Studio Code的内置终端。
没有提及如何是在Visual Studio Code中打开多项目的解决方案，以及打开解决方案里的项目。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3343b35c-90c1-2e11-498d-ee1d4eb409f6
* Version Independent ID: f2eda261-d4c3-c90a-1294-dfe11e55c341
* Content: [教程：使用 Visual Studio Code 在 macOS 中创建 .NET Core 解决方案 - .NET Core](https://docs.microsoft.com/zh-cn/dotnet/core/tutorials/using-on-macos)
* Content Source: [docs/core/tutorials/using-on-macos.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/tutorials/using-on-macos.md)
* Product: **dotnet-core**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

---

@srvbpigh commented on [Wed May 27 2020](https://github.com/dotnet/docs.zh-cn/issues/606#issuecomment-634739123)

Hello, @cnazev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by BillWagner** [comment] 2020-05-28 14:29
Translation:

> Follow the tutorial steps down
> In the debugging section does not match the screenshots in the tutorial
> There is a prompt Open a file who can be be be run.
> The Run and Debug button below is not available.

> In addition, this tutorial is titled 'Create a .NET Core Solution in macOS with Visual Studio Code'
> But the article is basically the same as the development under cli, just the built-in terminal of Visual Studio Code.
> There is no mention of how to open a multi-project solution in Visual Studio Code, or a project to open a solution.

/cc @tdykstra 

I think this has been partially addressed when I updated the screenshots for the latest Visual Studio for Mac. I think the remaining concerns are addressed with your recent updates. Do you agree?

**Comment by tdykstra** [comment] 2020-05-28 15:07
This is for the Visual Studio Code on macOS tutorial, not the Visual Studio for Mac one. This issue is a duplicate of #18670 on which I commented that the new series of Visual Studio Code tutorials I'm writing will replace this tutorial.

**Closed by tdykstra** 2020-05-28 15:07 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged
