### ISSUE TITLE
Packages for Debian and Ubuntu are not available

### ISSUE THREAD

**Issue by Aggression** [dotnet/docs#24717] opened 2021-06-17 08:17 UTC
Packages for Debian and Ubuntu are not available. Response is 404 Not Found 
https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb
Please check it 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#debian-10-)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by svick** [comment] 2021-06-17 11:35
This is a duplicate of https://github.com/dotnet/core/issues/6381, which contains more information about the current status of the issue.

**Comment by Youssef1313** [comment] 2021-06-17 14:21
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by Aggression** [comment] 2021-06-17 14:33
Yes, looks like it works now
Thanks

**Closed** 2021-06-17 14:34 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod

**Comment by MinzigesTV** [comment] 2021-06-24 18:28
> pi@raspberrypi:~ $ sudo apt-get install -y dotnet-runtime-5.0
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package dotnet-runtime-5.0
> E: Couldn't find any package by glob 'dotnet-runtime-5.0'
> E: Couldn't find any package by regex 'dotnet-runtime-5.0'

It does not work for me

**Comment by adegeo** [comment] 2021-06-28 17:31
I @MinzigesTV package managers aren't available for ARM processors. You must use a different installation method.
