### ISSUE TITLE
bug/typo

### ISSUE THREAD

**Issue by simon-stealthbits** [dotnet/docs#7939] opened 2018-09-28 05:40 UTC
the code in the first example (line 18 I think) says [ThreadStaticAttribute] but should say just    [ThreadStatic] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c6b692-4e39-7e27-dca3-bdd8a4df46e0
* Version Independent ID: 9c8d22a1-0c8c-29ee-3624-21d40a10f852
* Content: [Thread.FreeNamedDataSlot(String) Method (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.freenameddataslot?view=netframework-4.7.2)
* Content Source: [xml/System.Threading/Thread.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/Thread.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by arshadkazmi42** [comment] 2018-10-01 13:35
@simon-stealthbits I would like to take this up. Which file needs this type change.

**Comment by pkulikov** [comment] 2018-10-01 14:28
@simon-stealthbits using `[ThreadStaticAttribute]` is not a bug; it's equivalent to using `[ThreadStatic]`. Given that, Visual Studio suggests to simplify `[ThreadStaticAttribute]` into `[ThreadStatic]`.

**Comment by mairaw** [comment] 2018-10-01 22:14
@pkulikov is right. VS recommends that change but it's not required.
@arshadkazmi42 the files to change would be:
- https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_CLR_System/system.Threading.Thread.DoNotUseDataSlots/vb/source.vb
- https://github.com/dotnet/samples/blob/master/snippets/cpp/VS_Snippets_CLR_System/system.Threading.Thread.DoNotUseDataSlots/CPP/source.cpp
- https://github.com/dotnet/samples/blob/master/snippets/csharp/VS_Snippets_CLR_System/system.Threading.Thread.DoNotUseDataSlots/CS/source.cs

**Comment by rpetrusha** [comment] 2018-10-04 18:32
This has been fixed in dotnet/samples#336. Closing.

**Closed by rpetrusha** 2018-10-04 18:32 UTC
Labels: :books: Area - API Reference, :file_folder: Repo - dotnet-api-docs, P2, Source - Docs.ms, doc-enhancement, up-for-grabs
