### ISSUE TITLE
The "Applies to" section should be per overload

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/docs#7592] opened 2018-09-09 16:37 UTC
Only `Contains(String)` exists in .NET Framework and .NET Core 1.x. The other overloads only exist in .NET Core 2.x. Yet the "Applies to" section seems to indicate they're available for all frameworks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04df3272-a949-c303-8cf1-a8db2620a30d
* Version Independent ID: d0860c14-0cce-c669-b391-67af08fd4d67
* Content: [String.Contains Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=netcore-2.1#applies-to)
* Content Source: [xml/System/String.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by BillWagner** [comment] 2018-09-10 20:37
@dend Should this be moved to the MicrosoftDocs/Feedback repo?

**Comment by BillWagner** [comment] 2018-09-10 20:37
Closing as a duplicate of MicrosoftDocs/Feedback#314

**Closed by BillWagner** 2018-09-10 20:37 UTC
Labels: :books: Area - API Reference, external
