### ISSUE TITLE
Need a tab for .NET Core 3.0.100

### ISSUE THREAD

**Issue by donhuvy** [dotnet/docs#14965] opened 2019-10-04 19:29 UTC
Need a tab for .NET Core 3.0.100 . We just have guide for .NET Core 2.x and below.

![abcd](https://user-images.githubusercontent.com/1328316/66234519-1a6b9400-e718-11e9-91e3-2b5f3062169f.png)

Additional: I think tab **[.NET Core 2.1]** and **[.NET Core 2.0]** should be remove. Tab **[.NET Core 2.2]** is good enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b952f8a-18e1-4843-0741-6ca877fb303a
* Version Independent ID: d80dfb96-bc86-a960-abec-255dd907d04d
* Content: [dotnet new command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?tabs=netcore22)
* Content Source: [docs/core/tools/dotnet-new.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-new.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment] 2019-10-07 20:55
Duplicate of #9893

**Comment by Thraka** [comment] 2019-10-07 20:55
Thank you for letting us know. We have an issue (linked above) tracking this. I'm going to close. Thanks again!

**Closed by Thraka** 2019-10-07 20:55 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, :watch: Not Triaged, Source - Docs.ms
