### ISSUE TITLE
Code snippets split among multiple panes

### ISSUE THREAD

**Issue by strican** [dotnet/docs#4200] opened 2018-01-24 23:28 UTC
# Code snippets split among multiple panes

# General
There appears to be a pattern of using multiple segments of existing snippets to fill the need of simpler snippets. I've found this to be true [here](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-overview-wpf#markup-extensions), but may exist on other pages. The result is several subsequent code blocks that make it difficult for the reader to read or copy.

**Suggestion:** Ideally, there can be an extension to DocFX to combine subsequent snippets. Barring that, the snippets on this page should be split out into their own pages in the existing snippet project.

## Issues with Existing Topics

[Here](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-overview-wpf#markup-extensions) is a topic with this issue.

**Comment by mairaw** [comment] 2018-01-24 23:32
Hi @strican. Thanks for your feedback. We're aware of this problem (see issue #2994).

Unfortunately, we haven't had time to address that one yet. I'll be closing this one given that is a duplicate.

**Comment by mairaw** [comment] 2018-01-24 23:33
Duplicate of #2994

**Closed by mairaw** 2018-01-24 23:33 UTC
