### ISSUE TITLE
Operations about Solution Explorer are different from my Visual Studio Interface

### ISSUE THREAD

**Issue by seanlin-larc** [dotnet/docs#9995] opened 2019-01-15 14:38 UTC
Having been directed from "Getting Started - Build a class library with Visual Basic and the .NET Core SDK in Visual Studio 2017", the exercise could not continue after #5 of "Creating a unit test project" as there is no check-able item in the reference manager.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 579d660a-e58d-7264-e7b1-54c9259c9878
* Version Independent ID: 03696f0b-a16a-3db0-26dd-b3b5a8d89ca2
* Content: [Testing a class library with .NET Core in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio?tabs=vb)
* Content Source: [docs/core/tutorials/testing-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/testing-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment] 2019-01-15 23:55
Thanks for your feedback, @seanlin-larc. I'm having difficulty reproducing this. Could you include a screen capture of your Solution Explorer, please?

**Comment by seanlin-larc** [comment] 2019-01-16 23:31
As attached screenshots:

![screenshot 201901161529](https://user-images.githubusercontent.com/24693273/51285451-be06ef80-19a3-11e9-8a9d-35c6505491ec.png)

![screenshot 201901161530](https://user-images.githubusercontent.com/24693273/51285458-c52dfd80-19a3-11e9-8dd0-9faf07253590.png)

**Comment by rpetrusha** [comment] 2019-01-17 00:39
Thanks for the screen capture, @seanlin-larc. The basic problem here is that your project is not contained within a solution. Because of that, solution-related menu options don't appear, and you can't use a test framework to test a library because they have to be separate projects contained in a single solution.

I'm not at all sure how this might have happened -- as far as I know, Visual Studio, regardless of which edition you are using, always creates a solution file for a new project along with a project file. I'm trying to investigate why this might have happened, but I'd recommend two alternatives:

- Try the tutorials again from the beginning, making sure that when you create a new project, Visual Studio also creates a solution file that contains your project. Your Solution Explorer should look something like this:

   ![image](https://user-images.githubusercontent.com/10886961/51287402-1e019400-19ac-11e9-8a1b-cca59a504b9f.png)
  
- If that doesn't work, run the Visual Studio Installer and in the **More** field, select **Repair** to repair Visual Studio Community Edition.

I'm going to close your other two issues, since they're also caused by the absence of a solution file. We'll keep this one open, and please let us know whether you've managed to create a project that is contained within a solution file.

Incidentally, if all else fails, you can create a solution file and then add projects to it. To create an empty solution, select **File**, **New**, **Project**. In the Installed tab of the New Project dialog, select **Other Project Types**, **Visual Studio Solutions**. That creates an empty solution file. You can then use the context menu in Solution Explorer to add projects to it.

Please let us know whether you're continuing to have difficulty, or whether you've managed to create a project contained in a solution.

**Comment by rpetrusha** [comment] 2019-01-17 00:44
Also, @seanlin-larc, @Thraka found a configuration option that should cause the solution file to be displayed. See #9996. I think that it should solve the problems that you're having.

**Comment by Thraka** [comment] 2019-01-17 01:04
Whoops clicked the wrong button 😄

**Comment by SandraJones** [comment] 2019-01-18 20:50
When I add the namespace UtilityLibraries in a using statement I got an error, "namespace UtilityLibraries not found are you missing a using directive or assembly reference."

**Comment by Thraka** [comment] 2019-01-18 22:07
@SandraJones At the start this article it points out that you need to have completed a previous article. That previous article is where you create that UtilitiesLibrary namespace.

**Comment by SandraJones** [comment] 2019-01-19 21:53
Resolved by removing reference from String Library and added reference of StringLibrary to StringLibraryTest.

**Closed** 2019-03-05 00:05 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged, Source - Docs.ms, waiting-on-feedback
