### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by curtnichols** [dotnet/docs#17579] opened 2020-03-24 17:02 UTC
Links to `Option` on this page are largely broken, and point to msdn.microsoft.com. They're returning the error message `Sorry, this page is unavailable. Please try again later.` Unclear whether it's temporary, but the reference to `msdn` rather than `docs` seems telling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed1e23a2-091b-38be-3bbe-b3b38aa06aa5
* Version Independent ID: 431e250a-3588-7741-dd43-8021d6c7ffa8
* Content: [Options - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/options#feedback)
* Content Source: [docs/fsharp/language-reference/options.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/options.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment] 2020-03-25 23:47
Interesting, pages like this are erroring too, even though they show in search results:

https://msdn.microsoft.com/visualfsharpdocs/conceptual/array.iter%5b%27t%5d-function-%5bfsharp%5d

Thanks for letting us know, @curtnichols !

**Comment by gewarren** [comment] 2020-04-01 15:35
This is actually a dupe of #17557.

**Comment by curtnichols** [comment] 2020-04-01 15:38
I'm good with that. :)

**Comment by cartermp** [comment] 2020-04-01 15:40
FYI we're working with the team that does redirects on this one. The core issue is a small handful of links needed redirection, but something went awry and the whole reference was redirected. It's apparently a little tricky.

**Comment by gewarren** [comment] 2020-04-07 19:22
Thanks for reporting this. Closing as a duplicate.

**Closed by gewarren** 2020-04-07 19:22 UTC
Labels: :books: Area - F# Guide, duplicate
