### ISSUE TITLE
Update for 2.1?

### ISSUE THREAD

**Issue by TPucke** [dotnet/docs#17627] opened 2020-03-27 15:06 UTC
This page is stale. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de130a75-fed2-0567-6e3d-07a384900eec
* Version Independent ID: a2993c26-93f8-7281-d6ca-5fcc899e95f3
* Content: [What's new in the .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/whats-new/whats-new-in-dotnet-standard?tabs=csharp)
* Content Source: [docs/standard/whats-new/whats-new-in-dotnet-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/whats-new/whats-new-in-dotnet-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment] 2020-03-27 22:57
This is a dupe of #9221.

**Closed** 2020-03-27 22:58 UTC
Labels: :books: Area - .NET Guide, duplicate
