### ISSUE TITLE
Build Solution ended up creating a .dll file instead of an executable

### ISSUE THREAD

**Issue by seanlin-larc** [dotnet/docs#9996] opened 2019-01-15 14:41 UTC
As title, "Build Solution" is actually "Build {filename}" in my Visual Studio interface and it built a .dll file instead of a .exe executable as described in the tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10fd8911-61a3-05cb-4f72-ff128be2a632
* Version Independent ID: 9b8e4ffe-d069-f6f3-a326-c33c03f365b4
* Content: [.NET Core Hello World application with Visual Basic in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-with-visual-studio)
* Content Source: [docs/core/tutorials/vb-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/vb-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment] 2019-01-15 18:06
Hi @seanlin-larc! Thanks for your feedback.

Where are you seeing "Build {filename}"? This is what I see on the Build menu:
![image](https://user-images.githubusercontent.com/12971179/51199773-908b4a80-18ac-11e9-852e-b6c43b600430.png)
![image](https://user-images.githubusercontent.com/12971179/51199802-9ed96680-18ac-11e9-8918-2df9cf52ae3f.png)

I don't we mention in the tutorial that you get an .exe file since this was only introduced in 2.2. Generating a .dll file is the default behavior in .NET Core.

If you can point out where the causes of confusion are, we can try to clarify.

**Comment by mairaw** [comment] 2019-01-15 18:07
And this topic might be helpful: https://docs.microsoft.com/en-us/dotnet/core/deploying/

**Comment by rpetrusha** [comment] 2019-01-15 18:11
Thanks for your feedback, @seanlin-larc.

The first option on the Visual Studio **Build** menu, as well as the first option on the context menu displayed if you right-click on the solution in **Solution Explorer** is **Build Solution**. Is that not what you're seeing? Do you have both a solution file and a project file?

The tutorial does not suggest that an executable is output by the build process; in fact, the output of the build process is a DLL, as you've noted. This part of the tutorial simply assumes that the application is run interactively from Visual Studio. The tutorial on [publishing a .NET Core application](https://docs.microsoft.com/en-us/dotnet/core/tutorials/publishing-with-visual-studio) notes that the application is a DLL that can be run by using the .NET CLI (`dotnet <filename>.dll`).

Please feel free to respond if you still find something in the tutorial confusing. In the meantime, I'll close this issue as By Design, since a DLL is the expected output file type.

**Comment by seanlin-larc** [comment] 2019-01-15 18:45
Hi Ron,

This is what I saw on my screen.

[image: screenshot 201901151043.png]

**Comment by mairaw** [comment] 2019-01-15 18:50
We can't see screenshots on reply by e-mails @seanlin-larc. Can you post it via GitHub UI?

**Comment by seanlin-larc** [comment] 2019-01-15 19:07
Thanks for the clarification about .dll and .exe

As for my "Build" menu, basically I do not have the first 3 items of yours. Attached is my screenshot
![screenshot 201901151043](https://user-images.githubusercontent.com/24693273/51203304-933e6d80-18b5-11e9-8634-22a2d0bd203a.png)

**Comment by mairaw** [comment] 2019-01-15 19:12
Thanks for posting the image here @seanlin-larc. Can you confirm which version of VS you have? Maybe the different editions have different behaviors so I wanna make sure I test it on the same edition you're using.

**Comment by seanlin-larc** [comment] 2019-01-15 19:18
Microsoft Visual Studio Community 2017 version 15.9.5
Screenshot and detail follow:

![screenshot 201901151053](https://user-images.githubusercontent.com/24693273/51203920-288e3180-18b7-11e9-939d-01adab3f1061.png)

Microsoft Visual Studio Community 2017 
Version 15.9.5
VisualStudio.15.Release/15.9.5+28307.280
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA546
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.11009.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   15.9.18254.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   15.9.18254.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   15.9.18254.1
Provides templates and integration for the Django web framework.

Python - IronPython support   15.9.18254.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   15.9.18254.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

**Comment by rpetrusha** [comment] 2019-01-15 23:45
Here is the default Build menu from the Community Edition:

![image](https://user-images.githubusercontent.com/10886961/51217202-0bb82500-18dc-11e9-8e11-2f3b55763879.png)

Have you by any chance customized your menu, @seanlin-larc?

**Comment by seanlin-larc** [comment] 2019-01-16 23:03
My Visual Studio just started 2 days ago. I don't even know how to customize my menu....

**Comment by Thraka** [comment] 2019-01-16 23:47
Can you post a screenshot of your solution explorer? (usually the right-side)

I tried a bunch of things too and I can't replicate it.

**Comment by seanlin-larc** [comment] 2019-01-16 23:54
Here it is (with context menu open). Thanks for your help.

![screenshot 201901161553](https://user-images.githubusercontent.com/24693273/51286221-e04e3c80-19a6-11e9-8451-c407bbc88839.png)

**Comment by Thraka** [comment] 2019-01-17 00:30
Did you perchance choose VB developer settings (i can't remember the exact name) when you first installed and ran visual studio? I wonder if it's probably just a different config that doesn't put those build menu settings there.

**Comment by seanlin-larc** [comment] 2019-01-17 01:55
Cool. I got it. I really appreciate your help!

**Comment by tdykstra** [comment] 2020-05-07 21:07
Closing, as this tutorial no longer exists.

**Closed by tdykstra** 2020-05-07 21:07 UTC
Labels: :books: Area - .NET Core Guide, doc-bug
