### ISSUE TITLE
Asp.Net still compiles with C# 7.0, even when .Net 4.8 is installed

### ISSUE THREAD

**Issue by PoulBak** [dotnet/docs#15465] opened 2019-10-28 14:51 UTC
Although .Net 4.8 is installed and it should default to C# 7.3, asp.net still uses C# 7.0 - even in Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5694e62b-c756-1f62-4014-2ceafa54c011
* Version Independent ID: 3f01c378-22e4-197c-a862-ab4a924506c7
* Content: [C# language versioning - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version)
* Content Source: [docs/csharp/language-reference/configure-language-version.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/configure-language-version.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by cartermp** [comment] 2019-10-29 14:51
@PoulBak Thanks! You are correct, C# 7.3 should by the default. This sounds like a product bug if it reproduces with new ASP.NET projects - I'm assuming old-style ASP.NET here, since you mention .NET Framework - and the appropriate avenue here would be the Visual Studio Report A Problem tool.

I'd also double-check that you don't have a props file (e.g., `Directory.build.props`) setting the `LangVersion` for you in a way that defaults to C# 7.0.

**Comment by DaveSneddon** [comment] 2019-10-30 10:52
I have the version "Automatically selected based on framework version" for me which Automatically selects 7.0 and doesn't allow me to change it.  How do I turn this useless "helpful" feature off?  Using VS 2019 16.3.7 with .NET 4.7.2.

**Comment by PoulBak** [comment] 2019-10-30 13:31
@cartermp I don't have a props file. This is not new, it has been like that for several years. Asp.Net uses the 'Latest Major' compiler.
@DaveSneddon The only way to get the C# 7.3 compiler in asp.net is to install 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform' from Github (and distribute it to your server). You must set the langversion in web.config.

**Comment by cartermp** [comment] 2019-10-30 15:02
I'll defer to ASP.NET folks (such as @danroth27) on whether or not the legacy website project kinds should support later C# versions, but my intuition is no, given the abundance of features that depend on types (and now runtime features with Default Interface Members) that are only available on .NET Core.

**Comment by DaveSneddon** [comment] 2019-10-30 16:04
@BillWagner mine is a ASP.NET project.  @PoulBak thanks for your help, I've got it working now.  I already had the latest DotNetCompilerPlatform package but the langversion was set to 'default'.  Changing it to 'latest' fixed the issue. Why 'default' isn't 7.3 doesn't make sense to me.

**Comment by Thraka** [comment] 2019-11-07 19:21
I'm going to close this since your question seems to be answered on how to enable 7.3. Regarding defaults though, I'm unsure who you should raise this to. https://github.com/aspnet/AspNetWebStack/ perhaps?

**Closed by Thraka** 2019-11-07 19:21 UTC
Labels: :books: Area - C# Guide, resolved-by-customer

**Comment by RoboBurned** [comment] 2022-02-19 13:21
NET Framework 4.8 Projects of type Class Library (csproj) also have this issue. They are defaults to 7.0. (Visual Studio 2019 v16.11.9)
