### ISSUE TITLE
.NET Portability Analyzer does not install in VS 2022

### ISSUE THREAD

**Issue by ddemland** [dotnet/docs#28797] opened 2022-03-24 18:08 UTC
I am trying to install the analyzer on VS 2022. I get the following error:

3/24/2022 11:06:52 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Is there a way to install the analyzer on VS 2022?

Thank You,

David
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd8086b-9a95-38d5-160f-c12c653f954e
* Version Independent ID: 0f47d826-e3ef-8549-9d37-2e8afae29f46
* Content: [The .NET Portability Analyzer - .NET](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer)
* Content Source: [docs/standard/analyzers/portability-analyzer.md](https://github.com/dotnet/docs/blob/main/docs/standard/analyzers/portability-analyzer.md)
* Product: **dotnet-fundamentals**
* Technology: **dotnet-analyzers**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by Youssef1313** [comment] 2022-03-24 19:48
@buyaa-n Do you know if .NET portability analyzer is considered deprecated now that we have CA1416? or do both tools serve different goals?

**Comment by buyaa-n** [comment] 2022-03-24 21:27
Both analyzers serve similar goal but CA1416 is not complete replacement for portability analyzer. Specifically for .Net versions below .Net 5. it would not work as their source not annotated with required `SupportedOSPlatform("platform")`, `UnsupportedOSPlatform("platform")`  attributes. We could say CA1416 is replacement portability analyze for .Net 5+.

Not sure if portability analyzer is deprecated or if it should be supported in VS 2022 @terrajobst might answer that

**Comment by IEvangelist** [comment] 2022-05-27 19:42
Closing this issue, as it is by design: "The .NET Portability Analyzer is not supported in Visual Studio 2022."

**Closed by IEvangelist** 2022-05-27 19:42 UTC
Labels: doc-enhancement, Pri2, dotnet-fundamentals/prod, dotnet-analyzers/tech
