### ISSUE TITLE
"Escaping Brace" section is wrong (at least in .NET 6) 

### ISSUE THREAD

**Issue by olivier-spinelli** [dotnet/docs#36416] opened 2023-07-27 05:18 UTC
Lost one hour of my life to handle the "Escaping brace problem" described in the [doc](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#escaping-braces)... (without testing it first!).
It seems that in NET 6 (at least), this has been fixed:

```csharp
            string.Format( "{{{0:X}}}", 1024 ).Should().Be( "{400}" );
            string.Format( "{{{0:D}}}", 1024 ).Should().Be( "{1024}" );
```
This works like a charm :(.
Sorry to not have time to try on other versions, but the documentation needs a cleanup (or specificy on which version this occurs).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 50b5f5c7-99f8-e112-a3f4-691548e8fc06
* Version Independent ID: e4b0d61c-a09b-3bf0-1696-1d4472272237
* Content: [Composite formatting](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting)
* Content Source: [docs/standard/base-types/composite-formatting.md](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/composite-formatting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

---
[Associated WorkItem - 145032](https://dev.azure.com/msft-skilling/Content/_workitems/edit/145032)

**Comment by adegeo** [comment] 2023-08-07 20:07
Closing in favor of a different issue that also reported this problem. Thanks again.

**Comment by adegeo** [comment] 2023-08-07 20:07
Duplicate of #34929

**Closed by adegeo** 2023-08-07 20:07 UTC
Labels: doc-bug, Pri1, dotnet-fundamentals/prod, okr-health, :pushpin: seQUESTered
