### ISSUE TITLE
Problem with KnownTypeAttribute

### ISSUE THREAD

**Issue by mgwalm** [dotnet/docs#2951] opened 2017-08-20 22:30 UTC
# Issue Title

Problem with docs of KnownTypeAttribute 

## Issues with Existing Topics

I'm having a big problem with this attribute. Simply it isn't working (as it has been for approx. 10 years)
On tracking down the problem I found this in the docs:

the types that should be included for consideration during deserialization.

In previous version of this docs and in the previous version of using this attribute (for approx. the last 10 years) it was uaed during both serialization and deserialization.

So is it true it is only used during deserialization?

**Comment by mairaw** [comment] 2017-08-21 20:30
@ViktorHofer can you help with this question?

**Comment by ViktorHofer** [comment] 2017-08-21 20:33
Unfortunately not. This is not binary serialization but Data Contract Serializer (DCS). @shmao or @huanwu should be able to answer.

**Comment by shmao** [comment] 2017-08-21 21:00
@mgwalm Thanks for submitting the issue. The doc seems wrong. The attribute is used in both serialization and de-serialization. Can you please share a repro code with us for us to understand the issue?

**Comment by BillWagner** [comment] 2018-03-08 22:56
@mgwalm Is this still an issue? Do you have a repo you can share?

**Comment by BillWagner** [comment] 2018-03-08 22:56
@mairaw I cleared this from the backlog so we look at it and triage again. If there's no repo, we may want to close the issue.

**Comment by mairaw** [comment] 2018-03-12 20:48
Let's close it for now since we can't reproduce this issue. @mgwalm feel free to reopen if you have a repro you can share with us. Thanks!

**Closed by mairaw** 2018-03-12 20:48 UTC
Labels: question

**Comment by mgwalm** [comment] 2018-03-12 23:21
Thanks. It was too complex to get a repo. However in later versions of dotnet the problem has gone away and it is now working as expected.

**Comment by mairaw** [comment] 2018-03-12 23:23
Thanks for letting us know @mgwalm. I'm glad it's working now for you.
