### ISSUE TITLE
--include-source doesn't seem to work as documented if the package symbol format is snupkg

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#14165] opened 2019-09-03 08:08 UTC
Reference: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

If I run `dotnet pack MyPackage.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source` then the size of my snupkg is the same as if I ran `dotnet pack MyPackage.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg`, which implies to me that sources are **not** being embedded even though `--include-sources` is specified.

If I run `dotnet pack MyPackage.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:EmbedAllSources=true` then the snpukg is significantly larger, which implies that the sources are present in the resulting snupkg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e805a3-f2ec-b05a-d5c8-29f7a8c16a5f
* Version Independent ID: 4257ec12-df6f-ec52-aad3-012e5fce8133
* Content: [dotnet pack command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x)
* Content Source: [docs/core/tools/dotnet-pack.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-pack.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment] 2019-10-16 18:23
Hello!

I found this reported at https://github.com/NuGet/Home/issues/8589

I'm going to close this issue here. Thanks!

**Comment by Thraka** [comment] 2019-10-16 18:23
Duplicate of NuGet/Home#8589

**Closed by Thraka** 2019-10-16 18:23 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, :watch: Not Triaged, Source - Docs.ms
