### ISSUE TITLE
Links to C# lang spec are broken

### ISSUE THREAD

**Issue by konrad-jamrozik** [dotnet/docs#23189] opened 2021-03-06 01:27 UTC
Links to C# lang spec are broken

e.g. [awaitable expressions](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/~/_csharplang/spec/expressions.md#await-expressions)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07164632-3cf8-864e-cd1e-485b73ed95a0
* Version Independent ID: 67bfb75a-8dd8-ecf3-ce15-2a531833e8b5
* Content: [await operator - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await)
* Content Source: [docs/csharp/language-reference/operators/await.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/await.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-03-06 10:13
Duplicate of https://github.com/dotnet/docs/issues/23190

**Comment by BillWagner** [comment] 2021-03-06 16:37
Closing as fixed in #23194

**Closed by BillWagner** 2021-03-06 16:37 UTC
Labels: :watch: Not Triaged, Pri1, csharp-language-reference/tech, dotnet-csharp/prod
