### ISSUE TITLE
Docs about <EnableDynamicLoading>

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#15151] opened 2019-10-13 14:57 UTC
dotnet/samples#1064

> `<EnableDynamicLoading>` and `<EnableComHosting>` properties were added to the .NET Core SDK in Preview 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#feedback)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment] 2019-10-14 21:50
Thanks @NextTurn. We have a plan to document the entire set of properties for .NET Core, so I'm closing this as duplicate of #2642.

**Comment by NextTurn** [comment] 2019-10-14 23:40
A P0 issue with two years of history :smile: Any ETA?

**Comment by mairaw** [comment] 2019-10-14 23:47
I know 😢 It's the highest priority backlog item that we have but we're also behind our 3.0 deliverables. Still no ETA.

**Comment by ericstj** [comment] 2019-11-19 21:23
Here's the PR that added the property, should serve as a placeholder for those looking until docs are available.
https://github.com/dotnet/sdk/pull/3305#issuecomment-504549489

**Comment by gewarren** [comment] 2020-04-30 21:55
#2642 is too big, so I'm breaking it up into manageable chunks. Reopening this issue.

**Closed** 2020-11-16 16:42 UTC
Labels: :books: Area - .NET Core Guide, doc-enhancement, dotnet-cli/tech, dotnet-core/prod
