### ISSUE TITLE
Update Escaping braces with .Net Core 3.0 change

### ISSUE THREAD

**Issue by svick** [dotnet/docs#22156] opened 2020-12-25 10:52 UTC
Because of https://github.com/dotnet/runtime/issues/28649, .Net Core 3.0 changed how braces are escaped, which means that the Escaping Braces section of this article is now outdated and should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b5f5c7-99f8-e112-a3f4-691548e8fc06
* Version Independent ID: e4b0d61c-a09b-3bf0-1696-1d4472272237
* Content: [Composite formatting](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting?WT.mc_id=DOP-MVP-5002735#escaping-braces)
* Content Source: [docs/standard/base-types/composite-formatting.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/composite-formatting.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by PathogenDavid** [comment] 2020-12-25 11:48
(See also, related discussion: https://github.com/dotnet/roslyn/issues/50082)

Care should be taken when updating these docs since the old behavior is still required in projects targeting older runtimes or anything that's multi-targeted.

Not sure what the precedent is here (if there even is one), but my gut says that everything following and including "The way escaped braces are interpreted can lead to unexpected results." in that section should be broken out to a sub-section with a note saying it only applies to .NET Framework and .NET Core versions prior to 3.0.

**Comment by Youssef1313** [comment] 2020-12-25 12:26
@gewarren Plus updating the article, should this also be added to the .NET API breaking changes?

**Comment by gewarren** [comment] 2021-01-05 01:21
> @gewarren Plus updating the article, should this also be added to the .NET API breaking changes?

https://github.com/dotnet/coreclr/pull/23062 is not labeled as a breaking change, so I don't think so.

**Comment by Youssef1313** [comment] 2021-01-05 08:13
> > @gewarren Plus updating the article, should this also be added to the .NET API breaking changes?
> 
> [dotnet/coreclr#23062](https://github.com/dotnet/coreclr/pull/23062) is not labeled as a breaking change, so I don't think so.

I'm not sure why it wasn't labeled as a breaking change. It *does* seem like a breaking change to me.

The comment https://github.com/dotnet/runtime/issues/28649#issuecomment-469056758 states that this change:

> Is expected to break close to, if not, zero customers

However, it's still a breaking change even if such code isn't likely to exist in real projects.

I'd like the runtime team to review whether this should be doc'ed as breaking change or not.

**Comment by adegeo** [comment] 2023-08-07 20:09
Closing in favor of a different issue I started working on.

**Comment by adegeo** [comment] 2023-08-07 20:09
Duplicate of #34929

**Closed by adegeo** 2023-08-07 20:09 UTC
Labels: doc-bug, Pri2, dotnet-core/prod, dotnet-fundamentals/prod, okr-health
