### ISSUE TITLE
Ocelot seems not to be maintained any more

### ISSUE THREAD

**Issue by mbendtsen** [dotnet/docs#28235] opened 2022-02-14 10:06 UTC
In this article, Ocelot API gateway by ThreeMammels are not being maintained anymore. 
There are 79 open pull requests and 792 open issues which are not being answered.
[This ](https://github.com/ThreeMammals/Ocelot/issues/1539) discussion also discuss the issue. 

Should this be noted in this article or maybe pointed to an alternative solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by VaishaliRaval** [comment] 2022-02-16 15:52
Hey @mbendtsen , thank you for reaching out and reporting this.

As Ocelot is no longer maintained, we moved away from using it and we are currently using Envoy proxy for the redirections. Will be updating the content of docs for API Gateways accordingly.

I am closing this issue as of now, feel free to track the updation of docs in a similar issue [here](https://github.com/dotnet/docs/issues/27445)

**Closed** 2022-02-17 11:33 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-architecture/prod, microservices/tech

**Comment by raman-m** [comment] 2023-09-18 14:38
> @mbendtsen commented [on Feb 14, 2022](#issue-1137062617)
> @VaishaliRaval commented [on Feb 16, 2022](#issuecomment-1041808388)
> @muratcabuk FYI
> 
Ocelot is maintained by me since May of this year, after making of [latest 19.0.2 release](/ThreeMammals/Ocelot/releases). The problem is in merging PRs and pressing the Release button. These operations can be performed by repo owner only, by Tom.
I hope this problem gets resolved soon...
