### ISSUE TITLE
HttpClient

### ISSUE THREAD

**Issue by tudort-iquest** [dotnet/docs#13495] opened 2019-07-20 14:14 UTC
It would be useful to mention on this page also HttpClient, and when it should be used instead of WebClient..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf19b23d-3693-2508-dbbe-2a2ee2c86081
* Version Independent ID: e3e27e19-80a7-7411-4382-c88ec9a2da5b
* Content: [HTTP](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/http)
* Content Source: [docs/framework/network-programming/http.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/http.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment] 2019-11-07 21:33
@tudort-iquest Hello. Sorry for the delay in getting to this issue. Really this article needs to be rewritten for HttpClient. I'm closing this as a duplicate. Thanks!

**Comment by Thraka** [comment] 2019-11-07 21:33
Duplicate of #13253

**Closed by Thraka** 2019-11-07 21:33 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - NCL, :watch: Not Triaged
