### ISSUE TITLE
Language reference should mention implicit casting of 'foreach'

### ISSUE THREAD

**Issue by sjb-sjb** [dotnet/docs#11029] opened 2019-03-05 03:17 UTC
The language reference should mention an important aspect of 'foreach', which is that each enumerated value is cast to the type of the loop variable. An exception is thrown if the cast fails. For example, the foreach variable can have a class type derived from the type of elements in the collection. One can also iterate, for example, doubles from a list of int. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d710feeb-8f03-b211-a070-155938929d6b
* Version Independent ID: c980ea8e-ffb4-fbb1-1761-292858616cdd
* Content: [C# foreach statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in)
* Content Source: [docs/csharp/language-reference/keywords/foreach-in.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/foreach-in.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-03-11 21:37
Thanks for pointing this out @sjb-sjb 

I've added ti to our backlog to update when we update this article.

**Comment by pkulikov** [comment] 2019-03-12 06:50
@BillWagner it looks there is one more issue with the same concern: https://github.com/dotnet/docs/issues/4505

**Comment by BillWagner** [comment] 2019-03-12 13:04
thanks @pkulikov 

Closing this as a duplicate of #4505.  There is more discussion on that issue regarding the proposed solution.

**Closed by BillWagner** 2019-03-12 13:04 UTC
Labels: :books: Area - C# Guide, P1, Source - Docs.ms
