### ISSUE TITLE
hang in ReadInt activity

### ISSUE THREAD

**Issue by peterremote1980** [dotnet/docs#8623] opened 2018-10-25 00:16 UTC
hang in ReadInt activity, why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 677e14d7-3d84-0007-3d62-4302b46a8781
* Version Independent ID: d4a2f845-5bcd-48d4-eae6-72854e2f6598
* Content: [How to: Create a Sequential Workflow](https://docs.microsoft.com/en-us/dotnet/framework/windows-workflow-foundation/how-to-create-a-sequential-workflow)
* Content Source: [docs/framework/windows-workflow-foundation/how-to-create-a-sequential-workflow.md](https://github.com/dotnet/docs/blob/master/docs/framework/windows-workflow-foundation/how-to-create-a-sequential-workflow.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gewarren** [comment] 2019-11-22 23:37
This is a dupe of #8622.

**Closed by gewarren** 2019-11-22 23:37 UTC
Labels: :books: Area - .NET Framework Guide, :watch: Not Triaged
