### ISSUE TITLE
Controlling the Prediction Score Range

### ISSUE THREAD

**Issue by dorofino** [dotnet/docs#12235] opened 2019-05-07 15:34 UTC
Hi everyone, 
I have a question in regards to the Prediction Score.

I was wondering if there is any way I set up a range for the score between 0 to 1
For example:
0.5 &gt; positive
0.5 = neutral
0.5 &lt; negative

I'm currently using Cognitive Service Text Analytics API, and as you probably know their score between 0-1 [Link](https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-sentiment-analysis#step-3-view-results)

&gt; The sentiment analyzer classifies text as predominantly positive or negative, assigning a score in the range of 0 to 1. Values close to 0.5 are neutral or indeterminate. A score of 0.5 indicates neutrality. When a string cannot be analyzed for sentiment or has no sentiment, the score is always 0.5 exactly. For example, if you pass in a Spanish string with an English language code, the score is 0.5.

Let me know if you know an easy way to implement this method.

Thanks 
Diego

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [What is ML.NET and how does it work? - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work#feedback)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by luisquintanilla** [comment] 2019-05-08 14:55
Closing because it is a duplicate of #12242

**Closed by luisquintanilla** 2019-05-08 14:55 UTC
Labels: :books: Area - ML.NET Guide, :watch: Not Triaged, Source - Docs.ms
