### ISSUE TITLE
This sample does not work as described in VS 2022 on .Net 6 with .NetStandard 2.0

### ISSUE THREAD

**Issue by veemata** [dotnet/docs#27534] opened 2021-12-13 21:05 UTC
[Enter feedback here]
This sample does not work as described in VS 2022 on .Net 6 with .NetStandard 2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-12-14 14:44
adding @mikadumont 

Thanks for noting this @veemata We do need to update this article (and add more information on creating source generators).

**Comment by IEvangelist** [comment] 2021-12-14 14:52
Closing as a duplicate of the issue I'm working on right now: #27119

**Closed by IEvangelist** 2021-12-14 14:52 UTC
Labels: doc-bug, Pri1, dotnet-csharp/prod, csharp-roslyn/tech
