### ISSUE TITLE
a targets are not matching

### ISSUE THREAD

**Issue by Fxplorer** [dotnet/docs#40036] opened 2024-03-15 03:55 UTC
### Type of issue

Other (describe below)

### Description

_Issue is specifically about `docs/standard/base-types/custom-numeric-format-strings.md` but may apply to other pages_.

When reading the learn page on [Custom numeric format strings](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) I got to the section on 

> Per mille placeholder

 which has the link in the line 

> More information: [The "‰" Custom Specifier](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#SpecifierPerMille).

Following the link `https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#SpecifierPerMille` ends up at the bottom of the page of `docs/standard/base-types/custom-numeric-format-strings.md` instead of hitting the `<a name="SpecifierPerMille"></a>` page target.

Clicking the page link target for "The "‰" custom specifier" on the [page](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#the--custom-specifier-4) goes to `https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#the--custom-specifier-4`
when it should be hitting 
`https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#SpecifierPerMille`

Somewhere in the generation pipeline is changing the a target link or not picking it up. 

### Page URL

https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/standard/base-types/custom-numeric-format-strings.md

### Document Version Independent Id

18c2ed9b-4015-109c-1ac2-b9b39ed19e8b

### Article author

@adegeo

**Comment by adegeo** [comment] 2024-07-01 19:30
Tested with Edge. I just tested this and I'm not able to reproduce it. Perhaps it was automatically fixed? I'm going to close the issue, please feel free to reopen it if you still see this problem.

**Closed by adegeo** 2024-07-01 19:30 UTC
Labels: doc-bug, Pri3, dotnet-fundamentals/svc
