### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by Pxtl** [dotnet/docs#6578] opened 2018-07-20 16:38 UTC
It leaves out any discussion of serialization, and doesn't discuss how to add custom members.  Get it out of my search results or fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 041f6b4c-2b7e-5332-f24e-12af7a5b07aa
* Version Independent ID: e9c2287f-1c4e-ee07-a1ff-77a3f07ce1a4
* Content: [How to: Create User-Defined Exceptions](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions)
* Content Source: [docs/standard/exceptions/how-to-create-user-defined-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/standard/exceptions/how-to-create-user-defined-exceptions.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment] 2018-07-20 19:21
Thank you, @Pxtl, for your feedback. Unfortunately, your criticism of this topic is justified. It doesn't explicitly discuss inheriting from Exception, it doesn't discuss serialization, and it doesn't discuss adding additional members. 
This issue is a duplicate of #5949, so I'm going to close this issue. However, we have scheduled time to improve this topic so that it will provide all of the information needed to implement a custom exception.
I'm sorry that you found our documentation disappointing. But thank you for taking the time to point it out to us so that we can improve it.

**Closed by rpetrusha** 2018-07-20 19:21 UTC
Labels: Area - .NET Guide, Source - Docs.ms, duplicate, triaged
