### ISSUE TITLE
Samples - missing project/solution-files

### ISSUE THREAD

**Issue by Bartolomeus-649** [dotnet/docs#13585] opened 2019-07-26 14:22 UTC
A lot of samples at https://github.com/dotnet/samples/tree/master/core/ are missing solution/project files which makes it problematic to use them from Visual Studio.

After cloning the samples you have this GUI-view of the samples:
![image](https://user-images.githubusercontent.com/7513795/61957012-9c279e80-afbe-11e9-9c60-75f29bfd0026.png)

And after double clicking Samples, this list is presented:
![image](https://user-images.githubusercontent.com/7513795/61957660-0c82ef80-afc0-11e9-969a-5c16061b5acf.png)

And when you click "here", you get the "Open Solution" dialog box in Visual Studio.
And if you navigate to, for example, \core\hosting, there's no way to open any of the projects there.

**Is Visual Studio Enterprise/TFS still supported tools for working with dotNet, or did you abandon them without telling anyone, like you did with Silverlight?**

**Comment by Thraka** [comment] 2019-07-26 15:03
Thanks for alerting us. I've noticed this too when I've worked on a specific sample as any time you open the project Visual Studio wants to then create a SLN file for you.

I edited your issue title to remove the /core/hosting from it. This way the issue is a bit more generic about how we need to make sure every sample has a SLN file.

**Comment by Thraka** [comment] 2019-11-07 18:19
This will be fixed as we address #14824

**Closed** 2019-11-07 22:35 UTC
Labels: :file_folder: Repo - samples, P1, doc-enhancement
