### ISSUE TITLE
CommunityToolkit.Mvvm partial methods and IDE0060

### ISSUE THREAD

**Issue by robertodalmonte** [dotnet/docs#30518] opened 2022-08-08 07:13 UTC
[Enter feedback here]

Hello, 
I'm using the CommunityToolkit.Mvvm Version="8.0.0" and pretty often I take advantage of the partial methods created:
EXAMPLE:
 [ObservableProperty] private int _startAgeFilter;

then I use:
partial void OnStartAgeFilterChanged(int value)
    {
        Filter();
    }
    
I get the warning since the value parameter is not used, but I can't remove it otherwise I get a compile-time error (No defining declaration).
Regards
Roberto

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029ba69a-6673-836c-c69e-0105061904ea
* Version Independent ID: fc793abc-cd23-d6c5-2915-89ef59ca6d41
* Content: [IDE0060: Remove unused parameter - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0060)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0060.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0060.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2023-03-29 22:53
Closing as a duplicate of https://github.com/dotnet/roslyn/issues/57814.

**Closed by gewarren** 2023-03-29 22:53 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-fundamentals/prod
