### ISSUE TITLE
Why does an interpolated string not provide the same warning?

### ISSUE THREAD

**Issue by HugoRoss** [dotnet/docs#22347] opened 2021-01-13 12:43 UTC
Why does an interpolated string not provide the same warning (CA1305)? The danger is exactly the same there, both always use CultureInfo.CurrentCulture to format the given value (see sample below):

    public static void Main(string[] args) {
        //Initialize test values
        DateTime date = new DateTime(2021, 12, 31);
        decimal value = 1234.56M;
        //Initialize format providers
        string[] testCultures = new string[] { "de-CH", "en-US", "en-GB" };
        IEnumerable<CultureInfo> formatProviders = testCultures.Select(e => new CultureInfo(e, false));
        //Initialize results
        StringBuilder resultByFormat = new StringBuilder();
        StringBuilder resultByInterpolation = new StringBuilder();
        //Fill in results
        foreach (CultureInfo cultureInfo in formatProviders) {
            CultureInfo.CurrentCulture = cultureInfo;
            resultByFormat.AppendLine(string.Format("Value: {0}", value));
            resultByFormat.AppendLine(string.Format("Date: {0}", date));
            resultByInterpolation.AppendLine($"Value: {value}");
            resultByInterpolation.AppendLine($"Date: {date}");
        }
        //Assert that they are equal
        if (resultByInterpolation.ToString() == resultByFormat.ToString()) {
            Console.Out.WriteLine("Interpolation behaves the same as String.Format(..)."); //This string is written
        } else {
            Console.Out.WriteLine("Interpolation behaves differently than String.Format(..).");
        }
    }

Or do I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee726c26-f355-a0d8-9d7d-63d770e2a23c
* Version Independent ID: f8c1f8a7-0dcb-7e6d-0eaf-8acf31a65c42
* Content: [CA1305: Specify IFormatProvider (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1305)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1305.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1305.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment] 2021-01-13 13:02
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/2150

**Comment by gewarren** [comment] 2021-01-13 17:18
@Youssef1313 Thanks for that link. Closing this docs issue in favor of the product issue.

**Closed by gewarren** 2021-01-13 17:18 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged, dotnet-fundamentals/prod
