### ISSUE TITLE
`dotnet-core-uninstall` does not support .NET 6

### ISSUE THREAD

**Issue by tillig** [dotnet/docs#25357] opened 2021-07-27 17:03 UTC
The `dotnet-core-uninstall` tool [in GitHub here](https://github.com/dotnet/cli-lab) appears to be in a "maintenance mode" and does not support uninstalling .NET 6.0 versions. You may need to provide alternate instructions for .NET 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4efe9b33-ff9f-3b37-e8bd-a34c0a77bd1e
* Version Independent ID: 090b8fbd-39e6-b754-e1da-890b1123f2c4
* Content: [Remove the .NET runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/install/remove-runtime-sdk-versions?pivots=os-windows)
* Content Source: [docs/core/install/remove-runtime-sdk-versions.md](https://github.com/dotnet/docs/blob/main/docs/core/install/remove-runtime-sdk-versions.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-08-01 02:56
I think we should just handle this in the other issue you filed.

**Comment by adegeo** [comment] 2021-08-01 02:56
Duplicate of #25358

**Closed by adegeo** 2021-08-01 02:56 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
