### ISSUE TITLE
The annotation for nullable reference types should only be used in code within a '#nullable' context.

### ISSUE THREAD

**Issue by arivoir** [dotnet/docs#9517] opened 2018-12-10 16:00 UTC
After converting my project to c#8 and fixing all the problems. Every warning was removed, and suddently I got 97 Warnings of these
Warning	CS8632	The annotation for nullable reference types should only be used in code within a '#nullable' context.

Do I need to add the #nullabel context if I used &lt;NullableReferenceTypes&gt;true&lt;/NullableReferenceTypes&gt; in the proj file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a690704d-da32-dca7-ea3e-66b84fb1d00d
* Version Independent ID: 11f314de-dd3a-362e-b2bb-d0a2133cfc7b
* Content: [Nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references)
* Content Source: [docs/csharp/nullable-references.md](https://github.com/dotnet/docs/blob/master/docs/csharp/nullable-references.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2018-12-10 22:09
@arivoir Adding the `<NullableReferenceTypes>true</NullableReferenceTypes>` in your csproj, in a `PropertyGroup` should work fine.  A couple things to check:

- Do you also have the C# 8 compiler turned on? Check the `LangVersion` element to make sure its set to `8.0`
- Did those warnings go away as the IDE re-ran the analysis on the code? I've found initial  incorrect warning indicators go away after the IDE has run a full analysis on the project.

**Comment by arivoir** [comment] 2018-12-11 00:36
@BillWagner Yes, I have the LangVersion tag correctly. Actually I could migrate the project correctly and fix all the bugs that appeared because of the change to c#8. Now I'm seeing the warnings are comming from the Intellisense, because when I change the "Build+IntelliSense" combo box of the "Error List" to just "Build" they go away. Neither Analyze nor Clean nor Rebuild nor deleting bin and obj folders make any difference.

I'm using the following project to test [Open.Flickr](https://github.com/arivoir/Open.Flickr)

Please let me know if you need more info.

**Comment by arivoir** [comment] 2018-12-11 20:05
@jcouv I tried restarting Visual Studio and even the PC, but the problem is still there. Once you open the project it takes some seconds, apparently running the Intelli-sense, and the "Error List" is re-populated with these warnings.

**Comment by jcouv** [comment] 2018-12-11 21:37
@arivoir One more question: if you build the project (`F6`) and look at the Output pane, do these warnings also appear there?

**Comment by arivoir** [comment] 2018-12-11 21:45
@jcouv No, they do not appear in the "Output" pane. Only in "Error List"

**Comment by jcouv** [comment] 2018-12-11 22:37
@arivoir I talked to a coworker and I think we've figured this out.
There are two types of project files: legacy-style (big and gnarly) and new-style (short and sweet). The `NullableRerenceTypes` property is only fully understood in the new-style project files in dev16.0 preview1.

I suspect you have a legacy-style project file. So what happens is that Build does the right thing, but when the IDE tries to approximate the build process (Intellisense) it did not properly account for the `NullableReferenceTypes` property.

This will be fixed by the time C# 8.0 ships, and it is tracked by https://github.com/dotnet/project-system/issues/4058

In the meantime, you can use the "Build" filter (instead of "Build+Intellisense"), or if the project is small you could add `#nullable enable` to every file. Sorry for the confusion and inconvenience.

**Comment by arivoir** [comment] 2018-12-11 22:58
@jcouv I'm afraid it is not the case. It's actually using the new style [Open.Flickr.csproj](https://github.com/arivoir/Open.Flickr/blob/master/Open.Flickr/Open.Flickr.csproj) You can get the project and try in your environment. Please let me know whether you're having the same issue as me.

**Comment by arivoir** [comment] 2018-12-11 23:34
I originally found this problem in preview1, and then upgraded to preview1.1 where the problem continued.

Please let me know if there is any log or something I can make to help.

**Comment by jcouv** [comment] 2018-12-12 03:38
I tried this on a preview 1 (`VisualStudio.16.Preview/16.0.0-pre.1.0+28329.73`), but still couldn't repro.

I would be tempted trying to "repair" your preview 1 (or 1.1) installation.

Tagging @heejaechang in case he has some ideas. To summarize, the issue is that the "Error List" with  "Build+IntelliSense" filter shows some nullable warnings that appear nowhere else (neither in "Output" pane, nor in "Build" filter).
Do you know how to troubleshoot this?

**Comment by BillWagner** [comment] 2018-12-13 20:43
Closing this based on above discussion and issue.

**Comment by xuhongxu96** [comment] 2019-01-24 12:47
Hi, I have the same issue. And this warning will show in **Build Only Error List** as well as the **Output window**.

![image](https://user-images.githubusercontent.com/2201482/51679121-044df580-2019-11e9-9d08-d58c93825b4f.png)

Visual Studio 2019 Preview 2

**Comment by jcouv** [comment] 2019-01-24 15:58
@xuhongxu96 In preview2, the name of the build property changed.
Use `<NullableContextOptions>enable</NullableContextOptions>` instead. You may have to close/re-open VS for it to take effect.

Details https://github.com/dotnet/roslyn/blob/master/docs/features/nullable-reference-types.md#setting-project-level-nullable-context

**Comment by BillWagner** [comment] 2019-01-24 16:04
I'm reopening this. 

I'll update the docs in the next two weeks to reflect the change in the build property.

**Comment by xuhongxu96** [comment] 2019-01-25 08:52
@jcouv @BillWagner Thanks for help. It works after I added:
```xml
    <NullableContextOptions>enable</NullableContextOptions>
```
Though I'm not sure what the differences among `enable`|`disable`|`safeonly`|`warnings`|`safeonlywarnings` are.

**Comment by AlekseyTs** [comment] 2019-01-25 18:15
The way NullableContextOptions affects nullable annotation and warning context is described here https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/NullableContextOptions.cs.
The annotation and warning contexts are described here https://github.com/dotnet/csharplang/blob/master/proposals/nullable-reference-types-specification.md#nullable-contexts

The ```warnings``` option is useful for those who want to get warnings from flow analysis, even though the types aren't annotated. Flow analysis is still able to catch some NullReferenceException cases.

**Comment by jcouv** [comment] 2019-01-25 19:46
> The warnings option is useful for those who want to get warnings from flow analysis, even though the types aren't annotated. Flow analysis is still able to catch some NullReferenceException cases.

I expect people would use `safeonlywarnings` for that.
To illustrate the difference between `warnings` and `safeonlywarnings`:
```C#
var s = string.Empty;
s = null; // `warnings` produces a W-warning here, but I'm not sure which in which scenario that's desirable
```

**Comment by AlekseyTs** [comment] 2019-01-25 19:51
> I expect people would use safeonlywarnings for that.

Let the user make the choice. I personally value all nullable warnings.

**Comment by arivoir** [comment] 2019-01-28 16:43
I updated to preview 2, changed <NullableContextOptions>enable</NullableContextOptions>, restarted visual studio, rebuilt project, but I'm seeing exactly the same problem as before. No problem with the build, but when I enable "Build + IntelliSense" a bunch of wrong messages appear.

**Closed** 2019-02-19 21:29 UTC
Labels: :books: Area - C# Guide, P1, Source - Docs.ms

**Comment by isxaker** [comment] 2019-02-24 18:59
for` .net framework` project it doesn't work
I mean I created 2 projects `.net core` and `.net framework`
put the same settings:

```
<LangVersion>8.0</LangVersion>
<NullableContextOptions>enable</NullableContextOptions>
```

and you know what
the new feature become active only for `.net core` app
and` .net framework` app still has the same behavior getting me the following warning:
`Warning	CS8632	The annotation for nullable reference types should only be used in code within a '#nullable' context.`

What i did wrong ?
So now I'm only able to enable this feature for my .net framework app via  `#nullable enable`

**Comment by BillWagner** [comment] 2019-03-04 15:48
ping @jcouv for insight here.  

Are the compiler switches different for .NET Framework apps?  

@isxaker Is your .NET Framework project using the or the old style CSPROJ file? I don't know if that makes a difference, but it's worth knowing.

**Comment by isxaker** [comment] 2019-03-04 16:47
> @isxaker Is your .NET Framework project using the or the old style CSPROJ file? I don't know if that makes a difference, but it's worth knowing.

@BillWagner 

Didn't get it clear enough. 
I just go to `VS2019` click new project -> console app(.net framework)
And that's all. I can't turn this feature on via `.csproj` file.
The only one way how I'm able to turn this feature on for .net framework app is using `#nullable enable`

**Comment by dark2201** [comment] 2019-03-15 09:33
@isxaker 	works fine for me with .NET Framework

**Comment by isxaker** [comment] 2019-03-15 09:38
> @isxaker works fine for me with .NET Framework. Maybe it's fixed now?

can you post here your .csproj file please

**Comment by dark2201** [comment] 2019-03-15 10:04
@isxaker 

Okay, I've tested it and it doesn't seem with to work with .NET Framework unless you add `#nullable enable` in your code.

`<NullableContextOptions>enable</NullableContextOptions>` is ignored in old style projects.

but after converting to new csproj format it works with .NET Framework:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectGuid>{C192613D-2431-40F2-BA13-33B5B55241A5}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <NullableContextOptions>enable</NullableContextOptions>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyTitle>NullableReferenceTypesNetFramework</AssemblyTitle>
    <Product>NullableReferenceTypesNetFramework</Product>
    <Copyright>Copyright ©  2019</Copyright>
    <OutputPath>bin\$(Configuration)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
```

Also it doesn't work with ReSharper (but compiles fine).

additional notes:

`Nullable<string>` doesn't compile, and `string?` is missing `System.Nullable` properties like `HasValue` and `Value`

**Comment by AlexanderTaeschner** [comment] 2019-05-22 20:14
The option has been renamed to `<Nullable>`, so that `<Nullable>enable</Nullable>` in the csproj file now enables the nullability feature for all code files in the project (see https://github.com/dotnet/roslyn/issues/35432).

**Comment by egil** [comment] 2019-05-22 20:19
> The option has been renamed to `<Nullable>`, so that `<Nullable>enable</Nullable>` in the csproj file now enables the nullability feature for all code files in the project (see [dotnet/roslyn#35432](https://github.com/dotnet/roslyn/issues/35432)).

Great. That is a good simplification. I must have missed that in the release notes. Thanks for the hint.

**Comment by flcdrg** [comment] 2019-05-23 05:14
Just to clarify, SDK 2.2.204, 2.2.300 and 3.0.100-preview5-011568 still appear to use `NullableContextOptions` in `Microsoft.CSharp.Core.targets`

The same with Visual Studio 2019 16.1 (`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets`)

2019 16.2 Preview *does* have have it though (`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets`)

**Comment by bigdnf** [comment] 2019-06-16 10:34
I just enabled nullable like this

```
<PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

```
and my project is failing to compile 'Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version 'preview' or greater'. I'm using .NET Core 3 preview 6 and Visual Studio 16.2 Preview 2

**Comment by bdbc78** [comment] 2019-12-17 19:29
I'm getting this issue. Here's my project settings:
`<PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <nullable>enable</nullable>
    <AssemblyName>[assemblyname]</AssemblyName>
  </PropertyGroup>`

Adding LangVersion doesn't have any impact. This appears to align with updating to VS2019 16.4, however I cannot say that for certain. Nullable reference types were being used prior to the update without this message being decorated everywhere.

**Comment by Tiramonium** [comment] 2019-12-17 20:22
I was facing this kind of issue at my nullable reference type property declarations, so I kind of accidentally found the solution for this warning by setting `nullable` as you do a `region` block and the parameter values dug up by @xuhongxu96 and @jcouv.

So in the end my code ended up looking like this
`
\#nullable enabled
    public Type? TypeProp { get; set; }
\#nullable disabled
`

So my guess is that depending on the type of situation you are facing, you should use one of the values mentioned in @jcouv 's [answer](https://github.com/dotnet/docs/issues/9517#issuecomment-457630516), then disabling the setting by ending the block with `#nullable disabled`, if you prefer.

**Comment by bdbc78** [comment] 2019-12-17 20:37
Except that's not a solution to the issue, since setting `<nullable>enabled</nullable>` in the project file is supposed to negate the need for that directive. In fact, when nullable is enabled, really the only practical usage of the directives at that point is to use them to phase in the nullable functionality file by file (by using `#nullable disable`).

For some reason, in my situation the evaluation is ignoring the existence of the nullable setting in the project file.

**Comment by Tiramonium** [comment] 2019-12-17 21:21
My latest solution was to implement it as suggested by other answers and it worked just fine. NET Core versions older than 3.0 may still face the issue probably because their framework versions don't use C# 8.0 yet, which is used by default by VS 2019 as its IntelliSense compiler, as far as I know. Those cases will require either different fixes, maybe tinkering with the IDE settings, or for them to be worked on exclusively via VS 2017 instead.

Based on Microsoft's [own documentation] (https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts), I reached the following solution:
```c#
    <Project Sdk="Microsoft.NET.Sdk.Web">
        <PropertyGroup>
            <TargetFramework>netcoreapp3.1</TargetFramework>
            <LangVersion>8.0</LangVersion>
            <Nullable>annotations</Nullable>
        </PropertyGroup>
    </Project>
```

That enables the nullable context, eliminating the CS8632 warning message - disregarding the need for a `#nullable` block declaration - and disabled the nullable warning context, ensuring that nullable checks will be enforced against nullable reference types.

Also, you won't see it happen until you restart VS completely, since IntelliSense uses the last loaded setting for real time compilation.

**Comment by bdbc78** [comment] 2019-12-18 15:22
All of my project settings are correct as it pertains to what behavior I am expecting to see in the project regarding any nullable reference type warnings. However, after further investigation on another developer's development environment, it was determined that the latest version of ReSharper is the cause of the issues I'm seeing. So I will redirect my issue reporting to their issue tracker. Thank you.

**Comment by KishorTiwari** [comment] 2020-06-06 02:49
Thanks @Tiramonium It worked for me.

**Comment by ata18** [comment] 2021-05-13 19:48
I have the following in my.csproj file. When running in vscode on my local machine, it doesn't throw any warnings/errors. But when I build it in the Azure pipelines task, I get a bunch of these CS8632 warnings..  Any idea what might be happening?

```
 <TargetFramework>net5.0</TargetFramework>
 .
 .
 <LangVersion>9.0</LangVersion>
<Nullable>enable</Nullable>
<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
<AnalysisMode>AllEnabledByDefault</AnalysisMode>
<EnableNETAnalyzers>true</EnableNETAnalyzers>
```

**Comment by jcouv** [comment] 2021-05-17 20:40
@ata18 Just to confirm, when you're doing a local build (say from command-line, not VSCode), are you getting the expected nullability warnings?

There's also a small possibility that the specific compiler versions used in pipeline task and locally differ. The nullability feature has had revisions. You could troubleshoot this by confirming the compiler versions (add `#error version` to your source to create a diagnostic outputting the details).

**Comment by Tiramonium** [comment] 2021-05-24 11:43
@ata18 first of all, if you noticed, this warning got introduced in C# 8.0 and I'm assuming it carried onto 9.0 as well, which is used by NET 5.0. If you had read this thread you would have noticed that `<Nullable>true</Nullable>` enables this check instead of disabling it.

Another thing I noticed in your settings that might be causing unexpected results is that you set it to treat warnings as errors with `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`, so your Azure Pipeline(s) might be failing precisely because of that.

**Comment by ata18** [comment] 2021-05-24 23:05
@jcouv Thanks for your response, I will check the compiler versions. 

@Tiramonium You are correct. I know that <Nullable>true</Nullable> enables the check. And I have fixed all the errors related to `nullable references` and running it locally has no more warnings. However, I still get these CS8632 warnings in Azure pipelines.

**Comment by Tiramonium** [comment] 2021-06-29 18:02
@ata18 I just noticed a very basic error in your code. String is a C# reference type which inherently implements its nullable version, same with generic reference types like Object and Dynamic, therefore there's no such thing as a `string?` property.

**Comment by ata18** [comment] 2021-06-29 19:20
@Tiramonium I don't think that is true with c# 8+. 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/nullable-reference-types

**Comment by FreakyAli** [comment] 2022-09-20 16:50
Enabling `<Nullable>enable</Nullable>` on my current project just got it from 1 warning to 265 warnings 😱
