### ISSUE TITLE
csproj reference lacks detail about SDKs

### ISSUE THREAD

**Issue by proog** [dotnet/docs#3218] opened 2017-09-25 17:09 UTC
The [csproj reference](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#additions) topic lists the two main SDKs that can be specified in the `Sdk` attribute of a `<Project>` element.

While it does have a vague mention of the SDK being a "set of tasks and targets," it does not explain which, and perhaps more importantly does not explain what the consequences of choosing one over the other is.

In my opinion it would be helpful to have a paragraph dedicated to choosing the right SDK, or a reference to a more in-depth explanation of their differences.

**Comment by mairaw** [comment] 2018-01-22 19:32
Hi @proog, I've moved your comment to an issue we're capturing a new topic that should be truly a csproj reference. I'll be closing this one as a duplicate. Thanks for the feedback!

**Comment by mairaw** [comment] 2018-01-22 19:32
Duplicate of #2642

**Closed by mairaw** 2018-01-22 19:32 UTC
Labels: Area - .NET Core Guide, P2, enhancement
