### ISSUE TITLE
Ubuntu 21.10 packages are missing

### ISSUE THREAD

**Issue by akorda** [dotnet/docs#26910] opened 2021-11-10 08:48 UTC
Hi! It seems that the ubuntu 21.10 packages are missing. There is no https://packages.microsoft.com/config/ubuntu/21.10 folder.

Could you please add them?

Kind regards!

---
#### Λεπτομέρειες εγγράφου

⚠ *Μην επεξεργαστείτε αυτή την ενότητα. Απαιτείται για σύνδεση θεμάτων docs.microsoft.com ➟ GitHub.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/el-gr/dotnet/core/install/linux-ubuntu#2110-)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-11-10 21:34
Thank you for reporting this issue. The documentation is being updated. .NET packages haven't been released for Ubuntu 21.10 but are in progress. Using the 21.04 repository works just fine.

**Comment by adegeo** [comment] 2021-11-10 21:35
Duplicate of #26879

**Closed by adegeo** 2021-11-10 21:35 UTC
Labels: doc-bug, Pri1, dotnet/prod, dotnet-install/tech
