### ISSUE TITLE
Access level in Visual Basic

### ISSUE THREAD

**Issue by BrettBr0wn** [dotnet/docs#12149] opened 2019-05-01 20:34 UTC
The Access levels in Visual Basic link does not work. "For a comparison of Friend and the other access modifiers, see Access levels in Visual Basic."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcf094bf-2661-77a2-cfc0-e7767a5e06f4
* Version Independent ID: 2369e9af-9d7a-4355-841a-860cf408e5ca
* Content: [Friend (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference//modifiers/friend#feedback)
* Content Source: [docs/visual-basic/language-reference/modifiers/friend.md](https://github.com/dotnet/docs/blob/staging/docs/visual-basic/language-reference/modifiers/friend.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by mairaw** [comment] 2019-05-01 22:36
Thanks for your feedback @BrettBr0wn. If you access the URL without any extra //, the links work:
https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/friend

Do you know how you ended up on this page? Because it has an extra / in the path, which breaks our relative links.

![image](https://user-images.githubusercontent.com/12971179/57047414-d33c1d00-6c26-11e9-9ae2-3cce67b6c2fa.png)

**Comment by BrettBr0wn** [comment] 2019-05-17 16:43
I believe I accessed the page after searching Google for "vb friend function," but I can no longer recreate the issue.

**Comment by mairaw** [comment] 2019-06-03 22:55
Given that we can't reproduce this problem anymore and the correct page (https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/friend) doesn't present this issue, I'll close this.

**Closed by mairaw** 2019-06-03 22:55 UTC
Labels: :books: Area - Visual Basic Guide, Source - Docs.ms, broken-link, doc-bug
