### ISSUE TITLE
Error in Doc. Window 7 SP1 supports dotnet framework 4.7.2, but not windows 8?

### ISSUE THREAD

**Issue by athakral** [dotnet/docs#12090] opened 2019-04-29 13:13 UTC
Hi, 

Please double check the version and supported OS table. It seems there is an error. dotnet framework 4.7.2 is supported on Windows 7 SP1, but not supported on Windows 8. Can you please update it or explicitly call it out, that it is the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements#feedback)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/master/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2019-04-29 23:54
The information is correct, @athakral. NET Framework 4.7.2 is supported on Windows 8.1, but not on Windows 8.  Since I don't see a compelling reason to specifically call out this information, I'm going to close this issue as by design.

**Closed by rpetrusha** 2019-04-29 23:54 UTC
Labels: :books: Area - .NET Framework Guide, Source - Docs.ms, by-design
