### ISSUE TITLE
Invalid example code in jump statements, return ref

### ISSUE THREAD

**Issue by tbeest** [dotnet/docs#39458] opened 2024-02-08 13:56 UTC
### Type of issue

Code doesn't work

### Description

The ref returns section contains the following example code: `int[] xs = [10, 20, 30, 40];`

Output: `(1,12): error CS1525: Invalid expression term '['`

It should be `int[] xs = {10, 20, 30, 40};`

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/jump-statements#ref-returns

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/jump-statements.md

### Document Version Independent Id

e2587107-1293-4aa1-8f74-6417367d76e7

### Article author

@BillWagner

### Metadata

* ID: 5c1793eb-a1cc-62d8-2009-2d69eefa9413 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment] 2024-02-08 14:39
Hi @tbeest 

This is valid C#, starting with C# 12.  It's the new [collection expressions](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/collection-expressions) syntax.

I'll close this as by design.

**Comment by tbeest** [comment] 2024-02-08 22:56
Hi @BillWagner 

The editor on the website itself gives that error, so I guess that's not using the latest version yet.  
Do you know if there's anything which can be done about that?

**Comment by BillWagner** [comment] 2024-02-12 21:11
Thanks for clarifying that @tbeest 

I'll reopen this. 

For the short term, we can't use collection expressions in the Try.NET environment. The next semester deployment should include the C# 12 updates.

**Closed** 2024-02-20 18:20 UTC
Labels: doc-bug, Pri1, dotnet-csharp/svc, lang-reference/subsvc, in-pr, okr-health
