### ISSUE TITLE
The library author needs to move the default implementation into a protected static method

### ISSUE THREAD

**Issue by ericbrunner** [dotnet/docs#17066] opened 2020-02-13 08:18 UTC
This is not mandatory. You can define that method as public static , too.

And call it from the client side like so:

/// --- Default Interface Methods
            ICustomer customer = new Customer("eric");
            ICustomer.DefaultLoyaltyDiscount(customer);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3753657-9f0f-4e68-abde-5f461099cb6e
* Version Independent ID: f7bd9eb0-1653-15fd-5f0e-dc0ee5c3bf88
* Content: [Safely update interfaces using default interface methods in C#](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/default-interface-methods-versions#feedback)
* Content Source: [docs/csharp/tutorials/default-interface-methods-versions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/default-interface-methods-versions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-02-13 15:51
Thanks for writing this @ericbrunner 

For this tutorial, I'd prefer that method as protected, so it provides an implementation helper for types that implement the interface. 

I'm updating other content related to default interface members now. In those areas I do explain that each of the modifiers can be used.  

I'm going to close this as a duplicate of #14803, which I'm addressing in those updates.

**Closed by BillWagner** 2020-02-13 15:51 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged

**Comment by ericbrunner** [comment] 2020-02-13 17:40
Thanks @BillWagner 
Well Default Interface Methods is a huge topic and still not enough bullet-proof documentation online. I found that tutorial which helped me in understanding all possibilities a bit more.
https://www.talkingdotnet.com/default-implementations-in-interfaces-in-c-sharp-8/
