### ISSUE TITLE
Socket Server sample - make it non-blocking

### ISSUE THREAD

**Issue by kutovoy** [dotnet/docs#22540] opened 2021-01-28 00:18 UTC
While code works but it teaches a poor practice. Why not teach on how to accept multiple connections simultaneously and how to not block whole app while waiting for a next connection?

The article says "so execution of the server application is not suspended while it waits for a connection from a client" but the code does suspends while it waits for a connection "// Wait until a connection is made before continuing.  
                allDone.WaitOne();  "

Technically code works, article text contradicts its code example. Either I understood it wrong or its an acceptable level of a document which is ranked high in google search on the topic it describes. This code can't be a foundation for a network server C# app. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315ecd86-1347-1820-06ed-01f3f6ae1f9f
* Version Independent ID: d60a9356-c3c6-e886-0aa8-96cc8878ccbb
* Content: [Asynchronous Server Socket Example](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/asynchronous-server-socket-example)
* Content Source: [docs/framework/network-programming/asynchronous-server-socket-example.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/asynchronous-server-socket-example.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by gewarren** [comment] 2022-01-22 04:56
Related to https://github.com/dotnet/dotnet-api-docs/issues/7609.

**Comment by antonfirsov** [comment] 2022-10-05 17:56
Duplicate of #26911, addressed by #30759.

**Closed by antonfirsov** 2022-10-05 17:56 UTC
Labels: doc-enhancement, Pri1, dotnet-framework/prod, dotnet-networking/tech
