### ISSUE TITLE
Model Builder gif needs updated UI

### ISSUE THREAD

**Issue by beccamc** [dotnet/docs#33686] opened 2023-01-23 22:59 UTC
**Issue description**

[Model Builder gif](https://dotnet.microsoft.com/static/images/ml-dotnet-model-builder.gif?v=9CrGsE3IQVc1AljpUqtsWLv3vI1-DhB6iSJLb8P63Ic) should be updated to the latest UI. This UI is _years_ old, and doesn't demonstrate the full capabilities of Model Builder. Quick example is that it only shows 3 available scenarios. We now have 6 supported scenarios. 

https://dotnet.microsoft.com/en-us/apps/machinelearning-ai/ml-dotnet/model-builder

**Target framework**

not relevant 

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by gewarren** [comment] 2023-01-24 22:21
@mairaw This looks like a dotnet website issue. Can you transfer?

**Comment by mairaw** [comment] 2023-01-25 00:09
It's a duplicate of https://github.com/dotnet/website/issues/2640. This can be closed.

This has been on my backlog for a long time and I still haven't be able to address it. I'm hoping I can get to it next month.

**Closed by mairaw** 2023-01-25 00:09 UTC
Labels: :watch: Not Triaged, Pri3
