### ISSUE TITLE
Wrong example code in "Discards - C# Guide"

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9802] opened 2019-01-02 18:15 UTC
@sopepos commented on [Wed Jan 02 2019](https://github.com/dotnet/docs.ko-kr/issues/88)

There's no "switch" statement in example code of "Pattern matching with switch and is" section.

```csharp
   private static void ProvidesFormatInfo(object obj)         
   {
      if (obj is IFormatProvider fmt)
         Console.WriteLine($"{fmt} object");
      else if (obj is null) {
         Console.Write("A null object reference: ");
         Console.WriteLine("Its use could result in a NullReferenceException");
      }
      else
         Console.WriteLine($"Some object type without format information");
   }
```

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8047b417-55af-c6df-9333-f1e1c428e594
* Version Independent ID: 8bcc16bb-c2d8-0b6d-af20-6958964efe9e
* Content: [무시 항목 - C# 가이드](https://docs.microsoft.com/ko-kr/dotnet/csharp/discards)
* Content Source: [docs/csharp/discards.md](https://github.com/dotnet/docs.ko-kr/blob/live/docs/csharp/discards.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment] 2019-01-02 18:16
Hi team, 
I'm moving this here since the suggestion is about the code
best regards

**Comment by gonz01d** [comment] 2019-03-06 12:51
There also doesn't seem to be any use of the Discard in that example either.

**Comment by bombek92** [comment] 2019-05-28 08:59
I think "no switch" is not a problem with this example. The problem is that it is not realted to the topic of article - discards.

**Comment by Eilon** [comment] 2019-06-05 22:23
Just noticed this as well. The `Pattern matching with switch and is` sample doesn't use discards at all.

**Comment by BillWagner** [comment] 2019-06-05 22:34
I think this issue is fixed in https://github.com/dotnet/samples/pull/936

**Comment by BillWagner** [comment] 2019-06-06 20:42
Closing, dotnet/samples#936 fixed this as well

**Closed by BillWagner** 2019-06-06 20:42 UTC
Labels: :books: Area - C# Guide, P1, Source - Docs.ms
