### ISSUE TITLE
How can I mock BlobServiceClient for unit tests when using dependency injection?

### ISSUE THREAD

**Issue by svdHero** [dotnet/docs#27470] opened 2021-12-09 11:15 UTC
The documentation [here](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.-ctor?view=azure-dotnet#Azure_Storage_Blobs_BlobServiceClient__ctor) shows the default constructor `BlobServiceClient()` with the description "Initializes a new instance of the BlobServiceClient class for mocking."

How can I mock a `BlobServiceClient` for unit testing? More precisely, I would like to provide fake blob streams (e.g. from `MemoryStream`) and fake `BlobProperties` for my unit tests.

Please add some documentation how to achieve that.

I've also cross-posted this issue [here](https://github.com/Azure/azure-sdk-for-net/issues/25836).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0e2a2da-cb07-a454-dbfa-7349007812a2
* Version Independent ID: 2cbfee72-6851-6224-fd83-1819515926a9
* Content: [Dependency injection with the Azure SDK for .NET](https://docs.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection)
* Content Source: [docs/azure/sdk/dependency-injection.md](https://github.com/dotnet/docs/blob/main/docs/azure/sdk/dependency-injection.md)
* Product: **dotnet-azure**
* GitHub Login: @pakrym
* Microsoft Alias: **pakrym**

**Comment by tdykstra** [comment] 2021-12-09 20:01
@pakrym can you help with this question?

**Comment by pakrym** [comment] 2021-12-13 16:42
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/25836

**Closed by pakrym** 2021-12-13 16:42 UTC
Labels: doc-enhancement, waiting-on-feedback, Pri2, dotnet-azure/prod
