### ISSUE TITLE
Microsoft.CodeAnalysis.FxCopAnalyzers package deprecated

### ISSUE THREAD

**Issue by rtigithub** [dotnet/docs#22902] opened 2021-02-18 13:20 UTC
Now that the FxCopAnalyzers package is deprecated (https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers), this page should be updated to reference Microsoft.CodeAnalysis.NetAnalyzers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171973c7-c225-a776-793f-cf67869ea0b8
* Version Independent ID: f26f0129-8073-cc7e-1b3a-0002ad3af932
* Content: [Code analyzers for .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/code-analyzers)
* Content Source: [docs/framework/code-analyzers.md](https://github.com/dotnet/docs/blob/master/docs/framework/code-analyzers.md)
* Product: **dotnet-framework**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-02-19 10:07
Duplicate of https://github.com/dotnet/docs/issues/22613

**Comment by tdykstra** [comment] 2021-05-05 16:18
Closing since it's a duplicate of https://github.com/dotnet/docs/issues/22613

**Closed by tdykstra** 2021-05-05 16:18 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-framework/prod
