### ISSUE TITLE
Diagram using dark theme

### ISSUE THREAD

**Issue by daesolus** [dotnet/docs#6914] opened 2018-08-09 18:34 UTC
Some of the diagram is really hard to read in dark mode. Grey title on dark background is not ideal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d432d5bb-24a7-3bec-1e17-910c8129226e
* Version Independent ID: fa6385e8-91ad-7949-382f-ca8e03f8201c
* Content: [Domain events. design and implementation](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation)
* Content Source: [docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment] 2018-08-09 23:39
Thanks for your feedback @daesolus. This is a duplicate of #6547, so I'll be closing this one for that reason.

**Comment by mairaw** [comment] 2018-08-09 23:39
Duplicate of #6547

**Closed by mairaw** 2018-08-09 23:39 UTC
