### ISSUE TITLE
[global-json] Please add possible locations of the **global.json**

### ISSUE THREAD

**Issue by LisandroSu** [dotnet/docs#6625] opened 2018-07-23 19:25 UTC
@TobiasSekan commented on [Mon Jul 23 2018](https://github.com/dotnet/docs.de-de/issues/92)

Hello,
Please add possible locations (paths) of the **global.json**

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a94c335b-0b65-96cc-1c25-65777fbe4bb5
* Version Independent ID: 6d80613f-42dc-35d7-aeff-3187a36dbbca
* Content: [Global.json-Referenz](https://docs.microsoft.com/de-de/dotnet/core/tools/global-json)
* Content Source: [docs/core/tools/global-json.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/tools/global-json.md)
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment] 2018-07-30 18:34
I'm closing this one by design. The topic already covers that by saying: ".NET Core SDK looks for a global.json file in the current working directory (which isn't necessarily the same as the project directory) or one of its parent directories."

Basically, the global.json file can be anywhere on the machine. The SDK will search for a file in the current directory and if it doesn't find one, it will traverse back the folder structure trying to find one in its parent folders.

@TobiasSekan please let me know if that doesn't answer your issue.

**Closed by mairaw** 2018-07-30 18:34 UTC
Labels: Area - .NET Core Guide, by-design

**Comment by TobiasSekan** [comment] 2018-07-31 05:01
Hello,
yes i understand

(The main task behind the question was, if there a central location for the global.json like %APPDATA%, %LOCALAPPDATA%, %USERPROFILE% etc.)

**Comment by mairaw** [comment] 2018-07-31 09:30
No, there isn't @TobiasSekan.
