### ISSUE TITLE
Generated anchor links for the same titles with different capitalization

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11560] opened 2019-03-29 14:23 UTC
Hi team, 
I'm moving this issue from here: https://github.com/dotnet/docs.cs-cz/issues/13 
The user is reporting an error in the anchor links generation which replicates in the localized versions

> @lemichael  commented:
> Hello! There is a small issue with generated anchor links in the documentation when two sections have the same title which differs only in capitalization. For instance, << The "mm" custom format specifier >> and << The "MM" custom format specifier >> are two distinct sections but both have the same anchor #the-mm-customer-format-specifier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dda93f14-f1b5-fde6-e441-302cdac261ab
* Version Independent ID: 96abc7c4-3719-82da-e271-881d62f0640f
* Content: [Custom Date and Time Format Strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-ffffff-custom-format-specifier)
* Content Source: [docs/standard/base-types/custom-date-and-time-format-strings.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/custom-date-and-time-format-strings.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment] 2019-03-29 22:55
Actually, this is a localization issue @CeciAc. I've assigned this issue to @JasonCard.

The English content is capable of differentiating the two:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-mm-custom-format-specifier
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-mm-custom-format-specifier-1

But that is not happening for loc.

**Comment by JasonCard** [comment] 2019-03-30 01:01
Hi @lemichael @mairaw @CeciAc 

Thank you for reporting this issue and bringing to our attention. 
We understand the issue and why it only occurs for localized articles. Since we need to translate the headers, localized articles have different process from English to make the anchor links to work. It is not a simple fix and would take some developer time to resolve this issue.
However, it seems that this issue is very rare and probably only happens for a few anchor links in these two articles:
[https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
[https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
It also seems that this issue will not cause so much inconvenience to our users, as they will simply need to scroll down to the correct section.
Considering above reasons, we have decided to not fix this issue at this time. 
We may revisit this issue if we receive more similar feedback in the future.

We truly appreciate your contribution to our articles and hope you will continue to report issues you may find in the future.

Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment] 2019-03-30 01:03
@mairaw Although, this issue is assigned to me, I do not see the option to close it. Could you please help to close this issue?

**Comment by mairaw** [comment] 2019-03-30 01:20
Reopening. We could potentially use custom anchors in this case, no @JasonCard?

**Comment by JasonCard** [comment] 2019-04-01 17:51
@mairaw Thank you for your suggestion to use custom anchors. Yes, I confirmed with the [example](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs156#simpleSelf) you sent me that customized anchors does work for localized articles like [this example in [Czech](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs?tabs=vs156#simpleSelf). So if you could please help to add custom anchors to the headers with only difference in capitalization, they will be fixed in the localized articles:
[https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)  
[https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings)

**Comment by mairaw** [comment] 2019-04-01 20:54
Thanks for confirming @JasonCard. We just merged the change to master.

**Closed** 2019-04-01 20:53 UTC
Labels: :books: Area - .NET Guide, P2, Source - Docs.ms, loc

**Comment by JasonCard** [comment] 2019-04-03 22:55
Hi @lemichael, 
Thanks to help from @mairaw, I've confirmed this issue is now fixed for cs-cz. 
[https://docs.microsoft.com/cs-cz/dotnet/standard/base-types/custom-date-and-time-format-strings#FF_Specifier](https://docs.microsoft.com/cs-cz/dotnet/standard/base-types/custom-date-and-time-format-strings#FF_Specifier)
It will also be fixed for all languages. 
Thank you again for reporting this issue.

Kind regards,
Microsoft DOCS International Team
