### ISSUE TITLE
Flag missing from detailed install command

### ISSUE THREAD

**Issue by CygnusRoboticus** [dotnet/docs#16164] opened 2019-12-08 20:19 UTC
```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor microsoft.asc.gpg
```
Needs an output flag.
```
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o microsoft.asc.gpg
```

EDIT: Appears to be the case for [18.04](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md) and [16.04](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1604.md) as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172f0b88-61f2-d631-478f-e88af9be1f7d
* Version Independent ID: c610685f-57a2-048d-8dfa-146e19943434
* Content: [Install .NET Core on Ubuntu 19.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1904.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1904.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment] 2019-12-09 18:07
Similar to #16160

**Comment by CygnusRoboticus** [comment] 2019-12-09 18:54
Same issue different page, looks like this issue is the dupe.

**Comment by Thraka** [comment] 2019-12-09 19:38
Thanks I'll get this fixed

**Comment by Thraka** [comment] 2019-12-09 19:38
Duplicate of #16160

**Closed by Thraka** 2019-12-09 19:38 UTC
Labels: :books: Area - .NET Core Guide, doc-bug
