### ISSUE TITLE
RE: Item 8

### ISSUE THREAD

**Issue by thomb1** [dotnet/docs#8800] opened 2018-11-01 15:42 UTC
Section 8 describes the usage and reasons for first and second parameters. But it does not describe CharSet, ExactSpelling or CallingConvention

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20ab9743-9e38-281a-0f98-23200e261664
* Version Independent ID: 9886fc89-6701-e01c-f1cc-ffe77b391b91
* Content: [Walkthrough: Calling Windows APIs (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/com-interop/walkthrough-calling-windows-apis)
* Content Source: [docs/visual-basic/programming-guide/com-interop/walkthrough-calling-windows-apis.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/programming-guide/com-interop/walkthrough-calling-windows-apis.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by rpetrusha** [comment] 2019-01-08 23:46
Thanks for submitting your comment, @thomb1. The documentation for CharSet, ExactSpelling, and CallingConvention can be found in the [DllImportAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute) documentation. 

For calls to standard Windows DLLs, there's rarely a need to set any field other than CharSet.Unicode, since the default values used with CharSet.Unicode are CallingConvention.StdCall and ExactSpelling.True (the compiler prepends a "W" to string function calls). (If the CharSet field isn't defined, the default is CharSet.Ansi.) 

Although it doesn't fully document the fields of the `DllImport` attribute, providing that additional detail would be beyond the scope of the walkthrough, Although it would be nice to revise it to provide slightly more detail, we don't have the resources to do that right now. If you feel comfortable improving the topic, please feel free to submit a pull request to us; details can be found in our [Contributor's Guide](https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md).

I'm going to close this issue as By Design.

**Closed by rpetrusha** 2019-01-08 23:46 UTC
Labels: :books: Area - Visual Basic Guide, Source - Docs.ms, by-design
