### ISSUE TITLE
From .Net Core 2.1 only

### ISSUE THREAD

**Issue by tomap** [dotnet/docs#7864] opened 2018-09-24 13:06 UTC
I find this method only in .Net Core 2.1, not in .Net 2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9f79fd3-a3da-c4d7-dd6c-3ecc04311156
* Version Independent ID: e00ecbf9-cbe3-4290-1c8d-199746589493
* Content: [Convert.TryFromBase64String(String, Span&lt;Byte&gt;, Int32) Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.convert.tryfrombase64string?view=netcore-2.1)
* Content Source: [xml/System/Convert.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Convert.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-09-24 20:41
Thanks for your feedback @tomap. I'll have to investigate this and get back to you.

**Comment by mairaw** [comment] 2018-11-25 23:19
You're right @tomap. I could double check this at https://apisof.net/catalog/System.Convert.TryFromBase64String(String,Span%3CByte%3E,Int32) 

@terrajobst can I get the version of the 2.0 ref assemblies that are being used for the API Catalog? It seems my version is not correct.

**Comment by mairaw** [comment] 2018-11-27 02:49
I double checked with the path you sent today re. 2.2 @terrajobst and my assemblies match. Looking at the 2.0 assembly with ildasm I don't see that API in there.

Tagging @dend and @joelmartinez since mdoc automatically adds this API and others in the 2.0 index:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/FrameworksIndex/netcore-2.0.xml

**Comment by joelmartinez** [comment] 2018-11-27 22:00
@mairaw just wanted to chime in that this is under investigation … have confirmed that the binaries being used for 2.0 are in fact reporting that this method is not there. So there's some other reason that it's being included in this list. Will let you know when I find/fix the reason

**Comment by mairaw** [comment] 2018-11-27 22:06
Thanks for the update @joelmartinez!

**Comment by joelmartinez** [comment] 2018-12-11 14:52
Just to close the loop here, this issue was resolved here: https://github.com/mono/api-doc-tools/issues/357

Pending deployment/CI implementation :)

**Comment by mairaw** [comment] 2018-12-17 19:21
The latest CI run seems to have fixed that 🎆 closing this one!

**Closed by mairaw** 2018-12-17 19:21 UTC
Labels: :books: Area - API Reference, :file_folder: Repo - dotnet-api-docs, :mag: Under Investigation, P1, doc-bug, external, triaged
