### ISSUE TITLE
Document LinkBase

### ISSUE THREAD

**Issue by Styxxy** [dotnet/docs#7191] opened 2018-08-22 12:40 UTC
Maybe also document the new LinkBase?
See for discussion: https://github.com/dotnet/sdk/pull/1246 .

This feature is available (according the above link) since dotnet 2.0.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb4428fc-215c-78e1-5ff0-fe73f7a08260
* Version Independent ID: 6741b1de-38a4-fbb1-d79d-acc47d549a2d
* Content: [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj)
* Content Source: [docs/core/tools/csproj.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md)
* Product: **dotnet-core**
* GitHub Login: @blackdwarf
* Microsoft Alias: **mairaw**

**Comment by Styxxy** [comment] 2018-08-22 12:40
Possible duplicate with #2642 .

**Comment by mairaw** [comment] 2018-10-04 06:34
It is a duplicate of #2642.

**Closed by mairaw** 2018-10-04 06:34 UTC
Labels: :books: Area - .NET Core Guide, P2, Source - Docs.ms, doc-idea, duplicate, triaged
