### ISSUE TITLE
"When you pass a value type by reference" miss information

### ISSUE THREAD

**Issue by MutalibGozalov** [dotnet/docs#41099] opened 2024-05-29 11:39 UTC
### Type of issue

Missing information

### Description

**Original docs say**
When you pass a value type by reference:
- If the method assigns the parameter to refer to a different object, those changes **aren't** visible from the caller.

But when U pass either reference type or value type by reference (i.e argument with ref) and assign another instance to it, it will change the original passed variable and caller will see those changes.

In the ModifyString() method below i've assigned the struct parameter to a different object as docs say and then at the caller method logged it to console to see if changes are visible from the caller:
```
internal class Program
{
    private static async Task Main(string[] args)
    {
        StringHolder stringHolder = new("Initial value");
        Console.WriteLine($"stringHolder: {stringHolder}\n");

        ModifyString(ref stringHolder); // Passsing valueType by reference

        Console.WriteLine($"stringHolder: {stringHolder}\n");
    }

    private static void ModifyString(ref StringHolder stringHolder)
    {// assign the parameter to refer to a different object
        stringHolder = new("new instance value");
    }
}


struct StringHolder
{
    public StringHolder(string value)
    {
        Value = value;
    }
    public string Value { get; set; }

    public override string ToString()
    {
        return Value;
    }
}

//Output
stringHolder: Initial value

stringHolder: new instance value
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#ref-parameter-modifier

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/method-parameters.md

### Document Version Independent Id

7241f712-8d73-b5e0-37c0-5f05c92412c6

### Article author

@BillWagner

### Metadata

* ID: b8dd92fe-5053-1bc6-1c8f-cf9f88635cb5 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment] 2024-05-29 13:42
closing as a duplicate of #41087

**Closed by BillWagner** 2024-05-29 13:42 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/svc, lang-reference/subsvc
