### ISSUE TITLE
Broken links on the "Constant Interpolated Strings" page

### ISSUE THREAD

**Issue by vadim-96** [dotnet/docs#28121] opened 2022-02-08 11:32 UTC
Some of these links on the page don't work (404 error):

<img width="840" alt="Screenshot 2022-02-08 142849" src="https://user-images.githubusercontent.com/41098503/152978745-be964861-071e-429c-95ea-e019181f7a25.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a84dfb2-7abe-afd7-b017-abbaf2ef6646
* Version Independent ID: c4f6a4e8-6567-b74a-9c49-b2023f220f49
* Content: [Constant interpolated strings - C# 10.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/constant_interpolated_strings#feedback)
* Content Source: [proposals/csharp-10.0/constant_interpolated_strings.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/constant_interpolated_strings.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-02-08 17:00
This is a duplicate of the third task in #27789


I'll close as a duplicate. (This will be addressed this month).

**Closed by BillWagner** 2022-02-08 17:00 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-csharp/prod, csharp-spec/tech
