### ISSUE TITLE
cs1061

### ISSUE THREAD

**Issue by Sushmitapoojar** [dotnet/docs#38857] opened 2023-12-22 03:17 UTC
**Issue description**

**Target framework**

- [ ] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by gewarren** [comment] 2023-12-27 21:39
Closing as dupe of #38860

**Closed by gewarren** 2023-12-27 21:39 UTC
Labels: :watch: Not Triaged, Pri3
