### ISSUE TITLE
[Feature] Document the new `dotnet store` command 

### ISSUE THREAD

**Issue by BillWagner** [dotnet/docs#2725] opened 2017-07-23 17:56 UTC
The CLI added the dotnet-store command. This must document the command, and its options.

**Comment by GuardRex** [comment] 2017-07-24 14:37
@BillWagner @mairaw Work for this one is on https://github.com/dotnet/docs/pull/2496

**Comment by mairaw** [comment] 2017-07-29 00:42
Closing this one since it's a duplicate of #2139

**Closed by mairaw** 2017-07-29 00:42 UTC
Labels: Area - .NET Core Guide
