### ISSUE TITLE
Task.Delay throws an exception when the token is cancelled, so your example is incorrect

### ISSUE THREAD

**Issue by korggy** [dotnet/docs#33105] opened 2022-12-19 19:03 UTC
In the source code example for GracePeriodManagerService, the line following the loop within ExecuteAsync will never be called because Task.Delay throws an exception when stoppingToken is cancelled. The proper way to exit that loop is by surrounding the while loop with a try/catch.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 0707865f-9db7-0d71-42a5-bc1a1e89680a
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by erjain** [comment] 2023-01-04 08:40
Duplicate of #19072

**Closed** 2023-03-02 18:44 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-architecture/prod, microservices/tech, in-pr
