### ISSUE TITLE
.NET for imx28 env

### ISSUE THREAD

**Issue by heautio** [dotnet/docs#18055] opened 2020-04-24 10:23 UTC
I'm facing segmentation fault when manually installing .Net Core 3.1.3 to openWrt linux running at imx28 env.

My development env is Ubuntu 18.04.3 LTS and I'm able to cross compile other applications to the same target without any issues but not the Hello Word example from .Net. So I think my dev env is ok. 
I tried also the runtime binaries for linux-arm but the same issue is faced.

Here is the issue at target board:

root@openwrt:/usr/bin/dotnet/publish# echo $PATH
/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/dotnet/publish
root@openwrt:/usr/bin/dotnet/publish# echo $DOTNET_ROOT
/usr/bin/dotnet/publish
root@openwrt:/usr/bin/dotnet/publish# ./dotnet --info
Segmentation fault
root@openwrt:/usr/bin/dotnet/publish# LD_TRACE_LOADED_OBJECTS=1 /lib/ld-linux.so.3
./dotnet
libpthread.so.0 =&gt; /lib/libpthread.so.0 (0xb6ed0000)
libdl.so.2 =&gt; /lib/libdl.so.2 (0xb6ebd000)
libstdc++.so.6 =&gt; /usr/lib/libstdc++.so.6 (0xb6daa000)
libm.so.6 =&gt; /lib/libm.so.6 (0xb6ce6000)
libgcc_s.so.1 =&gt; /lib/libgcc_s.so.1 (0xb6cc9000)
libc.so.6 =&gt; /lib/libc.so.6 (0xb6b84000)
ld-linux-armhf.so.3 =&gt; /lib/ld-linux-armhf.so.3 (0xb6b52000)
/lib/ld-linux-armhf.so.3 =&gt; /lib/ld-linux.so.3 (0xb6efb000)
root@openwrt:/usr/bin/dotnet/publish#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70d62b80-ff88-7eea-e4cf-6d92d45e7e23
* Version Independent ID: 93efe3dd-e60b-e0f8-759d-24e2277f89ab
* Content: [Install .NET Core runtime on Windows, Linux, and macOS - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/runtime?pivots=os-linux#download-and-manually-install)
* Content Source: [docs/core/install/runtime.md](https://github.com/dotnet/docs/blob/master/docs/core/install/runtime.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment] 2020-04-29 20:16
Duplicate of #17959

**Closed by Thraka** 2020-04-29 20:16 UTC
Labels: :books: Area - .NET Core Guide, product-feedback
