### ISSUE TITLE
SA1000 and IDE0090 contradict each other

### ISSUE THREAD

**Issue by vslynko** [dotnet/docs#23311] opened 2021-03-15 09:34 UTC
From the example:
```
// csharp_style_implicit_object_creation_when_type_is_apparent = true
C c = new();
C c2 = new() { Field = 0 };
```

but SA1000 requires space after `new` keyword.
Which one should be given priority?

Suppressing one or another is not cool. It's about syntactic sugar, so the code should be more concise, not less.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9ae307d-3966-023f-b327-406e7d605436
* Version Independent ID: a55dc225-570c-97be-63c5-d27830efa653
* Content: [IDE0090: Simplify 'new' expression - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0090)
* Content Source: [docs/fundamentals/code-analysis/style-rules/ide0090.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/style-rules/ide0090.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Youssef1313** [comment] 2021-03-15 15:02
What version of StyleCopAnalyzers are you using? SA1000 was updated in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3187 to not require space for implicit object creation. The fix is in 1.2.0-beta.261 and later versions.

Duplicate of https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3214

**Comment by vslynko** [comment] 2021-03-15 15:25
latest stable 1.1.118

**Comment by Youssef1313** [comment] 2021-03-15 15:28
@vslynko This should get resolved if you upgraded to a beta version (latest beta is 1.2.0-beta.333).

**Comment by adegeo** [comment] 2021-05-05 20:29
Closing this as it seems resolved

**Closed by adegeo** 2021-05-05 20:29 UTC
Labels: Pri2, dotnet-fundamentals/prod, product-feedback

**Comment by DamianSuess** [comment] 2022-01-14 15:16
We're coming close to a year now and v1.2.x is still not released. The bug with the rule, SA1000, is breaking our standards.
