### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by axtens** [dotnet/docs#24751] opened 2021-06-21 06:06 UTC
The apostrophes are being improperly handled. The red text is distracting from what is executable statements and what is not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a7eed7e-92ba-239a-8162-591b666ad6ab
* Version Independent ID: 04d245fd-2a6a-725d-9b86-8e50998afdc3
* Content: [Shared - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/shared)
* Content Source: [docs/visual-basic/language-reference/modifiers/shared.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/modifiers/shared.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by Youssef1313** [comment] 2021-06-21 06:45
Duplicate of https://github.com/dotnet/docs/issues/24120, https://github.com/dotnet/docs/issues/23848, and https://github.com/dotnet/docs/issues/23753. This is unfortunately a general site issue.

**Comment by BillWagner** [comment] 2021-06-21 13:56
ping @meganbradley for visibility.

Closing as duplicate.

**Closed by BillWagner** 2021-06-21 13:56 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-visualbasic/prod
