### ISSUE TITLE
Ubuntu 20.04 has been released

### ISSUE THREAD

**Issue by solrevdev** [dotnet/docs#18054] opened 2020-04-24 10:02 UTC
How soon after ubuntu releases are the packages ready and how soon after will the "Ubuntu 19.10 Package Manager - Install .NET Core" page be ready?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-package-manager-ubuntu-1910)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by jvandertil** [comment] 2020-04-24 12:42
Came here to check this yesterday, this is the PR that will add the docs: https://github.com/dotnet/docs/pull/17869

It looks like the packages are up on https://packages.microsoft.com/config/ubuntu/20.04/ so you could just replace 19.10 with 20.04 and I *think* it should work.

**Comment by Thraka** [comment] 2020-04-24 17:35
Pretty much :) it's just some minor URL changes. Oh and we found a minor bug in `wget` statement on the page, which that PR fixes.

**Comment by Thraka** [comment] 2020-04-24 17:36
Duplicate of #17638

**Closed by Thraka** 2020-04-24 17:36 UTC
Labels: :books: Area - .NET Core Guide, duplicate
