### ISSUE TITLE
Links to deb packages are broken

### ISSUE THREAD

**Issue by MikaelUmaN** [dotnet/docs#24719] opened 2021-06-17 11:44 UTC
https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb

This link doesn't seem to be working, 404 errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by abydal** [comment] 2021-06-17 13:41
I have 404s on other ubuntu packages as well.
```bash
#6 2.885 E: Failed to fetch https://packages.microsoft.com/ubuntu/16.04/mssql-server-2017/pool/main/m/mssql-server/mssql-server_14.0.3391.2-12_amd64.deb  404  Not Found
```

This dockerfile fails with the error above:

```dockerfile
FROM mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
USER root
# Install prerequistes since it is needed to get repo config for SQL server
RUN apt-get -y update && \
    apt-get install -yq curl apt-transport-https
# Get official Microsoft repository configuration
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list | tee /etc/apt/sources.list.d/mssql-server.list && \
    apt-get update --fix-missing && \
    # Install optional packages
    apt-get install -y mssql-server-fts && \
    # Cleanup the Dockerfile
    apt-get clean && \
    rm -rf /var/lib/apt/lists

# Run SQL Server process
CMD /opt/mssql/bin/sqlservr
```

**Comment by abydal** [comment] 2021-06-17 13:59
duplicate of #24711

**Comment by Youssef1313** [comment] 2021-06-17 14:21
This should have been fixed now per https://github.com/dotnet/core/issues/6381#issuecomment-863274298

**Comment by adegeo** [comment] 2021-06-17 15:42
duplicate of #24711

**Comment by adegeo** [comment] 2021-06-17 15:42
I believe the main discussion is at https://github.com/dotnet/sdk/issues/18304 hopefully it gets working 100% soon!

**Closed by adegeo** 2021-06-17 15:42 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
