### ISSUE TITLE
Null Forgiveness Operator not Explained

### ISSUE THREAD

**Issue by kateract** [dotnet/docs#13998] opened 2019-08-22 16:56 UTC
Under Examine Survey Results, the null forgiveness operator is used but not explained.  It is easy to miss the existence of the null forgiving operator if you use this document alone as a guide for using NRT, leading to issues where you have to use it (such as entity framework) and don't know about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Design with nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/nullable-reference-types#examine-survey-responses)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-09-03 21:15
THanks for writing this @kateract 

We agree! This issue is a duplicate of #13420 

Closing as a duplicate. (When fixing #13420, this article should link to that update).

**Closed by BillWagner** 2019-09-03 21:15 UTC
Labels: :books: Area - C# Guide, :checkered_flag: Release: .NET Core 3.0, P1, Source - Docs.ms, duplicate
