### ISSUE TITLE
Broken link of 101 LINQ Samples

### ISSUE THREAD

**Issue by ArvindRSingh** [dotnet/docs#16470] opened 2019-12-31 10:01 UTC
101 LINQ Samples refers to non-existing page https://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e7bc95-4062-e6df-7475-21973ed1becc
* Version Independent ID: 571fd6fd-95b6-6fc9-d4df-9b44da6a01b4
* Content: [LINQ (Language Integrated Query)](https://docs.microsoft.com/en-us/dotnet/standard/using-linq#feedback)
* Content Source: [docs/standard/using-linq.md](https://github.com/dotnet/docs/blob/master/docs/standard/using-linq.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @cartermp
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2019-12-31 10:59
Duplicate of #13745

**Comment by gewarren** [comment] 2019-12-31 20:13
Thanks for reporting this @ArvindRSingh. I'll close this as a dupe of the issue that Youssef mentioned.

**Closed by gewarren** 2019-12-31 20:13 UTC
Labels: :books: Area - .NET Guide, duplicate
