### ISSUE TITLE
Debian file missing for Ubuntu 21.10

### ISSUE THREAD

**Issue by jmkni** [dotnet/docs#27024] opened 2021-11-10 21:21 UTC
Hi folks, this page suggests using wget to pull down **https://packages.microsoft.com/config/ubuntu/21.10/packages-microsoft-prod.deb**, however this file is missing. The 21.04 build works fine on 21.10 so not a bit deal, just a bit confusing. Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-11-10 21:34
Thank you for reporting this issue. The documentation is being updated. .NET packages haven't been released for Ubuntu 21.10 but are in progress. Using the 21.04 repository works just fine.

**Comment by adegeo** [comment] 2021-11-10 21:35
Duplicate of #26879

**Closed by adegeo** 2021-11-10 21:35 UTC
Labels: doc-bug, Pri1, dotnet/prod, dotnet-install/tech

**Comment by jmkni** [comment] 2021-11-10 22:17
Apologies didn't realize there was an open issue already, thanks

**Comment by adegeo** [comment] 2021-11-10 22:34
@jmkni No worries!
