### ISSUE TITLE
In Section "Other function members" in the code example one line can be changed.

### ISSUE THREAD

**Issue by akshays2112** [dotnet/docs#20801] opened 2020-09-28 09:05 UTC
------------
Main Issue
------------
In Section "Other function members" in the code example this line of code::

if (!object.Equals(a._items[i], b._items[i]))

Can be changed to the following I feel which might be better, given that the class has an indexer:

if (!object.Equals(a[i], b[i]))

------------------------
Consequence of Issue
------------------------
Since this works then at the compiler conceptual level the private variables can become "public" accessible between instances of the same class. So possible suggestion is to create a new compiler token accessibility name for a further level where instances cannot access private variables of each other. If you find this is alright logic on my part I will open a suggestion issue with the C# compiler team. In other words, to change class field values between instances of a class I would like to force them to talk to one and other for private class fields through public properties or methods to separate possible data corruption between instances of the class.

---------------------------------------------------------------------------------------------------------
Example of one instance object being able to change another instance objects private property.
---------------------------------------------------------------------------------------------------------
```csharp
namespace TestBreakingPrivateVariables
{
    public class TestClass1
    {
        string x = "abc";

        public void test(TestClass1 a)
        {
            a.x = "hjk";
        }
    }

    public class Test
    {
        public void test()
        {
            TestClass1 x = new TestClass1();
            TestClass1 y = new TestClass1();
            x.test(y);
        }
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3148b5e9-550e-67c9-eb13-907cb78f7fe7
* Version Independent ID: c723989f-2ff6-389d-dcb4-f55d97d14501
* Content: [The building blocks of C# programs](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/program-building-blocks)
* Content Source: [docs/csharp/tour-of-csharp/program-building-blocks.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tour-of-csharp/program-building-blocks.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-09-28 15:25
Thanks for writing this @akshays2112 There are a few points here.

First, on the code change in the sample. That's a change that's reasonable, but not necessary. We chose to compare the fields in this article because that is more typical in an override of `Equals`.

Next, on the point that this can introduce bugs. You are correct, and that's why other articles make recommendations for immutable types or other techniques to minimize it's concern.

Finally, to your point on a suggested change to the language. I think the changes that make it easier to create immutable types are a better solution to this concern.

I've added this to our backlog, and added the "up for grabs" label.

**Comment by akshays2112** [comment] 2020-09-28 15:29
Will do. Thx.

**Comment by akshays2112** [comment] 2020-11-18 04:54
@CyrusNajmabadi from the C# development team has closed out this issue when I later raised it there.

Please do not change the documentation as this is by design and intentionally meant to be this way.

**Comment by CyrusNajmabadi** [comment] 2020-11-18 05:47
Hey @BillWagner feel free to check in with me if you need any additional details :)

**Comment by BillWagner** [comment] 2020-11-18 14:51
Closing as no change is needed.

As noted in dotnet/roslyn#49390, this behavior is consistent with many object oriented languages, and is by design.

**Closed by BillWagner** 2020-11-18 14:51 UTC
Labels: :books: Area - C# Guide, :card_file_box: Technology - C# Get Started, P3, csharp-get-started/tech, dotnet-csharp/prod, up-for-grabs
