### ISSUE TITLE
Broken Additional Resources Links

### ISSUE THREAD

**Issue by bryanloeper** [dotnet/docs#19236] opened 2020-06-26 16:10 UTC
Both of the additional resources links return 404 from github. I tried digging around to find where those files should be now, but was unsuccessful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245ea389-75e9-1321-3be4-dc8d8e47a925
* Version Independent ID: 1db547e8-a0b0-cf44-dba4-b65786c576fe
* Content: [Testing ASP.NET Core services and web apps](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps#implementing-integration-and-functional-tests-for-each-microservice)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by Marusyk** [comment] 2020-08-03 21:23
Duplicate of #19245

**Closed** 2020-08-07 12:12 UTC
Labels: :book: guide - .NET Microservices, :books: Area - .NET Architecture Guide, P2, doc-bug
