### ISSUE TITLE
Missing "StreamWriter"

### ISSUE THREAD

**Issue by umor3** [dotnet/docs#23228] opened 2021-03-09 13:37 UTC
Greetings
just a litte thing missing under headline "Append text to an existing file".
`using StreamWriter file = new("WriteLines2.txt", append: true);`
should be 
`using StreamWriter file = new StreamWriter("WriteLines2.txt", append: true);`

Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09fbd113-dbad-8aef-4e74-151b0b7189ff
* Version Independent ID: 1e02473f-562b-aa40-756e-1c147cf41041
* Content: [How to write to a text file - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/file-system/how-to-write-to-a-text-file)
* Content Source: [docs/csharp/programming-guide/file-system/how-to-write-to-a-text-file.md](https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/file-system/how-to-write-to-a-text-file.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-03-09 14:55
Hi @umor3 

That line of code uses a new C# feature, ["target type new"](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new). The sample is correct.

I'll close this as by design.

**Closed by BillWagner** 2021-03-09 14:55 UTC
Labels: :watch: Not Triaged, Pri1, csharp-fundamentals/tech, dotnet-csharp/prod
