### ISSUE TITLE
Does adding projects using glob files really works?

### ISSUE THREAD

**Issue by thitemple** [dotnet/docs#6293] opened 2018-07-03 14:56 UTC
I'm trying to run `dotnet sln add src/**/*.fsproj` and I also tried `dotnet sln add src\**\*.fsproj` and `dotnet sln add **/*.fsproj` and none od those work. I always have an error such as `Could not find project or directory `**\*.fsproj``.
I'm on Win10 using the cli version .NET Command Line Tools (2.1.301)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b0701a-2043-4ac8-567a-03c1e35161b2
* Version Independent ID: 60d50636-8086-8d92-9ccc-60b7cecd714a
* Content: [dotnet sln command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
* Content Source: [docs/core/tools/dotnet-sln.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-sln.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by BlythMeister** [comment] 2018-07-16 14:09
Globbing is only supported on linux/unix according to the page as of 2018-07-16

**Comment by mairaw** [comment] 2018-07-16 18:33
I think that's still the case. @KathleenDollard @livarcocc @dsplaisted can one of you confirm? If so, are there any plans to support globbing pattern in the future?

**Comment by BlythMeister** [comment] 2018-07-16 18:47
I tested on windows with 2.1 and confirm it doesn't work.
I've not tested on Linux/Unix to prove its not a bug

**Comment by dsplaisted** [comment] 2018-07-16 18:52
If it works on Unix it's probably because the shell is expanding the glob before it gets to the CLI.

Supporting globs here would be a good idea.  I've filed https://github.com/dotnet/cli/issues/9670

**Comment by mairaw** [comment] 2018-07-16 19:49
Thanks @dsplaisted. Closing the doc issue then.

**Closed by mairaw** 2018-07-16 19:49 UTC
Labels: Area - .NET Core Guide, Source - Docs.ms, product-question
