### ISSUE TITLE
Changing to 20.04 leads to "package not found"

### ISSUE THREAD

**Issue by Biep** [dotnet/docs#18226] opened 2020-05-02 15:23 UTC
Running this, with all the 19.10s changed to 20.04s, doesn't add any dotnet packages to apt.  When leaving the 19.10, it leads to the unmet dependency errors described in the feedback named "this does not work".  So no solution, it seems..

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b5cbe58d-ad05-60fd-47d7-0d9ccfeecde4
* Version Independent ID: c9773e9b-dbc1-cb7b-b303-287cf8bd354c
* Content: [Install .NET Core on Ubuntu 19.10 package manager - .NET Core](https://docs.microsoft.com/nl-nl/dotnet/core/install/linux-package-manager-ubuntu-1910#troubleshoot-the-package-manager)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1910.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1910.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by svick** [comment] 2020-05-02 16:54
See https://github.com/dotnet/core/issues/4360. There are no official packages for 20.04 yet, though if you want, you can try the workarounds mentioned in that issue.

**Comment by Mizux** [comment] 2020-05-04 09:55
duplicate of #17638 -_-

**Comment by Thraka** [comment] 2020-05-04 17:10
Duplicate of #17638

**Closed by Thraka** 2020-05-04 17:10 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged
