### ISSUE TITLE
href parameter can also be used in <see> to allow click through to external URL, but it's not documented.

### ISSUE THREAD

**Issue by jameslear** [dotnet/docs#22839] opened 2021-02-14 23:47 UTC
It appears that "href" can also be used as a parameter in addition to "cref".  This will allow one to click through to the external link in IntelliSense.  However, it is not described in the documentation.
Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c9f2f59-0dec-c531-b19a-a2109ea0f973
* Version Independent ID: 74c6022c-8661-216e-4f48-e5f08f432f85
* Content: [&lt;see&gt; - C# programming guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/see)
* Content Source: [docs/csharp/programming-guide/xmldoc/see.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/xmldoc/see.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-02-15 08:51
This was supported by the IDE in https://github.com/dotnet/roslyn/pull/35667.

It's not fully supported by the compiler. For example, there is a `SyntaxKind.XmlCrefAttribute`, but no `SyntaxKind.XmlHrefAttribute`.

@jaredpar Does that limits its usage in any way? Should it be documented or not?

**Comment by BillWagner** [comment] 2021-02-16 15:12
closing as a duplicate of #19284, which was addressed in #19569

**Closed by BillWagner** 2021-02-16 15:12 UTC
Labels: :watch: Not Triaged, Pri2, csharp-fundamentals/tech, dotnet-csharp/prod
