### ISSUE TITLE
"Supported" is confusing Bing

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/docs#35840] opened 2023-06-15 17:49 UTC
I asked Bing for [supported versions of .net framework](https://www.bing.com/search?q=supported+versions+of+.net+framework&cvid=34b6f9fe75054733bf798779f7fe4a8a&aqs=edge.0.0j69i57j0l7.6137j0j4&FORM=ANAB01&PC=U531) and got this back:

![image](https://github.com/dotnet/docs/assets/1784452/b0802f5b-e5f5-4b85-8f18-8fdb1c09f9e2)

It took me a minute to figure out what was happening, but I believe it is confused because out-of-support Windows versions are listed as "Supported", as there are two different meanings in play. Windows supports certain versions of .NET Framework, but those versions of Windows are out of support. 

Maybe the OSes should be separated into supported and unsupported OS sections and "Supported editions" could be simplified to "Editions"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8afd1f96-b008-8b2e-bf3e-89d91f8cca5e
* Version Independent ID: 2010bd32-59f6-823c-f193-27439e12798d
* Content: [.NET Framework system requirements - .NET Framework](https://learn.microsoft.com/en-us/dotnet/framework/get-started/system-requirements)
* Content Source: [docs/framework/get-started/system-requirements.md](https://github.com/dotnet/docs/blob/main/docs/framework/get-started/system-requirements.md)
* Product: **dotnet-framework**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---
[Associated WorkItem - 143916](https://dev.azure.com/msft-skilling/Content/_workitems/edit/143916)

**Comment by IEvangelist** [comment] 2023-06-19 12:12
This isn't something that we have direct control over, while I agree it's not ideal the source material that is cited does correctly describe the support details. I think we should close this is it's not a docs issue. Do you agree @gewarren?

**Comment by gewarren** [comment] 2023-06-19 17:46
That is kind of interesting. I wonder if we should use the word "compatible" instead of "supported"? Or perhaps split it into supported and out-of-support versions, like @mairaw did here: https://github.com/dotnet/core/blob/main/os-lifecycle-policy.md?WT.mc_id=dotnet-35129-website.

**Closed** 2023-08-11 22:04 UTC
Labels: doc-enhancement, Pri1, dotnet-framework/prod, in-pr, :pushpin: seQUESTered

**Comment by mdell-seradex** [comment] 2024-03-08 18:22
I realize that this is closed, but I disagree with the change as it was done.
The issue is that this makes it seem like .NET Framework 4.8 cannot be installed on Windows versions that are no longer in Mainstream support.
If a link to the migration guide article was included on that page with a note that somehow mentions that it lists the operating systems where it can be installed, that would be better.
