### ISSUE TITLE
Add content for .NET Standard 2.1

### ISSUE THREAD

**Issue by richlander** [dotnet/docs#9221] opened 2018-11-24 22:42 UTC
We should have the first batch of content in place by the time .NET Core 3.0 Preview 1 is released. Right?

/cc @terrajobst 

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de130a75-fed2-0567-6e3d-07a384900eec
* Version Independent ID: a2993c26-93f8-7281-d6ca-5fcc899e95f3
* Content: [What's new in the .NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/whats-new/whats-new-in-dotnet-standard?tabs=csharp)
* Content Source: [docs/standard/whats-new/whats-new-in-dotnet-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/whats-new/whats-new-in-dotnet-standard.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by terrajobst** [comment] 2018-11-25 04:09
There isn’t going to be a release of .NET Standard 2.1 in preview 1 — all bits are going out first time in Preview 2.

**Comment by mairaw** [comment] 2018-11-27 02:35
Moving this to the backlog since we don't have what to document at this moment.

**Comment by mairaw** [comment] 2020-01-16 20:54
Closed a duplicate of this work item and removing the blocked label. 

Related blog post: https://devblogs.microsoft.com/dotnet/announcing-net-standard-2-1/

**Closed** 2021-01-25 14:44 UTC
Labels: :books: Area - .NET Guide, :checkered_flag: Release: .NET Core 3.0, P1, Pri2, doc-idea, dotnet-standard/tech, dotnet/prod, won't fix
