### ISSUE TITLE
CS0029 - @ref causes compilation error see #17416

### ISSUE THREAD

**Issue by johnyjp** [dotnet/docs#35449] opened 2023-05-23 06:52 UTC
https://github.com/dotnet/AspNetCore.Docs/issues/17416

Removing the @ref makes it compile. eg
`<AgentFullRecord @ref="agentForm" Agent="@selectedAgent" OnChanged="OnChanged" />`

does not compile, but
`<AgentFullRecord Agent="@selectedAgent" OnChanged="OnChanged" />`

does

I have created an issue from this page as it referes to @ref, I cant find a more relavent one. its an easy issue to recreate. Read #17416. Instructions say to add comments to an existing issue even if its closed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60c195c0-99f6-64f5-66a3-4e69109dc8ee
* Version Independent ID: 24368808-4b90-f75a-e887-eb72a1c85f5b
* Content: [Build reusable UI components with Blazor](https://learn.microsoft.com/en-us/dotnet/architecture/blazor-for-web-forms-developers/components)
* Content Source: [docs/architecture/blazor-for-web-forms-developers/components.md](https://github.com/dotnet/docs/blob/main/docs/architecture/blazor-for-web-forms-developers/components.md)
* Product: **dotnet-architecture**
* Technology: **blazor**
* GitHub Login: @danroth27
* Microsoft Alias: **daroth**

**Comment by giuseppe-terrasi** [comment] 2023-05-24 08:53
As a temporary solution, SDK 7.0.202 can be used

**Comment by Chandradev819** [comment] 2023-05-24 09:31
Yes, I also downgraded to lower "version": "7.0.203" for work around.

**Comment by danroth27** [comment] 2023-05-24 23:41
Hi folks. We believe this is a duplicate of https://github.com/dotnet/razor/issues/8718, which we are working to get addressed.

**Closed by danroth27** 2023-05-24 23:41 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-architecture/prod, blazor/tech

**Comment by mrs99mrs99** [comment] 2024-01-03 22:46
I'm facing the same issue.  Why is this closed? 

Removing the @ref makes it compile. eg
<AgentFullRecord @ref="agentForm" Agent="@selectedAgent" OnChanged="OnChanged" />

does not compile, but
<AgentFullRecord Agent="@selectedAgent" OnChanged="OnChanged" />

does


WHAT'S THE WORKAROUND?

**Comment by danroth27** [comment] 2024-01-04 01:24
@mrs99mrs99 I'm not able to reproduce this issue with VS 17.8.3. Can you create a small repo with a project that reproduces the problem you are seeing and share it with us?

**Comment by johnyjp** [comment] 2024-01-04 09:12
To confirm, this now works for me (as of June).

**Comment by mrs99mrs99** [comment] 2024-01-04 14:41
I have removed all irrelevant code from my solution and have attached it as a zip.   The @ref is located in Teams, Pages, Organization, CreateOrganizationComponent.razor file.  Any help would be greatly appreciated.
[Teams.zip](https://github.com/dotnet/docs/files/13831219/Teams.zip)

**Comment by danroth27** [comment] 2024-01-05 01:04
@mrs99mrs99 Thanks for sharing your project. When I build your project, I get the error: "The type name 'PopUp' does not exist in the type 'Teams'". The project defines both the global namespace `Teams` and a `Teams` component type. The *_Imports.razor* has an `@using` directive for `global::Teams` to differentiate between the two, but it looks like this isn't being handled correctly by the Razor compiler. If I rename *Teams.razor* to something else and change the `@using` directive to not be globally qualified, then the project compiles.

Since this appears to be a different issue than the original `@ref` issue discussed here, could you please open a new GitHub issue for this in the [dotnet/razor](https://github.com/dotnet/razor) repo? Also, instead of sharing the code as a zip file, it would help if you could share it as a GitHub repo.
