### ISSUE TITLE
Using TSL with default netTcpBinding

### ISSUE THREAD

**Issue by dushantha80** [dotnet/docs#10594] opened 2019-02-21 02:05 UTC
Hi,

With default netTcpBinding (Mode=Transport + clientCredentialType= Windows + protectionLevel=EncryptAndSign) TLS used secure the transport channel? or something else used to encrypt the channel?

I found below link. I need to confirm this,

https://stackoverflow.com/questions/4187604/how-does-nettcpbindingread-windowsstreamsecuritybindingelement-encrypt-sign-me

If default netTcpBinding does not use TLS then, the only when it can be used for transport level security by using Certificate (Mode=Transport + clientCredentialType= Certificate + protectionLevel=EncryptAndSign)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 028a8be0-9ff5-f253-aa43-d02fc1c8e9be
* Version Independent ID: 75ce978f-aecd-5b60-be3f-54c78a6a71aa
* Content: [Transport Security Overview](https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/transport-security-overview)
* Content Source: [docs/framework/wcf/feature-details/transport-security-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wcf/feature-details/transport-security-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @Lxiamail
* Microsoft Alias: **wcfsrvt**

**Comment by gewarren** [comment] 2019-12-03 03:19
Dupe of #10592.

**Closed by gewarren** 2019-12-03 03:19 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WCF, duplicate
