### ISSUE TITLE
'dotnet new --install' is deprecated

### ISSUE THREAD

**Issue by dalumedic** [dotnet/docs#32195] opened 2022-11-04 16:38 UTC
Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.
For more information, run:
   dotnet new install -h

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment] 2022-12-14 22:30
Related to #32949

**Comment by adegeo** [comment] 2023-09-18 18:31
Duplicate of #32949

**Closed by adegeo** 2023-09-18 18:31 UTC
Labels: doc-bug, Pri2, dotnet-fundamentals/prod, okr-health
