### ISSUE TITLE
Ubuntu 20.04 incorrectly listed as no longer supported

### ISSUE THREAD

**Issue by binarica** [dotnet/docs#25413] opened 2021-07-31 03:58 UTC
The [table of supported Ubuntu versions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-) lists 20.04 as supported, along with previous LTS versions 18.04 and 16.04:

![image](https://user-images.githubusercontent.com/9634969/127727946-fc4a43c3-5a12-4776-b854-027915480820.png)

However, on the [section for the actual 20.04 version](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-) it's stated that it's no longer supported:
![image](https://user-images.githubusercontent.com/9634969/127727779-ad7858ac-66a9-41e2-bb5c-012808ab3328.png)

The right side navigation menu also lists 20.04 as unsupported:

![image](https://user-images.githubusercontent.com/9634969/127727914-fc9b1d53-8eff-4f15-83de-f32bf14ca1fa.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004-)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-08-01 02:50
Duplicate of #25382

**Comment by adegeo** [comment] 2021-08-01 02:51
This was fixed but publishing was lagging behind. I just force published to get this updated asap.

**Closed by adegeo** 2021-08-01 02:50 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
