### ISSUE TITLE
Add .NET Framework 4.8.1 

### ISSUE THREAD

**Issue by andrewlock** [dotnet/docs#30742] opened 2022-08-18 08:40 UTC
In the section [Detect .NET Framework 4.5 and later versions](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#minimum-version) the minimum **Release** REG_DWORD value required to identify a specific version of .NET Framework is listed. 

This table should should be updated to include the values for .NET Framework 4.8.1 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [Determine which .NET Framework versions are installed - .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/main/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2022-08-18 15:56
This will be addressed by #30619.

**Comment by gewarren** [comment] 2022-08-29 17:19
Closing as a duplicate of #30553.

**Closed by gewarren** 2022-08-29 17:19 UTC
Labels: doc-enhancement, Pri1, dotnet-framework/prod, dotnet-appcompat/tech
