### ISSUE TITLE
No Storyboard TargetProperty attached property and link from associated field goes to incorrect url

### ISSUE THREAD

**Issue by tonyhallett** [dotnet/docs#19869] opened 2020-08-06 15:44 UTC
There attached properties for Target and TargetName but not for TargetProperty.
From the [reference source](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Media/Animation/Storyboard.cs,153)

The associated field [Storyboard.TargetPropertyProperty Field](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.animation.storyboard.targetpropertyproperty?view=netcore-3.1) has the following incorrect link

> Identifies the [TargetProperty](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.animation.storyboard.targetproperty?view=netcore-3.1) **attached property**.

This links to Storyboard.TargetProperty **Field** - Identifies the Target attached property.

The link should point to the missing page.

- [x] .NET Core
- [x] .NET Framework
- [ ] .NET Standard

**Comment by tonyhallett** [comment] 2020-08-06 16:00
I assume that the generation process does not work as the attached property Member element MemberName would clash with the MemberName of the TargetProperty field.  

Noticed that this issue has already been [raised](https://github.com/mono/api-doc-tools/issues/426#issuecomment-615983532_)

**Comment by adegeo** [comment] 2020-08-10 19:20
Spot on @tonyhallett 

I'll close this issue as a duplicate of the other one.

**Comment by adegeo** [comment] 2020-08-10 19:21
Duplicate of mono/api-doc-tools#426

**Closed by adegeo** 2020-08-10 19:21 UTC
Labels: :watch: Not Triaged
