### ISSUE TITLE
Changing from the new version of Visual Studio .NET 6.0 back to .NET 5.0 version.

### ISSUE THREAD

**Issue by Andrea-Wafula** [dotnet/docs#30615] opened 2022-08-10 21:21 UTC
[Enter feedback here]
I was able to gain some access to the previous .NET 5.0 version tab by right-clicking the project and selecting Properties. The General Tab on the left side of the screen brings you to a couple of more options such as the Output Type, The Target OS, The Target Framework, The Startup Object, and the Assembly Time. Changing the .NET version from version 6.0 to 5.0 does not really bring any changes to the program, nor does it change the format of the Program File. It still remains the same with a link at the top of the screen i.e. "// See **_https://aka.ms/new-console-template_** for more information". 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e23ae-0256-d8c1-4dca-d31fe21602a5
* Version Independent ID: 926db74c-be79-f7cd-a4e9-e156dafa6287
* Content: [C# console app template changes in .NET 6 - .NET](https://docs.microsoft.com/en-gb/dotnet/core/tutorials/top-level-templates)
* Content Source: [docs/core/tutorials/top-level-templates.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/top-level-templates.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gewarren** [comment] 2022-08-11 20:52
@Andrea-Wafula Are you trying to convert a file from the top-level template to the old style?

**Comment by Andrea-Wafula** [comment] 2022-08-23 23:37
@gewarren Yes I was but not anymore. I was commenting on how the new .NET 6.0 version of the C# Console App template still remains the same even after manually changing it in the Properties tab.

**Comment by gewarren** [comment] 2022-08-29 16:48
I believe that is by design, so I'm going to close this issue.

**Closed by gewarren** 2022-08-29 16:48 UTC
Labels: needs-more-info, Pri1, dotnet-fundamentals/prod

**Comment by ConnieBlue221** [comment] 2022-09-07 02:15
#29442
