### ISSUE TITLE
inconsistent use of white-space/white space

### ISSUE THREAD

**Issue by wstaelens** [dotnet/docs#4439] opened 2018-02-20 08:20 UTC
https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options

white-space characters
white space character
**white-space vs white space (" " vs "-")**

inconsistent use of white-space/white space ?

This work can be addressed in individual PRs, as follows:

- [x] docs/core
- [x] docs/csharp
- [x] docs/framework 
- [x] docs/fsharp
- [x] docs/standard
- [x] docs/visual-basic 
- [x] samples (see the [list](https://gist.github.com/rpetrusha/02afff2520aeeba03552f90a7152681b) for C#, VB, and C++)
- [ ] dotnet-api-docs (see the [list](https://gist.github.com/rpetrusha/02afff2520aeeba03552f90a7152681b))

**Comment by mairaw** [comment] 2018-02-20 18:27
HI @wstaelens. The only difference I'm seeing is when white space is used as a noun (two words) vs. an adjective (hyphened), so I believe this is by design. @rpetrusha can you take a look?

**Comment by wstaelens** [comment] 2018-02-20 18:48
OH ok. Not native English speaker. Thought this was a mistake. My bad.

**Comment by rpetrusha** [comment] 2018-02-20 20:10
Thanks for pointing this out, @wstaelens. The general convention is that the noun should appear as **white space** and the adjective should appear as **white-space** (with a hyphen).  For the most part, the documentation is consistent, although over all the occurrences of this phrase in our documentation set, there are also numerous inconsistencies. 
We've classified this as an up-for-grabs backlog item. If you (or anyone else) is interested in doing some of the work to correct the inconsistencies, please let us know, and we'll provide some guidance to help you begin the work.

**Comment by lucasnobredev** [comment] 2018-03-03 21:21
@rpetrusha I'd like to correct these inconsistencies. Can you help me to begin the work?

**Comment by rpetrusha** [comment] 2018-03-06 22:06
Thanks for volunteering, @lucasnobredev. We really appreciate your help.

Two immediate questions come to mind: 
- How to identify what should be fixed.
- How to break down the work into manageable units.

The correct usage is "white space" for a noun, "white-space" for an adjective. I'm sure that there are cases in the documentation of "white space" used  an adjective and "white-space used as a noun. But identifying and fixing those is likely to be more trouble than it's worth -- it requires a review of *all* the occurrences of the two phrases, most of which will be correct. In looking at the [Regular Expression Options](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options) topic that @wstaelens identified, usage is correct except for the word "whitespace". So that suggests that searching for "whitespace" and replacing it with either "white space" or "white-space" will have the biggest impact.

In terms of dividing the work and submitting PRs, it's best to avoid enormous PRs. To do this:
- Submit a separate PR for each subdirectory of the dotnet/docs/docs (e.g., core, csharp, framework, etc.). If that still seems to large, break down each .NET directory into a set of subdirectories and submit the PR for those.
- Code comments in code in the dotnet/docs/samples directory may contain the word "whitespace". You can correct those on a subdirectory-by-subdirectory basis. 
- The dotnet/docs/xml directory contains the API reference documentation. It is extensive. Probably the best approach is to do the Microsoft* namespaces in one PR, the Mono* in another, and then to divide the System* namespaces into a number of arbitrary groups.

Of course, let me know if you have any questions.

**Comment by rpetrusha** [comment] 2018-03-06 22:11
One additional detail that I forgot to mention, @lucasnobredev. One you get started and decide exactly how to approach splitting up the PRs, we can add a task item for each PR that will be submitted to the issue description. That will allow us to see exactly what's been done and what work remains to be done.

**Comment by lucasnobredev** [comment] 2018-03-10 19:21
Thanks for the tips, @rpetrusha . I agree with your approach. I already 'forked' the project and I'm looking for these errors. I'll open first PR as soon as I can.

**Comment by lucasnobredev** [comment] 2018-03-11 05:26
I opened a [PR](https://github.com/dotnet/docs/pull/4605) with fixes to docs/standard section. 

After that, I'll do in alphabetical order (core, csharp, framework, etc.).

I just have one question: 
We have in [this page](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) a "whitespace". I wasn't sure if I should fix it or not. Can you help me?

**Comment by rpetrusha** [comment] 2018-03-21 18:04
Sorry, @lucasnobredev, that I didn't respond earlier to your question.  The "whitespace" and its variations on the page are intended to indicate how to use "white space" as an identifier (a variable name, a type name, a parameter name) and so are necessarily one word. So those occurrences of "whitespace" are correct in their context.

**Comment by lucasnobredev** [comment] 2018-03-21 18:35
Very well. In next few days I'll open a new PR to continue our task.

**Comment by rpetrusha** [comment] 2018-03-21 19:44
That sounds good. We appreciate your doing this work, @lucasnobredev.

**Comment by lucasnobredev** [comment] 2018-04-16 04:49
Guys, just an update for what I did so far:

**Pull request opened and merged**
- docs/csharp 
- docs/standard

**There's not a whitespace word**
- docs/core

I'll review in this week _docs/framework_. If there's nothing, I'll see the next one and I'll update here too.

**Comment by lucasnobredev** [comment] 2018-07-10 05:51
Hello @rpetrusha @mairaw , I'm sorry for take so much longer to do this task. 
After 3 months, I'll review each docs/ again to be sure everything is ok.
For now, I opened a PR about docs/framework.

**Comment by lucasnobredev** [comment] 2018-07-11 01:10
Well, I looked again on docs/core and there is nothing there.

**Comment by lucasnobredev** [comment] 2018-07-11 19:54
@rpetrusha @mairaw , there is another section to review or can we finish this job?

**Comment by mairaw** [comment] 2018-07-11 22:07
We'll review and make sure that we check off that item if it's done now. Thanks @lucasnobredev!!

**Comment by rpetrusha** [comment] 2018-07-12 00:48
There are additional topics with "whitespace" instead of either "white space" or "white-space" in the dotnet/dotnet-api-docs and the dotnet/samples repos, @lucasnobredev. I've created a [gist](https://gist.github.com/rpetrusha/02afff2520aeeba03552f90a7152681b) that lists each occurrence.

**Comment by lucasnobredev** [comment] 2018-08-15 02:33
Hello @rpetrusha , is there another section to review or can we finish this job?

**Comment by lucasnobredev** [comment] 2018-10-30 06:36
Guys, I saw errors again in dotnet/docs. I'll looking for in dotnet-api-docs and samples.

**Closed** 2021-01-25 14:33 UTC
Labels: :books: Area - .NET Guide, P2, Pri3, doc-enhancement, up-for-grabs, won't fix
