### ISSUE TITLE
4th bullet at "Add a class" topic

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9638] opened 2018-12-17 20:28 UTC
@aylingumus  commented an hour ago — with docs.microsoft.com • 

There is need to add HelloWorld namespace as "using HelloWorld;" to second line to call the method of Class1.

It should be like this:
```
using System;
using HelloWorld;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Class1 c1 = new Class1();
            Console.WriteLine($"Hello World! {c1.ReturnMessage()}");
        }
    }
}
```

Best regards,
Aylin

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: 8cc2e9c2-f333-f6a1-064e-790d950b684c
* Version Independent ID: 25a4c9b9-2808-e296-df03-5837000dcbad
* Content: [C# ve Visual Studio Code kullanmaya başlama](https://docs.microsoft.com/tr-tr/dotnet/core/tutorials/with-visual-studio-code#debug)
* Content Source: [docs/core/tutorials/with-visual-studio-code.md](https://github.com/dotnet/docs.tr-tr/blob/live/docs/core/tutorials/with-visual-studio-code.md)
* Product: **dotnet-core**
* GitHub Login: @kendrahavens
* Microsoft Alias: **mairaw**

**Comment by kendrahavens** [comment] 2018-12-17 21:42
Since these classes share the same namespace you shouldn't need to add a using directive to Program.cs. It's good to note that the namespace in your Program.cs file is automatically set to the containing folder name. Meaning, if you started the tutorial in a folder not named "HelloWorld" then the copied Class.cs file won't have the same namespace as your Program.cs file. In that case, you would need a using directive. 

I'll leave the instructions as is for now. Let me know if there is an issue I'm not seeing or if there is a better way to make this distinction clear.

Thank you for taking the time to log this feedback!

**Comment by mairaw** [comment] 2018-12-17 23:19
Closing as by design then. @aylingumus please let us know if there is a step that is not clear.

**Closed by mairaw** 2018-12-17 23:19 UTC
Labels: :books: Area - .NET Core Guide, Source - Docs.ms, by-design
