### ISSUE TITLE
Mistake in the default value of VBA

### ISSUE THREAD

**Issue by Tucduk** [dotnet/docs#29216] opened 2022-04-29 13:13 UTC
Hy !
In this page, it's said that the default value is ByVal
![image](https://user-images.githubusercontent.com/38108647/165950129-da2ad2ba-f204-4f91-9cb7-da2d28a2aa3f.png)

But in fact, in VBA the default value is Byref, then it may need to be corrected to prevent mistake for VBA users... 
If you speak only about VB i don't know but maybe we could make an advertissment for VBA users.
As i see, it's look like the documentation of VB and VBA as been mixed.
Thanks for your consideration if this ticket is useful and sorry if it's not

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3085184c-671d-92b5-b596-3af0a848b7c8
* Version Independent ID: 4b8973b8-47df-64cd-98ff-5b3ea17860cf
* Content: [ByVal - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/modifiers/byval#remarks)
* Content Source: [docs/visual-basic/language-reference/modifiers/byval.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/modifiers/byval.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment] 2022-11-28 16:05
I'll close this as by design.

This section is about Visual Basic, not VBA.

**Closed by BillWagner** 2022-11-28 16:05 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-visualbasic/prod
