### ISSUE TITLE
Links not rendering correctly in Exceptions section

### ISSUE THREAD

**Issue by svick** [dotnet/docs#2593] opened 2017-07-11 17:28 UTC
In the Exceptions section for [`Activator.CreateInstance(Type)`](https://docs.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=netframework-4.7#System_Activator_CreateInstance_System_Type_), normal Markdown links aren't rendering properly:

![](https://user-images.githubusercontent.com/287848/28081104-75f17844-666e-11e7-9ab9-cda5f1a7ebba.png)

[The source code](https://github.com/dotnet/docs/blob/7e76b6e/xml/System/Activator.xml#L318-L326) looks okay to me, so I think this is an issue with the tooling. This could be related to the fact that the problematic text is inside `<block subset="none" type="note"><para>` XML tags.

**Comment by mairaw** [comment] 2017-07-12 07:07
Thanks @svick. We had noticed that and had already opened an internal bug to track this issue: 1028877

**Comment by GuardRex** [comment] 2017-07-13 03:41
Duplicate of https://github.com/dotnet/docs/issues/1931

**Closed by GuardRex** 2017-07-13 03:41 UTC
Labels: Area - API Reference, external
