### ISSUE TITLE
Ubuntu 18.04 in WSL1, Unable to locate package dotnet-sdk-3.1

### ISSUE THREAD

**Issue by PhilipHassialis** [dotnet/docs#16098] opened 2019-12-04 11:15 UTC
Hello,

I have tried every path in this page, even the "Unable to locate package" commands (the last bunch of them, where you start by installing gpg). Unfortunately, when I try to "sudo apt-get install dotnet-sdk-3.1" I always get the following responses:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package dotnet-sdk-3.1
E: Couldn't find any package by glob 'dotnet-sdk-3.1'
E: Couldn't find any package by regex 'dotnet-sdk-3.1'

Is .net core sdk 3.1 for Linux up or not? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f33bad-b152-c53b-1b0a-234c9a075bd7
* Version Independent ID: 565e7432-c4b3-a1c2-8ce3-c8c1a0d8ebe8
* Content: [Install .NET Core on Ubuntu 18.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1804#feedback)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1804.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1804.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by tomnuen** [comment] 2019-12-04 11:38
Yes. I also have similar issue.

**Comment by ogswr** [comment] 2019-12-04 11:46
Me, too, When will it be available? I'm thinking about whether to manually install it.

**Comment by roduman** [comment] 2019-12-04 11:53
When will version 3.1 be available?

**Comment by hdnebat** [comment] 2019-12-04 12:04
seems all Linux distributions don't have 3.1 yet

**Comment by hdnebat** [comment] 2019-12-04 12:18
sudo snap install dotnet-sdk --classic
is working

**Comment by mightyshazam** [comment] 2019-12-04 16:03
If you don't want to use the snap installation, you can also download the binaries and extract them to the proper directory.
``sudo tar -xvf dotnet-sdk-3.1.100-linux-x64.tar.gz -C /usr/share/dotnet/``

**Comment by Thraka** [comment] 2019-12-05 06:03
This should be available now. 

```bash
sudo apt update
apt search dotnet-sdk
```

And I see the 3.1 release is now available

```bash
$ apt search dotnet-sdk
Sorting... Done
Full Text Search... Done
dotnet-sdk-2.1/bionic 2.1.802-1 amd64
  Microsoft .NET Core SDK 2.1.802

dotnet-sdk-2.1.105/bionic 2.1.105-1 amd64
  Microsoft .NET Core SDK - 2.1.105

dotnet-sdk-2.1.200/bionic 2.1.200-1 amd64
  Microsoft .NET Core SDK - 2.1.200

dotnet-sdk-2.1.201/bionic 2.1.201-1 amd64
  Microsoft .NET Core SDK - 2.1.201

dotnet-sdk-2.1.202/bionic 2.1.202-1 amd64
  Microsoft .NET Core SDK - 2.1.202

dotnet-sdk-2.1.300-preview2-008533/bionic 2.1.300-preview2-008533-1 amd64
  Microsoft .NET Core SDK 2.1.300 - Preview

dotnet-sdk-2.1.300-rc1-008673/bionic 2.1.300-rc1-008673-1 amd64
  Microsoft .NET Core SDK 2.1.300 - rc1

dotnet-sdk-2.2/bionic 2.2.402-1 amd64
  Microsoft .NET Core SDK 2.2.402

dotnet-sdk-3.0/bionic 3.0.101-1 amd64 [upgradable from: 3.0.100-1]
  Microsoft .NET Core SDK 3.0.100

dotnet-sdk-3.1/bionic 3.1.100-1 amd64
  Microsoft .NET Core SDK 3.1.100
```

**Comment by Thraka** [comment] 2019-12-05 06:03
Duplicate of #16100

**Closed by Thraka** 2019-12-05 06:03 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged

**Comment by utsabshrestha** [comment] 2020-07-30 09:30
**The trick is to first let the package manager know that it should include packages from ‘packages.microsoft.com’:**

_wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb_
_sudo dpkg -i packages-microsoft-prod.deb_
_sudo apt-get update_
_apt search dotnet-sdk_

reference [from](https://bartwullems.blogspot.com/2019/12/install-net-core-31-sdk-on-ubuntu-1804.html)

**Comment by PabloFerreiraB** [comment] 2020-09-27 23:23
https://dev.to/solrevdev/install-net-core-on-ubuntu-20-04-lts-focal-fossa-53m9

**Comment by emaalouf** [comment] 2021-08-13 10:34
This saved my life! Thank you so much!
