### ISSUE TITLE
CustomTextMessageEncoderFactory Implementation Issue

### ISSUE THREAD

**Issue by shyamjiniranjan** [dotnet/docs#13452] opened 2019-07-18 07:07 UTC
As per below link
https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/custom-message-encoder-custom-text-encoder 
There is a class 
public class CustomTextMessageEncoder : MessageEncoder
{
}
but there is no more class MessageEncoder, so from where i will get this class declaration?

**Comment by Thraka** [comment] 2019-07-18 16:22
duplicate of #13454

**Closed** 2019-07-18 16:22 UTC
