### ISSUE TITLE
Clarify note re in parameter modifier benefits

### ISSUE THREAD

**Issue by david-john-wilson** [dotnet/docs#25639] opened 2021-08-14 09:41 UTC
> Because int is no larger than a reference in most modern machines, there is no benefit to passing a single int as a readonly reference.

I think this should be:
> …, there is no *performance* benefit to passing a single int as a readonly reference.

since there is value in explicitly preventing modification of parameters inside a method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b1434b0-5459-7569-47f7-46bf33fc3953
* Version Independent ID: 8a4ae81b-1ae5-cbe6-d58b-df455414e245
* Content: [in parameter modifier - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/in-parameter-modifier)
* Content Source: [docs/csharp/language-reference/keywords/in-parameter-modifier.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/in-parameter-modifier.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-08-16 13:45
Thanks for writing this @david-john-wilson 

My first inclination was to close this. My reasoning is that you'd normally pass `int` parameters *by value*, so any modifications affect the copy, not the original.

But then, I starting thinking more. There could be a benefit to `in`, so that the method could not modify the value. That's a bit different than the safety of modifying a copy.

And then, I thought more. In the case where a developer declared an `int` parameter using the `in` modifier, the developer could create a local copy and modify that anyway. 

So, I think I'm back where I started. I think it's true that there isn't any practical benefit to passing an `int` by readonly reference.

What do you think after my comments?

**Comment by david-john-wilson** [comment] 2021-08-16 17:17
I would say that on balance I disagree.

You could make a similar argument that a local `const` has no benefit because a developer could assign a copy to a local variable where it could then be modified.

I think that ignores that the original developer has conveyed intent by declaring the `const` and the developer’s future self or colleague must explicitly and intentionally jump through some hoops to disregard that original intent.

**Comment by svick** [comment] 2021-08-16 19:09
@david-john-wilson Personally, I think you shouldn't modify the signature of a method because of an implementation detail. You're effectively making the parameter `ref readonly` just to make it `readonly` and ignoring the `ref` part.

**Comment by david-john-wilson** [comment] 2021-08-16 20:00
The documentation indicates that the `in` modifier is not considered to be part of the method signature, though (at least not for the purposes of overload resolution), so I’m not sure that’s significant.

> The `in`, `ref`, and `out` keywords are not considered part of the method signature for the purpose of overload resolution

**Comment by BillWagner** [comment] 2021-08-17 15:08
@david-john-wilson I opened #25666 to address the misconception caused by the sentence you cite in your previous comment. The C# standard updated this for V5, and I thought I had caught most of those in the language reference. This one slipped through. 

With that change in place, I agree with @svick that no further changes should be made here.

I'll close this.

**Closed by BillWagner** 2021-08-17 15:08 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-language-reference/tech
