### ISSUE TITLE
Prototypes are in C++. There are no VB versions.

### ISSUE THREAD

**Issue by jbstcyr** [dotnet/docs#8555] opened 2018-10-22 21:10 UTC
Prototypes in C++ only.  No VB versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6298b73a-8016-f280-a68a-ecafefa3bbc6
* Version Independent ID: 4e0a4520-b5f2-17c3-8785-c42c1313b6f7
* Content: [FileStream Constructor (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netframework-4.7.2#System_IO_FileStream__ctor_System_String_System_IO_FileMode_System_Security_AccessControl_FileSystemRights_System_IO_FileShare_System_Int32_System_IO_FileOptions_System_Security_AccessControl_FileSecurity_)
* Content Source: [xml/System.IO/FileStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/FileStream.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-10-22 22:52
Thanks @jbstcyr. @Joelmartinez it looks like mdoc is not generating the VB signature for this API:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/FileStream.xml#L1417

**Comment by mairaw** [comment] 2018-10-22 23:04
Duplicate of https://github.com/mono/api-doc-tools/issues/356

For that reason, I'm closing this issue.

**Closed by mairaw** 2018-10-22 23:04 UTC
Labels: :books: Area - API Reference, :file_folder: Repo - dotnet-api-docs, Source - Docs.ms, duplicate, external
