### ISSUE TITLE
Revise dotnet restore to note that it runs implicitly in some scenarios

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/docs#3323] opened 2017-10-05 15:59 UTC
# Revise dotnet restore to note that it runs implicitly in some scenarios

# General

Starting with .NET Core 2.0, [`dotnet restore`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x) runs implicitly in some cases. The reference documentation should discuss those.

//cc @mairaw, @BillWagner

**Comment by mairaw** [comment] 2017-10-09 20:25
Isn't this a duplicate of #2722 @rpetrusha?

**Comment by rpetrusha** [comment] 2017-10-10 21:50
@mairaw, actually it's not. #2722 is largely aimed at cases where dotnet restore is used. What I had in mind is that the [`dotnet restore`](https://docs.microsoft.com/dotnet/core/tools/dotnet-restore?tabs=netcore2x) command itself needs additional revision and detail.

**Comment by mairaw** [comment] 2017-10-10 22:06
Ah ok. Makes sense @rpetrusha!

**Comment by BillWagner** [comment] 2017-10-23 20:22
@rpetrusha I added this to the Sprint 127 milestone. Is that when you had planned to finish it? If not, go ahead and move it to another sprint.

**Comment by mairaw** [comment] 2017-11-13 21:35
should this be assigned to you @rpetrusha?

**Comment by rpetrusha** [comment] 2017-11-13 23:21
Yes, I just assigned it to myself, @mairaw.

**Closed** 2017-11-30 23:47 UTC
Labels: Area - .NET Core Guide, P0, update
