### ISSUE TITLE
Missing closing parentheses to sample code in document

### ISSUE THREAD

**Issue by DaeunSim** [dotnet/docs#19950] opened 2020-08-11 00:37 UTC
Missing closing parenthesis '}' in the document's example code.

PrimeService_IsPrimeShould.cs :

```c#
using NUnit.Framework;
using Prime.Services;

namespace Prime.UnitTests.Services
{
    [TestFixture]
    public class PrimeService_IsPrimeShould
    {
        private PrimeService _primeService;

        [SetUp]
        public void SetUp()
        {
            _primeService = new PrimeService();
        }

        [Test]
        public void IsPrime_InputIs1_ReturnFalse()
        {
            var result = _primeService.IsPrime(1);

            Assert.IsFalse(result, "1 should not be prime");
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0063ceb-57ea-f30c-efed-b2a36314ccaa
* Version Independent ID: bd9a321e-2ef2-491d-cd37-2d9c66f90cc9
* Content: [Unit testing C# with NUnit and .NET Core - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit)
* Content Source: [docs/core/testing/unit-testing-with-nunit.md](https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-nunit.md)
* Product: **dotnet-core**
* GitHub Login: @rprouse
* Microsoft Alias: **wiwagn**

**Comment by tdykstra** [comment] 2021-08-09 16:39
Duplicate of #21705, which was fixed by #22028

**Closed by tdykstra** 2021-08-09 16:39 UTC
Labels: doc-enhancement, Pri2, dotnet-core/prod
