### ISSUE TITLE
Reorganize

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11276] opened 2019-03-12 16:52 UTC
@gerich-home commented on [Tue Mar 12 2019](https://github.com/dotnet/docs.ru-ru/issues/182)

Good article, but can be slightly reorganized.

It feels like comparison with existing frameworks (.Net framework, Mono) gives reader lots of understanding about the position of .Net Core. Maybe it needs to be moved closer to the top of article?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 581f6cbb-c666-87ee-ab0c-f131baca403c
* Version Independent ID: 9205f603-e1d4-e0eb-1273-f176fcbf520f
* Content: [Сведения о .NET Core](https://docs.microsoft.com/ru-ru/dotnet/core/about#feedback)
* Content Source: [docs/core/about.md](https://github.com/dotnet/docs.ru-ru/blob/live/docs/core/about.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment] 2019-03-12 16:53
Hi team, 
I'm moving this here since the user is making suggestions on the original document 
best

**Comment by rpetrusha** [comment] 2019-03-14 15:39
It seems to me that the comparison of .NET Core with other .NET frameworks (Mono and .NET Framework) is in the appropriate place, after a basic discussion of what .NET Core is. That's particularly the case since .NET Core is an independent implementation from Mono, 
Closing as By Design.

**Closed by rpetrusha** 2019-03-14 15:39 UTC
Labels: :books: Area - .NET Core Guide, Source - Docs.ms, by-design
