### ISSUE TITLE
Is it correct to charge extra overdraft fee for the charge of monthly interest?

### ISSUE THREAD

**Issue by chaseliu** [dotnet/docs#30805] opened 2022-08-24 04:12 UTC
Date            Amount  Balance Note
2022/8/24       -1000   -1000   Take out monthly advance
2022/8/24       50      -950    Pay back small amount
2022/8/24       -5000   -5950   Emergency funds for repairs
2022/8/24       -20     -5970   Apply overdraft fee
2022/8/24       150     -5820   Partial restoration on repairs
2022/8/24       -407.40 -6227.40        Charge monthly interest
2022/8/24       -20     -6247.40        Apply overdraft fee

The output of last example is above.

Is it correct to charge extra overdraft fee for the charge of monthly interest?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece1648c-e8a7-153d-a22b-350a619aa26d
* Version Independent ID: a0c9221a-cc55-4c31-4f54-0e5fbdcbce25
* Content: [Object-Oriented Programming (C#)](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/tutorials/oop)
* Content Source: [docs/csharp/fundamentals/tutorials/oop.md](https://github.com/dotnet/docs/blob/main/docs/csharp/fundamentals/tutorials/oop.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-08-24 14:08
Hi @chaseliu 

That's what I'd done in the example. It could be coded with different rules, if you'd like.

I'll close this as by design.

**Closed by BillWagner** 2022-08-24 14:08 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/prod, csharp-fundamentals/tech
