### ISSUE TITLE
Allow the built documents from CI to be accessible in some way

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/docs#15153] opened 2019-10-13 16:17 UTC
It seems that I cannot build the docs/dotnet-api-docs repo locally because of internal repos that the build process depend on. This is annoying because I cannot verify the changes I've made before the PR is merged; it would be great if the document pages built from the CI can be made visible to us, so that we can make additional change for completeness before the PR is merged.

From what I can see, post-CI build reports ([Example](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C12%5C500c749d-de78-3d4a-00e4-269d599bf9ec%5CPullRequest%5C201910121858302749-3334%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bV7JIozpW2L55cWpNqP2EV%2BCYqHVNbNt44a25drBSTc%3D&st=2019-10-12T19%3A30%3A01Z&se=2019-11-12T19%3A35%3A01Z&sp=r)) seem to have links to the built pages, but they redirect to MS Login page and logging in results in 403 unauthorised error.

[Docs authoring package for VS Code](https://github.com/microsoft/vscode-docs-authoring) could be an option; but [I've been having problems using the plugin](https://github.com/microsoft/vscode-docs-authoring/issues/343) and given that it's a plugin that merely imitates the behaviour I wouldn't fully trust the plugin to do the same thing as the ones built from here.

**Comment by svick** [comment] 2019-10-13 17:04
This is a duplicate of https://github.com/MicrosoftDocs/feedback/issues/533, where the resolution was:

> we do have a future roadmap item to figure out a way to review a PR from a non-Microsoft user that doesn’t require an @microsoft.com address.

Though it's not clear to me when can we expect anything to happen in this area.

**Comment by Thraka** [comment] 2019-10-14 21:25
Closing as duplicate.

**Comment by Thraka** [comment] 2019-10-14 21:25
Duplicate of MicrosoftDocs/feedback#533

**Closed by Thraka** 2019-10-14 21:25 UTC
Labels: docs-experience

**Comment by Thraka** [comment] 2019-10-14 21:27
@Gnbrkm41 The docs authoring pack doesn't really do anything for the API docs 😦 We really appreciate any help you do in the API space. Thank you for your help.
