### ISSUE TITLE
System.InvalidOperationException at IDataView trainingData =..

### ISSUE THREAD

**Issue by siya003** [dotnet/docs#17285] opened 2020-03-02 17:15 UTC
System.InvalidOperationException: 'Field 'ImagePath' is missing the LoadColumnAttribute attribute'
It seems some problem with the tags.tsv file down loaded from assets location. Please help to resolve the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ca0a402-fa67-fbd4-4cbc-604b4b59c97c
* Version Independent ID: c8a996eb-82ed-a4bd-94d8-ef0b32158c67
* Content: [Tutorial: ML.NET image classification model from TensorFlow - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/image-classification#feedback)
* Content Source: [docs/machine-learning/tutorials/image-classification.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/image-classification.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by natke** [comment] 2020-03-02 18:57
Thank you for reporting this issue @siya003. We are looking into it.

**Comment by natke** [comment] 2020-03-02 22:04
Hi @siya003, we cannot reproduce your issue. Can you please provide some more details about the environment on which you are developing the application, such as: operating system, development environment etc, and a more detailed log of the error.

**Comment by natke** [comment] 2020-03-04 21:21
Hi @siya003, we didn't hear back from you. Closing this issue for now. Please reach out if you have any more issues.

**Closed by natke** 2020-03-04 21:21 UTC
Labels: :books: Area - ML.NET Guide, needs-more-info
