### ISSUE TITLE
Variable inside a class used as a counter

### ISSUE THREAD

**Issue by vpprof** [dotnet/docs#5751] opened 2018-06-01 18:48 UTC
It is worth mentioning that it is impossible to declare your counter inside a class like so:

==MyClass module
Public i as Integer

==Main module
Dim MyInstance as MyClass: Set MyInstance = New MyClass
For MyInstance.i = 1 To 10
    Debug.Print "Hello"
Next

The above code generates a compile-time error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 513d5fec-4fa8-511f-4472-0ef6f9582332
* Version Independent ID: 68efde66-3840-baf6-c25c-eaf18be9b11d
* Content: [For...Next Statement (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/for-next-statement#BKMK_Counter)
* Content Source: [docs/visual-basic/language-reference/statements/for-next-statement.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/statements/for-next-statement.md)
* Service: **unspecified**
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-07-09 20:30
Thanks @vpprof for your feedback. We'll take a look at this. Is this VB6 or Visual Basic .NET code?

**Comment by rpetrusha** [comment] 2018-07-09 21:58
In looking at your code, @vpprof, I suspect it's Visual Basic 6.0 code. At least, the `Set` statement, the use of `MyClass` (a Visual Basic keyword), and the absence of parentheses around `"Hello"` suggest that, since they all generate compiler errors. In addition, I can't reproduce the condition that you mention. Here is the Visual Basic .NET code, which compiles and runs successfully:

```
 Imports System.Diagnostics

Public Class Example
   Public Shared Sub Main()
      Dim MyInstance as CClass
      MyInstance = New CClass()

      For MyInstance.i = 1 To 10
         Console.WriteLine("Hello")
'         Debug.Print("Hello")
      Next
   End Sub
End Class

Public Class CClass
   Public i As Integer

End Class
```

Since this is documentation for Visual Basic .NET only, and since I can't reproduce your issue, I'm going to close this issue as Not Repro. If I'm wrong or you disagree, feel free to respond.

**Closed by rpetrusha** 2018-07-09 21:58 UTC
Labels: Area - Visual Basic Guide, P2, Source - Docs.ms

**Comment by vpprof** [comment] 2018-07-12 21:29
Well, this is actually VBA code, running on Excel 2013. Where to seek help then?

**Comment by mairaw** [comment] 2018-07-12 21:32
I believe this is the page for VBA https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/using-fornext-statements

**Comment by mairaw** [comment] 2018-07-12 21:33
And here's the repository for their docs: https://github.com/OfficeDev/VBA-content
