### ISSUE TITLE
CheckBox size not Square (Box width * height = 14*13)

### ISSUE THREAD

**Issue by Conghung43** [dotnet/docs#9195] opened 2018-11-23 08:49 UTC
-Status : When I create a CheckBox in windows 7, VS2013, .NET 4.5, the size of Box is 13x13 pixel 
-Problem: Using the same code and run it in windows 10, VS2015, Every version .NET 4.0 =&gt; .NET 4.7.2 , the size of Box is 14x13 pixel. Even though Bring Release project in Windows 7 then run the file in Windows 10, result is the same (size of Box is 14x13 pixel).
I already checked in many computers and they have the same problem.
=> is this a bug from windows 10 and How to fix it becomes square (box size is 13x13 pixel) without change ScaleX, ScaleY in LayoutTransformer ?
Any help would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df35d659-55bc-23e4-34fc-b9b007eff251
* Version Independent ID: 5fa7257c-0aa5-34aa-f767-b4f9f8dfce20
* Content: [CheckBox](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/checkbox)
* Content Source: [docs/framework/wpf/controls/checkbox.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/controls/checkbox.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment] 2018-12-11 23:19
@Conghung43 Hi, thank you for the question. I think this question is better suited for a community like StackOverflow. I'm going to close this because the issue is not related to a problem with the article.

My personal guess is that their is something from the operating system that defines how the control should look and therefore is rendered.

**Closed by Thraka** 2018-12-11 23:19 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WPF, Source - Docs.ms, forum, product-question
