### ISSUE TITLE
7.3? 

### ISSUE THREAD

**Issue by Welchen** [dotnet/docs#5394] opened 2018-05-15 18:03 UTC
Is there going to be an update to these docs for 7.3? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36588d0-6bdf-1740-220c-10b20bb88730
* Version Independent ID: 587ed47f-f532-e018-9b0d-6ee76afd20e4
* Content: [What's New in C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/)
* Content Source: [docs/csharp/whats-new/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/index.md)
* Service: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2018-05-15 18:07
@Welchen That work is in progress. You can see all the work so far in [this project](https://github.com/dotnet/docs/projects/32)  

This particular issue is a duplicate of #5289  To answer your question, I expect to finish that early next week. 

Thanks for participating in docs.

Closing as a duplicate of #5289

**Closed by BillWagner** 2018-05-15 18:07 UTC
Labels: Source - Docs.ms, duplicate, triaged
