### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by lonevvolf** [dotnet/docs#11662] opened 2019-04-04 14:19 UTC
Trying the following command:
./dotnet-install.ps1 -Runtime aspnetcore -InstallDir "C:\Program Files\dotnet"
I get: Index was outside the bounds of the array.
At line:1 char:2
+  ./dotnet-install.ps1 -Runtime aspnetcore -InstallDir "C:\Program Fil ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [dotnet-install.ps1], IndexOutOfRangeException
    + FullyQualifiedErrorId : System.IndexOutOfRangeException,dotnet-install.ps1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#feedback)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment] 2019-04-08 21:52
Can you give me more information? Are you running as admin? What OS are you using?

**Comment by mairaw** [comment] 2019-04-22 21:45
Closing this one due to the lack of information. Please get back to us @lonevvolf if you have the information that @Thraka requested.

**Comment by skwasiborski** [comment] 2019-04-25 13:51
Hi,

I am experiencing the same issue. The issue seems to be not related with OS version privileges etc. but with contents of the latest.version file. For dotnet runtime it contains two lines one with commit hash and one with version number, the one for aspnetcore runtime only contains one line with version number. The files can be found respectively in: [dotnet](https://dotnetcli.azureedge.net/dotnet/Runtime/LTS/latest.version) and [aspnetcore](https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/LTS/latest.version).

dotnet-install.ps1 in function Get-Version-Info-From-Version-Text (line 171) assumes this file has two lines. This is why the exception can be observed.

I reproduced it on Win10 (admin and not-admin) and on Win Server 2016.

**Comment by Thraka** [comment] 2019-04-26 18:21
I'll do some testing.

**Comment by Thraka** [comment] 2019-05-03 19:11
I tracked down the problem. The version feed for aspnetcore does not contain the hash for the version, and the script fails on line 177 where it tries to access the hash value.

@dsplaisted @stevenbrix.

**Comment by dsplaisted** [comment] 2019-05-03 23:08
@johnbeisner Can you look at this?  Is this a bug in the script or is it a problem with the version feed (or both)?

**Comment by Thraka** [comment] 2019-05-04 16:42
@dsplaisted I think it's both possibly. Does the feed need to include the hash? I would assume it should since the dotnet feed (non asp runtime feed) does include the hash. If that hash is in the feed result, the script will work correctly. 

The script could be modified to be more robust in detecting the hash missing.

**Comment by johnbeisner** [comment] 2019-05-29 20:01
Duplicate: https://github.com/dotnet/cli/issues/10663
This has been addressed: https://github.com/dotnet/cli/pull/11359

**Comment by Thraka** [comment] 2019-05-29 20:03
@johnbeisner Thanks!
@lonevvolf Thank you for reporting the problem.

**Closed by Thraka** 2019-05-29 20:03 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, Source - Docs.ms, waiting-on-feedback
