### ISSUE TITLE
Async Streams sample code links are no longer valid

### ISSUE THREAD

**Issue by agc93** [dotnet/docs#18391] opened 2020-05-13 01:43 UTC
The code samples linked from the [Run the starter application](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream?WT.mc_id=dotnet-devto-cephilli#run-the-starter-application) section are no longer valid.

They're actually in the `dotnet/samples` repository under the same path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17f03524-58d6-870c-e43f-e7f9565608e5
* Version Independent ID: da634f1c-bb77-efb5-0066-c3760b79fa4c
* Content: [Generate and consume async streams](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/generate-consume-asynchronous-stream?WT.mc_id=dotnet-devto-cephilli#feedback)
* Content Source: [docs/csharp/tutorials/generate-consume-asynchronous-stream.md](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/generate-consume-asynchronous-stream.md)
* Product: **dotnet-csharp**
* Technology: **csharp-async**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by IEvangelist** [comment] 2020-05-13 13:58
Hi @agc93,
Thank you for posting this issue. If you are able to create a pull request to address the issue, we'd happily review it. If you do not have time, we'll try to address this in the next sprint. Thank you

**Comment by tiesmaster** [comment] 2020-05-26 12:18
@IEvangelist I ran into this same issue, and was about to put in a PR to get it fixed. Though, I noticed that the links are fixed by @mairaw 2 weeks ago on `master`, however, the change is not showing up. Is there something wrong with the sync of these documents?

**Comment by IEvangelist** [comment] 2020-05-26 12:49
Hi @tiesmaster - great catch, I think you might be correct. This should have been fixed in #18414. I'll take a deeper look into this and report back.

**Comment by tiesmaster** [comment] 2020-05-26 20:55
@IEvangelist Ah, this is actually quite bizarre 😅 I stumbled upon this page a couple weeks ago, and still had it open in a tab. I was reading this today, and ran into the broken link. I checked for open issues via docs, and saw the issue, and got here ;)

Needless to say, I can't reproduce anymore as well, so time to close it?

**Comment by IEvangelist** [comment] 2020-05-27 12:42
This issue cannot be reproduced and we believe has already been fixed...

**Closed by IEvangelist** 2020-05-27 12:42 UTC
Labels: :books: Area - C# Guide, :card_file_box: Technology - C# What's New, P2, docs-experience, up-for-grabs
