### ISSUE TITLE
Clarify Shared Framework resolution rules when using FDD 

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/docs#2942] opened 2017-08-18 19:55 UTC
This issue refers to the following documentation
End User Link:  https://docs.microsoft.com/en-us/dotnet/core/deploying/
Doc Source:  https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md

The `Framework-dependent deployments` section states that following:

```
There are also a few disadvantages:

Your app can run only if the version of .NET Core that you target, or a later version, is already installed on the host system.
```

This doesn't seem like the correct Shared Framework resolutions rules.  For example if you take a FDD which targets 1.0.5 and run it in an environment with only the 1.1.2 shared framework you will get the following error:

```
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.2
  - Alternatively, install the framework version '1.0.5'.
```

I am not knowledgeable in this space to definitively state the correct rules.  I stumbled across [this gist](https://gist.github.com/schellap/c2260ee9755fce1d78a564183be4609d#shared-framework-selection) which is in-line with my understanding of what the rules are.

**Comment by mairaw** [comment] 2017-08-21 20:28
Hi @MichaelSimons. Yes, we're missing this scenario. I believe this is a duplicate of #2880 so I'm closing this one.

**Closed by mairaw** 2017-08-21 20:28 UTC
