### ISSUE TITLE
Language requested (C++) results in examples in C#

### ISSUE THREAD

**Issue by doctordns** [dotnet/docs#3619] opened 2017-11-06 16:04 UTC
# Issue Title
On page: https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=netframework-4.7.1#Applies_to Selecting Language C++ gives examples in C#.

# General

See the graphic - The language requested is C++, while the examples offered are shown in C#

[2017-11-06_15-52-16](https://user-images.githubusercontent.com/3630329/32450044-1d0b2db6-c30b-11e7-9ed4-890399ab447c.png)

I've had a look at the XML for this page but nothing jumps out.

**Comment by mairaw** [comment] 2017-11-07 19:16
Duplicate of #3620

**Closed by mairaw** 2017-11-07 19:16 UTC
