### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MichaelLHerman** [dotnet/docs#8233] opened 2018-10-10 15:41 UTC
"Default WPF Themes" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c77316ba-f765-fc01-8bef-2451b6b44ebf
* Version Independent ID: e3895129-2893-7d9a-5f99-fb03f1ce3e8f
* Content: [Button Class (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.button?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/Button.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/Button.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-10-10 17:46
Duplicate of #6831

**Comment by mairaw** [comment] 2018-10-10 17:46
Thank you @MichaelLHerman for your feedback. I'm closing this one as duplicate since we already have an issue covering the same problem.

**Closed by mairaw** 2018-10-10 17:46 UTC
Labels: :books: Area - API Reference, :file_folder: Repo - dotnet-api-docs, Source - Docs.ms, broken-link, duplicate
