### ISSUE TITLE
Consider adding guidance regarding deterministic builds

### ISSUE THREAD

**Issue by tkp1n** [dotnet/docs#17735] opened 2020-04-07 12:11 UTC
As demonstrated by @clairernovotny [here](https://github.com/clairernovotny/DeterministicBuilds), it is likely recommended to "CONSIDER" deterministic builds if one considers using Source Link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db5ae44-5ee9-ed62-7355-7c0cbc1bfc07
* Version Independent ID: f54c98e2-bbae-42c6-2103-e94d6ec0e931
* Content: [Source Link and .NET libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink)
* Content Source: [docs/standard/library-guidance/sourcelink.md](https://github.com/dotnet/docs/blob/master/docs/standard/library-guidance/sourcelink.md)
* Product: **dotnet**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by clairernovotny** [comment] 2020-04-07 12:25
The screen shot could probably be updated to the latest version of NuGet Package Explorer, which makes it easier to validate that Source Link information is present.

**Comment by Thraka** [comment] 2020-04-07 20:23
Hello, thank you for opening this issue. I think this is covered by another issue that was opened a few days ago. I'll add your link though to that issue. Thanks again.

**Comment by Thraka** [comment] 2020-04-07 20:23
Duplicate of #17710

**Comment by Thraka** [comment] 2020-04-07 20:25
Oh sorry, I thought this was the same article as the other! My mistake. I'll reopen this!

**Closed** 2020-05-11 17:35 UTC
Labels: :books: Area - .NET Guide, doc-enhancement
