### ISSUE TITLE
Compiler warning in VS2017 for usesystemdefault and bypassonlocal

### ISSUE THREAD

**Issue by PerJogback** [dotnet/docs#11977] opened 2019-04-23 06:33 UTC
The example gives the following warnings in VS2017:
The 'usesystemdefault' attribute is invalid - The value 'true' is invalid according to its datatype 'NmToken' - The Enumeration constraint failed.
The 'bypassonlocal' attribute is invalid - The value 'true' is invalid according to its datatype 'NmToken' - The Enumeration constraint failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9079251a-98f0-5711-9cca-6352e98dec61
* Version Independent ID: 1a610214-183b-0328-744a-90161d572aa1
* Content: [&lt;defaultProxy&gt; Element (Network Settings)](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings#feedback)
* Content Source: [docs/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings.md)
* Product: **dotnet-framework**
* Technology: **dotnet-networking**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by Thraka** [comment] 2019-11-21 21:07
@PerJogback Sorry for the late reply, is this something you can:

- Test in VS2019
- Provide some example code so I can test it?

**Comment by RhomGit** [comment] 2019-12-18 02:29
Visual Studio v16.4.2

![image](https://user-images.githubusercontent.com/25700833/71050708-e33a4a00-2180-11ea-8336-9616ca068525.png)

**Comment by Thraka** [comment] 2020-01-06 23:17
@davidsh, is this something you can comment on?

**Comment by mairaw** [comment] 2020-01-28 00:57
@davidsh @karelz we need the input from the NCL team on this issue. Can you please take a look?

**Comment by davidsh** [comment] 2020-02-05 17:52
I tried using the latest Visual Studio 2019, 16.4.4
![image](https://user-images.githubusercontent.com/7684835/73868273-04bcc700-47fd-11ea-9ee7-4b3d6cae27b9.png)

I did not see any Intellisense errors when constructing the following app.config file:
![image](https://user-images.githubusercontent.com/7684835/73868324-1d2ce180-47fd-11ea-8c6a-9c8e1342d241.png)

Errors like this in Visual Studio are usually caused by a faulty installation of Visual Studio where the Intellisense XML files are missing/corrupted.

**Comment by RhomGit** [comment] 2020-02-05 23:22
Its just because the boolean value is lower case. Using "True" instead of "true", and "False" instead of "false" fixes it.

**Comment by davidsh** [comment] 2020-02-05 23:45
>Its just because the boolean value is lower case. Using "True" instead of "true", and "False" instead of "false" fixes it.

Yes, the values for attributes (such as 'usesystemdefault') are case sensitive. The Intellisense will show you how to properly format each attribute value as shown above.

**Comment by davidsh** [comment] 2020-02-05 23:46
Closing this issue as 'by-design'. The behavior of showing an error using improper casing for attribute values is correct.

**Closed by davidsh** 2020-02-05 23:46 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - NCL, by-design, doc-bug
