### ISSUE TITLE
is it possible to deploy FDE with VS2017 publish profile?

### ISSUE THREAD

**Issue by ikarakaya** [dotnet/docs#10321] opened 2019-02-05 11:25 UTC
i can publish "sudo dotnet publish -c Release -f netcoreapp2.2 -r debian.9-x64 --self-contained false" to Debian 9 running on Virtualbox. 

is it possible to deploy from VS2017 as FDE with FTP publish profile?
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core Application Deployment - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/deploying/)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment] 2019-02-12 04:43
@KathleenDollard @richlander @peterhuene do you know if we can already deploy using FDE from VS as well?

**Comment by peterhuene** [comment] 2019-02-12 04:55
It should be.  However, I'm tracking dotnet/cli#10647 that causes no apphost to be generated when `RuntimeIdentifier` is set through the `.pubxml` file.

The cause is that we have a number of apphost-related properties that get set before the `.pubxml` file is imported, thus are not correct for what will eventually be the target RID.  This causes a failure to discover the apphost in the restored native assets and thus it doesn't get published.

Note that this is fixed for TFM `netcoreapp3.0` because we don't rely on the file name (and thus a RID-based executable extension) to figure out what the apphost asset is.

**Comment by ikarakaya** [comment] 2019-02-12 08:44
@mairaw i tried to deploy from VS with publish settings below. It creates a ".dll" file which i can run with "dotnet xxx.dll". 

  `<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`
`  <PropertyGroup>`
`   <WebPublishMethod>FTP</WebPublishMethod>`
`  <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>`
`  <LastUsedPlatform>Any CPU</LastUsedPlatform>`
`  <SiteUrlToLaunchAfterPublish />`
`  <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>`
`   <ExcludeApp_Data>False</ExcludeApp_Data>`
`   <TargetFramework>netcoreapp2.2</TargetFramework>`
`   <ProjectGuid>e689de47-6a8e-4488-a11b-89a04aea846f</ProjectGuid>`
`   <SelfContained>false</SelfContained>`
`   <_IsPortable>true</_IsPortable>`
`   <publishUrl>192.168.43.108</publishUrl>`
`   <DeleteExistingFiles>True</DeleteExistingFiles>`
`   <FtpPassiveMode>True</FtpPassiveMode>`
`   <FtpSitePath>/var/www/deneme</FtpSitePath>`
`   <UserName>ismail</UserName>`
`   <_SavePWD>True</_SavePWD>`
`   <RuntimeIdentifier>debian.9-x64</RuntimeIdentifier>`
`  </PropertyGroup>`
`</Project>`

When i use CLI publish as i mentioned in first post, it creates executable.

**Comment by KathleenDollard** [comment] 2019-02-12 22:21
I believe VS 2019 will support this.

**Comment by Thraka** [comment] 2019-03-19 23:21
@peterhuene 

I'm going to infer from this that VS 2017 will not support this?

**Comment by peterhuene** [comment] 2019-03-19 23:35
2017 does support it with a 2.2 SDK, provided `RuntimeIdentifier` is set in the project file and not the publish profile (see dotnet/cli#10647, which I'm actually in the middle of fixing now).

If we accept a servicing fix for this with 2.2, a future patched 2.2 SDK should work with a `RuntimeIdentifier` set in the publish profile.

**Comment by peterhuene** [comment] 2019-03-25 20:56
So I have a fix that corrects the following if `RuntimeIdentifier` is set in a publish profile:

* We now properly calculate the expected apphost filename for the runtime being targeted (e.g. if `RuntimeIdentifier` is 
* We now properly calculate `SelfContained` so that it also doesn't need to be specified in the publish profile (a non-empty `RuntimeIdentifier` implies `SelfContained` is `true`).
* We now properly calculate `UseAppHost` so that it doesn't need to be specified in the publish profile (defaults to true for `netcoreapp2.2` or later published applications that specify a `RuntimeIdentifier`).
* We now properly calculate `DeployAppHost` so that it defaults to true when using the apphost.

**Comment by peterhuene** [comment] 2019-03-25 21:08
I will be attempting a servicing fix for 2.2 so that this scenario works as expected for 2017 users.

For now, users should be able to workaround this by explicitly setting `RuntimeIdentifier` and `SelfContained` in the project file rather than the publish profile; note that this will affect all building and publishing, however.

See dotnet/cli#10647 for more details on the fix.

**Closed** 2021-01-25 14:47 UTC
Labels: :books: Area - .NET Core Guide, Pri2, dotnet-core/prod, product-question, waiting-on-feedback, won't fix
