### ISSUE TITLE
Odd example code

### ISSUE THREAD

**Issue by SpontaneousDuck** [dotnet/docs#8185] opened 2018-10-09 00:33 UTC
Example code has the last bracket split out in to a second code section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef481df4-ecb1-b588-5fde-b8d9aa4c6a42
* Version Independent ID: 1bdcc46d-b5a9-18ae-3317-69376389782b
* Content: [FrameworkElement.DefaultStyleKey Property (System.Windows)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.defaultstylekey?view=netframework-4.7.2#System_Windows_FrameworkElement_DefaultStyleKey)
* Content Source: [xml/System.Windows/FrameworkElement.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows/FrameworkElement.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by imba-tjd** [comment] 2018-10-09 07:44
This seems to be by design

**Comment by rpetrusha** [comment] 2018-10-09 20:04
It is by design, though it isn't a particularly useful way of presenting code. It's caused by a difference in the way snippets were handled in our old build system (they were merged) and our new one (they are treated as separate snippets). There are numerous instances of this, especially in the WPF docs. I thought that there was an open issue to address these and fix them over time, though I can't find it.

I'll open a PR to fix this issue, though.

**Closed** 2018-10-10 16:15 UTC
Labels: :books: Area - API Reference, :card_file_box: Technology - WPF, :file_folder: Repo - dotnet-api-docs, :file_folder: Repo - samples, P2, Source - Docs.ms, triaged
