### ISSUE TITLE
Compile-time logging source generation example triggers analyzer error "partial method must have an implementation part because it has accessibility modifiers"

### ISSUE THREAD

**Issue by wjrogers** [dotnet/docs#27471] opened 2021-12-09 14:20 UTC
When I write a class like the one in the example on this page,

```csharp
public static partial class Log
{
    [LoggerMessage(
        EventId = 0,
        Level = LogLevel.Critical,
        Message = "Could not open socket to `{hostName}`")]
    public static partial void CouldNotOpenSocket(
        ILogger logger, string hostName);
}
```

the IDE flags it with an error:
> Partial method 'void CouldNotOpenSocket(ILogger, string)' must have an implementation part because it has accessibility modifiers.

However, the code compiles and executes successfully. Will you please add some guidance to this page about this error, especially if there is a way to silence it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc4ecf0-19e4-54d3-c34e-b6eadb80262b
* Version Independent ID: decc74aa-a2d5-8727-f22b-3862bacde737
* Content: [Compile-time logging source generation](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator)
* Content Source: [docs/core/extensions/logger-message-generator.md](https://github.com/dotnet/docs/blob/main/docs/core/extensions/logger-message-generator.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @maryamariyan
* Microsoft Alias: **maariyan**

---
[Associated WorkItem - 68965](https://dev.azure.com/msft-skilling/Content/_workitems/edit/68965)

**Comment by tdykstra** [comment] 2021-12-09 20:03
@maryamariyan can you help with this question?

**Comment by maryamariyan** [comment] 2021-12-10 02:07
I got a repro for this. Thanks for your report @wjrogers.

@pranavkm what approach do you recommend to silence a diagnostic?

**Comment by pranavkm** [comment] 2021-12-10 20:52
You could use a pragma warning suppress to do this: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/suppress-warnings#use-a-preprocessor-directive

**Comment by dotnetshadow** [comment] 2021-12-21 07:56
> You could use a pragma warning suppress to do this: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/suppress-warnings#use-a-preprocessor-directive

I did try the following but the error still came up
```
#pragma warning disable CS8795 // Rethrow to preserve stack details
```

**Comment by maryamariyan** [comment] 2021-12-21 21:12
> Also the link to this doc produces an 404
https://docs.microsoft.com/en-us/dotnet/csharp/misc/sorry-we-don-t-have-specifics-on-this-csharp-error?f1url=%3FappId%3Droslyn%26k%3Dk(CS8795)

FYI, this issue is tracked by https://github.com/dotnet/docs/issues/23900

**Comment by ds185357** [comment] 2022-01-10 14:23
I got the same behavior. The code compiles successfully, but VS with static analysis enabled produces CS8795 and CA1822. The CA1822 can be suppressed, CS8795 cannot.
![image](https://user-images.githubusercontent.com/68111207/148781540-92a8a9d3-598c-4e80-86bb-58908f4fc01b.png)

**Comment by stap123** [comment] 2022-01-11 19:38
I also get the CS8795 error for all methods. The project successfully compiles and works as expected but VS 2022 shows an error for every method.

**Comment by seangwright** [comment] 2022-03-12 02:05
I experience this same issue. `#pragma` directives didn't solve it. However I was able to resolve the errors by authoring the code, then closing VS, and finally starting VS and opening the solution back up. No amount of rebuilding solutions/projects or closing/reopening files solved the issue. I had to restart VS.

I've noticed this same issue with other source generator related code/libraries and it was solved in the same way.

Note: I am using Visual Studio 17.1.1

**Comment by jasonvasquez** [comment] 2023-01-03 18:28
For what it's worth, I see this issue with Rider as well.  I suspect it's not a Visual Studio issue specifically, but perhaps a Roslyn issue.  (The same close and re-open workaround works with Rider)

**Comment by RealDotNetDave** [comment] 2023-03-03 20:56
I have the same issue, but only when the solution builds on Linux.

**Comment by tdykstra** [comment] 2023-03-04 02:21
@maryamariyan I can't repro this in VS 2022 17.5, so it seems to have been at least partially addressed, just not in Linux per @RealDotNetDave.  That being the case it seems not to be a docs issue -- should I transfer this issue to the runtime repo?

**Comment by tdykstra** [comment] 2023-03-14 19:21
ping @maryamariyan

**Comment by dbead** [comment] 2023-03-17 12:31
Seems fixed atm in 17.5.2 for me but was happening in 17.5.1 using dotnet 6.

**Comment by maryamariyan** [comment] 2023-03-17 17:18
cc @dotnet/area-extensions-logging

**Comment by layomia** [comment] 2023-03-17 17:25
Thanks @maryamariyan.

@RealDotNetDave are you still seeing this issue on Linux with the latest VS version?

**Comment by MrBildo** [comment] 2023-04-27 20:10
I'm still seeing this issue in 17.5.4. No amount of suppression makes it go away. I have NoWarn in my project. .serverity = none in .editorconfig. Like others, it'll go away for a little while then crop back up.

I'm seeing it using the https://mapperly.riok.app/ library which uses heavy source generation.

**Comment by tdykstra** [comment] 2023-04-28 00:44
@layomia Given that it looks like this may still be an issue, is the runtime repo the right place to transfer this issue to?

**Comment by tarekgh** [comment] 2023-04-28 01:24
This looks the same issue https://github.com/dotnet/roslyn/issues/58913 and supposes to be fixed a while ago by https://github.com/dotnet/roslyn/pull/58990. 

@jasonmalinowski do you know why this still repro for the users? 

CC @Youssef1313

**Comment by MrBildo** [comment] 2023-04-28 13:08
I'm happy to provide more details. Again, this is being triggered from a 3rd party library, which certainly is the underlying cause. However, I would expect to be able to suppress it in some way.

**Comment by Youssef1313** [comment] 2023-04-28 13:14
This is roslyn-related issue.

I see https://github.com/dotnet/roslyn/issues/67123 which mentions:

> IntelliSense not working correctly (red squiggly lines all over the place for generated members)

So this seems very similar.

**Comment by Youssef1313** [comment] 2023-04-28 13:15
Also there is https://github.com/dotnet/roslyn/issues/65044

**Comment by tdykstra** [comment] 2023-10-02 18:20
> This looks the same issue [dotnet/roslyn#58913](https://github.com/dotnet/roslyn/issues/58913) and supposes to be fixed a while ago by [dotnet/roslyn#58990](https://github.com/dotnet/roslyn/pull/58990).
> 
> @jasonmalinowski do you know why this still repro for the users?

@tarekgh Can we close this as a duplicate of [dotnet/roslyn#58913](https://github.com/dotnet/roslyn/issues/58913)? It doesn't appear to be a doc issue.

**Comment by jasonmalinowski** [comment] 2023-10-02 18:52
Yeah, this is a product bug, so I'm not sure why we'd document workarounds rather than, well, fixing it.

**Comment by tarekgh** [comment] 2023-10-02 19:01
> Can we close this as a duplicate of https://github.com/dotnet/roslyn/issues/58913? It doesn't appear to be a doc issue.

@MrBildo was claiming the issue is still reported from a third-party library https://github.com/dotnet/docs/issues/27471#issuecomment-1527540007. If this is not the case anymore then we can close. Otherwise, it will be good if @MrBildo provide a repo if the issue is still showing up.

**Comment by MrBildo** [comment] 2023-10-02 19:27
In the case of Mapperly, the library I was using, it is no longer an issue, nor have I seen it recently with other source generators. Something fixed it along the way. I no longer have an issue. Regardless it doesn't seem like a doc problem.

**Closed** 2023-10-02 20:30 UTC
Labels: doc-enhancement, waiting-on-feedback, Pri2, dotnet-fundamentals/prod, :pushpin: seQUESTered
