### ISSUE TITLE
Invalid Path For 21.10

### ISSUE THREAD

**Issue by jfcarr** [dotnet/docs#26904] opened 2021-11-10 02:16 UTC
https://packages.microsoft.com/config/ubuntu/21.10 is not a valid path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by philomath-code** [comment] 2021-11-10 04:12
@jfcarr - I also experienced this issue. I had to download version 21.04

Tue 09 Nov 2021 10:12:03 PM CST


**Currently Running**
Distributor ID:  Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma

**Comment by adegeo** [comment] 2021-11-10 21:34
Thank you for reporting this issue. The documentation is being updated. .NET packages haven't been released for Ubuntu 21.10 but are in progress. Using the 21.04 repository works just fine.

**Comment by adegeo** [comment] 2021-11-10 21:35
Duplicate of #26879

**Closed by adegeo** 2021-11-10 21:35 UTC
Labels: doc-bug, Pri1, dotnet/prod, dotnet-install/tech
