### ISSUE TITLE
Please clarify in the docs what type of collection is created when using collection initializers with interfaces

### ISSUE THREAD

**Issue by SetTrend** [dotnet/docs#43967] opened 2024-12-13 20:14 UTC
### Type of issue

Missing information

### Description

The below mentioned documentation page doesn't provide information about what kind of collections are created by interface collection initializers, like:

```c#
ICollection<string> c = [];
IList<string> l = [];
...
```

Please add information to the below mentioned page, describing which types are inferred from collection interfaces when using collection initializers.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md

### Document Version Independent Id

95025282-20a0-ded8-c6d2-3b8ffff600c4

### Article author

@BillWagner

### Metadata

* ID: 0efd6a6a-b52a-f6a2-d98b-f245b55115ff 
* Service: **dotnet-csharp**
* Sub-service: **fundamentals**

[Related Issues](https://github.com/dotnet/docs/issues?q=is%3Aissue+is%3Aopen+95025282-20a0-ded8-c6d2-3b8ffff600c4)

**Comment by BillWagner** [comment] 2024-12-16 14:22
Hi @SetTrend 

The type of collection created is implementation specific, and details aren't provided by design. The compiler and runtime might change the actual type in future implementations.

The code you reference specifies that the type must be a type that implements the target interface. The compiler will generate a collection implements that interface.

In cases where you want a specific concrete type, you should specify the target type required.  You can learn more in [this article](https://learn.microsoft.com/dotnet/csharp/language-reference/operators/collection-expressions#conversions),

I'll close this as by-design. I am curious why you need this information in this context.

**Closed by BillWagner** 2024-12-16 14:22 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/svc, fundamentals/subsvc

**Comment by SetTrend** [comment] 2024-12-16 15:53
Hi @BillWagner,

I was just curious to know because different kinds of collections have different runtime performance footprints (arrays are fast to access while slow to resize, Lists vice versa). So I was interested in what the compiler will generate.

**Comment by BillWagner** [comment] 2024-12-17 14:55
@SetTrend 

> I was just curious to know because different kinds of collections have different runtime performance footprints (arrays are fast to access while slow to resize, Lists vice versa). So I was interested in what the compiler will generate.

It's not specified because the compiler can choose how to create the collection in the most efficient manner. A great resource to get that kind of detailed implementation information is the [LDM](https://github.com/dotnet/csharplang/tree/main/meetings) notes on collection expressions. The [feature specification](https://learn.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-12.0/collection-expressions#design-meetings) links to most of the pertinent discussions.

**Comment by SetTrend** [comment] 2024-12-18 17:57
Thanks for pointing me!
