### ISSUE TITLE
[Breaking change]: .NET 8.0.100 SDK requires MSBuild 17.7 to load and 17.8 to target net8.0

### ISSUE THREAD

**Issue by marcpopMSFT** [dotnet/docs#36659] opened 2023-08-11 20:07 UTC
### Description

We've updated the minimum required MSBuild and Visual Studio version for the 8.0.100-rc.1 SDK to be 17.7.

Change to the minimum
https://github.com/dotnet/sdk/pull/34565

Other document with this information
https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules

Prior breaking change notice
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/vs-msbuild-version

### Version

.NET 8 RC 1

### Previous behavior

Prior previews would load into 17.6 (though the preview 7 SDK would error when used with 17.6).

### New behavior

The .NET 8.0.100-rc.1 SDK will not even load in 17.6 or earlier VS.

### Type of breaking change

- [ ] **Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation.
- [ ] **Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully.
- [X] **Behavioral change**: Existing binaries may behave differently at run time.

### Reason for change

Planned minimum version update

### Recommended action

Customers should update their version of Visual Studio to 17.7.0 or newer or use global.json to pin to an older SDK.

### Feature area

SDK

**Comment by gewarren** [comment] 2023-09-05 20:42
@marcpopMSFT This looks like a duplicate of #35480?

**Comment by marcpopMSFT** [comment] 2023-09-05 21:48
Looks like it. I guess I was proactive and already filed this.

**Closed** 2023-09-05 21:54 UTC
Labels: doc-idea, breaking-change, Pri1
