### ISSUE TITLE
Formatting colour is incorrect

### ISSUE THREAD

**Issue by tlordello** [dotnet/docs#23863] opened 2021-04-21 13:45 UTC
The code example in this page has incorrect colour formatting. After the commented line "' The following is the only Case clause that evaluates to True.", the rest of the code is shown in red, as though it was a comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca8b932e-d836-483e-d0bf-3e7e74161a52
* Version Independent ID: 4c706a34-5017-b2b8-88ad-0c7b1d0506d8
* Content: [Select...Case Statement - Visual Basic](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/select-case-statement)
* Content Source: [docs/visual-basic/language-reference/statements/select-case-statement.md](https://github.com/dotnet/docs/blob/main/docs/visual-basic/language-reference/statements/select-case-statement.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by BillWagner** [comment] 2021-04-21 14:09
Ping @mimisasouvanh 

Where should we move this for the site team to address?

**Comment by Youssef1313** [comment] 2021-04-21 15:24
Duplicate of https://github.com/dotnet/docs/issues/23848.

**Comment by BillWagner** [comment] 2021-04-22 13:01
closing as duplicate.

**Closed by BillWagner** 2021-04-22 13:01 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-visualbasic/prod
