### ISSUE TITLE
HTTP 404 for Debian and Ubuntu repos

### ISSUE THREAD

**Issue by pitervergara** [dotnet/docs#25557] opened 2021-08-10 22:35 UTC
The URL  https://packages.microsoft.com/debian/10/prod returning HTTP 404. Same happens for the Debian 9 URL and Ubnuntu. 

I believe it's related with  #ubuntu repositories #24717 and #6381 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c3310a1-6a2e-ca98-9618-8f3d729eafdd
* Version Independent ID: ab01f0aa-d1c0-df64-b0f9-ee211d45001f
* Content: [Install .NET on Debian - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian)
* Content Source: [docs/core/install/linux-debian.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-debian.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-08-10 23:08
Thank you for opening this issue. I do know a lot of different sites have been down today or intermittent connectivity. The docs aren't the source of the problem though. It will probably be tracked in the .NET github repo

**Comment by adegeo** [comment] 2021-08-10 23:08
Duplicate of https://github.com/dotnet/core/issues/6559

**Closed by adegeo** 2021-08-10 23:08 UTC
Labels: :watch: Not Triaged, Pri1, dotnet/prod, dotnet-install/tech
