### ISSUE TITLE
CA2248 message is misleading or wrong

### ISSUE THREAD

**Issue by puchs** [dotnet/docs#24052] opened 2021-05-05 12:23 UTC
Visual Studio will flag the two calls of HasFlag in the following small test program with CA2248:
Message	CA2248	This call will always returns 'false' because the enum type 'NoFlags' is not marked with 'FlagsAttribute'	

```csharp
using System;

namespace enumtests {

  public enum NoFlags { 
    One,Two
  }
  class Program {
    static void Main() {
      NoFlags noFlags = NoFlags.Two;
      Console.WriteLine($"{noFlags.HasFlag(NoFlags.One)} {noFlags.HasFlag(NoFlags.Two)}");
    }
  }
}
```

But the result will actually be "True True". This means that it always returns true for the "0" flag ("One" in this case.) and it will return true if one asks for the actual value of the variable ("Two" in this case.). If one sets the variable noFlags to NoFlags.One the result is "True False". The statement of CA2248 is therefore IMHO wrong and/or misleading. 

Tested with .NET 5.0 and Visual Studio 16.9.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f687388-f567-39fb-fe08-ab813f1bbc39
* Version Independent ID: 7f48169d-ddf9-306e-f981-57e57778b92c
* Content: [CA2248: Provide correct enum argument to Enum.HasFlag (code analysis) - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2248)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2248.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2248.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @mavasani
* Microsoft Alias: **mavasani**

**Comment by adegeo** [comment] 2021-05-05 14:29
@puchs Hello! The documentation here seems correct, and the problem is Visual Studio is reporting the wrong suggestion/error, correct? If so, please close this issue and use the Feedback tool in Visual Studio to report this problem. Thanks!

**Closed** 2021-05-06 07:45 UTC
Labels: Pri2, dotnet-fundamentals/prod, needs-more-info
