### ISSUE TITLE
"Add-ins and Extensibility" links not working

### ISSUE THREAD

**Issue by wstaelens** [dotnet/docs#4326] opened 2018-02-06 13:58 UTC
https://docs.microsoft.com/en-us/dotnet/framework/add-ins/index

The links in this section are not working:

> Discovery and Activation

> You can activate an add-in by using a token from a collection that represents the add-ins found from an information store. Add-ins are found by searching for the type that defines the host's view of the add-in. You can also find a specific add-in by the type that defines the add-in. The information store consists of two cache files: the pipeline store and the add-in store. 
> 
> For information about updating and rebuilding the information store, see Add-in Discovery. For information about activating add-ins, see Add-in Activation and How to: Activate Add-ins with Different Isolation and Security. 
> 

for example clicking the "see Add-in Discovery." link results in:
https://msdn.microsoft.com/library/5d268dde-11df-4c4d-a022-f58d88bbc421 

> This topic is no longer available
> 
> 
> We're sorry—the topic that you requested is no longer available. Use the search box to find related information.

same for other links on that page.
(possible that other links also don't work, didn't click on every link.)

**Comment by wstaelens** [comment] 2018-02-06 14:14
same for https://docs.microsoft.com/en-us/dotnet/framework/add-ins/walkthrough-create-extensible-app

and a lot of other pages... 😞

**Comment by mairaw** [comment] 2018-02-06 23:14
Yes, we're slowly fixing those links. We have tons of those. We have issue #2037 keeping track of reviewing these msdn links.

**Comment by mairaw** [comment] 2018-02-07 00:14
Duplicate of #2037

**Closed by mairaw** 2018-02-07 00:14 UTC
