### ISSUE TITLE
Fix type signature for MatchCollection

### ISSUE THREAD

**Issue by alfredmyers** [dotnet/docs#5608] opened 2018-05-25 14:35 UTC
The [type signature](https://github.com/dotnet/dotnet-api-docs/blob/bccdeb19b6e77427d5689159edb4f4b6bd673470/xml/System.Text.RegularExpressions/MatchCollection.xml#L2-L6) for MatchCollection corresponds to the .NET Framework's implementation 

`public class MatchCollection : ICollection`

... not the .NET Core's implementation

`public class MatchCollection : IList<Match>, IReadOnlyList<Match>, IList`

Do the docs support providing different type signatures for different versions and/or implementations of the APIs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e16a7933-4b45-c84f-0953-1e5c34dc137c
* Version Independent ID: cf29f7db-43b7-d5ae-7070-958617dd278e
* Content: [MatchCollection Class (System.Text.RegularExpressions)](https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.matchcollection?view=netframework-4.7.2)
* Content Source: [xml/System.Text.RegularExpressions/MatchCollection.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Text.RegularExpressions/MatchCollection.xml)
* Service: **unspecified**
* Product: **.net**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2018-05-25 17:28
Thanks for pointing this out, @alfredmyers. We don't support multiple type signatures for different versions/implementations, at least as far as I know.  @dend, is that accurate?

**Comment by alfredmyers** [comment] 2018-05-25 18:05
Here's another instance: X509Certificate [added IDisposable in .NET Framework 4.6](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate?view=netframework-4.7.2#remarks)

**Comment by mairaw** [comment] 2018-05-30 00:16
Duplicate of https://github.com/MicrosoftDocs/feedback/issues/222

**Closed by mairaw** 2018-05-30 00:16 UTC
Labels: :file_folder: Repo - dotnet-api-docs, Source - Docs.ms, duplicate, external, triaged
