### ISSUE TITLE
Images in this page are duplicate

### ISSUE THREAD

**Issue by altwohill** [dotnet/docs#20194] opened 2020-08-20 04:29 UTC
All the images in this page are the same, but the captions are different. It looks like the other images did not migrate correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a749bf08-a45c-e441-6125-8a2bfbe7a75e
* Version Independent ID: f2fca24c-5b4e-bbf9-45d5-f7af0149ac5a
* Content: [Azure Monitor](https://docs.microsoft.com/en-us/dotnet/architecture/cloud-native/azure-monitor)
* Content Source: [docs/architecture/cloud-native/azure-monitor.md](https://github.com/dotnet/docs/blob/master/docs/architecture/cloud-native/azure-monitor.md)
* Product: **dotnet-architecture**
* Technology: **cloud-native**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by sughosneo** [comment] 2020-09-10 12:02
Hello @altwohill , thank you for your feedback. 

There is already an active PR #19936 on this topic.
This is the duplicate of https://github.com/dotnet/docs/issues/18738

So closing this issue as of now. If you have any further question, please feel free to reopen it.

**Closed by sughosneo** 2020-09-10 12:02 UTC
Labels: :book: guide - Cloud Native, :books: Area - .NET Architecture Guide, :watch: Not Triaged
