### ISSUE TITLE
dotnet-install.sh error on linux mint 19 "unable to locate zlib"

### ISSUE THREAD

**Issue by lonewolfnsp** [dotnet/docs#17857] opened 2020-04-15 10:27 UTC
I followed the instruction to invole the shell script in terminal in linux mint 19, after "chmod +x". I got an error: unable to locate zlib. probable prerequisite missing: install zlib

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e484a9-5e0c-eb3e-1413-7b507c4fa07d
* Version Independent ID: 5bc7caa5-f1c2-d7d5-fe02-80c65cca9672
* Content: [dotnet-install scripts - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script)
* Content Source: [docs/core/tools/dotnet-install-script.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-install-script.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

I tried running the dotnet-install.sh in linux mint 19 and got an error: WARNING: unable to locate zlib. probable prerequisite missing, install zlib. 

I typed "sudo apt install zlib1g-dev" to install zlib and tried runnign the script again.. and it's still giving the same error.. what should I do, short of manually keying all the commands myself to install the SDK, which was what I did before.. just trying to see if there's a less painful way to install the SDK on new linux machjnes..  but it seems this script is even more painful.  :'( 

please help.. I'm on a clean install of Linux mint 19, which is based on ubvuntu 19.

**Comment by tdykstra** [comment] 2020-04-15 16:17
@johnbeisner Can you help with this?

**Comment by lonewolfnsp** [comment] 2020-04-16 18:25
I wish I could but I'm not that familiar with Linux and shell scripting
myself. The original script is way beyond me. Well I just copied the
commands into gedit and run them in the terminal line by line and it got
the job done. Yeah it's a stupid way, I know.

One thing though, the runtime installation might benefit from having an
ansible playbook since whoever needs it is going to have to install it on
all the machines that run it. I'm learning ansoble now. Initially was
thinking of using playbook to install the SDK. If you guys can put it in
chocolaty that may work for runtime installation on Windows machines. So
sorry about this.

Just a side note I've tried the shell script on Ubuntu 18 as well, so it's
safe to say it couldn't work on Ubuntu 28 and 19 since mint 19 is based on
Ubuntu 19.

**Comment by tdykstra** [comment] 2020-05-01 01:43
@donJoseLuis can you help with this?

**Comment by wes-novack** [comment] 2020-05-02 00:43
Same issue on Fedora 32

**Comment by bozturkMSFT** [comment] 2020-06-19 12:39
We already have an issue tracking this here https://github.com/dotnet/install-scripts/issues/6 . Can we close this one @tdykstra ?

**Comment by tdykstra** [comment] 2020-06-19 17:28
Closing as duplicate of https://github.com/dotnet/install-scripts/issues/6

**Closed by tdykstra** 2020-06-19 17:28 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, P2, product-question, waiting-on-feedback
