### ISSUE TITLE
Server 2019 does not support 4.8.1 

### ISSUE THREAD

**Issue by battaile** [dotnet/docs#41576] opened 2024-06-27 13:24 UTC
### Type of issue

Other (describe below)

### Description

As documented here among other places, 4.8.1 isn't supported by server 2019:
https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies

Verified that an error saying OS not supported occurs if you attempt to install it.
<img width="413" alt="attempt to install 4.8.1 on server 2019 fails" src="https://github.com/dotnet/docs/assets/939551/2d279991-e05e-478f-a33d-8a062ba7e410">

### Page URL

https://learn.microsoft.com/en-us/dotnet/framework/install/on-server-2019

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/framework/install/on-server-2019.md

### Document Version Independent Id

0bde7c8f-df1a-eb9c-1879-1401b63ef040

### Article author

@adegeo

### Metadata

* ID: a353245f-339b-60d2-d5c9-c8ac50b401fe 
* Service: **dotnet-framework**
* Sub-service: **install-deployment**

**Comment by adegeo** [comment] 2024-06-27 14:19
Thank you for reporting this.

**Comment by adegeo** [comment] 2024-06-27 14:20
Duplicate of #41341

**Closed by adegeo** 2024-06-27 14:20 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-framework/svc, install-deployment/subsvc
