### ISSUE TITLE
sugges

### ISSUE THREAD

**Issue by NAIVEddd** [dotnet/docs#6390] opened 2018-07-10 09:32 UTC
#markup-extensions  This section's code should be in one block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76affea4-8d55-0f6d-0c39-ec25a8dcc0dc
* Version Independent ID: bebc890a-fdd2-525a-207c-cf23b56060ff
* Content: [XAML Overview (WPF)](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/xaml-overview-wpf#feedback)
* Content Source: [docs/framework/wpf/advanced/xaml-overview-wpf.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/xaml-overview-wpf.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-07-13 22:55
Thank you for your feedback @NAIVEddd. This is a migration issue that we have in our backlog to fix it. A duplicate issue tracking the same work can be found at #2994.

**Comment by mairaw** [comment] 2018-07-13 22:55
Duplicate of #2994

**Closed by mairaw** 2018-07-13 22:55 UTC
