### ISSUE TITLE
I guess there is something wrong in the following code snippet

### ISSUE THREAD

**Issue by asloppyone** [dotnet/docs#11744] opened 2019-04-09 11:37 UTC
public void Search(string directory, string searchPattern, bool searchSubDirs = false)
{
    if (searchSubDirs)
    {
        var allDirectories = Directory.GetDirectories(directory, "*.*", SearchOption.AllDirectories);
        var completedDirs = 0;
        var totalDirs = allDirectories.Length + 1;
        foreach (var dir in allDirectories)
        {
            directoryChanged?.Invoke(this,
                new SearchDirectoryArgs(dir, totalDirs, completedDirs++));
            // Recursively search this child directory:
            SearchDirectory(dir, searchPattern);
        }
        // Include the Current Directory:
        directoryChanged?.Invoke(this,
            new SearchDirectoryArgs(directory, totalDirs, completedDirs++));
        SearchDirectory(directory, searchPattern);
    }
    else
    {
        SearchDirectory(directory, searchPattern);
    }
}

Actually, I dont't think just call SearchDirectory in all cases will make it run recursively. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b37f1a-cd59-d9e5-067b-30ea5f26e5cc
* Version Independent ID: d2078536-1ee3-5b60-3872-f2635d245cc2
* Content: [Standard .NET event patterns](https://docs.microsoft.com/en-us/dotnet/csharp/event-pattern)
* Content Source: [docs/csharp/event-pattern.md](https://github.com/dotnet/docs/blob/master/docs/csharp/event-pattern.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by asloppyone** [comment] 2019-04-09 11:40
I guess the author was intended to write as this:
public void Search(string directory, string searchPattern, bool searchSubDirs = false)
{
    if (searchSubDirs)
    {
        var allDirectories = Directory.GetDirectories(directory, "*.*", SearchOption.AllDirectories);
        var completedDirs = 0;
        var totalDirs = allDirectories.Length + 1;
        foreach (var dir in allDirectories)
        {
            directoryChanged?.Invoke(this, new SearchDirectoryArgs(dir, totalDirs, completedDirs++));
            // Recursively search this child directory:
            Search(dir, searchPattern,True);
        }
        // Include the Current Directory:
        directoryChanged?.Invoke(this,new SearchDirectoryArgs(directory, totalDirs, completedDirs++));
        Search(directory, searchPattern,false);
    }
    else
    {
        SearchDirectory(directory, searchPattern);
    }
}

**Comment by Thraka** [comment] 2019-05-17 00:03
This is not a bug. The `Directory.GetDirectories(directory, ".", SearchOption.AllDirectories);` line actually pulls every directory from the base directory in a single call. This list of **all** directories is iterated on and there is no need to call the `Search` method recursively.

Closing this issue. 😄

**Closed by Thraka** 2019-05-17 00:03 UTC
Labels: :books: Area - C# Guide, P1, Source - Docs.ms
