### ISSUE TITLE
Reversed translation

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#13979] opened 2019-08-21 16:38 UTC
@NextTurn commented on [Mon Aug 19 2019](https://github.com/dotnet/docs.zh-cn/issues/432)

https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/regular-expression-language-quick-reference

https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md

https://github.com/dotnet/docs.zh-cn/blob/a5269e6005f5b3f8771f39bf6574bca1fb1ae867/docs/standard/base-types/regular-expression-language-quick-reference.md#L84

The `\A` example translation is reversed.

---

@srvbpigh commented on [Mon Aug 19 2019](https://github.com/dotnet/docs.zh-cn/issues/432#issuecomment-522640682)

Hello, @NextTurn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-08-21 16:51
Hi team, 
the reported error was found in the zh-CN page but it could be also present in the source
can you please check this?
thanks in advance

**Comment by mairaw** [comment] 2019-08-21 22:58
@CeciAc the text is correct in English so I'll close this one by design.

It seems this is purely a translation issue since you reverse some but not all strings? I can't read Chinese so I don't know what the translation means.

![image](https://user-images.githubusercontent.com/12971179/63474054-81fda680-c42c-11e9-88ed-acd09d031579.png)

**Closed** 2019-08-21 22:59 UTC
Labels: by-design, loc

**Comment by imba-tjd** [comment] 2019-08-21 23:12
What his `Reversed` means is that he fixed this once, but the translation team broke this again.

**Comment by mairaw** [comment] 2019-08-21 23:16
Thanks @imba-tjd for the clarification. Still I cannot do anything in the source to fix this. The localization team needs to fix this issue. /cc @JasonCard

**Comment by NextTurn** [comment] 2019-08-22 01:11
I believe that I've fixed this several times.
