### ISSUE TITLE
 OrderedDictionary is not typed

### ISSUE THREAD

**Issue by bravequickcleverfibreyarn** [dotnet/docs#42837] opened 2024-10-04 14:57 UTC
### Type of issue

Typo

### Description

From https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/libraries#ordereddictionarytkey-tvalue

> Since the early days of .NET, the [OrderedDictionary](https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary) type has supported this scenario, but only in a non-generic manner, with keys and values typed as [OrderedDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ordereddictionary-2) collection, which provides an efficient, generic type to support these scenarios.

I belive wording should be something like:

- either: _"Since the early days of .NET, the [OrderedDictionary](https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary) type has supported this scenario, but only in a non-generic manner, with keys and values typed as [OrderedDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ordereddictionary-2) collection provides an efficient, generic type to support these scenarios."_
- or: _"Since the early days of .NET, the [OrderedDictionary](https://learn.microsoft.com/en-us/dotnet/api/system.collections.specialized.ordereddictionary) type has supported this scenario, but only in a non-generic manner, **newly** with keys and values typed as [OrderedDictionary<TKey,TValue>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ordereddictionary-2) collection, which provides an efficient, generic type to support these scenarios."_

### Page URL

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/libraries

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/core/whats-new/dotnet-9/libraries.md

### Document Version Independent Id

0c8c7059-86a1-e5df-32e6-fae6fdc5cae0

### Article author

@gewarren

### Metadata

* ID: 7c184200-3411-aa5b-ba3f-0b4a3ce0f589 
* Service: **dotnet-fundamentals**

**Comment by gewarren** [comment] 2024-10-08 16:50
Dupe of #42664.

**Closed by gewarren** 2024-10-08 16:50 UTC
Labels: Pri1, dotnet-fundamentals/svc
