### ISSUE TITLE
Please update the document and include .Net Core 2.1

### ISSUE THREAD

**Issue by szyb** [dotnet/docs#7028] opened 2018-08-15 17:21 UTC
Please update the document and include .Net Core 2.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb8b774-c6f0-8235-6964-15219baf2ea7
* Version Independent ID: 6819a4a7-7527-d8c7-e132-767f7344e00e
* Content: [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)
* Content Source: [docs/standard/net-standard.md](https://github.com/dotnet/docs/blob/master/docs/standard/net-standard.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment] 2018-08-15 18:05
2.1 doesn't need to be added to the topic. The table lists the minimum version for each .NET Standard version. So closing this one by design. But please let me know if I missed anything.

**Closed by mairaw** 2018-08-15 18:05 UTC
Labels: :books: Area - .NET Guide, Source - Docs.ms, by-design, resolved
