### ISSUE TITLE
Error in code section 'protected internal' page

### ISSUE THREAD

**Issue by paulkamer** [dotnet/docs#25667] opened 2021-08-17 16:00 UTC
The second code example on this pagecontains an error. A line of code is out-commented, which should not be.

I suggest you change:
```csharp
// Assembly2.cs
// Compile with: /reference:Assembly1.dll
class DerivedClass : BaseClass
{
    static void Main()
    {
        var baseObject = new BaseClass();
        var derivedObject = new DerivedClass();

        // Error CS1540, because myValue can only be accessed by
        // classes derived from BaseClass.
        // baseObject.myValue = 10;

        // OK, because this class derives from BaseClass.
        derivedObject.myValue = 10;
    }
}
```
To:
```csharp
// Assembly2.cs
// Compile with: /reference:Assembly1.dll
class DerivedClass : BaseClass
{
    static void Main()
    {
        var baseObject = new BaseClass();
        var derivedObject = new DerivedClass();

        // Error CS1540, because myValue can only be accessed by
        // classes derived from BaseClass.
        baseObject.myValue = 10;

        // OK, because this class derives from BaseClass.
        derivedObject.myValue = 10;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650c563e-748e-7ad7-fea9-0504549a56ab
* Version Independent ID: ad6dac17-6e62-1447-e85d-e502ae39a343
* Content: [protected internal - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/protected-internal)
* Content Source: [docs/csharp/language-reference/keywords/protected-internal.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/protected-internal.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @sputier
* Microsoft Alias: **wiwagn**

**Comment by paulkamer** [comment] 2021-08-17 16:18
Note: I realize this style of out-commenting lines of code that triggers errors is quite common. However on some pages, such lines are not out-commented, see for example: 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/internal#example-2

```C#
// Assembly2_a.cs  
// Compile with: /reference:Assembly2.dll  
public class TestAccess
{  
   static void Main()
   {  
      var myBase = new BaseClass();   // Ok.  
      BaseClass.intM = 444;    // CS0117  
   }  
}  
```

**Comment by BillWagner** [comment] 2021-08-18 13:42
adding @tdykstra 

We are inconsistent here. Do we have any guidance for all of docs as to which style (commented out, or uncommented) for examples of code with errors?

**Comment by tdykstra** [comment] 2021-08-18 15:58
Not that I know of.  The appropriate place for that, if we had it or if we add it, is the code-in-docs article -- [internal ](https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master) and [external](https://docs.microsoft.com/en-us/contribute/code-in-docs).

**Comment by tdykstra** [comment] 2021-08-18 16:14
@BillWagner I can add something to that doc, but which direction should we take?

* Code that causes compile errors -- comment out, include explanation in text and code comments
* Code that is not recommended but compiles -- don't comment out, include warning in text and code comments

**Comment by BillWagner** [comment] 2021-08-19 16:04
@tdykstra 

> Code that causes compile errors -- comment out, include explanation in text and code comments

I have a slight preference for this option. That's because it will make it easier for us to have our CI build work correctly. It's a slight preference though.

**Comment by BillWagner** [comment] 2021-11-01 13:32
I'm closing this as by design. We want the code that introduces errors to be commented out.

**Closed by BillWagner** 2021-11-01 13:32 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-csharp/prod, csharp-language-reference/tech
