### ISSUE TITLE
Full Event Sourcing in preventing loss of domain event published to event bus subscribed by other microservicess

### ISSUE THREAD

**Issue by PingPongSet** [dotnet/docs#13695] opened 2019-08-01 22:09 UTC
I want to find out exactly how full event sourcing pattern can prevent the issue of losing event when publishing domain event to event bus.

&gt; For this scenario, using the full Event Sourcing (ES) pattern is one
&gt; of the best approaches, if not the best.

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events

Specifically, the scenario is that Catalog microservice updated a product price and published a ProductPRiceChanged event. How can full ES prevent loss of that event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 384e5c2c-d3ba-b5ba-260b-65b8e900b78e
* Version Independent ID: 534541bb-0ffe-f7d6-8cc3-22da784c96a6
* Content: [Subscribing to events](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/subscribe-events)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/subscribe-events.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/subscribe-events.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by mvelosop** [comment] 2019-08-08 14:59
Closing as duplicate of https://github.com/dotnet-architecture/eShopOnContainers/issues/1111

**Closed by mvelosop** 2019-08-08 14:59 UTC
Labels: :book: guide - .NET Microservices, :books: Area - .NET Guide, :card_file_box: Technology - .NET Architecture, :watch: Not Triaged, Source - Docs.ms
