### ISSUE TITLE
Sample code throws exception

### ISSUE THREAD

**Issue by LarryLan** [dotnet/docs#6794] opened 2018-08-02 10:45 UTC
ArgumentOutOfRangeException: Training feature column 'Features' must be a known-size vector of R4, but has type: Vec&lt;R4&gt;.
Could you please provide a fix?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Use ML.NET in a sentiment analysis binary classification scenario](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/tutorials/sentiment-analysis.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by pkulikov** [comment] 2018-08-02 16:06
@LarryLan have you tried to run the original code provided in the [dotnet/samples](https://github.com/dotnet/samples) GitHub repo:
https://github.com/dotnet/samples/tree/master/machine-learning/tutorials/SentimentAnalysis

Does it work for you?

**Comment by jkshan** [comment] 2018-09-19 04:56
I'm positive for both the test sentences.

**Comment by JRAlexander** [comment] 2018-09-25 21:12
@LarryLan, closing this as I'm assuming resolved. Please reopen if you are still having issues.

**Comment by landis22b** [comment] 2018-10-17 16:19
I get the same issue.

**Comment by JRAlexander** [comment] 2018-10-17 16:21
@landis22b - Did you type it or download the sample? Thanks!

**Comment by landis22b** [comment] 2018-10-17 16:40
In case it helps

Stacktrace:
```
SentimentAnalysis git:(master) ✗ dotnet run
Warning: Term map for output column 'Features_WordExtractor' contains no entries.
Not adding a normalizer.

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: Training feature column 'Features' must be a known-size vector of R4, but has type: Vec<R4>.
Parameter name: data
   at Microsoft.ML.Runtime.Training.TrainerUtils.CheckFeatureFloatVector(RoleMappedData data)
   at Microsoft.ML.Runtime.FastTree.FastTreeBinaryClassificationTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Runtime.Training.TrainerEstimatorBase`2.Microsoft.ML.Runtime.ITrainer.Train(TrainContext context)
   at Microsoft.ML.Runtime.Data.TrainUtils.TrainCore(IHostEnvironment env, IChannel ch, RoleMappedData data, ITrainer trainer, RoleMappedData validData, ICalibratorTrainer calibrator, Int32 maxCalibrationExamples, Nullable`1 cacheData, IPredictor inputPredictor)
   at Microsoft.ML.Runtime.EntryPoints.LearnerEntryPointsUtils.Train[TArg,TOut](IHost host, TArg input, Func`1 createTrainer, Func`1 getLabel, Func`1 getWeight, Func`1 getGroup, Func`1 getName, Func`1 getCustom, ICalibratorTrainerFactory calibrator, Int32 maxCalibrationExamples)
   at Microsoft.ML.Runtime.FastTree.FastTree.TrainBinary(IHostEnvironment env, Arguments input)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.ML.Runtime.EntryPoints.EntryPointNode.Run()
   at Microsoft.ML.Runtime.EntryPoints.EntryPointGraph.RunNode(EntryPointNode node)
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAllNonMacros()
   at Microsoft.ML.Runtime.EntryPoints.JsonUtils.GraphRunner.RunAll()
   at Microsoft.ML.Legacy.LearningPipeline.Train[TInput,TOutput]()
   at SentimentAnalysis.Program.Train() in /Users/lbeezy/Projects/SentimentAnalysis/SentimentAnalysis/Program.cs:line 69
   at SentimentAnalysis.Program.Main(String[] args) in /Users/lbeezy/Projects/SentimentAnalysis/SentimentAnalysis/Program.cs:line 28
   at SentimentAnalysis.Program.<Main>(String[] args)
```

sdk and runtime information:
```
➜  SentimentAnalysis git:(master) ✗ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.403
 Commit:    04e15494b6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.403/

Host (useful for support):
  Version: 2.1.5
  Commit:  290303f510

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by landis22b** [comment] 2018-10-17 16:46
I've additionally updated my .csproj to be an exact copy of https://raw.githubusercontent.com/dotnet/samples/master/machine-learning/tutorials/SentimentAnalysis/SentimentAnalysis.csproj
Previously I was using a slightly different language version.
This also has had no effect.

**Comment by pkulikov** [comment] 2018-10-17 16:53
@landis22b you use the `float` type, not `double`, as well?

**Comment by landis22b** [comment] 2018-10-17 17:00
SentimentData.Sentiment is a float.

**Comment by landis22b** [comment] 2018-10-17 18:49
Turns out, there is an unclose quoted field in the sample data on line 83.
After fixing that there still appear to be some issues. Doing some research on those now.

**Comment by landis22b** [comment] 2018-10-17 19:16
Related issue https://github.com/dotnet/machinelearning/issues/245
As it turns out, I've resolved the underlying cause.
It works fine with or without the closing quote on line 83 and simply rejects that row.
The cause of the issue is Visual Studio for Mac replaces tabs with spaces on non code files.  :|

**Closed** 2018-11-08 16:53 UTC
Labels: :books: Area - ML.NET Guide, Source - Docs.ms, needs-more-info

**Comment by JRAlexander** [comment] 2018-11-08 16:54
Thanks. Now resolved so closing!
