### ISSUE TITLE
Support / Info for other RHEL-based distros since CentOS 8 was retired

### ISSUE THREAD

**Issue by Mighty-Monarch** [dotnet/docs#28928] opened 2022-04-06 07:03 UTC
Since CentOS 8 was killed off by RedHat in favor of the Stream distro, the new alternates to RHEL8 should be listed here:

- AlmaLinux 8
- Rocky Linux 8
- Oracle Linux 8

Most former Users of CentOS have migrated to one of these distros.

Same goes for PowerShell Core for Linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e92ae0e3-2f90-5eeb-ed2c-bdfb85c5eaca
* Version Independent ID: 1850602d-6b92-1449-c8bd-116e36fc0f26
* Content: [Install .NET on Linux distributions - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux)
* Content Source: [docs/core/install/linux.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment] 2022-04-07 23:48
Related to #28915

**Comment by adegeo** [comment] 2022-05-16 18:47
duplicate of #28915

**Closed by adegeo** 2022-05-16 18:47 UTC
Labels: :watch: Not Triaged, Pri2, dotnet/prod, dotnet-install/tech
