### ISSUE TITLE
The "New object initialization syntax" example code does not work in Focus Mode

### ISSUE THREAD

**Issue by bunda3d** [dotnet/docs#16413] opened 2019-12-27 04:24 UTC
This code does not run (I have not tried it locally in VS or VSCode--could be a 'using' declaration issue, but that shouldn't be an issue in Focus Mode) : 
-------------
public class Path : IEnumerable&lt;Point3D&gt;
{
    private List&lt;Point3D&gt; points = new List&lt;Point3D&gt;();
    public IEnumerator&lt;Point3D&gt; GetEnumerator() =&gt; points.GetEnumerator();
    IEnumerator IEnumerable.GetEnumerator() =&gt; points.GetEnumerator();

    public void Add(Point3D pt) =&gt; points.Add(pt);
}

public static class Extensions
{
    public static void Add(this Path path, double x, double y, double z) =&gt; path.Add(new Point3D(x, y, z));
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a3686c2-4c73-5686-0da9-abc38c74aeec
* Version Independent ID: ca995f80-9375-e9ca-b855-6e6893581e23
* Content: [Explore C# 6 - Try the new features in C# 6 interactively, using your browser](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/csharp-6?tutorial-step=10&source=docs#feedback)
* Content Source: [docs/csharp/tutorials/exploration/csharp-6.yml](https://github.com/dotnet/docs/blob/master/docs/csharp/tutorials/exploration/csharp-6.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2019-12-27 09:02
The new object initialization syntax works fine for me.

![image](https://user-images.githubusercontent.com/31348972/71510647-35255300-2898-11ea-8940-8ee82cc456dd.png)

**Comment by bunda3d** [comment] 2019-12-27 12:31
That is not the code I posted.

**Comment by Youssef1313** [comment] 2019-12-27 14:16
@bunda3d, My fault.
I think the example you're referring to misses the following using statements:

```csharp
using System.Collections;
using System.Collections.Generic;
```

and misses a Point3D declaration which could be like this:

```csharp
public class Point3D
{
    private double _x;
    private double _y;
    private double _z;

    public Point3D(double x, double y, double z)
    {
        _x = x;
        _y = y;
        _z = z;
    }
}
```

You may need to wait for @BillWagner to review this. I also think that it will be better to add an entry point (Main method) to the example for further illustration.

**Comment by bunda3d** [comment] 2019-12-27 15:24
I was thinking it needed "using" statements, but that doesn't usually need to be considered in the "focus mode" editor, for whatever reasons.

**Comment by BillWagner** [comment] 2020-01-02 15:13
Thanks for writing this @bunda3d 

The problem is due to an issue in the underlying try.net experience used on docs. An update will get deployed this month, and that will enable us to fix this.

I've added this to the list of planned work for this sprint.

/cc @LadyNaggaga @aprilspeight

**Comment by tdykstra** [comment] 2021-01-20 01:44
Closing as duplicate of #20753

**Closed by tdykstra** 2021-01-20 01:44 UTC
Labels: :books: Area - C# Guide, :woman_technologist: .NET Interactive, P1, Pri2, doc-bug, dotnet-csharp/prod
