### ISSUE TITLE
Framework design guidelines for .NET Core seem only a subset of relevant design guidelines

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/docs#10332] opened 2019-02-06 02:21 UTC
The Framework design guidelines here
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/index

seem only a subset of the older version (marked with "not being updated") here
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229042(v%3dvs.100)

For example, the new version seems to be missing the chapter "choosing between properties and methods" https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms229054(v=vs.100)

Was this intentional subsetting?

If not I think this would be valuable to fix - these guidelines are important/influential.

**Comment by mairaw** [comment] 2019-02-07 02:10
I don't recall removing that intentionally. @rpetrusha would you know?

I do know that we purposely removed the following one:
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/b1yfkh5e(v%3dvs.100)

in favor of:
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

Because that one generated the most comments and we couldn't react to them because of the copyright issues. But I've already asked @KrzysztofCwalina once if he intended to update the book. 😉

**Comment by rpetrusha** [comment] 2019-02-07 23:33
No @mairaw, we didn't do that intentionally. The history of index.md shows no significant changes other than the redirection of the Dispose article, so I suspect that it was never migrated from CAPS.

**Comment by mairaw** [comment] 2019-04-29 21:45
They don't exist in CAPS either 😮 So the clean-up must have happened in DxStudio. 

So, do we want to restore those sections? I can bring them from the archive.

**Comment by rpetrusha** [comment] 2019-04-29 22:23
The problem is that the archived content is excerpted from the first edition of the book, while the non-archived content is excerpted from the second edition. I doubt that we have the right to republish it.

**Comment by mairaw** [comment] 2019-04-29 23:04
Ah, good point @rpetrusha! So probably we should close this one by design.

**Comment by rpetrusha** [comment] 2019-04-29 23:26
Yes. I'll close it as by design, @mairaw and @danmosemsft.

**Closed by rpetrusha** 2019-04-29 23:26 UTC
Labels: :book: guide - Framework Design Guidelines, :books: Area - .NET Guide, P2, waiting-on-feedback
