### ISSUE TITLE
"Notes to Callers" sections have a weird style

### ISSUE THREAD

**Issue by Librazy** [dotnet/docs#3880] opened 2017-12-06 19:14 UTC
Some methods have a [incorrectly rendered "Notes to Callers"](https://docs.microsoft.com/en-us/dotnet/api/system.string.trimend?view=netframework-4.7.1) section, which has a weird style.  
![qq 20171207025901](https://user-images.githubusercontent.com/2211542/33679838-cedc2ab6-dafa-11e7-9464-53e08a1fd93d.png)
After some searching, it looks like that some other pages containing "Notes to Callers" looks just fine.  
[Example of correctly rendered "Notes to Callers"](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsshell?view=visualstudiosdk-2017)
![qq 20171207030051](https://user-images.githubusercontent.com/2211542/33679933-0cff408a-dafb-11e7-8515-c9670ce6786f.png)

**Comment by mairaw** [comment] 2017-12-06 19:22
Thanks for your feedback @Librazy. We're aware of this issue and a fix should happen soon.

Duplicate of #3652

**Comment by mairaw** [comment] 2017-12-06 19:23
Duplicate of #3652

**Closed by mairaw** 2017-12-06 19:22 UTC
