### ISSUE TITLE
How about "simple" localization

### ISSUE THREAD

**Issue by RobinHood70** [dotnet/docs#6124] opened 2018-06-25 19:11 UTC
So, Microsoft's recommended localization process for WPF is to modify your build process, build a custom tool, run several commands from that newly built tool, and honestly, I stopped reading after that because this entire process is incomprehensible. Perhaps this documentation could include a link to some of the older methods, like the project Resource files and/or the "for dummies" version of localization? Not everyone who's localizing their app has this level of knowledge. There are small-time programmers, hobbyists, and people who are in a time-crunch who want simple localization. This level of complexity is just unacceptable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [How to: Localize an Application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application#feedback)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by JRAlexander** [comment] 2018-06-25 20:11
Hi @RobinHood70, this is a duplicate of #3623. Thanks for your feedback and know this is on the list.

**Closed by JRAlexander** 2018-06-25 20:11 UTC
Labels: :card_file_box: Technology - WPF, Source - Docs.ms, duplicate
