### ISSUE TITLE
Client example

### ISSUE THREAD

**Issue by wiezykrwi** [dotnet/docs#6075] opened 2018-06-21 14:11 UTC
It says in the description that UdpClient is used, then goes and uses Socket.
Example with UdpClient:
        UdpClient udpClient = new UdpClient("192.168.1.255", 11000);
        byte[] sendbuf = Encoding.ASCII.GetBytes(args[0]);  
        udpClient.Send(sendbuf, sendbuf.Length);
        Console.WriteLine("Message sent to the broadcast address"); 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f7ffdc6-548a-fd6e-c4ed-27c2c497abb0
* Version Independent ID: 1c827898-93da-abc0-d0ae-6a8354c26409
* Content: [Using UDP Services](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/using-udp-services)
* Content Source: [docs/framework/network-programming/using-udp-services.md](https://github.com/dotnet/docs/blob/master/docs/framework/network-programming/using-udp-services.md)
* Product: **dotnet-framework**
* GitHub Login: @mcleblanc
* Microsoft Alias: **markl**

**Comment by svick** [comment] 2018-06-21 15:05
This seems to be a duplicate of https://github.com/dotnet/docs/issues/6070.

**Comment by rpetrusha** [comment] 2018-06-21 17:58
Thanks for submitting your feedback, @wiezykrwi; we appreciate it. 

@svick is right; this is a duplicate of #6070, I'll mark it as duplicate and close it.

**Closed by rpetrusha** 2018-06-21 17:58 UTC
Labels: :card_file_box: Technology - NCL, :file_folder: Repo - docs, Area - .NET Framework Guide, duplicate
