### ISSUE TITLE
Error 404 

### ISSUE THREAD

**Issue by AngelJC** [dotnet/docs#25558] opened 2021-08-10 22:48 UTC
Hello, I'm trying download and get error 404 in all versions available for Ubuntu
https://packages.microsoft.com/config/ubuntu/XX.XX/packages-microsoft-prod.deb

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-08-10 23:09
Thank you for opening this issue. I do know a lot of different sites have been down today or intermittent connectivity. The docs aren't the source of the problem though. It will probably be tracked in the .NET github repo

**Comment by adegeo** [comment] 2021-08-10 23:09
Duplicate of dotnet/core#6559

**Closed by adegeo** 2021-08-10 23:09 UTC
Labels: :watch: Not Triaged, Pri1, dotnet/prod, dotnet-install/tech

**Comment by adegeo** [comment] 2021-08-10 23:30
Tracked in issue dotnet/core#6560
