### ISSUE TITLE
No inheritance from EventWaitHandle on documentation for AutoResetEvent

### ISSUE THREAD

**Issue by 23Alex24** [dotnet/docs#8688] opened 2018-10-27 14:02 UTC
Inheritance Object =&gt; MarshalByRefObject =&gt; WaitHandle =&gt; AutoResetEvent
But must be 
Inheritance Object =&gt; MarshalByRefObject =&gt; WaitHandle =&gt; EventWaitHandle =&gt; AutoResetEvent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f5d171-3991-9728-7044-a65e84b95f25
* Version Independent ID: 2365e1e5-f64e-00ac-e825-bf727f73fa45
* Content: [AutoResetEvent Class (System.Threading)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.autoresetevent?redirectedfrom=MSDN&view=netcore-2.1)
* Content Source: [xml/System.Threading/AutoResetEvent.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Threading/AutoResetEvent.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by pkulikov** [comment] 2018-10-27 14:33
@23Alex24 this is the duplicate (or related) of the MicrosoftDocs/feedback#616

**Comment by 23Alex24** [comment] 2018-10-27 15:35
Yes, I think the essence of the problem is the same, but this ticket belongs to AutoResetEvent

**Comment by mairaw** [comment] 2018-11-19 23:03
Given the root cause is the same, I'm closing this issue. All APIs that have a different hierarchy between the two platforms will have the same issue. Once MicrosoftDocs/feedback#616 is fixed, this should be fixed too.

**Closed by mairaw** 2018-11-19 23:03 UTC
Labels: :books: Area - API Reference, :file_folder: Repo - dotnet-api-docs, Source - Docs.ms, docs-experience, duplicate, external
