### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by adibradfield** [dotnet/docs#5695] opened 2018-05-30 20:54 UTC
The link for the CodeDOM Quick Reference is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ceb2afd-2c2e-1c86-9839-54a3c8b0bd7e
* Version Independent ID: 01453121-3a20-8e81-5906-895bfec826f7
* Content: [Dynamic Source Code Generation and Compilation](https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/dynamic-source-code-generation-and-compilation)
* Content Source: [docs/framework/reflection-and-codedom/dynamic-source-code-generation-and-compilation.md](https://github.com/dotnet/docs/blob/master/docs/framework/reflection-and-codedom/dynamic-source-code-generation-and-compilation.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by svick** [comment] 2018-05-31 12:51
Are you talking about the last link in the article, in the Related Sections section? That link links to http://msdn.microsoft.com/library/c77b8bfd-0a32-4e36-b59a-4f687f32c524, which works for me.

**Comment by rpetrusha** [comment] 2018-05-31 16:16
The link works for me also, @adibradfield. I'm going to close this issue, since we can't reproduce the broken link. If it continues to be a problem, please respond to this issue to let us know.

**Closed by rpetrusha** 2018-05-31 16:16 UTC

**Comment by adibradfield** [comment] 2018-06-01 08:07
I can confirm that I am no longer getting the issue
