### ISSUE TITLE
Order of selected indices

### ISSUE THREAD

**Issue by riehlj2002** [dotnet/docs#5771] opened 2018-06-03 21:17 UTC
It would be helpful if the documentation included whether the selected indices are guaranteed to be in order. Looking at the reference source it appears that they will be (https://referencesource.microsoft.com/#System.Web/UI/WebControls/ListControl.cs,d5438019c2f3dec6), but if that's not guaranteed in future framework revisions it would be helpful to know that too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 608bd194-054a-7813-1e72-ef1e07bc663e
* Version Independent ID: b1314425-943f-3ade-b9e3-5e884ac3512e
* Content: [ListBox.GetSelectedIndices Method (System.Web.UI.WebControls)](https://docs.microsoft.com/en-us/dotnet/api/system.web.ui.webcontrols.listbox.getselectedindices?view=netframework-4.7.2#System_Web_UI_WebControls_ListBox_GetSelectedIndices)
* Content Source: [xml/System.Web.UI.WebControls/ListBox.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Web.UI.WebControls/ListBox.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment] 2018-07-09 21:02
Thanks, @riehlj2002, for your comment. With occasional exceptions (such as APIs that return sorted elements from a collection), the order of items returned from a collection is undefined; it's an implementation detail that is subject to change in the future. For that reason, we've generally left the discussion of the order of returned items undocumented throughout our documentation set. 
I'm going to close this issue as by design. If you disagree, please feel free to respond.

**Closed** 2018-07-09 21:02 UTC
Labels: :file_folder: Repo - dotnet-api-docs, Area - API Reference, Source - Docs.ms, by-design, triaged
