### ISSUE TITLE
Missing version of .NET Framework: 528033

### ISSUE THREAD

**Issue by prochan2** [dotnet/docs#12230] opened 2019-05-07 12:12 UTC
I've just installed the latest updates on Windows Server 2016 running in a VM in Azure Resouce Manager. Following this guide, I get version 528033, which is not listed here. The Version entry in the same subkey says 4.8.03745.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2115da38-e95e-46fc-1e2d-da88ef92c6cf
* Version Independent ID: a3790e8a-0654-851b-c991-ab7382025406
* Content: [How to: Determine which .NET Framework versions are installed](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#feedback)
* Content Source: [docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/how-to-determine-which-versions-are-installed.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2019-05-08 21:04
528033 is a pre-release value, @prochan2. The article documents only release values.

Since this behavior is by design, I'll close this issue.

**Closed by rpetrusha** 2019-05-08 21:04 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - AppCompat, Source - Docs.ms, by-design
