### ISSUE TITLE
The "XML Markup Compatibility Specification" link is dead

### ISSUE THREAD

**Issue by BillHally** [dotnet/docs#6696] opened 2018-07-27 08:36 UTC
The "XML Markup Compatibility Specification" link is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24bd8086-9dca-a3a9-9407-efb73bf12cc9
* Version Independent ID: c54654c5-f11c-a654-62f6-84afcae9aa5a
* Content: [mc:ProcessContent Attribute](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/mc-processcontent-attribute)
* Content Source: [docs/framework/wpf/advanced/mc-processcontent-attribute.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/mc-processcontent-attribute.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-07-31 09:05
Duplicate of #6695

**Comment by mairaw** [comment] 2018-07-31 09:06
Given that this is about the same FwLink, I'll be closing this as a duplicate.

**Closed by mairaw** 2018-07-31 09:06 UTC
Labels: :card_file_box: Technology - WPF, P2, Source - Docs.ms, duplicate, migration-fixes, triaged
