### ISSUE TITLE
Weird &lrm; in the TOC for articles ending with #

### ISSUE THREAD

**Issue by svick** [dotnet/docs#1823] opened 2017-03-29 12:00 UTC
I see a weird `&lrm;` sequence (HTML character reference for the left-to-right mark character) in the TOC for the articles *Tour of C#* and *What's new in C#*:

![](https://cloud.githubusercontent.com/assets/287848/24453154/fe021fd4-1486-11e7-9a79-899e813097e5.png)

This seems to be affecting all articles whose titles end with # (a few more examples are under the *Using F# on Azure* node).

**Comment by BillWagner** [comment] 2017-03-29 14:21
@DuncanmaMSFT This is new.  Is this a regression in the most recent build?

**Comment by DuncanmaMSFT** [comment] 2017-03-29 14:29
It is a new bug in our template. We had to add a bunch of logic to treat # special to avoid it being treated like punctuation when viewing the page in right-to-left languages. Seems like it has an issue.

On Mar 29, 2017 7:21 AM, Bill Wagner <notifications@github.com> wrote:

@DuncanmaMSFT<https://github.com/DuncanmaMSFT> This is new. Is this a regression in the most recent build?

**Comment by geoffrk00** [comment] 2017-03-29 15:18
Is there a url that we can look at that has this problem? I am not able to reproduce this locally.

**Comment by BillWagner** [comment] 2017-03-29 15:47
@geoffrk00 Here are a couple: https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/
https://docs.microsoft.com/en-us/dotnet/articles/csharp/whats-new/



Look at the first TOC node. You'll find this anywhere an H1 header ends in '#' C# and F# docs do that a lot.  /cc @cartermp

**Comment by geoffrk00** [comment] 2017-03-29 18:29
thank you for the link. 
We have fixed this and it will be deployed soon

**Comment by BillWagner** [comment] 2017-07-18 21:01
Closing as this has now been fixed.

**Closed by BillWagner** 2017-07-18 21:01 UTC
Labels: external
