### ISSUE TITLE
Use TransactionScope instead of BeginTransaction

### ISSUE THREAD

**Issue by Rookian** [dotnet/docs#8131] opened 2018-10-06 11:19 UTC
How do I use EnableRetryOnFailure with multiple DbContexts and TransactionScope?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57452ceb-e885-d193-d813-d7baf7291cbc
* Version Independent ID: 3bd0845a-a3dc-b71d-d7eb-0fd581f11d4c
* Content: [Implement resilient Entity Framework Core SQL connections](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections)
* Content Source: [docs/standard/microservices-architecture/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections.md](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/implement-resilient-applications/implement-resilient-entity-framework-core-sql-connections.md)
* Product: **dotnet**
* GitHub Login: @CESARDELATORRE
* Microsoft Alias: **wiwagn**

See also: [13530](https://github.com/aspnet/EntityFrameworkCore/issues/13530)

**Comment by mairaw** [comment] 2018-10-08 21:32
@mvelosop @CESARDELATORRE @divega can you look at this feedback for the microservices e-book related to EF Core?

**Comment by divega** [comment] 2018-10-11 04:09
@mairaw I think we can close this as duplicate. @Rookian has already asked this question at https://github.com/aspnet/EntityFrameworkCore/issues/13530. Unfortunately we haven't got to it yet in triage, but we will.

**Comment by mairaw** [comment] 2018-10-11 07:17
Ok. Thanks @divega.

**Comment by mairaw** [comment] 2018-10-11 07:17
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/13530

**Closed by mairaw** 2018-10-11 07:17 UTC
Labels: :book: e-book - .NET Microservices, :books: Area - .NET Guide, :card_file_box: Technology - .NET Architecture, Source - Docs.ms, product-question, waiting-on-feedback
