### ISSUE TITLE
Documentation on the switch expression is missing

### ISSUE THREAD

**Issue by vmilev** [dotnet/docs#14889] opened 2019-10-02 08:17 UTC
This page is about the switch statement. Is it going to be expanded to include documentation about switch expression (https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#more-patterns-in-more-places) or is it going to be a separate page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d9cc47-5caf-184a-0ad6-cb968850be7a
* Version Independent ID: f058bf17-04e9-9e23-05c7-66c1864445ad
* Content: [C# switch statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/switch#feedback)
* Content Source: [docs/csharp/language-reference/keywords/switch.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/switch.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Thraka** [comment] 2019-10-02 16:27
I would gather it would be a different page under that same parent. Considering they are different selection mechanisms and it discusses **Switch Expression** vs **Switch Statement**.

@BillWagner has a project tracking C# 8.0 updates. I'll add this issue to that project and let @BillWagner  take it on from here. 

Thanks!

**Comment by Thraka** [comment] 2019-10-02 16:33
GitHub is acting weird. I can't set backlog as the milestone..

**Comment by BillWagner** [comment] 2019-10-03 13:43
I set the milestone to November. I want to update all the reference pages between now and .NET Core 3.1.

**Comment by KUTlime** [comment] 2019-12-20 22:04
It is end of December and no documentation on switch expression! Come on guys, you could better.

**Comment by pkulikov** [comment] 2019-12-20 22:57
@KUTlime currently the `switch` expression is briefly explained at the "What's new in C# 8.0" page:
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions

What, if any, do you think is missing there?

**Comment by KUTlime** [comment] 2019-12-20 23:43
@pkulikov You just said it - *briefly*.

What is missing:

- example with use of ternary operator
- example with use of `when` condition
- example with pattern matching
- discussion when to use it and why
- runtime benefits if any

I know how to do it. I'm trying to say that this could be helpful for newcomers to C# 8.0. The switch expressions are more or less equal to the switch statements. The switch expression deserves their own page with more examples and a structure as the switch statement page.

**Comment by pkulikov** [comment] 2019-12-20 23:51
@KUTlime thank you! 

I wonder what made you put the example with use of ternary operator first? Why particularly this operator?

**Comment by KUTlime** [comment] 2019-12-21 00:02
Officially, I chose from-the-most-simple-use scenario ordering.

Unofficially, last two hours, I was analysing a weir problem in VS when switch expression and ternary operator was used. This brought me to this page. The problem was caused by R# and solved by update to the R# latest version but for a brief moment, I was convinced that ternary operator can't be used together with switch expression simply because of the fact that I wasn't able to find any proof that I'm wrong or vice versa.

**Comment by pkulikov** [comment] 2019-12-21 12:12
By the way, the following C# 8.0 pattern matching tutorial contains examples with the `switch` expression:
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/pattern-matching

In particular, it covers:

> - example with use of `when` condition
> - example with pattern matching

**Comment by BillWagner** [comment] 2020-03-11 21:06
I'm starting to work on this, and it's exposing some flaws in the current organization of the language reference.  I'd like feedback on the following ordered set of thoughts:

1. The new information really doesn't belong on this page. The *switch expression* is different than the *switch statement*:
    - Most obviously, it is an *expression*, not a *statement*.
    - The syntax has many differences. `=>` instead of `:` and `break`
    - The switch arms must be expressions (not statements, or blocks)
1. This article is already rather long. I'm concerned with making it much longer by adding the information on switch expressions.
1. The obvious location for a new article on switch expressions would be an **Expressions** section. But, there isn't one. All expressions are in the **Operators** section. 

That leads me to this conclusion:  

***Is this the right time to rename the  "Operators" section "Expressions", and add the new article there?***

I propose "Yes".

If so, which of the sub-sections should be named **<something> expressions** instead of **<something> operators**? 

I propose renaming these:

- Member access expressions
- ?: expression
- await expression
- default expression

Should there be others? Should some be dropped?

/cc @pkulikov for input.

**Comment by pkulikov** [comment] 2020-03-12 06:54
@BillWagner I agree mostly with you and have had the similar thoughts about expressions.

> Is this the right time to rename the "Operators" section "Expressions", and add the new article there?

Yes, however I suggest to rename the section to **Operators and expressions** (or **Expressions and operators**). What do you think?

As for renamings, I don't think `?:` should be renamed, as it's widely known as "ternary operator", also "C# conditional operator" [is more checked in Google](https://trends.google.com/trends/explore?q=C%23%20conditional%20operator,C%23%20conditional%20expression) than "C# conditional expression".

As for the member access, I think it should be "Member access operators and expressions", because invocation `()` is more an expression, but range `..` is commonly referred as an operator.

With other two I agree and have some more, so:

- await expression
- default expression
- stackalloc expression
- nameof expression

What do you think?
As soon as we agree on renamings, I would like to submit the corresponding PR. There we can discuss the remaining minor details if any, and after it's merged, there are no blocks for the `switch` expression. Is that fine with you?

**Comment by BillWagner** [comment] 2020-03-12 14:51
> What do you think?

I like your additions @pkulikov 

>  submit the corresponding PR. There we can discuss the remaining minor details if any, and after it's merged, there are no blocks for the switch expression. Is that fine with you?

Great plan. I agree. I'll start working on a draft, and then rebase once I've seen your PR.

**Closed** 2020-03-24 16:56 UTC
Labels: :books: Area - C# Guide, :card_file_box: Technology - C# Language Reference, P1, doc-enhancement
