### ISSUE TITLE
Deserialization from UTF-8

### ISSUE THREAD

**Issue by JCKodel** [dotnet/docs#30998] opened 2022-09-02 20:02 UTC
The page says that `Json.Deserialize(ReadOnlySpan<Byte>)` is capable of understanding UTF-8 text, but this is not true!

For instance:

```csharp
foreach (var file in _env.ContentRootFileProvider.GetDirectoryContents(path)) {
  Span<byte> fileContents = stackalloc byte[(int)file.Length];

  file.CreateReadStream().Read(fileContents);
  _dataSchemas[file.Name[..^".json".Length]] = JsonSerializer.Deserialize<DataSchema>(fileContents)!;
}
```

will fail, because a .json file created inside Visual Studio 2022 (as a text file) contains an UTF-8 BOM (0xef, 0xbb, 0xbf) and the deserializer complains about that 0xef byte in the first position.

Either `Json.Deserialize` is not compatible with UTF-8 (which is allowed to have a BOM), or it have a bug that don't consider BOM at all, so we have to treat this exception ourselves:

```csharp
if (fileContents[0] == 0xef) {
  _dataSchemas[file.Name[..^".json".Length]] = JsonSerializer.Deserialize<DataSchema>(fileContents[3..])!;
} else {
  _dataSchemas[file.Name[..^".json".Length]] = JsonSerializer.Deserialize<DataSchema>(fileContents)!;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 588ae32f-3429-143f-824c-5ab2d046d24a
* Version Independent ID: 002f9f2a-48d1-0671-a079-b99b9f6bab58
* Content: [How to serialize and deserialize JSON using C# - .NET](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to)
* Content Source: [docs/standard/serialization/system-text-json-how-to.md](https://github.com/dotnet/docs/blob/main/docs/standard/serialization/system-text-json-how-to.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by svick** [comment] 2022-09-03 13:29
This is the intended behavior, see https://github.com/dotnet/runtime/issues/37327#issuecomment-637857177:

>  its by design that the `Stream`-consuming APIs look for the BOM, while the `byte[]` and `string`-consuming APIs don't. The general idea behind this is that the BOM is a marker that says "the rest of the data after this BOM is UTF-xx text". Once you have a `ROS<byte>` or a `string` that is that text, any U+FEFF that occurs _is part of the text itself_ and shouldn't be stripped.

In your case, I think the best option is to directly deserialize the `Stream` returned by `CreateReadStream()`. This has the added advantage that it bypasses your incorrect use of `Read()` and your dangerous and inefficient use of `stackalloc`.

**Comment by gewarren** [comment] 2022-09-26 18:43
Thanks @svick. I'm going to close this issue now.

**Closed by gewarren** 2022-09-26 18:43 UTC
Labels: support-request, Pri1, dotnet-fundamentals/prod
