### ISSUE TITLE
Documentation runs off page and x-scroll is disabled

### ISSUE THREAD

**Issue by mikeditchagh** [dotnet/docs#19222] opened 2020-06-25 13:02 UTC
Documentation runs off the side of the page and there's no scrollbar to allow the user to scroll over to read the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d476d66c-4f04-3742-cf90-4177aceb4138
* Version Independent ID: 482be47f-3dec-5470-5e83-88afd9c2bcca
* Content: [Retargeting Changes for Migration from .NET Framework 4.7.2 to 4.8](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/retargeting/4.7.2-4.8)
* Content Source: [docs/framework/migration-guide/retargeting/4.7.2-4.8.md](https://github.com/dotnet/docs/blob/master/docs/framework/migration-guide/retargeting/4.7.2-4.8.md)
* Product: **dotnet-framework**
* Technology: **dotnet-appcompat**
* GitHub Login: @chlowell
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment] 2020-06-25 13:14
Hi @mikeditchagh - thank you for posting this issue. I'll fix this right away.

**Comment by mikeditchagh** [comment] 2020-06-25 13:18
You're welcome. Just trying to help! :)

**Comment by gewarren** [comment] 2020-06-25 20:31
Dupe of #19220?

**Comment by IEvangelist** [comment] 2020-06-26 12:45
> Dupe of #19220?

This issue

**Comment by mikeditchagh** [comment] 2020-06-26 12:52
To further clarify the issue I reported, it's only the "Windows Form" section of the page.

**Comment by IEvangelist** [comment] 2020-06-26 12:59
Hi @mikeditchagh - we found it to be a problem elsewhere as well. Thanks again for reporting it, we're getting fixed and appreciate the heads up on this. Hope you have a great weekend.

**Closed** 2020-06-26 19:39 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - AppCompat, P0, doc-bug
