### ISSUE TITLE
.cctor

### ISSUE THREAD

**Issue by vladomelchuk** [dotnet/docs#8002] opened 2018-10-02 15:13 UTC
I suppose that cctor also would be trigerred if we have and call custom method from struct. Something like 

    class Program
    {
        static void Main(string[] args)
        {
           MyStruct str = new MyStruct();

           str.DoWork();
        }
    }

    struct MyStruct
    {
        public void DoWork()
        {
        }
    }

Not only if we reference static member or explicitly declared constructor called?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 758450b3-62d1-800d-91fd-98e75b3acc60
* Version Independent ID: 5e6f2879-7292-b686-193b-de9a5a0a2e5e
* Content: [Structs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/structs)
* Content Source: [spec/structs.md](https://github.com/dotnet/csharplang/blob/master/spec/structs.md)
* Product: **dotnet-csharp**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2018-10-29 21:39
Thanks @vladomelchuk 

I think @gafter is looking at this same issue.  Should I move it to the dotnet/csharplang repo?

**Comment by svick** [comment] 2018-10-29 22:02
@BillWagner There's already an issue about this on csharplang: https://github.com/dotnet/csharplang/issues/1948.

**Comment by BillWagner** [comment] 2018-10-29 23:19
Closing as a duplicate of dotnet/csharplang#1948

**Closed by BillWagner** 2018-10-29 23:19 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, triaged
