### ISSUE TITLE
Add C# 9 to version history

### ISSUE THREAD

**Issue by jovton** [dotnet/docs#24661] opened 2021-06-14 07:03 UTC
Hi. Please add C# 9 to language version history. The page currently only goes to version 8. Thanks and kind regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d252158-0367-77c8-1816-dbc385c5c40b
* Version Independent ID: 575872e5-6273-f8f6-e3e2-2b911cd9d009
* Content: [The history of C# - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-version-history)
* Content Source: [docs/csharp/whats-new/csharp-version-history.md](https://github.com/dotnet/docs/blob/main/docs/csharp/whats-new/csharp-version-history.md)
* Product: **dotnet-csharp**
* Technology: **csharp-whats-new**
* GitHub Login: @erikdietrich
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-06-14 13:38
Closing as a duplicate of #22885

**Closed by BillWagner** 2021-06-14 13:38 UTC
Labels: :watch: Not Triaged, Pri1, csharp-whats-new/tech, dotnet-csharp/prod
