### ISSUE TITLE
Where to find all .CSPROJ Options?

### ISSUE THREAD

**Issue by obsidience** [dotnet/docs#15872] opened 2019-11-16 19:35 UTC
VSCode, by default has a very simplistic build step in tasks.json which relies more on the project file rather than these command line options.  Where do we find all available build/publish options with msbuild v16+ inside the .CSPROJ (not pubxml). 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910cd365-d63a-00dc-417c-db017f83bf6f
* Version Independent ID: 5e495ddd-140e-de5c-a793-d4a9f88be51e
* Content: [dotnet build command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#feedback)
* Content Source: [docs/core/tools/dotnet-build.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-build.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by Thraka** [comment] 2019-11-18 19:53
Duplicate of #2642

**Comment by Thraka** [comment] 2019-11-18 19:59
@obsidience Hello

Currently we have https://docs.microsoft.com/en-us/dotnet/core/tools/csproj as the way to explore the csproj file format. We have plans to completely redo this article, it just keeps getting pushed back :( Currently people kind of look around https://github.com/dotnet/sdk/tree/master/src/Tasks/Microsoft.NET.Build.Tasks/targets to understand how things get transformed, which is horrible to do.

I'm going to close this as duplicate.

**Closed by Thraka** 2019-11-18 19:59 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, product-question

**Comment by obsidience** [comment] 2019-11-18 22:31
Understood, thank you for the info and responding Thraka!
