### ISSUE TITLE
Add cultures that do not follow the xx-xx language/country/region convention

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#12029] opened 2019-04-25 17:58 UTC
@LokiMidgard commented on [Thu Apr 25 2019](https://github.com/dotnet/docs.de-de/issues/138)

>When you package your application's resources, you must name them using the resource naming conventions that the common language runtime expects. The runtime identifies a resource by its culture name. Each culture is given a unique name, which is usually a combination of a *two-letter, lowercase culture name* associated with a language and, if required, a *two-letter, uppercase subculture name* associated with a country or region. The subculture name follows the culture name, separated by a dash (-). Examples include ja-JP for Japanese as spoken in Japan, en-US for English as spoken in the United States, de-DE for German as spoken in Germany, or de-AT for German as spoken in Austria. See the National Language Support (NLS) API Reference at the Go Global Developer Center for a complete list of culture names.

Generating a Resource using Visual Studio (2019) and setting language to different simplified chinise versions result in following files
 - Form1.zh-Hans.resx
 - Form1.zh-Hans-HK.resx
 - Form1.zh-Hans-MO.resx

The subculture does not consists of a two-letter subculture code.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4e742bf0-abf8-259c-5194-3687febd38b0
* Version Independent ID: 6d1d9bfb-6174-6215-befe-641babe8a746
* Content: [Verpacken und Bereitstellen von Ressourcen in .NET-Apps](https://docs.microsoft.com/de-de/dotnet/framework/resources/packaging-and-deploying-resources-in-desktop-apps#resource-naming-conventions)
* Content Source: [docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md](https://github.com/dotnet/docs.de-de/blob/live/docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md)
* Product: **dotnet-framework**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment] 2019-04-25 18:01
Hi team, 
I'm moving this here since the contributor is making a suggestion on the original documentation
best

**Comment by rpetrusha** [comment] 2019-04-25 23:09
The documentation indicates that this is *usually* a combination of a two-letter language code and a two-letter country/region code. I'm going to close this as By Design; the qualification is here is adequate, even if some culture/region names violate the rule.

**Comment by LokiMidgard** [comment] 2019-04-26 07:23
Thanks for the fast response.

@rpetrusha The documentation also includes some samples. 
>[...] Examples include ja-JP for Japanese [etc ...]
Could it make sense to include a sample that violate this *usally*. This would emphasize that there are exceptions.

**Comment by rpetrusha** [comment] 2019-04-29 16:06
It might be helpful to add some examples with code that are more than two letters in length, @LokiMidgard. I'll reopen this issue and add it to our backlog, as well as to the community contributor's project.

**Closed** 2019-10-01 17:31 UTC
Labels: :books: Area - .NET Guide, Source - Docs.ms, example-request
