### ISSUE TITLE
Issue downloading Ubuntu .deb file from microsoft.com

### ISSUE THREAD

**Issue by youradds** [dotnet/docs#24718] opened 2021-06-17 08:17 UTC
[Enter feedback here]
As per your documentation page: https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu 

There is an issue downloading this file:

wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 
sudo dpkg -i packages-microsoft-prod.deb 

The file is a 404.

The weird thing, is that if you navigate to: https://packages.microsoft.com/config/ubuntu/20.04/ , you can see the file there. You click on it, and its a 404.

I can't install it until this is fixed :(

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by aleks-ivanov** [comment] 2021-06-17 09:14
Was just about to create an issue for this.

All Ubuntu .deb files are 404, since 2hrs ago.

**Comment by youradds** [comment] 2021-06-17 09:26
haha just my luck it happened 2 hours ago, just when I was about to us it :D

**Comment by lastseenjustnow** [comment] 2021-06-17 09:32
Step 20/25 : RUN ACCEPT_EULA=Y apt-get -y install msodbcsql17 --fix-missing
 ---> Running in ea24424f2562
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libodbc1 multiarch-support odbcinst odbcinst1debian2 unixodbc unixodbc-dev
Suggested packages:
  unixodbc-bin
The following NEW packages will be installed:
  msodbcsql17 multiarch-support unixodbc
The following packages will be upgraded:
  libodbc1 odbcinst odbcinst1debian2 unixodbc-dev
4 upgraded, 3 newly installed, 0 to remove and 37 not upgraded.
Need to get 1,721 kB of archives.
After this operation, 253 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 multiarch-support amd64 2.28-10 [215 kB]
Err:2 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:3 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc-dev amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:4 https://packages.microsoft.com/debian/10/prod buster/main amd64 odbcinst1debian2 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:5 https://packages.microsoft.com/debian/10/prod buster/main amd64 libodbc1 amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:6 https://packages.microsoft.com/debian/10/prod buster/main amd64 unixodbc amd64 2.3.7
  404  Not Found [IP: 104.214.230.139 443]
Err:7 https://packages.microsoft.com/debian/10/prod buster/main amd64 msodbcsql17 amd64 17.7.2.1-1
  404  Not Found [IP: 104.214.230.139 443]

same here with another packages

**Comment by aleks-ivanov** [comment] 2021-06-17 14:20
@youradds @lastseenjustnow they just fixed it, so it works now 🙂

**Comment by youradds** [comment] 2021-06-17 14:24
Thanks for the heads up @aleks-ivanov

**Comment by adegeo** [comment] 2021-06-17 15:45
I believe the main discussion is at dotnet/sdk#18304 hopefully it gets working 100% soon!

**Comment by adegeo** [comment] 2021-06-17 15:45
Duplicate of #24711

**Closed by adegeo** 2021-06-17 15:45 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
