### ISSUE TITLE
Awesome Docs..

### ISSUE THREAD

**Issue by mamukundan** [dotnet/docs#6447] opened 2018-07-13 14:00 UTC
The documentation is pretty good. Thanks for your efforts. I just thought it would help if we could have a Prev and Next button as that would ease the navigation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36515e3d-e8ab-5dfb-d5e9-332f767d9607
* Version Independent ID: adddc073-2413-197a-e74c-20a71d4abcd3
* Content: [Get Started - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/index)
* Content Source: [docs/csharp/getting-started/index.md](https://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment] 2018-07-13 18:50
@mamukundan thanks for your kind words. We have another issue in our backlog tracking the same request: #817

Do you mind if I ask you in what kind of device are you reading the docs? Is it on mobile, desktop, etc?

**Comment by mairaw** [comment] 2018-07-13 18:50
Duplicate of #817

**Closed by mairaw** 2018-07-13 18:50 UTC

**Comment by nguyenthanhliemfc** [comment] 2019-04-15 01:42
I like read docs on my PC, then I can try in Visual Studio at the same time!
