### ISSUE TITLE
Needs updating and breaking changes for Core 5.0

### ISSUE THREAD

**Issue by paul1956** [dotnet/docs#20450] opened 2020-09-04 01:26 UTC
Name have changed for .Net 5.0 and information is not included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks in SDK-style projects - .NET](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment] 2020-09-04 02:15
Dupe of #20297.

**Closed by gewarren** 2020-09-04 02:15 UTC
Labels: :books: Area - .NET Guide, :watch: Not Triaged
