### ISSUE TITLE
Deprecated analyzers recommended in this article

### ISSUE THREAD

**Issue by jwooley** [dotnet/docs#25648] opened 2021-08-16 03:19 UTC
[Enter feedback here]
The article recommends use of Microsoft.NetFramework.Analyzers and FxCopAnalyzers both of which have been deprecated. Please update to recommended alternatives.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 171973c7-c225-a776-793f-cf67869ea0b8
* Version Independent ID: f26f0129-8073-cc7e-1b3a-0002ad3af932
* Content: [Code analyzers for .NET Framework](https://docs.microsoft.com/en-us/dotnet/framework/code-analyzers)
* Content Source: [docs/framework/code-analyzers.md](https://github.com/dotnet/docs/blob/main/docs/framework/code-analyzers.md)
* Product: **dotnet-framework**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-08-17 10:35
Duplicate of https://github.com/dotnet/docs/issues/22613.

cc @gewarren @mavasani

**Comment by gewarren** [comment] 2021-08-17 17:06
Thanks @Youssef1313. Closing this as a duplicate.

**Closed by gewarren** 2021-08-17 17:06 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-framework/prod
