### ISSUE TITLE
old msdn links are broken

### ISSUE THREAD

**Issue by simonmcconnell** [dotnet/docs#17607] opened 2020-03-26 10:27 UTC
there are a few broken links: for Unchecked.defaultof, Array.zeroCreate and AllowNullLiteral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae21b87-1505-41b6-8fc9-1cfa59c90ed5
* Version Independent ID: 514581e9-9a8d-3771-928a-5d079c809a42
* Content: [Null Values - F#](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/values/null-values#feedback)
* Content Source: [docs/fsharp/language-reference/values/null-values.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/values/null-values.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by gewarren** [comment] 2020-03-27 17:24
This is probably the same problem as #17579.

**Comment by gewarren** [comment] 2020-04-07 19:22
Thanks for reporting this. Closing as a duplicate of #17557.

**Closed by gewarren** 2020-04-07 19:22 UTC
Labels: :books: Area - F# Guide, duplicate
