### ISSUE TITLE
Ocelot is is no longer maintained

### ISSUE THREAD

**Issue by muratcabuk** [dotnet/docs#32760] opened 2022-11-27 09:36 UTC
Ocelot is is no longer maintained

you can check the github page : https://github.com/ThreeMammals/Ocelot/issues/1539

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10ce8eaa-b3ff-9b69-fea1-131eed36b9ec
* Version Independent ID: 771d9f72-b506-79ef-5398-030c1705ee9a
* Content: [Implementing API Gateways with Ocelot](https://learn.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md](https://github.com/dotnet/docs/blob/main/docs/architecture/microservices/multi-container-microservice-net-applications/implement-api-gateways-with-ocelot.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by muratcabuk** [comment] 2022-11-27 09:40
dublicate : https://github.com/dotnet/docs/issues/28235

**Comment by gewarren** [comment] 2023-03-29 22:45
Closing as duplicate of #27445.

**Closed by gewarren** 2023-03-29 22:45 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-architecture/prod, microservices/tech
