### ISSUE TITLE
What about Nullable struct?

### ISSUE THREAD

**Issue by gpetrou** [dotnet/docs#11834] opened 2019-04-15 06:30 UTC
Should there be some information here on whether to use or not the in-modifier with Nullable struct?
For example should we have
public void Method(int? arg) {}
or
public void Method(in int? arg) {}
?
ErrorProne.NET for example flags this as a special case: https://github.com/SergeyTeplyakov/ErrorProne.NET/blob/5cc962abfaf0005890dd0a9fba46a9e304a8a450/src/ErrorProne.NET.StructAnalyzers/TypeExtensions.cs#L28

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac8804c7-6acd-ab2a-4e14-0b99265969a5
* Version Independent ID: 183efcbd-a781-d303-f9cd-1c22da1676de
* Content: [Write safe and efficient C# code](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code#feedback)
* Content Source: [docs/csharp/write-safe-efficient-code.md](https://github.com/dotnet/docs/blob/master/docs/csharp/write-safe-efficient-code.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-04-22 21:46
That's a great question @gpetrou 

I'd have to benchmark that case.

Ping @jaredpar if the C# team has any general guidance on nullable structs as `in` parameters.

**Comment by jaredpar** [comment] 2019-04-22 21:56
They should not be marked as `readonly` because a `Nullable<T>` is a `struct` which is non-readonly. There was an attempt to make `Nullable<T>` into a `readonly struct` but that was a breaking change. The reasoning is detailed here:

https://github.com/dotnet/corefx/pull/24997#issuecomment-346523578

In short though the problem is the backing `T` was never marked `readonly` and making it `readonly` now can cause observable side effects. Consider for example a `ToString` implementation that memoized the result. Before that was cached in the `Nullable<T>` and now it's not. Hence it remains a standard `struct` and should follow the same rules.

**Comment by gpetrou** [comment] 2019-04-23 07:18
Thanks for the explanation. I will open an issue in Error.Prone repository to fix this.

**Closed** 2019-04-25 18:23 UTC
Labels: :books: Area - C# Guide, P1, Source - Docs.ms
