### ISSUE TITLE
No information about Span<T> and friends

### ISSUE THREAD

**Issue by IanKemp** [dotnet/docs#8817] opened 2018-11-02 12:50 UTC
The addition of [Span&lt;T>](https://github.com/dotnet/corefxlab/blob/master/docs/specs/span.md) and associated classes is an important change to the language, but is not mentioned on this page at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f86ebf5-b5c0-324a-43df-c17015729d01
* Version Independent ID: 8ce4ad4a-3dbd-42dc-bae3-230900097299
* Content: [What's new in C# 7.2](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2)
* Content Source: [docs/csharp/whats-new/csharp-7-2.md](https://github.com/dotnet/docs/blob/master/docs/csharp/whats-new/csharp-7-2.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment] 2018-11-02 17:17
Thanks for your feedback, @IanKemp . The C# What's New topics document changes in language features. Span\<T>, Memory\<T>, and their related types are additions to the .NET Class Library, which is designed to be language-independent. They're noted in the [.NET Core What's New article](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1#api-changes) for .NET Core 2.1.

Since the exclusion of these types from the C# What's New is by design, I'll close this issue.

**Closed by rpetrusha** 2018-11-02 17:17 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, by-design
