### ISSUE TITLE
nice boys and girls treat warnings as errors (so should you in docs)

### ISSUE THREAD

**Issue by ghost** [dotnet/docs#11679] opened 2019-04-05 05:36 UTC
If the issue is:

**Issue description**

your List<T> has warnings. I understand that this is an educational exercise, but still...

assuming that you use System.Collections.Generic (for EqualityComparer<T[]>...)
a minimal decency List<T> should look like:

    public class List<T>
    {
        // Constant...
        const int defaultCapacity = 4;

        // Fields...
        T[] items;
        int count;

        // Constructors...
        public List(int capacity = defaultCapacity)
        {
            items = new T[capacity];
        }

        // Properties...
        public int Count
        {
            get { return count; }
        }
        public int Capacity
        {
            get
            {
                return items.Length;
            }
            set
            {
                if (value < count) value = count;
                if (value != items.Length)
                {
                    T[] newItems = new T[value];
                    Array.Copy(items, 0, newItems, 0, count);
                    items = newItems;
                }
            }
        }

        // Indexer...
        public T this[int index]
        {
            get
            {
                return items[index];
            }
            set
            {
                items[index] = value;
                OnChanged();
            }
        }

        // Methods...
        public void Add(T item)
        {
            if (count == Capacity) Capacity = count * 2;
            items[count] = item;
            count++;
            OnChanged();
        }
        protected virtual void OnChanged()
        {
            Changed?.Invoke(this, EventArgs.Empty);
        }
        public override bool Equals(object other)
        {
            if (other == (object)null) return this == (object)null;
            return Equals(this, other);
        }
        static bool Equals(List<T> a, List<T> b)
        {
            if (a == (object)null) return b == (object)null;
            if (b == (object)null || a.count != b.count) return false;
            for (int i = 0; i < a.count; i++)
                if (!object.Equals(a.items[i], b.items[i])) return false;
            return true;
        }

        public override int GetHashCode()
        {
            var hashCode = 515152603;
            hashCode = hashCode * -1521134295 + EqualityComparer<T[]>.Default.GetHashCode(items);
            hashCode = hashCode * -1521134295 + count.GetHashCode();
            return hashCode;
        }

        // Event...
        public event EventHandler Changed;

        // Operators...
        public static bool operator ==(List<T> a, List<T> b)
        {
            return Equals(a, b);
        }
        public static bool operator !=(List<T> a, List<T> b)
        {
            return !Equals(a, b);
        }
    }

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by Thraka** [comment] 2019-04-05 18:48
Duplicate of #11681

**Comment by Thraka** [comment] 2019-04-05 18:59
test
Duplicate of #11679

**Closed** 2019-04-05 18:59 UTC
Labels: product-feedback
