### ISSUE TITLE
-- is missing for install

### ISSUE THREAD

**Issue by martinman-hrbl** [dotnet/docs#32958] opened 2022-12-08 21:21 UTC
[Enter feedback here]

the command should be dotnet new --install ./
otherwise it wont work!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 097102bb-f6d9-c469-5556-ae1f16fdc4fe
* Version Independent ID: 77b25381-6e0f-949f-5f96-b83e9b61e9fc
* Content: [Create a project template for dotnet new - .NET](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template)
* Content Source: [docs/core/tutorials/cli-templates-create-project-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-project-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment] 2022-12-14 21:21
Dupe of #32949.

**Comment by adegeo** [comment] 2022-12-27 19:57
Duplicate of #32949

**Closed by adegeo** 2022-12-27 19:57 UTC
Labels: doc-bug, Pri2, dotnet-fundamentals/prod, okr-health
