### ISSUE TITLE
Sync localized docs

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs#9865] opened 2019-01-06 17:01 UTC
Some of the problems fixed in this repo also appear in any other localized docs.

When will these fixes be synced? Shall I create pull requests in those repos?

**Comment by mairaw** [comment] 2019-01-07 22:03
Hi @NextTurn, it takes a while for the issues fixed here to show up in the localized repos. The content needs to go through the localization pipeline first, Sometimes it might take days or even weeks. @JasonCard can probably explain how the process works better but I'm closing this since this behavior is by design.

**Closed by mairaw** 2019-01-07 22:03 UTC
Labels: :watch: Not Triaged

**Comment by JasonCard** [comment] 2019-01-07 22:22
Hi @NextTurn, 

There is no need to create pull requests in localized repos for fixes in English repo to be synced. 
Typically, changes made to English repo should be synced within two weeks, depending on the timing and number of changes made. 

cc @mairaw

**Comment by JasonCard** [comment] 2019-01-07 23:47
If English and localized content is in sync, but there are issues that only appear in localized docs, such as untranslated content, then please do open GitHub Issue or PR for the localized repo.
