### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by maryob77062** [dotnet/docs#7974] opened 2018-10-01 21:07 UTC
Default WPF Themes.  http://go.microsoft.com/fwlink/?LinkID=158252

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb616ad-a690-f807-1632-7e6e9dd74e8f
* Version Independent ID: 3f4ba5eb-613e-4e01-31f3-16c9f1d3b2cd
* Content: [ToolBar Class (System.Windows.Controls)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.toolbar?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Controls.ToolBar);k(VS.XamlEditor);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Controls/ToolBar.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Controls/ToolBar.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-10-01 21:13
Thank you for your feedback @maryob77062. This is a duplicate of issue #6831.

**Comment by mairaw** [comment] 2018-10-01 21:14
Duplicate of #6831

**Closed by mairaw** 2018-10-01 21:14 UTC
Labels: :books: Area - API Reference, :file_folder: Repo - dotnet-api-docs, Source - Docs.ms, duplicate
