### ISSUE TITLE
Blazor still appears as "éblouissant" in french docs…

### ISSUE THREAD

**Issue by vintzl** [dotnet/docs#22731] opened 2021-02-09 13:08 UTC
See my past issues on this subject…
- https://docs.microsoft.com/fr-fr/aspnet/core/blazor/state-management?view=aspnetcore-5.0&pivots=webassembly
- https://docs.microsoft.com/fr-fr/dotnet/core/compatibility/aspnet-core/5.0/blazor-browser-support-updated

**Comment by Youssef1313** [comment] 2021-02-09 14:35
Well, there are two issues here:

1. For the first link, it belongs to [another repo](https://github.com/dotnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/state-management.md), and the issue is that "Blazor" is already in no-loc metadata. @JasonCard 

2. For the second link, it belongs to this repo and is missing no-loc metadata. <https://github.com/dotnet/docs/blob/master/docs/core/compatibility/aspnet-core/5.0/blazor-browser-support-updated.md>

**Comment by Youssef1313** [comment] 2021-02-09 15:21
Just figured out that the article is relying on an "include" in the ASP.NET docs repo, which doesn't have no-loc.

So for both links, it's the same reason.

However, there is one occurrence that I don't know how to lock its localization:

https://github.com/dotnet/AspNetCore.Docs/blob/c8600c840f492164308c14dd12e7f7ec389cb50d/aspnetcore/zone-pivot-groups.yml#L13-L20

**Comment by JasonCard** [comment] 2021-02-10 01:41
@Youssef1313 Regarding the text coming from zone-pivot-group.yml, that file should not have been localized, so it's been reverted back to English.

**Comment by gewarren** [comment] 2021-02-11 16:45
Can we close this issue now?

**Comment by Youssef1313** [comment] 2021-02-11 16:48
@gewarren I think yes. The remaining issues are tracked in asp docs repo.

**Closed** 2021-02-11 17:01 UTC
Labels: :watch: Not Triaged, Pri3
