### ISSUE TITLE
Normalization on vector or fields 

### ISSUE THREAD

**Issue by PeterPann23** [dotnet/docs#12228] opened 2019-05-07 08:53 UTC
No mention on the strategy to normalize a vector of data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c298a5-b76f-25d9-beda-e298ac03cf35
* Version Independent ID: 392ab238-4442-015c-ec30-eae546794cc9
* Content: [Prepare Data - ML.NET](https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/prepare-data-ml-net)
* Content Source: [docs/machine-learning/how-to-guides/prepare-data-ml-net.md](https://github.com/dotnet/docs/blob/master/docs/machine-learning/how-to-guides/prepare-data-ml-net.md)
* Product: **dotnet-ml**
* GitHub Login: @luisquintanilla
* Microsoft Alias: **luquinta**

**Comment by luisquintanilla** [comment] 2019-05-13 14:36
Thanks for the feedback @PeterPann23. Normalization works the same on vectors as it does with a single value. An example of this can be found in the [NormalizeMinMax API documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.ml.normalizationcatalog.normalizeminmax?view=ml-dotnet#Microsoft_ML_NormalizationCatalog_NormalizeMinMax_Microsoft_ML_TransformsCatalog_Microsoft_ML_InputOutputColumnPair___System_Int64_System_Boolean_).

**Comment by natke** [comment] 2019-06-04 17:12
Closing as a dupe of #12280

**Closed by natke** 2019-06-04 17:12 UTC
Labels: :books: Area - ML.NET Guide, P2, Source - Docs.ms, triaged
