### ISSUE TITLE
maybe it mistakes mistake if input come incorrect.

### ISSUE THREAD

**Issue by Arashz22** [dotnet/docs#12278] opened 2019-05-09 19:20 UTC
[Enter feedback here]

it's better to change the position of this :
`DirectoryInfo dir = new DirectoryInfo(sourceDirName);
`

and this :
 ```
  if (!dir.Exists)
            {
                throw new DirectoryNotFoundException(
                    "Source directory does not exist or could not be found: "
                    + sourceDirName);
            }
```

something like this :

```
if (!Directory.Exists(sourceDirName))
            {
                throw new DirectoryNotFoundException(
                    "Source directory does not exist or could not be found: "
                    + sourceDirName);
            }

            DirectoryInfo dir = new DirectoryInfo(sourceDirName);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d050f686-38eb-bb76-5747-9e138f4da679
* Version Independent ID: 93b69d5a-5df1-c0e1-930d-2f5ee1c1fe6e
* Content: [How to: Copy directories](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-copy-directories#feedback)
* Content Source: [docs/standard/io/how-to-copy-directories.md](https://github.com/dotnet/docs/blob/master/docs/standard/io/how-to-copy-directories.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by rpetrusha** [comment] 2019-05-09 21:32
Thank you for your feedback, @Arashz22. Given that the DirectoryInfo class doesn't actually validate the file path passed to it in the constructor either until the value of the Exists property is retrieved or a method is called that attempts to perform an operation on the file system, this code should not throw a DirectoryNotFound exception before the Exists property is retrieved. Whether you prefer the coding style in the example or the one that you've proposed is really a matter of preference. 

Given that, I'm going to close this issue as By Design.

**Closed by rpetrusha** 2019-05-09 21:32 UTC
Labels: :books: Area - .NET Guide, Source - Docs.ms

**Comment by ProgramNew** [comment] 2019-05-12 16:16
Hello @rpetrusha  I was looking into the code and was wondering how do you make I am looking at your code and though I do understand it I do not know how to copy the sub folders and any document within my folder, please could you show me where I am going wrong

static void Main(string[] args)
        {
            cDirectory(".", @"C:\Users\Alucard\Desktop\CopyDirectory", true); 
            /*the copied directory, please note the pathway may have to change on the computer it 
            is compiled on. thank you.*/
                 }

        private static void cDirectory(string sDir, string dDir, bool copied)
        {
            DirectoryInfo tDirectory = new DirectoryInfo(@"C:\Users\Alucard\Desktop\CopyDirectory\sfold"); 
            //Getting it from this certain directory

            if (!tDirectory.Exists) //if the direcory does not exist then write onthe console and create the directory
            {
                Console.WriteLine("The source directory is not found");
                Directory.CreateDirectory(@"C:\Users\Alucard\Desktop\CopyDirectory\sFold");
                        } //if the file does not work then it should write on the console that the source folder does not exist.

            DirectoryInfo[] tDirectorys = tDirectory.GetDirectories(); //checks the directory and gets all of the directories of the folder 

                         if (!Directory.Exists(@"C:\Users\Alucard\Desktop\CopyDirectory\dFold"))
                         {
                             Directory.CreateDirectory(@"C:\Users\Alucard\Desktop\CopyDirectory\dFold"); }
                        //if the directory is not in the location provided then create the direcory  in the path.
                         FileInfo[] tFiles = tDirectory.GetFiles(); //retrivie all of the files within the directory
                        
                            foreach (FileInfo tFile in tFiles)//for every file inside the direcory and put them in this destination direcoty
                            {
                                 string tLocation = Path.Combine(@"C:\Users\Alucard\Desktop\CopyDirectory\", tFile.Name); //by combine the location of the destination directory
                        tFile.CopyTo(tLocation, false); 
                                }


            /*if (copied) 
            {
                foreach (DirectoryInfo othdir in tDirectorys)
                {
                    string tLocation = Path.Combine(@"C:\Users\Alucard\Desktop\CopyDirectory\", othdir.Name);
                    cDirectory(othdir.FullName, tLocation, copied);
                }
            }
            
            The above code represents if there are any other sub-direcories then copy them and their contents to this directory*/
           
        }

**Comment by ProgramNew** [comment] 2019-05-12 16:24
@rpetrusha , sorry I didnt make sense, What I am trying to do is make sure that as we copy the folders, I would like to copy any subfolders, and text documents to any documents which these folders have to be copied with them in the same folder. I am just slightly confused on this
