### ISSUE TITLE
Need an example about "Implement both dispose and async dispose patterns" with a bool disposed field.

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/docs#22891] opened 2021-02-18 02:02 UTC
This may cause the `Dispose(disposing: false);` not work (If there are unmanaged resources). 

```cs
class A : IDisposable, IAsyncDisposable {
        private bool Disposed { get; private set; }

        public void Dispose() => Dispose(disposing: true);

        public async ValueTask DisposeAsync() {
            if (!Disposed) {
                await DisposeAsyncCore().ConfigureAwait(false);

                Dispose(disposing: false);

                Disposed = true;
            }
        }

        protected virtual void Dispose(bool disposing) {
            if (!Disposed) {
                if (disposing) {
                    _encryptor.Dispose();
                    _status = Status.Closed;
                }

                Disposed = true;
            }
        }

        protected virtual ValueTask DisposeAsyncCore() {
            Dispose(disposing: true);

            return ValueTask.CompletedTask;
        }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a961dc-3ebf-2a96-a6eb-2e0b62ab909f
* Version Independent ID: d72276e1-9059-815f-dc14-a03a7544ab87
* Content: [Implement a DisposeAsync method](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-disposeasync)
* Content Source: [docs/standard/garbage-collection/implementing-disposeasync.md](https://github.com/dotnet/docs/blob/master/docs/standard/garbage-collection/implementing-disposeasync.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by IEvangelist** [comment] 2021-02-18 15:21
Hi 👋 @GF-Huang 
Thank you so much for posting this issue. We really appreciate it.

The pattern for implementing both, is to _not_ include a field. Instead, `null` out the references to unmanaged (or cascaded) disposable instances. Please follow the suggested pattern. I'm going to close this for now, but we can always reopen it if need be.

**Closed by IEvangelist** 2021-02-18 15:21 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-fundamentals/prod, sample-code

**Comment by Bosch-Eli-Black** [comment] 2022-10-17 09:01
@IEvangelist What about in the case where the fields are `readonly`? In that case, we'd need a field, right?

**Comment by IEvangelist** [comment] 2022-10-17 12:52
> @IEvangelist What about in the case where the fields are `readonly`? In that case, we'd need a field, right?

Hi @Bosch-Eli-Black, if they're `readonly` then you cannot `null` them out. Dispose, both async and sync should be idempotent, so it shouldn't matter. If you're following the prescribed pattern then your field wouldn't be `readonly`, so that you could `null` them out.

**Comment by IEvangelist** [comment] 2022-10-20 14:19
It's not necessary. Calling it multiple times shouldn't matter.

**Comment by Bosch-Eli-Black** [comment] 2022-10-25 09:39
Oooh, right, because calling `Dispose()` multiple times on the properties is also supposed to be safe! Thanks 🙂

**Comment by Bosch-Eli-Black** [comment] 2022-11-17 06:32
@lonix1, I think what @IEvangelist is saying is that calling `.Dispose()` or `.DisposeAsync()` multiple times on an object is okay, because those methods are required to perform no work after the first time that they're called. (That is, they're idempotent)

@IEvangelist BTW, if this is the case, do you know why https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#the-disposebool-method-overload recommends using a `_disposed` variable for non-async disposal? Is it just an optimization? Thanks 🙂

**Comment by IEvangelist** [comment] 2022-11-18 14:31
Hey, @Bosch-Eli-Black

> Is it just an optimization?

Yeah, that is just an optimization.

The IDE does take a few liberties, but I didn't think that it added the `_disposed` bit for `IAsyncDisposable`. I'm going to ask around a bit.

**Comment by Bosch-Eli-Black** [comment] 2022-11-22 02:38
@IEvangelist Thanks, appreciate it 🙂

**Comment by IEvangelist** [comment] 2022-11-28 14:33
> @IEvangelist Thanks, appreciate it 🙂

I have confirmed, that the `_disposed` is not added when using the tooling to auto-implement the `IAsyncDisposable` interface through a cascading type.

**Comment by Bosch-Eli-Black** [comment] 2022-11-29 09:45
Thanks, @IEvangelist 🙂  Just to be absolutely clear:
* For non-async disposal, using `_disposed` is just an optimization. We could safely not use `_disposed` and everything would still be correct.

Is that correct?

Thanks again 🙂

**Comment by Bosch-Eli-Black** [comment] 2022-11-30 05:32
Thanks, @IEvangelist, that helps a lot 🙂

**Comment by Bosch-Eli-Black** [comment] 2022-11-30 05:57
@lonix1 I think what he's saying is that this should be fine:

```c#
protected readonly Lazy<Task<IJSObjectReference>> _moduleTask;

//...

protected virtual async ValueTask DisposeAsyncCore()
{
  if (_moduleTask.IsValueCreated)
  {
    var module = await _moduleTask.Value;
    await module.DisposeAsync().ConfigureAwait(false);
  }

  //base.DisposeAsyncCore();   // if this is a subclass then call base class too
}
```
