### ISSUE TITLE
Default compilation includes does not work if your path has '%'

### ISSUE THREAD

**Issue by crgarcia12** [dotnet/docs#16066] opened 2019-12-03 10:10 UTC
We had a git repo with a space, that translated into a % and then this was not working. It took us quite some time to be able to troubleshoot. You should include a warning in this section:
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#default-compilation-includes-in-net-core-projects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa484235-d872-f50e-96fc-aa5b4a2a42fa
* Version Independent ID: 871c22e0-65a2-f3a4-41b9-f050489dba7a
* Content: [.NET project SDK overview](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#default-includes-and-excludes)
* Content Source: [docs/core/project-sdk/overview.md](https://github.com/dotnet/docs/blob/master/docs/core/project-sdk/overview.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by tdykstra** [comment] 2019-12-03 16:55
@crgarcia12 Thanks for pointing that out. I'm putting this on our backlog and we'll leave the issue open until it's addressed.

**Comment by gewarren** [comment] 2021-01-20 19:17
@crgarcia12 Can you help me reproduce this?

I created a project with a folder named _New%Folder_, put a code file in that folder, and it compiled and ran fine.
Also, when I tried to create a repo on GitHub with a space in the name, it added hyphens where the spaces were.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-21 00:36
I don't know whether this is the problem that @crgarcia12 hit, but the build does blow up with a folder named `100%fake` and .NET SDK 5.0.102:

```
PS C:\Projects\100%fake> Get-ChildItem

    Directory: C:\Projects\100%fake

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           21.1.2021     2.19            183 100%fake.csproj
-a---           21.1.2021     2.19             86 Class1.cs

PS C:\Projects\100%fake> Get-Content 100%fake.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RootNamespace>_100_fake</RootNamespace>
  </PropertyGroup>

</Project>
PS C:\Projects\100%fake> Get-Content Class1.cs
using System;

namespace _100_fake
{
    public class Class1
    {
    }
}
PS C:\Projects\100%fake> dotnet --version
5.0.102
PS C:\Projects\100%fake> dotnet build
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Projects\100%fake\100%fake.csproj (in 57 ms).
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file 'C:\Projects\100úke\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Projects\100%fake\100%fake.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file 'C:\Projects\100úke\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Projects\100%fake\100%fake.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.69
```

Note how it tried to use a directory named `100úke` rather than `100%fake`. This really seems a product bug to me, but I'm not sure whether the bug is in MSBuild or NuGet.

**Comment by gewarren** [comment] 2021-01-21 19:23
@KalleOlaviNiemitalo Thank you for that (and PowerShell is cool!). Can you log a bug at https://github.com/dotnet/msbuild/issues?

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-21 20:13
Might be a duplicate of <https://github.com/dotnet/msbuild/issues/2178>, actually.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-21 20:15
And in <https://github.com/dotnet/core/issues/4468#issuecomment-606021948> they say it's "Unlikely to be fixable". That could make the problem worth documenting here.

**Comment by gewarren** [comment] 2021-01-21 20:58
I think that https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build might be a better place to add a note about this.

**Comment by crgarcia12** [comment] 2021-01-25 22:16
Thank you @gewarren :)

**Closed** 2021-01-26 23:17 UTC
Labels: :books: Area - .NET Core Guide, :card_file_box: Technology - CLI, Pri2, doc-enhancement, dotnet-cli/tech, dotnet-core/prod, dotnet-fundamentals/prod
