### ISSUE TITLE
Do not use CA1309: Use ordinal StringComparison for string.Equals

### ISSUE THREAD

**Issue by ninedan** [dotnet/docs#35393] opened 2023-05-17 21:24 UTC
CA1309: Use ordinal StringComparison should not be applied on string.Equals(string, string).

If you force people to switch string.Equals(string, string) to string.Equals(string, string, StringComparison.Ordinal), it could slow down critical code path.

This is totally different from string.Compare(string, string), because the later is using super slow current culture comparison.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bcf38956-3a4b-98f2-4bbf-6c8f699bd150
* Version Independent ID: b3112dde-7fb5-6daa-5e3b-66502de5fdf0
* Content: [CA1309: Use ordinal StringComparison (code analysis) - .NET](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1309)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca1309.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca1309.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by ninedan** [comment] 2023-05-17 23:56
![image](https://github.com/dotnet/docs/assets/19536938/4b68caa8-2d00-4836-9421-27fd6957ca73)

**Comment by gewarren** [comment] 2023-07-18 18:53
Closing this a dupe of https://github.com/dotnet/roslyn-analyzers/issues/4627. LMK if you disagree.

**Closed by gewarren** 2023-07-18 18:53 UTC
Labels: :watch: Not Triaged, Pri2, dotnet-fundamentals/prod
