### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by Svetomechc** [dotnet/docs#14475] opened 2019-09-17 13:14 UTC
What's the reasoning behind this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 315af9fc-a5f1-9a51-a154-a7c703975a91
* Version Independent ID: d83911ea-0426-fc82-622a-3c607d7b787a
* Content: [Compiler Warning (level 1) CS0809](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0809)
* Content Source: [docs/csharp/misc/cs0809.md](https://github.com/dotnet/docs/blob/master/docs/csharp/misc/cs0809.md)
* Product: **dotnet-csharp**
* Technology: **csharp-diagnostics**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2019-09-17 14:01
The reason is in the article:
> Typically, a member that is marked as obsolete should not override a member that is not marked as obsolete.

Correcting the error is also mentioned:
> Remove the Obsolete attribute from the overriding member, or add it to the base class member.

**Comment by Svetomechc** [comment] 2019-09-17 14:05
@Youssef1313, sorry, but "typically" is not reasonable enough for me (:

**Comment by BillWagner** [comment] 2019-09-18 00:57
@Svetomechc 

If you declare a member obsolete, you're giving callers a warning that they should not call that method (but hopefully call a preferred replacement.) If that method is virtual, all implementations, in base and derived classes, should be considered obsolete. 

Adding this attribute is warning callers of an impending breaking change.

If your intent is to remove a derived implementation of a method and defer to the base class, you can safely remove it. Because it's overriding a virtual method, removing a derived implementation is not a breaking change. 

I'll close this as by design.

**Closed by BillWagner** 2019-09-18 00:57 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged, Source - Docs.ms

**Comment by Svetomechc** [comment] 2019-09-18 09:48
@BillWagner, thx for explanation!
