### ISSUE TITLE
How to create an analyzer

### ISSUE THREAD

**Issue by loicmorvan** [dotnet/docs#5073] opened 2018-04-29 15:29 UTC
Can you add a link to a document that explains how to create an analyzer from scratch? Would be nice :) Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee024463-2572-2106-a85d-7c53f8d9dc0c
* Version Independent ID: 1cd4a2f3-3055-1faa-0fa9-46bbfb6dcef1
* Content: [The Roslyn based Analyzers - .NET](https://docs.microsoft.com/en-us/dotnet/standard/analyzers/)
* Content Source: [docs/standard/analyzers/index.md](https://github.com/dotnet/docs/blob/master/docs/standard/analyzers/index.md)
* Service: **unspecified**
* GitHub Login: @BillWagner
* Microsoft Alias: **billwagner**

**Comment by svick** [comment] 2018-04-29 15:42
I think such document doesn't exist in the docs yet. Here is an issue about creating one: https://github.com/dotnet/docs/issues/4831.

**Comment by BillWagner** [comment] 2018-04-30 20:37
I'll close this as a duplicate of #4831 

In the meantime, [this tutorial](https://docs.microsoft.com/visualstudio/extensibility/roslyn-analyzers-and-code-aware-library-for-immutablearrays) has a lot of the information necessary. It's just not in a location that's easy to find if you're looking for roslyn analyzers.

**Closed by BillWagner** 2018-04-30 20:37 UTC

**Comment by mairaw** [comment] 2018-04-30 22:25
Duplicate of #4831

**Comment by loicmorvan** [comment] 2018-05-01 08:01
@BillWagner This is exactly what I was looking for, thanks!
