### ISSUE TITLE
Parameters not documented

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#9794] opened 2019-01-01 21:20 UTC
@agowa338 commented on [Tue Jan 01 2019](https://github.com/dotnet/docs.de-de/issues/118)

Parameters are not documented (output of `dotnet msbuild /help`)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a9083568-6c58-1c1b-0062-10632e61a88d
* Version Independent ID: a1d47471-9482-9f69-f11e-3424e62383f6
* Content: [dotnet-msbuild-Befehl – .NET Core-CLI](https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-msbuild)
* Content Source: [docs/core/tools/dotnet-msbuild.md](https://github.com/dotnet/docs.de-de/blob/live/docs/core/tools/dotnet-msbuild.md)
* Product: **dotnet-core**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment] 2019-01-01 21:20
Hi team, 
I'm moving this here since the user is reporting missing documentation

**Comment by rpetrusha** [comment] 2019-05-24 17:29
@mairaw, the documentation links to the MSBuild command line reference for information on the options., Should this be closed as By Design?

**Comment by Thraka** [comment] 2019-10-24 15:56
This is sufficiently documented in the MS Build docs, which is linked. @mairaw I think we can close this. I'll defer to you since you own it 😄

**Comment by gewarren** [comment] 2020-01-17 21:14
@mairaw I think this can be closed.

**Comment by mairaw** [comment] 2020-01-17 21:32
I agree. We don't want to duplicate all that.

**Closed by mairaw** 2020-01-17 21:32 UTC
Labels: :books: Area - .NET Core Guide, doc-enhancement

**Comment by agowa338** [comment] 2020-01-23 11:01
@mairaw The link `MSBuild-Befehlszeilenreferenz` within document: https://github.com/dotnet/docs.de-de/blob/live/visualstudio/msbuild/msbuild-command-line-reference
does not work, it only returns a 404. Can you please check?
