### ISSUE TITLE
broken link issue

### ISSUE THREAD

**Issue by jack147527** [dotnet/docs#12382] opened 2019-05-16 02:36 UTC
In the [foreach, in (C# reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in#feedback) page, the Try.NET link in the[ Examples](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in#examples) will show empty. Somebody has reported this issue, but it seems that it has been not solved.

edit by @mairaw: added topic details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d710feeb-8f03-b211-a070-155938929d6b
* Version Independent ID: c980ea8e-ffb4-fbb1-1761-292858616cdd
* Content: [C# foreach statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/foreach-in)
* Content Source: [docs/csharp/language-reference/keywords/foreach-in.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/foreach-in.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by mairaw** [comment] 2019-06-03 23:07
Thanks @jack147527. You're right. It hasn't been solved yet.

But I'll resolve this one as duplicate of #11979 to keep only one tracking issue.

**Closed by mairaw** 2019-06-03 23:07 UTC
Labels: :books: Area - C# Guide, duplicate
