### ISSUE TITLE
Clarification: CheckConfirmedGracePeriodOrders

### ISSUE THREAD

**Issue by shoorik** [dotnet/docs#10439] opened 2019-02-12 19:29 UTC
Presumably, you may also want to pass stoppingToken to CheckConfirmedGracePeriodOrders function so that it can use it to gracefully interrupt any pending calls to query database and publishing messages to queues and rollback things cleanly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49a03c0-a844-26eb-48a5-33a612dd3ead
* Version Independent ID: 0707865f-9db7-0d71-42a5-bc1a1e89680a
* Content: [Implement background tasks in microservices with IHostedService and the BackgroundService class](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice#feedback)
* Content Source: [docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md](https://github.com/dotnet/docs/blob/master/docs/architecture/microservices/multi-container-microservice-net-applications/background-tasks-with-ihostedservice.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by rpetrusha** [comment] 2019-03-04 23:15
//cc @mvelosop

**Comment by mvelosop** [comment] 2019-03-07 12:49
Hi @shoorik, you could do it for sure.

Since handling the cancellation token also adds complexity, you just have to consider up to what point you're going to do it.

This is a simplified sample so it's not that important.

You might want to take a look at a more refined way to handle integration events publishing, by using the OutBox pattern, which is explained in the [Subscribing to events section in this guide](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events) and [can be "seen" in the log traces](https://github.com/dotnet-architecture/eShopOnContainers/wiki/18.-Centralized-Structured-Logging-in-eShopOnContainers#integration-event-handling).

Hope this helps.

**Comment by maulik-modi** [comment] 2019-07-15 14:33
Can anyone point me to source code of CheckConfirmedGracePeriodOrders?

**Comment by mvelosop** [comment] 2019-08-07 17:49
Hi @maulik-modi, I'm sorry for the delay, you can find the code here: https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Ordering/Ordering.BackgroundTasks/Tasks/GracePeriodManagerTask.cs

**Comment by mvelosop** [comment] 2019-08-07 17:50
Closing this issue now as the original question was answered, but feel free to comment, will reopen if needed.

**Closed by mvelosop** 2019-08-07 17:50 UTC
Labels: :book: guide - .NET Microservices, :books: Area - .NET Guide, :card_file_box: Technology - .NET Architecture, :watch: Not Triaged, Source - Docs.ms
