### ISSUE TITLE
Webshop referal

### ISSUE THREAD

**Issue by Tickles** [dotnet/docs#23876] opened 2021-04-22 12:38 UTC
The webshop which is refered to on github in the "https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#clean-architecture"
is adviced to not use or create your SOLID application from. It suffers from reference issues, its not loose coupled as Jason Taylors version etc. Can you pls correct the solution and update it in github. 
Example, Dependency injection in web project with configurations for services? It should be decoupled, A reference in one of the ConfigurexxxServices is wrong etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: b227c667-82ae-97ef-c175-7e17051c5ab2
* Content: [Common web application architectures](https://docs.microsoft.com/en-us/dotnet/architecture/modern-web-apps-azure/common-web-application-architectures#clean-architecture)
* Content Source: [docs/architecture/modern-web-apps-azure/common-web-application-architectures.md](https://github.com/dotnet/docs/blob/main/docs/architecture/modern-web-apps-azure/common-web-application-architectures.md)
* Product: **dotnet-architecture**
* Technology: **modern-web-apps-azure**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by ardalis** [comment] 2021-04-22 15:49
The only "webshop" referenced in that section would be the one the book is associated with, which is 
https://github.com/dotnet-architecture/eShopOnWeb

**Comment by ardalis** [comment] 2021-04-22 15:54
Never mind, I see that is the one you were referring to. I think any issues with that sample can be addressed with issues there, with your issue https://github.com/dotnet-architecture/eShopOnWeb/issues/524 as a good starting point and for tracking.

**Comment by tdykstra** [comment] 2021-05-05 18:13
Closing as duplicate of https://github.com/dotnet-architecture/eShopOnWeb/issues/524

**Closed by tdykstra** 2021-05-05 18:13 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-architecture/prod, modern-web-apps-azure/tech
