### ISSUE TITLE
The operations about Solution Explorer are different from my Visual Studio interface

### ISSUE THREAD

**Issue by seanlin-larc** [dotnet/docs#9994] opened 2019-01-15 14:31 UTC
Some operations are actually under "File" tab and could not achieve from Solution Explorer window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c598765c-1c4d-bf43-f5c6-a894f3af37ea
* Version Independent ID: 3b77a3ea-1d26-a462-05c5-40bb61919c97
* Content: [Building a Visual Basic .NET Core class library in Visual Studio 2017 - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/vb-library-with-visual-studio)
* Content Source: [docs/core/tutorials/vb-library-with-visual-studio.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/vb-library-with-visual-studio.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment] 2019-01-15 23:57
Can you be more specific, @seanlin-larc? What operations were on the File tab instead of the Solution Explorer window? Thanks.

**Comment by seanlin-larc** [comment] 2019-01-16 01:06
As the screenshot, the first step of tutorial says "1.In Solution Explorer, open the context menu for the ClassLibraryProjects solution node and select Add > New Project." However, I couldn't find such option in my context menu in Solution Explorer. I could start a new project as step 2 described from the File tab, but I found no check-able item in step 5.

I'm using Visual Studio 2017 Community Edition.

![screenshot 201901151701](https://user-images.githubusercontent.com/24693273/51219778-39569b80-18e7-11e9-8852-7f63aafc314a.png)

**Comment by rpetrusha** [comment] 2019-01-17 00:41
For more information, see #9995. 
Closing as Duplicate, since the root cause of this behavior is the same as #9995.

**Closed** 2019-10-07 17:58 UTC
Labels: :books: Area - .NET Core Guide, Source - Docs.ms, duplicate
