### ISSUE TITLE
incomplete

### ISSUE THREAD

**Issue by altimmons** [dotnet/docs#6524] opened 2018-07-18 07:36 UTC
its like the person who wrote this doc page and its parent read the example but knew nothing else.  Clearly there exist more methods, the example itself uses a method not on the mouse page.  I know it gets swapped buttons and scroll wheel but what else?  Position? Speed? Acceleration.  Over? This could be so useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9abe70-6b85-fd08-5d96-316de3da9305
* Version Independent ID: d5db0542-0790-6c3c-3433-f3bd1491a22e
* Content: [Mouse Constructor (Microsoft.VisualBasic.Devices)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.devices.mouse.-ctor?view=netframework-4.7.2)
* Content Source: [xml/Microsoft.VisualBasic.Devices/Mouse.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualBasic.Devices/Mouse.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-07-30 20:47
Thanks for your feedback @altimmons. This is the constructor page. If you navigate back to the class, you'll see the list of properties, methods, etc.

![image](https://user-images.githubusercontent.com/12971179/43422577-f6072646-93fe-11e8-9fcf-e2eea43779f2.png)

https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.devices.mouse 

So I'm closing this as by design. Please let us know if you have other questions.

**Closed by mairaw** 2018-07-30 20:47 UTC
Labels: :file_folder: Repo - dotnet-api-docs, Area - API Reference, Source - Docs.ms, by-design
