### ISSUE TITLE
DirectoryInfo.EnumerateFiles Method

### ISSUE THREAD

**Issue by seanxs** [dotnet/docs#5797] opened 2018-06-05 02:32 UTC
[Enter feedback here]
Hi All,
  I use the following code, the first one is working fine, but the second one will throw exception.
  It make me confused, please help.
  DirectoryInfo tempdir = new DirectoryInfo(@"d:\WorkFloder\ABCD\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Security.ApplicationId.Wizards.AutomaticRuleGenerationWizard.resources\v4.0_10.0.0.0_zh-HANS_31bf3856ad364e35");
// work fine
   List<FileInfo> tempfilesok = new List<FileInfo>(tempdir.EnumerateFiles("*"));  
// throw DirectoryNotFoundException
   List<FileInfo> tempfilesExp = new List<FileInfo>(tempdir.EnumerateFiles(@"Microsoft.Security.ApplicationId.Wizards.AutomaticRuleGenerationWizard.resources.dll")); 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7c1e86f-031c-6ce6-5088-26a0cece9d90
* Version Independent ID: 4cfebbe8-a6cc-970d-9983-ecbec07aa2a2
* Content: [DirectoryInfo.EnumerateFiles Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.enumeratefiles?view=netframework-4.7.1#System_IO_DirectoryInfo_EnumerateFiles_System_String_)
* Content Source: [xml/System.IO/DirectoryInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/DirectoryInfo.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment] 2018-07-17 19:16
Thanks for submitting your feedback, @seanxs. I can't reproduce your issue, though. I'm going to close this issue as not repo. If you're still having this issue, though, and can't diagnose its cause, it might be helpful to include a larger block of your code, including its exception handling.

**Closed by rpetrusha** 2018-07-17 19:16 UTC
Labels: :file_folder: Repo - dotnet-api-docs, Area - API Reference, Source - Docs.ms, not-repro
