### ISSUE TITLE
20.04 ❌ ❌ Please note that this version of Ubuntu is no longer supported.

### ISSUE THREAD

**Issue by czirok** [dotnet/docs#25423] opened 2021-07-31 21:37 UTC
This is true? The last long-supported Ubuntu 20.04 is no longer supported?

---
#### A dokumentum adatai

⚠ *Ezt a szakaszt ne szerkessze. A szakasz a docs.microsoft.com ➟ GitHub-problémák hivatkozásaihoz szükséges.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/hu-hu/dotnet/core/install/linux-ubuntu#2004-)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-08-01 02:51
Duplicate of #25382

**Comment by adegeo** [comment] 2021-08-01 02:51
It is still supported. This was fixed but publishing was lagging behind. I just force published to get this updated asap.

**Closed by adegeo** 2021-08-01 02:51 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-install/tech, dotnet/prod
