### ISSUE TITLE
Add a page for dotnet-gcdump

### ISSUE THREAD

**Issue by aelij** [dotnet/docs#19692] opened 2020-07-26 15:46 UTC
https://devblogs.microsoft.com/dotnet/collecting-and-analyzing-memory-dumps/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a269a64-0a27-27d3-a509-47b9a0d114bf
* Version Independent ID: 49ff97ff-b39a-5ae8-e4b8-81a4f8eab50c
* Content: [dotnet-dump - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump)
* Content Source: [docs/core/diagnostics/dotnet-dump.md](https://github.com/dotnet/docs/blob/master/docs/core/diagnostics/dotnet-dump.md)
* Product: **dotnet-core**
* GitHub Login: @sdmaclea
* Microsoft Alias: **stmaclea**

**Comment by Youssef1313** [comment] 2020-07-26 16:50
Duplicate of #18935

**Closed** 2020-07-26 16:51 UTC
Labels: :books: Area - .NET Core Guide, :watch: Not Triaged
