### ISSUE TITLE
Default Value of reference type is null

### ISSUE THREAD

**Issue by Deepakgullipalli** [dotnet/docs#16158] opened 2019-12-08 08:38 UTC
If default value of reference type is null, then why do we get "use of unassigned local variable *****".

example :
A class TestClass has a method MyTestMethod1.

TestClass t;
t.MyTestMethod1;

I would get compile time error for the same.
if by default it is null.

TestClass t;
t = null;
t.MyTestMethod1;

compiled successfully, although runtime exception comes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 928ebcaa-7cf2-2741-2aee-2f298d9c83d4
* Version Independent ID: 242cda66-d4ca-018a-17a2-0fe1a8745828
* Content: [Default values table - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/default-values-table?source=docs#feedback)
* Content Source: [docs/csharp/language-reference/keywords/default-values-table.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/default-values-table.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2019-12-09 13:52
Thanks for writing this @Deepakgullipalli 

This behavior is by design: In C#, variables must be assigned before use. The compiler enforces this language rule to minimize program errors due to accessing uninitialized variables.

I'll close this as an answered product question.

**Closed by BillWagner** 2019-12-09 13:52 UTC
Labels: :books: Area - C# Guide, by-design, product-question
