### ISSUE TITLE
Tutorial doesn't work in VS2019 16.7

### ISSUE THREAD

**Issue by garfbradaz** [dotnet/docs#19876] opened 2020-08-06 20:19 UTC
[Enter feedback here]

FYI Currently using VS 2019 16.7 (Community) - this tutorial doesnt work.

Logged an issue here if anyone else has problems.

https://developercommunity.visualstudio.com/content/problem/1140324/path-is-not-of-legal-form---creating-roslyn-analyzer.html
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/master/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2020-08-07 20:01
@BillWagner @IEvangelist, I think roslyn sdk docs need much improvements. Beside the reported issue, I don't find any intermediate to advanced scenarios that one will face when writing analyzers and code fixers. I tried to write analyzers before in both dotnet/roslyn and dotnet/roslyn-analyzers, and I always came across different problems. No resources are available anywhere online. Neither on docs, blogs, or stackoverflow. I was only able to get help from Roslyn team.

I'm still not experienced enough in this area, so I won't be able to help much unfortunately. However, you can look at my previous PRs related to writing analyzers in roslyn or roslyn-analyzers repos. I faced a problem in almost every PR. I hope these PRs can give you an insight of what mistakes/problems customers may face, and decide what deserves to be documented.

This probably will be hard to be done before .NET 5 and C# 9 waves as I think they're the top priority now.

**Comment by BillWagner** [comment] 2020-08-10 14:11
@Youssef1313 Yes, we know the roslyn analyzer area needs more work. We simply haven't had time. I'm hoping that as we keep improving the other C# content, I can start to prioritize this more.

> However, you can look at my previous PRs related to writing analyzers in roslyn or roslyn-analyzers repos. I faced a problem in almost every PR. I hope these PRs can give you an insight of what mistakes/problems customers may face, and decide what deserves to be documented.

These are incredibly helpful. Thank you.

**Comment by BillWagner** [comment] 2020-08-10 14:11
closing as duplicate of #19915

**Closed by BillWagner** 2020-08-10 14:12 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged
