### ISSUE TITLE
csc -debug options missing

### ISSUE THREAD

**Issue by Sebbl22** [dotnet/docs#23275] opened 2021-03-10 19:08 UTC
The documentation for the -debug flag of csc.exe only lists two options: full | pdbonly

However, there were two more options added with the introduction of the new portable PDB file format some years ago: embedded and portable
![grafik](https://user-images.githubusercontent.com/10319545/110682623-6d822a00-81db-11eb-8291-9219381b5232.png)

I would expect the documentation to include:
- A list of all possible values of -debug (full, pdbonly, portable, embedded)
- An explanation of the possible values and their impact on the compilation process
- A recommendation when to use what option. The csc.exe default value is "full" - Visual Studios default value is "portable" when creating new .NET Core projects
- An explanation/update to the Note in the `Remarks`-section, when the `DebuggableAttribute` is set. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3029908f-c2ff-3620-7d51-b9f6a3b768dc
* Version Independent ID: 0f310c2a-3dc6-54a4-5014-264d7f727f2f
* Content: [-debug (C# Compiler Options)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/debug-compiler-option)
* Content Source: [docs/csharp/language-reference/compiler-options/debug-compiler-option.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/compiler-options/debug-compiler-option.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by Youssef1313** [comment] 2021-03-11 14:00
This appears to be a duplicate of #6773

**Comment by BillWagner** [comment] 2021-03-11 15:12
closing as a duplicate of #6773

**Closed by BillWagner** 2021-03-11 15:12 UTC
Labels: :watch: Not Triaged, Pri2, csharp-language-reference/tech, dotnet-csharp/prod
