### ISSUE TITLE
Documents for the incremental source generator

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/docs#30728] opened 2022-08-17 13:43 UTC
Hopes more documents on the incremental source generator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4410c-4c8d-0107-845b-9a951bb76682
* Version Independent ID: f1ed9873-3e29-b4bd-2dbb-44dd9a05d790
* Content: [Source Generators](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
* Content Source: [docs/csharp/roslyn-sdk/source-generators-overview.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/source-generators-overview.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-08-22 17:01
Hi :wave: @WeihanLi 

@KathleenDollard is working on a set of docs now. We expect to publish them in the next month or so.

**Comment by Youssef1313** [comment] 2022-11-25 15:03
Duplicate of #30659

**Closed** 2024-10-25 20:05 UTC
Labels: doc-idea, Pri1, dotnet-csharp/svc, roslyn-sdk/subsvc, in-pr, :world_map: reQUEST
