### ISSUE TITLE
Shift Operators in VB

### ISSUE THREAD

**Issue by Buzzardbait** [dotnet/docs#7388] opened 2018-08-30 02:45 UTC
The left shift operator (&lt;&lt;) fails in Visual Basic with "expected expression" error.
Syntax precisely as shown in the examples. Data type is Byte.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bb40a2-e717-801b-0d3c-f93aaa928da6
* Version Independent ID: 3032bdf1-eec5-ea63-6175-2ad8855e9ce0
* Content: [&lt;&lt;= Operator (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/operators/left-shift-assignment-operator)
* Content Source: [docs/visual-basic/language-reference/operators/left-shift-assignment-operator.md](https://github.com/dotnet/docs/blob/master/docs/visual-basic/language-reference/operators/left-shift-assignment-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment] 2018-08-30 17:47
I can't reproduce this behavior, @Buzzardbait. Can you reply with your code that is producing the error?

**Comment by Buzzardbait** [comment] 2018-08-30 18:16
I think I understand the problem. I'm using Office 365 VB For Applications. Microsoft co mingles all languages in their VB Programming Reference which is a bad idea. Usually examples will show C++ at the top if it applies to C++ but this one didn't.  I don't think VBA has the << or >> operator. I converted to string and did it that way to solve the problem. Anyway, the code was exactly like the example for << except I tried both short and byte variables.

**Comment by rpetrusha** [comment] 2018-08-30 20:08
I think that's the problem, @Buzzardbait. I may be wrong, but I *think* that the right and left-shift operators were added to Visual Basic .NET only in .NET Framework 2.0. They definitely were not included in VBA or Visual Basic 6.0 and earlier.

Thanks for your comment, though. I'll close this issue.

**Closed by rpetrusha** 2018-08-30 20:08 UTC
Labels: :books: Area - Visual Basic Guide, :file_folder: Repo - docs, Source - Docs.ms, needs-more-info
