### ISSUE TITLE
operator "like" is supported by VB

### ISSUE THREAD

**Issue by CeciAc** [dotnet/docs#11845] opened 2019-04-15 17:33 UTC
@UlliBien commented on [Sun Apr 14 2019](https://github.com/dotnet/docs.de-de/issues/137)

documentation is wrong. operator "like" is supported by VB. you can overwrite it too.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bec570c0-3c04-a8d1-9f13-1696f93080a3
* Version Independent ID: ce60c1cc-649a-5bef-28b2-ac34108d9483
* Content: [Like-Operator (Visual Basic)](https://docs.microsoft.com/de-de/dotnet/visual-basic/language-reference/operators/like-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(vb.Like)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-VB)%26rd%3Dtrue#feedback)
* Content Source: [docs/visual-basic/language-reference/operators/like-operator.md](https://github.com/dotnet/docs.de-de/blob/live/docs/visual-basic/language-reference/operators/like-operator.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by CeciAc** [comment] 2019-04-15 17:34
Hi team,
moving this here since the user is making a suggestion on the original documentation
best

**Comment by mairaw** [comment] 2019-04-15 18:18
@UlliBien can you clarify which part of the article is wrong? If this is regarding the support of the Like operator in .NET Core, AFAIK that's still true, I got compiler errors when trying to use this operator in .NET Core projects.

**Comment by UlliBien** [comment] 2019-04-16 08:59
This code gives a MessageBox with
            'abc' like 'a*'

```
Sub test()
   Dim a As String = "abc"
   If a Like "b" Then
      MsgBox("'abc' like 'b'")
   End If
   If a Like "a*" Then
      MsgBox("'abc' like 'a*'")
   End If
End Sub
```
I'm using:
Microsoft Visual Studio Community 2017 
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.7.03056

Application Type is "Windows Forms-App (.NET Framework)"

Selecting 'Like' in the code and pressing F1 leads to this page: [https://docs.microsoft.com/de-de/dotnet/visual-basic/language-reference/operators/like-operator?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(vb.Like)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-VB)%26rd%3Dtrue](url)

**Comment by svick** [comment] 2019-04-16 11:13
@UlliBien 

> Application Type is "Windows Forms-App (.NET Framework)"

That means it is not a .Net Core or .Net Standard project, so the warning is still correct.

**Comment by mairaw** [comment] 2019-04-22 21:41
Closing this one by design given the note is still accurate. Please let us know if you have any other questions @UlliBien.

**Closed by mairaw** 2019-04-22 21:41 UTC
Labels: :books: Area - Visual Basic Guide, Source - Docs.ms, needs-more-info
