### ISSUE TITLE
resource namespace local: does not find converter

### ISSUE THREAD

**Issue by Ray-Wynn** [dotnet/docs#13362] opened 2019-07-12 03:25 UTC
A converter class defined in the main window application namespace is not found using the XAML local: reference. 

Implementing the same converter class in another namespace - eg. MyNameSpace and XAML reference xmlns:="clr-mynamespace:MyNameSpace" works!

Why not local: ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 747dba09-a143-8d47-b7db-9e94b9ad5d87
* Version Independent ID: a440e344-bde0-7360-e92d-45f9748d08ab
* Content: [How to: Convert Bound Data](https://docs.microsoft.com/en-us/dotnet/framework/wpf/data/how-to-convert-bound-data#feedback)
* Content Source: [docs/framework/wpf/data/how-to-convert-bound-data.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/data/how-to-convert-bound-data.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment] 2019-07-17 04:46
Duplicate of #13363

**Closed by Thraka** 2019-07-17 04:46 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WPF, :watch: Not Triaged, Source - Docs.ms
