### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by fotoguy42** [dotnet/docs#5551] opened 2018-05-22 22:03 UTC
the link to LocBaml Tool Sample, is dead. It goes to a url that times out. I had to go get it from here: https://github.com/JeremyDurnell/locbaml 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72e544a8-3979-26ea-39fb-316eafa71cdb
* Version Independent ID: 5b84e3b3-e09f-be5d-8936-ed1ceb81203c
* Content: [How to: Localize an Application](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application)
* Content Source: [docs/framework/wpf/advanced/how-to-localize-an-application.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/how-to-localize-an-application.md)
* Service: **unspecified**
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2018-05-23 16:37
Thanks for your feedback @fotoguy42. This is a duplicate of another existing issue #3623 so I'm going to be closing this one. We're still trying to determine the right replacement link with the product team.

**Closed** 2018-05-23 16:37 UTC
Labels: Source - Docs.ms, triaged
