### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by TheMinefighter** [dotnet/docs#11446] opened 2019-03-21 20:49 UTC
The link `LocBaml Tool Sample` is dead, and should be replaced with a working one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4baeeb7d-bba4-c8c5-6f54-97dc68a59aef
* Version Independent ID: d248598d-5657-1a8c-3f91-b37384243eff
* Content: [WPF Globalization and Localization Overview](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/wpf-globalization-and-localization-overview)
* Content Source: [docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md](https://github.com/dotnet/docs/blob/master/docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2019-03-22 23:03
Thanks for your feedback @TheMinefighter.
 
Closing as a duplicate of #3623.

**Closed by mairaw** 2019-03-22 23:03 UTC
Labels: :books: Area - .NET Framework Guide, :card_file_box: Technology - WPF, Source - Docs.ms, broken-link, duplicate
