### ISSUE TITLE
The example does not call "Close" on HttpListener object

### ISSUE THREAD

**Issue by upsilonth** [dotnet/docs#6388] opened 2018-07-10 06:08 UTC
As title, the mothod HttpListener.Close is not called in the example.

On the other hand, the example of [HttpListener.Stop](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.stop) does not call Stop method, maybe this issue could be solved by swapping these two examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53cff974-cdd8-d0b2-d4b6-1f481fc69254
* Version Independent ID: 76ae0f29-0c32-8ff2-5b80-99dd504fa231
* Content: [HttpListener.Close Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.httplistener.close?view=netframework-4.7.1#System_Net_HttpListener_Close)
* Content Source: [xml/System.Net/HttpListener.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/HttpListener.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by upsilonth** [comment] 2018-07-10 06:14
On the other hand, the exmple of HttpListener.Stop does not call Stop method, maybe swapping these two examples is enough.

**Comment by rpetrusha** [comment] 2018-10-16 20:08
Thanks for pointing this out, @upsilonth. This issue is a duplicate of #5572, so we'll close this issue.

**Closed by rpetrusha** 2018-10-16 20:08 UTC
Labels: :books: Area - API Reference, :card_file_box: Technology - NCL, :file_folder: Repo - dotnet-api-docs, Source - Docs.ms
