### ISSUE TITLE
Docs dates are ambigious and confusing

### ISSUE THREAD

**Issue by RussKie** [dotnet/docs#14492] opened 2019-09-18 08:21 UTC
**Issue description**

IIUIC the dates on https://docs.microsoft.com are rendered in the US format, and this looks confusing to customers residing outside the US, and thus using different date presentation formats.

The following date is ambigiuos and can be both interpreted as 9th May 2019 or 5th September 2019:
![image](https://user-images.githubusercontent.com/4403806/65129721-92417b00-da04-11e9-895b-d7b7de5670f5.png)

Whilst for some docs publishing dates may not be material, dates of announcements carry an intrinsic value that help customers to decide whether a specific document is relevant to a problem they are researching or not, without spending time reading the doc.

**Desired**
Please render dates in a way that offers no confusion, e.g. "5 Sep 2019", "5th September 2019", or "2019-09-05".

**Comment by Thraka** [comment] 2019-09-19 16:23
Greetings @RussKie 

Feedback relating to the design of docs.ms.com should be logged at https://aka.ms/sitefeedback

I'm going to close this issue. Thanks again.

**Closed by Thraka** 2019-09-19 16:23 UTC
Labels: docs-experience

**Comment by RussKie** [comment] 2019-09-19 16:26
@Thraka why not just move it instead?

/cc: @mairaw

**Comment by Thraka** [comment] 2019-09-20 23:52
I can't move it, you need some sort of admin perms on both repos or something.

**Comment by mairaw** [comment] 2019-09-21 02:18
I manually port them when these come in. Move doesn't work across orgs. I'll open there.

Here's an example: https://github.com/MicrosoftDocs/feedback/issues/1315

**Comment by mairaw** [comment] 2019-09-21 02:19
Although it seems that they closed a similar issue by design: https://github.com/MicrosoftDocs/feedback/issues/1326

**Comment by RussKie** [comment] 2019-09-24 02:19
Thank you

**Comment by RussKie** [comment] 2019-09-24 02:35
> Move doesn't work across orgs.

I didn't know that. I'll keep this in mind.
Thanks
