### ISSUE TITLE
Missing samples

### ISSUE THREAD

**Issue by Herohtar** [dotnet/docs#16155] opened 2019-12-08 05:27 UTC
The table at the top of the page refers to several samples that are not actually provided -- "OSInfo sample", "Arrays Sample", and "HandleRef sample".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9466a98-6498-3816-8385-3fa97ce746e3
* Version Independent ID: b7eba3f0-803c-8895-56f6-633de8ec857d
* Content: [Marshaling Classes, Structures, and Unions](https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-classes-structures-and-unions?source=docs#systime-sample)
* Content Source: [docs/framework/interop/marshaling-classes-structures-and-unions.md](https://github.com/dotnet/docs/blob/master/docs/framework/interop/marshaling-classes-structures-and-unions.md)
* Product: **dotnet-framework**
* GitHub Login: @mairaw
* Microsoft Alias: **dotnetcontent**

**Comment by Thraka** [comment] 2019-12-09 17:32
Closing as duplicate.

**Comment by Thraka** [comment] 2019-12-09 17:32
Duplicate of #16156

**Closed by Thraka** 2019-12-09 17:32 UTC
Labels: :books: Area - .NET Framework Guide, doc-enhancement
