### ISSUE TITLE
Documention for the new "x is null" syntax in C# 7

### ISSUE THREAD

**Issue by verelpode** [dotnet/docs#6856] opened 2018-08-06 16:32 UTC
Please document the lovely new "x is null" syntax that was added to C# 7.  I'm talking about the same thing as this setting controls:  Open VS 2017 then click menubar -&gt; Tools -&gt; Options -&gt; Text Editor -&gt; C# -&gt; Code Style -&gt; General -&gt; "Prefer 'is null' over 'object.ReferenceEquals(..., null)'".

C# now allows us to write:
if (x is null) {...}
instead of:
if (object.ReferenceEquals(x, null)) {...}

Please document the difference between "x is null" versus "x == null", meaning the difference when the class contains an operator-overload for the "==" operator.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1f2a2fe-8279-e6b3-93e8-33398167655f
* Version Independent ID: 35191215-988f-3700-1f85-4751711f692e
* Content: [Pattern Matching - C# Guide](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching)
* Content Source: [docs/csharp/pattern-matching.md](https://github.com/dotnet/docs/blob/master/docs/csharp/pattern-matching.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2018-08-06 20:16
closing as duplicate of #6855

**Closed by BillWagner** 2018-08-06 20:16 UTC
