### ISSUE TITLE
New article and sample idea: Inspecting assembly contents using MetadataLoadContext

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [dotnet/docs#17360] opened 2020-03-06 08:36 UTC
.NET Framework had the reflection-only assembly load mode that allowed to inspect the contents of an assembly without loading it for execution. This mode is not supported in .NET Core. The replacement API is [MetadataLoadContext](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext?view=dotnet-plat-ext-3.1), however, there's no information how to start using it. Searching for "c# MetadataLoadContext" only gives API reference and some unanswered StackOverflow questions. I suggest to create article similar to https://docs.microsoft.com/en-us/dotnet/framework/reflection-and-codedom/how-to-load-assemblies-into-the-reflection-only-context that will cover MetadataLoadContext

## Suggested TOC location
Under https://docs.microsoft.com/en-us/dotnet/standard/assembly/

## Abstract
 The article will explain how to create the isolated MetadataLoadContext using fixed set of paths to resolve assemblies, load assembly into it and extract information about metdata (for example, attributes, defined types...)

## Outline
- Introduction: purpose of MetadataLoadContext, possible scenarios when it is useful
- Prerequisites
- Create MetadataAssemblyResolver for MetadataLoadContext
- Create MetadataLoadContext
- Example

My suggested code sample that can be used for this article: https://github.com/MSDN-WhiteKnight/CodeSamples/tree/master/MetadataLoadContextSample

**Comment by Thraka** [comment] 2020-03-06 19:00
@MSDN-WhiteKnight I think this is a duplicate of #2729 although this is a great write up. Would you mind if I ported this info to that issue?

**Comment by MSDN-WhiteKnight** [comment] 2020-03-07 07:05
> @MSDN-WhiteKnight I think this is a duplicate of #2729 although this is a great write up. Would you mind if I ported this info to that issue?

Yes, I'm okay with this.

**Comment by Thraka** [comment] 2020-03-17 16:34
Ported info over to #2729 
Will close this one.

**Closed by Thraka** 2020-03-17 16:34 UTC
Labels: :card_file_box: Technology - .NET Standard, duplicate
