### ISSUE TITLE
When you pass a value type by reference

### ISSUE THREAD

**Issue by s-horbach** [dotnet/docs#39802] opened 2024-03-05 11:33 UTC
### Type of issue

Typo

### Description

> When you pass a value type by reference

> If the method assigns the parameter to refer to a different object, those changes aren't visible from the caller.

But in fact those changes **are** visible from the caller, isn't it?

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#ref-readonly-modifier

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/method-parameters.md

### Document Version Independent Id

7241f712-8d73-b5e0-37c0-5f05c92412c6

### Article author

@BillWagner

### Metadata

* ID: b8dd92fe-5053-1bc6-1c8f-cf9f88635cb5 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

**Comment by BillWagner** [comment] 2024-03-05 17:58
Hi @s-horbach 

The current article is correct. Here's an example:

```csharp
public in m(ref p)
{
   int localVar = 24;
    p = 42; // This change is visible in the calling context.
    p = ref localVar; // p refers to localVar. This change isn't visible in the calling context.
}
```

I'll close this as by design.

**Closed by BillWagner** 2024-03-05 17:58 UTC
Labels: :watch: Not Triaged, Pri1, dotnet-csharp/svc, lang-reference/subsvc

**Comment by s-horbach** [comment] 2024-03-06 09:47
Hi @BillWagner, thanks for your response.

Maybe I got it wrong, but for me `When you pass a value type by reference` > `If the method assigns the parameter to refer to a different object, those changes aren't visible from the caller` sounds like this:

```
var myStruct = new MyStruct();
Console.WriteLine(myStruct.X);
TestStruct(ref myStruct);
Console.WriteLine(myStruct.X);

static void TestStruct(ref MyStruct myStruct) =>
    myStruct = new MyStruct { X = "New value" };

struct MyStruct
{
    public string X;

    public MyStruct() =>
        X = "Default value";
}
```

, where `TestStruct` method assigns the `myStruct` parameter to refer to a different object, so in this case those changes aren't visible from the caller. Output:
>Default value
New value
