### ISSUE TITLE
Wrong command for installing a newly created dotnet template

### ISSUE THREAD

**Issue by fgheysels** [dotnet/docs#32994] opened 2022-12-13 13:39 UTC
The tutorial describes how a .NET template must be created.
At a certain point, it is said how to install the template, but the command that is mentionned is wrong.  (At least, it  gives an error on my machine).

The command `dotnet new install .\` should be `dotnet new --install .\`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d9cb6bd4-1194-91fa-014c-2e72d809e772
* Version Independent ID: c3fddda9-24c1-f20c-a1b6-6aeea61d6e53
* Content: [Create an item template for dotnet new - .NET CLI](https://learn.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-item-template)
* Content Source: [docs/core/tutorials/cli-templates-create-item-template.md](https://github.com/dotnet/docs/blob/main/docs/core/tutorials/cli-templates-create-item-template.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by gewarren** [comment] 2022-12-14 21:19
Looks like a dupe of #32958.

**Comment by adegeo** [comment] 2023-09-18 16:43
Duplicate of #32958

**Closed by adegeo** 2023-09-18 16:43 UTC
Labels: doc-bug, Pri2, dotnet-fundamentals/prod, okr-health
