### ISSUE TITLE
see also how to use #if for language version

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/docs#12210] opened 2019-05-06 20:43 UTC
this page should include a reference for that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49205137-dcec-a120-e5e7-1b9c79cdafbb
* Version Independent ID: 4352856b-5ccf-8e62-48b4-3151340cac56
* Content: [Target frameworks](https://docs.microsoft.com/en-us/dotnet/standard/frameworks)
* Content Source: [docs/standard/frameworks.md](https://github.com/dotnet/docs/blob/master/docs/standard/frameworks.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

**Comment by svick** [comment] 2019-05-07 20:38
As has been mentioned in https://github.com/dotnet/docs/issues/12211, there is no such feature and you would have to do it manually in MSBuild. Since I don't think it's a common requirement, I don't think it should be documented here.

**Comment by rpetrusha** [comment] 2019-05-20 22:49
I agree with @svick. There's also no mention of language version in the article, and there's no convenient link (especially given multi-language support) that could be added. I'll close this issue as By Design.

**Closed by rpetrusha** 2019-05-20 22:49 UTC
Labels: :books: Area - .NET Guide, Source - Docs.ms, by-design
