### ISSUE TITLE
Improvement in page regarding Volatile keyword in C#

### ISSUE THREAD

**Issue by JoaoCampos07** [dotnet/docs#22546] opened 2021-01-28 10:04 UTC
I think the document is not quite clear, and the example could be better. 
In the text is not refering a example like having two or three threads, what would happen.
And in the code, only one thread is used. Maybe in the example it could be used another thread
to call the DoWork() and illustrate better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d226514d-c7cb-0d1b-b9dc-fb791399dc47
* Version Independent ID: aa5d1078-7f89-98ce-7fdc-107c9ed3eebc
* Content: [volatile - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile)
* Content Source: [docs/csharp/language-reference/keywords/volatile.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/volatile.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2021-01-28 15:13
@JoaoCampos07 This concern was discussed in both #5763 and #5206.

The problem is that a simple multi-threaded sample that exhibits different behavior consistently with the addition of the `volatile` keyword is notoriously difficul.t. In fact, the spec language doesn't guarantee that such a sample exists:

> These restrictions ensure that all threads will observe volatile writes performed by any other thread in the order in which they were performed. A conforming implementation is not required to provide a single total ordering of volatile writes as seen from all threads of execution.

I'm closing this as a duplicate of the above issues.

**Closed by BillWagner** 2021-01-28 15:13 UTC
Labels: :books: Area - C# Guide, :watch: Not Triaged, csharp-language-reference/tech, dotnet-csharp/prod
