### ISSUE TITLE
CA2254 doesn't trigger in Azure Function projects

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/docs#30902] opened 2022-08-29 15:17 UTC
Use (say) an interpolated string in `LogError`, `LogWarning` etc. calls in an ASP.NET project, and this warning will trigger.

But in an Azure Function it won't trigger.  I even made it an explicit error and it still didn't trigger.

This is most likely the reason: https://github.com/dotnet/roslyn-analyzers/issues/5987

_Furthermore_ in an Azure Function project:-

```
log.LogInformation("C# HTTP trigger function processed a request, {name}.");
```

does not give a compilation error saying that an arg is missing (for `params object[] args`).  Again, ASP.NET projects get this right.

I am using Visual Studio 2022 173.2 and .NET 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5662dc7-dcf6-47d5-9340-55b22ebfeca8
* Version Independent ID: 0df9ae80-f763-ba60-a876-a98e86d64887
* Content: [CA2254: Template should be a static expression - .NET](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254)
* Content Source: [docs/fundamentals/code-analysis/quality-rules/ca2254.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/ca2254.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @Youssef1313
* Microsoft Alias: **gewarren**

**Comment by IEvangelist** [comment] 2022-08-29 17:18
This isn't a docs issue, but I'm not sure where it should be transferred. Let's ask @gewarren or @BillWagner as I assume they'd know.

**Comment by Youssef1313** [comment] 2022-08-29 17:25
@Ievangelist That would be dotnet/roslyn-analyzers, but I'm not sure if that's a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/5987 and can just be closed?

**Comment by IEvangelist** [comment] 2022-08-29 18:33
I cannot transfer to that repo. I'm going to close this, as it seems to be captured in that issue - and this isn't a docs issue.

**Closed by IEvangelist** 2022-08-29 18:33 UTC
Labels: product-feedback, Pri2, dotnet-fundamentals/prod
