### ISSUE TITLE
Could you include the offending expression in the NullReferenceException message?

### ISSUE THREAD

**Issue by johnv-microsoft** [dotnet/docs#27736] opened 2022-01-05 20:49 UTC
It would be nice if NullReferenceException included the expression that actually caused the exception.
So, if this code threw an exception:
```
bool value = obj1.Method1().BoolProperty && obj2.Method2().BoolProperty;
```
You'd get more than the line number.  You'd get "obj1.Method1() returned null" as part of the exception, for instance.
Many times, I've run into a null reference exception on a line with lots of dereferencing.  So it's hard to know what caused it.

Maybe some of the work to make CallerArgumentExpression possible could be leveraged for that purpose.
I wonder if it's practical performance-wise, or feasible at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5d9ede5-d454-ad2c-9b49-30ccde7edaf3
* Version Independent ID: 0d087957-2ceb-554c-1b52-c20cbef1cacd
* Content: [Caller argument expression - C# 10.0 draft specifications](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/caller-argument-expression)
* Content Source: [proposals/csharp-10.0/caller-argument-expression.md](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-10.0/caller-argument-expression.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2022-01-06 21:41
@333fred

Should I move this to the roslyn repo for discussion?

**Comment by 333fred** [comment] 2022-01-07 01:09
This wouldn't be a Roslyn or C# discussion. @stephentoub, would the runtime be an appropriate place for this (or would you happen to know of an existing discussion to link, as I doubt this is the first)?

**Comment by stephentoub** [comment] 2022-01-07 01:15
https://github.com/dotnet/runtime/issues/3858

**Comment by 333fred** [comment] 2022-01-07 01:22
Thanks! I'll close this out as a duplicate of that one then.

**Closed by 333fred** 2022-01-07 01:22 UTC
Labels: duplicate, Pri2, dotnet-csharp/prod, csharp-spec/tech

**Comment by BillWagner** [comment] 2022-01-07 01:28
Thanks everyone.
