### ISSUE TITLE
require keyword examol

### ISSUE THREAD

**Issue by krajniak** [dotnet/docs#37637] opened 2023-10-19 09:47 UTC
### Type of issue

Code doesn't work

### Description

The code example under the paragraph:

"""
An init accessor doesn't force callers to set the property. Instead, it allows an object initializer to set the initial value while prohibiting later modification. You can add the required modifier to force callers to set a property. The following example shows the same behavior:
"""

seems to be incorrect, nothing refere to required modifier

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/init

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/init.md

### Document Version Independent Id

fc780319-a7fd-d9d1-1877-638ac05eb5f4

### Article author

BillWagner

**Comment by BillWagner** [comment] 2023-10-19 13:53
Duplicate of #37625

**Closed by BillWagner** 2023-10-19 13:53 UTC
Labels: :watch: Not Triaged, Pri3, dotnet-csharp/prod, csharp-language-reference/tech
