### ISSUE TITLE
UnixEpochDateTimeConverter issue

### ISSUE THREAD

**Issue by karenpayneoregon** [dotnet/docs#24075] opened 2021-05-06 18:16 UTC
Using Unix epoch date format UnixEpochDateTimeConverter method does not return a proper date time. See unit test method in the following GitHub repo

https://github.com/karenpayneoregon/power-shell-process-cs/tree/master/JsonUnitTestProject

```csharp
[TestMethod]
[TestTraits(Trait.UnixEpochDateTime)]
public async Task Deserialize_Object_With_UnixEpochDateTime()
{
    var cdi = await Operations.GetPartialComputerInformationTask("computerDateInfo.json");

    var today = new DateTime(
        cdi.OsLocalDateTime.Year, 
        cdi.OsLocalDateTime.Month,
        cdi.OsLocalDateTime.Day, 
        cdi.OsLocalDateTime.Hour,
        cdi.OsLocalDateTime.Minute,
        0);


    /*
     * OsLocalDateTime deserialized with converter returns incorrect date time
     */
    Debug.WriteLine($"{cdi.OsLocalDateTime:G} -- {DateTime.Now:G}");
    
}
```
Feeding json from PowerShell

```csharp
public class Operations
{
    public static async Task<DateContainer> GetPartialComputerInformationTask(string fileName)
    {

        var start = new ProcessStartInfo
        {
            FileName = "powershell.exe",
            RedirectStandardOutput = true,
            Arguments = "Get-ComputerInfo | select BiosReleaseDate,OsLocalDateTime,OsLastBootUpTime,OsUptime | ConvertTo-Json",
            CreateNoWindow = true
        };

        using var process = Process.Start(start);
        using var reader = process.StandardOutput;

        process.EnableRaisingEvents = true;

        var fileContents = await reader.ReadToEndAsync();

        await File.WriteAllTextAsync(fileName, fileContents);
        await process.WaitForExitAsync();

        var json = await File.ReadAllTextAsync(fileName);

        return JSonHelper.DeserializeObjectUnixEpochDateTime<DateContainer>(json);

    }
}
```
Container

```csharp
public class DateContainer
{
    public DateTime BiosReleaseDate { get; set; }
    public DateTime OsLocalDateTime { get; set; }
    public DateTime OsLastBootUpTime { get; set; }
    public Osuptime OsUptime { get; set; }
}
```
```csharp
public class Osuptime
{
    public long Ticks { get; set; }
    public int Days { get; set; }
    public int Hours { get; set; }
    public int Milliseconds { get; set; }
    public int Minutes { get; set; }
    public int Seconds { get; set; }
    public float TotalDays { get; set; }
    public float TotalHours { get; set; }
    public float TotalMilliseconds { get; set; }
    public float TotalMinutes { get; set; }
    public float TotalSeconds { get; set; }
    public override string ToString() => $"{Hours} hours {Minutes} minutes {Days} days";
}
```
Results:

```csharp
Debug.WriteLine($"OsLocalDateTime: {cdi.OsLocalDateTime:G} --> {DateTime.Now:G}");
```

`OsLocalDateTime: 5/6/2021 6:13:12 PM --> 5/6/2021 11:13:16 AM`

Using PowerShell in Windows PowerShell window

```
 Get-ComputerInfo | select OsLocalDateTime

OsLocalDateTime
---------------
5/6/2021 11:14:33 AM
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb41b02f-8fe9-44a1-544f-b6016f1ff4b3
* Version Independent ID: 77358796-3ee2-9b86-7e0a-92c60ebc371a
* Content: [DateTime and DateTimeOffset support in System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support)
* Content Source: [docs/standard/datetime/system-text-json-support.md](https://github.com/dotnet/docs/blob/main/docs/standard/datetime/system-text-json-support.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @layomia
* Microsoft Alias: **laakinri**

**Comment by karenpayneoregon** [comment] 2021-05-08 02:44
I’m not reporting a bug in .NET, instead if the code sample on the page is not working properly so this is an issue with code in the documentation for the page.

 

The following code on the page does not work as explained in my feedback hence whomever wrote the code below needs to run my code to show the code does not work which means it’s not a .NET bug.

 

https://docs.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support#using-unix-epoch-date-format

 

My main reason for reporting this is that someone moving from Newtonsoft to this will not be happy to find a Microsoft code sample to not work. I copied and pasted the code and used it w/o alterations.

**Comment by karenpayneoregon** [comment] 2021-05-08 14:49
As mentioned in an email (sent to me yesterday) if this was a .NET issue versus documentation, I see this was a incomplete code sample for the converter as stated in the issue. To see what needs to change in code or to keep code `as is` and document it see the [following page](https://github.com/karenpayneoregon/karenpayneoregon.github.io/blob/master/csharp/unixEpochDateFormat.md) and full [source code](https://github.com/karenpayneoregon/power-shell-process-cs/tree/master/PowerShellLibrary) and [test method](https://github.com/karenpayneoregon/power-shell-process-cs/blob/master/JsonUnitTestProject/MainTest.cs#L38).

**Comment by adegeo** [comment] 2021-05-20 16:46
@karenpayneoregon Thank you for the clarifications. I'll tag some people to see if they can help

@layomia can you respond to this and verify the code?

**Comment by tarekgh** [comment] 2021-05-20 16:57
@layomia can know better here as it looks the call `JSonHelper.DeserializeObjectUnixEpochDateTime<DateContainer>(json);` is the place which doing the conversion/deserialization. but looking at the output, it looks to me the issue is the deserialized date/time is converted to local time. I guess @karenpayneoregon is located in a time zone -7:00 hours from Utc.

**Comment by adegeo** [comment] 2021-07-07 18:56
@layomia did you have anything to add? Otherwise I'll close this issue.

**Closed** 2021-09-24 13:31 UTC
Labels: waiting-on-feedback, product-question, Pri1, dotnet-fundamentals/prod
