### ISSUE TITLE
Implicitly Typed Local Variables

### ISSUE THREAD

**Issue by abdu95** [dotnet/docs#18940] opened 2020-06-13 07:22 UTC
In the section **Implicitly Typed Local Variables**, it is recommended to **not to use implicit typing to determine the type of the loop variable in foreach loops.**
But in the example, implicit typing is used (var - implicit, char - explicit).
Should it be `(char ch in laugh)` instead of `(var ch in laugh)`?

The following example uses explicit typing in a foreach statement.

```cs
foreach (var ch in laugh)
{
    if (ch == 'h')
        Console.Write("H");
    else
        Console.Write(ch);
}
Console.WriteLine();
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by BillWagner** [comment] 2020-06-15 15:14
Thanks for writing this @abdu95 

This rule should be removed.  Where it is useful, it's redundant with the rule for using var "only when the type is obvious". That's the rule we've been following in our samples.

**Comment by abdu95** [comment] 2020-06-15 20:42
@BillWagner Got it, thanks!

**Comment by BillWagner** [comment] 2020-06-19 13:49
closing as a duplicate of #18900

**Closed by BillWagner** 2020-06-19 13:49 UTC
Labels: :books: Area - C# Guide, P2, doc-bug, up-for-grabs
