### ISSUE TITLE
Linux update commands could be simplified, don't need 2 updates and 2 installs

### ISSUE THREAD

**Issue by poggdogg** [dotnet/docs#17203] opened 2020-02-25 06:58 UTC
sudo apt-get update
sudo apt-get install dotnet-sdk-3.1

can be reduced/simplified to:
sudo apt-get update
sudo apt-get install apt-transport-https dotnet-sdk-3.1

or a one-liner:
sudo apt-get update && sudo apt-get install apt-transport-https

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 172f0b88-61f2-d631-478f-e88af9be1f7d
* Version Independent ID: c610685f-57a2-048d-8dfa-146e19943434
* Content: [Install .NET Core on Ubuntu 19.04 package manager - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1904)
* Content Source: [docs/core/install/linux-package-manager-ubuntu-1904.md](https://github.com/dotnet/docs/blob/master/docs/core/install/linux-package-manager-ubuntu-1904.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by Thraka** [comment] 2020-02-28 18:00
Duplicate of #16262 

This is currently needed and there is a discussion on this at https://github.com/dotnet/docs/issues/16262#issuecomment-566227335

Cheers!

**Comment by Thraka** [comment] 2020-02-28 18:00
Duplicate of #16262

**Closed by Thraka** 2020-02-28 18:00 UTC
Labels: :books: Area - .NET Core Guide, duplicate
