### ISSUE TITLE
Docs unclear if dotnet is supported on Ubuntu 20.10

### ISSUE THREAD

**Issue by alyssajotice** [dotnet/docs#25364] opened 2021-07-27 21:47 UTC
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

The above documentation details which .NET versions run on which versions of Ubuntu. In the [table of supported distributions](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#supported-distributions), 20.10 has a red "X". But on the side panel and later on the page, it has a green checkmark. It is unclear whether or not dotnet is supported on Ubuntu 20.10.

[Edited to add doc details]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80707602-f283-e796-d3b8-3287fbc011dc
* Version Independent ID: 1d732b15-9e64-633a-000c-ad96d9d3818a
* Content: [Install .NET on Ubuntu - .NET](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu)
* Content Source: [docs/core/install/linux-ubuntu.md](https://github.com/dotnet/docs/blob/main/docs/core/install/linux-ubuntu.md)
* Product: **dotnet**
* Technology: **dotnet-install**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2021-07-30 21:02
Duplicate of #25382

**Closed by adegeo** 2021-07-30 21:02 UTC
Labels: :watch: Not Triaged, Pri3
