### ISSUE TITLE
Examples don't woek:

### ISSUE THREAD

**Issue by darkoverlordofdata** [dotnet/docs#22168] opened 2020-12-29 05:03 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836d726d-1f95-51e7-c5c3-a7200adc5772
* Version Independent ID: 3e9e6e89-7017-7a7c-faea-4c0e76cef442
* Content: [Get started with F# with command-line tools](https://docs.microsoft.com/en-us/dotnet/fsharp/get-started/get-started-command-line)
* Content Source: [docs/fsharp/get-started/get-started-command-line.md](https://github.com/dotnet/docs/blob/master/docs/fsharp/get-started/get-started-command-line.md)
* Product: **dotnet-fsharp**
* GitHub Login: @cartermp
* Microsoft Alias: **phcart**

**Comment by cartermp** [comment] 2020-12-29 05:37
closing as dupe of https://github.com/dotnet/docs/issues/22170

**Closed by cartermp** 2020-12-29 05:37 UTC
Labels: :books: Area - F# Guide, :watch: Not Triaged, dotnet-fsharp/prod
