### ISSUE TITLE
Verify email address: code/regex is too restrictive

### ISSUE THREAD

**Issue by Styxxy** [dotnet/docs#20013] opened 2020-08-12 15:59 UTC
The sample code on how to validate an email address is too restrictive. Valid addresses like `myemail_@domain.tld` fail on this code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202e3f9f-a12a-53de-9069-fd469e3dbebc
* Version Independent ID: fd3699bb-4881-b6b4-1275-43eed3d5f626
* Content: [How to verify that strings are in valid email format](https://docs.microsoft.com/en-us/dotnet/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format)
* Content Source: [docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md](https://github.com/dotnet/docs/blob/master/docs/standard/base-types/how-to-verify-that-strings-are-in-valid-email-format.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @adegeo
* Microsoft Alias: **adegeo**

**Comment by adegeo** [comment] 2020-08-14 00:43
Hi. This issue has been reported 😄 We're not really doing much on this article because there are endless ways to change the regex to validate an email address. We have an old discussion open at #9547

**Comment by adegeo** [comment] 2020-08-14 00:43
Duplicate of #16299

**Closed by adegeo** 2020-08-14 00:43 UTC
Labels: :books: Area - .NET Guide, :watch: Not Triaged
