### ISSUE TITLE
missing access modifiers

### ISSUE THREAD

**Issue by 3ric6** [dotnet/docs#12379] opened 2019-05-15 20:51 UTC
should have links to abstract, partial, sealed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6d56158-da5c-4124-a105-db8af724f3af
* Version Independent ID: 51389ca5-2d35-b830-2b48-54293c880839
* Content: [Accessibility Levels - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/accessibility-levels#feedback)
* Content Source: [docs/csharp/language-reference/keywords/accessibility-levels.md](https://github.com/dotnet/docs/blob/master/docs/csharp/language-reference/keywords/accessibility-levels.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by rpetrusha** [comment] 2019-05-15 21:07
abstract, partial, and sealed are unrelated to access modifiers, @3ric6, so adding links to them is not likely to be helpful. I'll close this this issue as by design.

**Closed by rpetrusha** 2019-05-15 21:07 UTC
Labels: :books: Area - C# Guide, Source - Docs.ms, by-design
